# scripts/generate_ch6.py
"""
Generates Chapter 6 data: 38 Single Choice, 30 Multiple Choice, 28 True/False.
Chapter 6: Firewall Hot Standby Technologies
"""
import json

def get_ch6_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 6 SINGLE CHOICE (38 questions)
    s_data = [
        ("HA Uptime Standard", "In enterprise high availability (HA) network design, what availability percentage is commonly known as 'five nines' availability?",
         ["99.000%", "99.900%", "99.999%", "99.9999%"], "C",
         "'Five nines' refers to 99.999% system availability, allowing at most approximately 5.26 minutes of unscheduled downtime per year across enterprise services."),
        ("VRRP RFC Standard", "Virtual Router Redundancy Protocol (VRRP) is standard protocol defined by which standards body?",
         ["IEEE 802.3", "IETF (RFC 3768 / RFC 5798)", "ITU-T X.509", "ISO 27001"], "B",
         "VRRP is an open industry standard protocol defined by the Internet Engineering Task Force (IETF) in RFC 3768 (VRRPv2) and RFC 5798 (VRRPv3) to provide gateway redundancy."),
        ("VRRP Virtual MAC Format", "What is the standard format of a VRRP Virtual MAC address for an IPv4 VRRP group with VRID 1?",
         ["00-E0-FC-00-00-01", "00-00-5E-00-01-01", "FF-FF-FF-FF-FF-01", "01-00-5E-00-01-01"], "B",
         "The standard VRRP IPv4 Virtual MAC format is `00-00-5E-00-01-XX`, where the last byte `XX` represents the VRID in hexadecimal. For VRID 1, the Virtual MAC is `00-00-5E-00-01-01`."),
        ("VRRP Default Priority", "What is the default priority value assigned to a router participating in a standard VRRP group?",
         ["1", "50", "100", "255"], "C",
         "The default VRRP priority is 100. Configurable priorities range from 1 to 254. Priority 255 is automatically reserved for the router that owns the actual physical IP address matching the Virtual IP."),
        ("VRRP Advertisement Interval", "By default, at what interval does the VRRP Master router broadcast VRRP Advertisement packets?",
         ["100 milliseconds", "1 second", "5 seconds", "30 seconds"], "B",
         "The default VRRP advertisement interval is 1 second. If the Backup router fails to receive advertisements for three consecutive intervals (3 * Advertisement_Interval + Skew_Time), it transitions to Master."),
        ("VRRP Multicast Destination", "What is the standard IPv4 multicast address used by the VRRP Master to send advertisement packets to backup routers?",
         ["224.0.0.1", "224.0.0.2", "224.0.0.18", "224.0.1.1"], "C",
         "VRRP protocol advertisements are encapsulated in IP packets (Protocol 112) and transmitted to the dedicated multicast address `224.0.0.18`."),
        ("Standard VRRP Limitation on Firewalls", "What is the primary technical limitation of deploying standard standalone VRRP on multi-interface stateful firewalls?",
         ["VRRP cannot run over Ethernet interfaces",
          "VRRP groups on uplink and downlink interfaces operate independently; a failure on the uplink does not trigger a failover on the downlink, creating a routing black hole",
          "VRRP disables all NAT translation features on firewalls",
          "VRRP requires physical serial cables between routers"], "B",
         "Standard VRRP operates per-interface independently. If Firewall A's external uplink fails, its internal interface remains VRRP Master. Internal traffic still flows to Firewall A, where it is blackholed because Firewall A has lost its upstream path."),
        ("VGMP Definition", "What is the VRRP Group Management Protocol (VGMP) on Huawei firewalls?",
         ["An open IETF protocol used to configure wireless access points",
          "A Huawei proprietary protocol that manages all VRRP groups on a firewall as a unified entity to coordinate synchronized state switchovers",
          "A protocol used exclusively to update antivirus signature databases",
          "A routing protocol replacing OSPF in data centers"], "B",
         "VGMP is a Huawei proprietary protocol that groups all VRRP interfaces (uplink, downlink, DMZ) under a centralized management group, ensuring that when one interface fails, all VRRP groups switch states together."),
        ("VGMP Management Groups", "In Huawei firewall hot standby, what are the two predefined VGMP management groups?",
         ["Active Group and Standby Group", "Master Group and Slave Group", "Primary Group and Secondary Group", "Trust Group and Untrust Group"], "A",
         "VGMP provides two management groups: the Active Group (default state is Active) and the Standby Group (default state is Standby)."),
        ("VGMP Default Priority", "What is the default initial priority of both the Active and Standby VGMP management groups on Huawei firewalls?",
         ["100", "1000", "45000", "65000"], "D",
         "By default, the initial priority of both the Active VGMP group and the Standby VGMP group is 65000."),
        ("VGMP Priority Adjustment on Failure", "When a monitored interface on the active firewall goes DOWN, how does VGMP adjust its group priority by default?",
         ["It resets the priority to 0",
          "It decrements the VGMP priority (typically by 2) for each failed monitored interface",
          "It doubles the VGMP priority to compensate",
          "It leaves the priority unchanged and reboots the firewall"], "B",
         "When an interface tracked by VGMP fails, VGMP reduces its priority value (default reduction is 2). This causes the active firewall's priority (e.g. 64998) to drop below the standby firewall's priority (65000), triggering an immediate switchover."),
        ("VGMP Unified Switchover", "What occurs across all VRRP groups on a firewall when its VGMP management group transitions from Active to Standby?",
         ["All associated VRRP groups switch from Master to Backup simultaneously",
          "All internal network switches lose power",
          "Only the failed interface switches, while others remain unchanged",
          "The firewall formats its configuration disk"], "A",
         "Because VGMP centrally controls all member VRRP groups, when the VGMP group changes state, every associated VRRP group (internal, external, DMZ) transitions simultaneously, preventing asymmetric routing black holes."),
        ("HRP Definition", "What is the primary role of the Huawei Redundancy Protocol (HRP)?",
         ["To assign IP addresses to DHCP clients across the WAN",
          "To synchronize configuration commands, session tables, and status information between active and standby firewalls over heartbeat interfaces",
          "To provide public key digital certificate verification",
          "To calculate shortest path trees for OSPF routing"], "B",
         "HRP is a Huawei proprietary protocol running over heartbeat links that synchronizes configuration commands (`hrp enable`), dynamic session tables, Server-Map entries, and IPsec SA states between clustered firewalls."),
        ("HRP Heartbeat Transport Protocol", "Which transport protocol and port number are utilized by HRP heartbeat packets?",
         ["TCP port 80", "UDP port 18514", "TCP port 443", "UDP port 500"], "B",
         "HRP encapsulates heartbeat packets and synchronization data inside UDP datagrams using destination port 18514."),
        ("HRP Synchronized Data Types", "Which of the following dynamic state tables is synchronized in real-time by HRP to prevent active TCP sessions from dropping during a failover?",
         ["The BGP routing information base (RIB)",
          "The firewall Session Table",
          "The switch STP topology change table",
          "The CPU instruction cache"], "B",
         "Real-time session table synchronization by HRP ensures that the backup firewall maintains an identical copy of active connection states. When a failover occurs, established TCP connections continue without interruption."),
        ("HRP Backup Modes - Real-Time Backup", "When does HRP 'Real-Time Backup' execute data synchronization?",
         ["Once every 24 hours at midnight",
          "Immediately as each new session table entry or configuration command is created or modified",
          "Only when the administrator manually enters a synchronization command",
          "Only when an interface physically fails"], "B",
         "Real-time backup continuously replicates state changes: as soon as a new session is established or a security policy is modified, HRP immediately transmits the update to the standby peer."),
        ("HRP Backup Modes - Batch Backup", "Under which circumstance is HRP 'Batch Backup' primarily triggered?",
         ["During an active DDoS attack",
          "When the standby firewall boots up, re-establishes heartbeat connectivity, or an administrator manually triggers `hrp sync config`",
          "When a user types a wrong password three times",
          "Whenever an ICMP ping packet is received"], "B",
         "Batch backup bulk-synchronizes all configuration commands and existing session tables. It executes upon initial peer connection establishment, manual administrator command (`hrp sync`), or after a reboot."),
        ("Quick Session Backup Purpose", "Why is 'Quick Session Backup' specifically implemented in Load-Balancing (Active/Active) hot standby mode?",
         ["To immediately replicate sessions before return packets arrive in asymmetric routing topologies, preventing session drop on the peer firewall",
          "To permanently disable stateful packet inspection",
          "To reduce CPU clock speeds during business hours",
          "To convert TCP packets into UDP broadcasts"], "A",
         "In Active/Active mode, asymmetric routing can cause outbound traffic to traverse FW1 while return traffic reaches FW2. Quick session backup instantly pushes the session from FW1 to FW2 upon creation so FW2 can forward the return packet without dropping it."),
        ("Hot Standby Mode - Active/Standby", "In Active/Standby (1+1 Redundancy) mode, how is network traffic handled under normal operating conditions?",
         ["Both firewalls forward 50% of the traffic simultaneously",
          "The Active firewall processes all service traffic, while the Standby firewall remains idle ready to take over upon failure",
          "The Standby firewall processes only voice traffic",
          "Traffic bypasses both firewalls completely"], "B",
         "In Active/Standby mode, one firewall (the active unit) handles all network forwarding, policy enforcement, and NAT. The standby firewall does not forward traffic; it synchronizes states and monitors the active unit."),
        ("Hot Standby Mode - Load Balancing", "In Load-Balancing (Active/Active) mode, how are VRRP groups typically deployed across the two firewalls?",
         ["Both firewalls are configured as Backup for all VRRP groups",
          "Firewall A is configured as Master for VRRP Group 1 and Backup for Group 2; Firewall B is configured as Master for Group 2 and Backup for Group 1",
          "Neither firewall is assigned a virtual IP address",
          "VRRP is completely disabled on both firewalls"], "B",
         "In Active/Active mode, services are divided between two VRRP groups. FW1 is Master for Group 1 (gateway for Subnet A), and FW2 is Master for Group 2 (gateway for Subnet B). Both forward traffic concurrently, providing mutual backup."),
        ("Heartbeat Interface Type", "What type of interface is recommended for connecting the HRP heartbeat link between two clustered firewalls?",
         ["A dedicated point-to-point Layer 3 physical interface or dedicated Eth-Trunk",
          "A public Internet WAN interface routed through an external ISP",
          "An unmanaged consumer Wi-Fi connection",
          "An optical interface connected to an analog television tuner"], "A",
         "Best practice mandates dedicated point-to-point physical links (or aggregated Eth-Trunk links) directly connecting the two firewalls for heartbeat traffic, preventing heartbeat loss from intermediate switch failures."),
        ("HRP Enable Command", "Which command is executed in Huawei VRP system view to enable the Huawei Redundancy Protocol?",
         ["hrp enable", "vrrp start", "firewall cluster on", "ha mode active"], "A",
         "The command `hrp enable` activates the HRP process and begins heartbeat transmission and state synchronization."),
        ("HRP Track Interface Command", "Which command configures a firewall interface to be monitored by VGMP so that its failure decrements the VGMP priority?",
         ["hrp track interface <interface-name>", "interface monitor enable", "vrrp track link", "ha watch port"], "A",
         "In Huawei firewalls, executing `hrp track interface <interface-type> <interface-number>` registers the specified interface with VGMP for health tracking."),
        ("HRP Command Synchronization Prompt", "When HRP configuration synchronization is active, what prefix typically appears before the CLI command prompt on the secondary firewall?",
         ["[HRP_Active]", "[HRP_Standby]", "[Master_Node]", "[Sync_Disabled]"], "B",
         "On the standby firewall, the CLI prompt is typically modified to `HRP_S` or `HRP_Standby` to indicate that local configuration is locked and synchronized from the active unit (`HRP_A` / `HRP_Active`)."),
        ("Standby Configuration Lockout", "Why does HRP lock out direct configuration changes on the Standby firewall by default?",
         ["To prevent conflicting configuration discrepancies between the clustered firewalls",
          "Because the standby firewall's flash memory is physically removed",
          "Because the standby firewall runs a different operating system",
          "To allow unauthorized guest users to reconfigure security rules"], "A",
         "To guarantee consistent policy enforcement, configurations should only be performed on the Active firewall, which automatically replicates them to the Standby firewall. Modifying the Standby directly causes split-brain configuration mismatches."),
        ("HRP Manual Synchronization Command", "Which CLI command forces an immediate manual batch synchronization of configuration from the active firewall to the standby peer?",
         ["hrp sync config", "copy running startup", "save cluster", "vrrp update now"], "A",
         "Executing `hrp sync config` on the active firewall forces an immediate batch synchronization of all configuration parameters to the standby unit."),
        ("Preemption Mode Function", "What is the function of the 'Preemption Mode' setting in firewall hot standby?",
         ["It causes the firewall to randomly reboot during network congestion",
          "When a failed primary firewall recovers, it automatically reclaims the Active role after a configurable preemption delay",
          "It permanently shuts down the secondary firewall",
          "It prevents any user from accessing web services"], "B",
         "Preemption mode allows the primary firewall (with higher default priority) to reclaim the Active role once it recovers from a failure. A preemption delay is configured to allow routing protocols and interfaces to stabilize before reclaiming traffic."),
        ("Preemption Delay Rationale", "Why is it critical to configure a 'Preemption Delay' (e.g. 60 seconds) rather than allowing immediate preemption upon primary firewall recovery?",
         ["To let the primary firewall's cooling fans accelerate",
          "To allow routing protocols (OSPF/BGP), physical interfaces, and session tables to fully converge before traffic is switched back, preventing packet loss",
          "To give the administrator time to cancel the preemption manually",
          "Because the standby firewall requires 60 seconds to format its storage"], "B",
         "If the primary firewall preempts immediately upon booting, routing tables and neighbor adjacencies may not have converged, resulting in blackholed traffic. A delay ensures complete network stabilization before traffic switchback."),
        ("Split-Brain Scenario", "What occurs in a 'Split-Brain' condition when the heartbeat connection between two firewalls is completely severed while both units remain powered on?",
         ["Both firewalls perceive the peer as dead; both transition to the Active state, causing IP/MAC conflicts on virtual IP addresses",
          "Both firewalls automatically enter sleep mode",
          "The firewalls merge into a single physical unit",
          "All network packets are converted into frame relay"], "A",
         "When heartbeat connectivity is lost, each firewall assumes the peer has failed. Both promote themselves to Active/Master, claiming the same virtual IP and virtual MAC addresses, resulting in ARP thrashing, IP conflicts, and widespread network paralysis."),
        ("Display HRP State Command", "Which command is used to check the operational status of HRP, the active/standby role, and heartbeat link health?",
         ["display hrp state", "display vrrp brief", "display ha status", "display cluster info"], "A",
         "The command `display hrp state` outputs the current HRP operational state (e.g., Active or Standby), local and peer VGMP priorities, heartbeat link status, and synchronization counters."),
        ("Multi-Heartbeat Link Redundancy", "Why is it recommended to configure multiple redundant heartbeat interfaces or an Eth-Trunk heartbeat between firewalls?",
         ["To increase the speed of user web browsing",
          "To prevent a single cable failure from triggering a devastating Split-Brain condition",
          "To allow the firewalls to mine cryptocurrency in idle periods",
          "To eliminate the need for VRRP virtual IP addresses"], "B",
         "Heartbeat redundancy (via dual physical links or link aggregation) ensures that the failure of a single cable or SFP module does not sever heartbeat communications, protecting the cluster against split-brain failures."),
        ("HRP Heartbeat Interface Negotiation", "How does HRP determine which firewall is Active when both firewalls are powered on simultaneously with equal initial VGMP priorities (65000)?",
         ["They flip a random coin electronically",
          "They compare configured roles (e.g., `hrp standby config` or preemption settings) or use tie-breaking rules such as lower heartbeat IP or MAC address",
          "The firewall with larger physical dimensions becomes Active",
          "Both firewalls remain permanently disabled until manual intervention"], "B",
         "If priorities are equal, configured roles (`hrp standby config`), preemption rules, or tie-breakers (such as IP address comparison) dictate which firewall assumes the Active role."),
        ("HRP Server-Map Synchronization", "Why must Server-Map tables be synchronized via HRP in addition to session tables?",
         ["Because Server-Map entries store user desktop wallpaper preferences",
          "To ensure that dynamic pinholes for multi-channel protocols (e.g. FTP data) and static NAT Server mappings are immediately available on the peer during failover",
          "Because Server-Map entries contain the firewall serial numbers",
          "To convert public IP addresses into private IP addresses"], "B",
         "Synchronizing Server-Map entries ensures that active multi-channel data transfers (FTP, SIP) and NAT Server mappings seamlessly continue without requiring renegotiation when a failover occurs."),
        ("IPsec SA Synchronization via HRP", "How does HRP synchronization of IPsec Security Associations (SAs) benefit remote branch VPN connections during firewall failover?",
         ["It requires remote branch routers to re-enter their pre-shared keys",
          "The backup firewall assumes the existing IPsec SAs, allowing encrypted VPN tunnels to continue forwarding data without renegotiating IKE Phase 1 or Phase 2",
          "It changes the encryption algorithm from AES to DES",
          "It permanently disables the IPsec tunnel"], "B",
         "Replicating IPsec SAs allows the standby firewall to decrypt and encrypt ongoing IPsec traffic immediately upon taking over, avoiding tunnel renegotiation dropped packets and IKE re-authentication delays."),
        ("VRRP Tracking Upper Link Command", "In standard VRRP, how does an interface track another interface's status?",
         ["vrrp vrid <id> track interface <interface-name> [reduced <value>]",
          "interface track enable",
          "vrrp follow port",
          "track link status"], "A",
         "In VRRP, the command `vrrp vrid <id> track interface <interface> [reduced <value>]` dynamically decrements VRRP priority if the tracked interface goes down."),
        ("Firewall Load-Balancing Route Asymmetry", "In Load-Balancing mode with two firewalls, why does symmetric routing engineering matter?",
         ["To prevent firewalls from overheating",
          "Because stateful firewalls require session synchronization to handle return traffic if forward and return packets take different firewall paths",
          "Because Ethernet switches cannot learn two MAC addresses simultaneously",
          "Because routing protocols cannot run on standby firewalls"], "B",
         "Asymmetric traffic paths cause return packets to reach a firewall that did not see the initial SYN. Without quick session synchronization, the firewall drops the return packet as an invalid state transition."),
        ("HRP Packet Authentication", "Can HRP heartbeat communication be authenticated using a shared secret key?",
         ["No, HRP packets are always unauthenticated cleartext",
          "Yes, a shared key can be configured using `hrp key <password>` to verify heartbeat packet authenticity and prevent spoofing",
          "HRP can only be authenticated using physical iris scanners",
          "Authentication is handled automatically by the ISP router"], "B",
         "Administrators can configure an HRP authentication key (`hrp key <key>`) to cryptographically authenticate heartbeat packets exchanged between the firewalls, preventing unauthorized injection of forged VGMP packets."),
        ("VGMP Priority Deduction Customization", "Can the priority deduction value applied by VGMP when an interface fails be customized?",
         ["No, it is permanently hardcoded to 100",
          "Yes, administrators can specify custom priority reduction values when tracking interfaces or IP links",
          "VGMP priority can only be modified by rebooting",
          "Priority reduction is prohibited by RFC standards"], "B",
         "Administrators can customize the priority deduction value (e.g. `hrp track interface GigabitEthernet 0/0/1 reduced 50`) to tailor failover sensitivity across multi-interface topologies.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 6,
            "chapter_title": "Firewall Hot Standby Technologies",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 6 MULTIPLE CHOICE (30 questions)
    m_data = [
        ("VRRP Core Entities", "Which of the following are primary operational entities defined in a VRRP deployment?",
         ["VRRP Master Router", "VRRP Backup Router", "Virtual IP Address (VIP)", "Virtual MAC Address", "Virtual Satellite Receiver"], "ABCD",
         "VRRP defines Master and Backup router roles, associated with a shared Virtual IP address and Virtual MAC address. There is no 'Virtual Satellite Receiver'."),
        ("Standard VRRP Router States", "Which of the following represent valid operational states in the standard VRRP finite state machine?",
         ["Initialize", "Master", "Backup", "Listening"], "ABC",
         "The standard VRRP state machine defines three states: Initialize (waiting for interface startup), Master (forwarding traffic), and Backup (monitoring Master)."),
        ("Huawei Hot Standby Protocols", "Which two proprietary protocols are implemented by Huawei to achieve comprehensive firewall hot standby clustering?",
         ["VRRP Group Management Protocol (VGMP)",
          "Huawei Redundancy Protocol (HRP)",
          "Border Gateway Protocol (BGP)",
          "Spanning Tree Protocol (STP)"], "AB",
         "Huawei dual-system hot standby combines VGMP (managing VRRP groups unifiedly) and HRP (synchronizing configuration and state tables across heartbeat links)."),
        ("Data Synchronized by HRP", "Which of the following data and state tables are synchronized between clustered firewalls by HRP?",
         ["Security Policy and NAT configuration commands",
          "Active Session Tables (connection states)",
          "Server-Map tables (dynamic and static pinholes)",
          "IPsec Security Associations (SAs)",
          "Local hardware BIOS firmware binaries"], "ABCD",
         "HRP synchronizes configuration rules (security/NAT policies), dynamic session tables, Server-Map entries, and IPsec SA states. BIOS firmware is hardware-specific and not synchronized over HRP."),
        ("VGMP Management Group States", "Which of the following are valid operational states for a VGMP management group on a Huawei firewall?",
         ["Active", "Standby", "Initialize", "Disabled"], "ABC",
         "VGMP management groups operate in Active, Standby, or Initialize states."),
        ("Heartbeat Link Connection Methods", "Which of the following physical connection methods are recommended for HRP heartbeat links between dual firewalls?",
         ["Direct point-to-point connection using a dedicated Ethernet cable",
          "Aggregated link connection using a dedicated Eth-Trunk across multiple physical cables",
          "Connecting through intermediate Layer 2 switches over a dedicated VLAN",
          "Routing heartbeat packets across the public untrusted Internet without encryption"], "ABC",
         "Heartbeat links can be direct physical cables, aggregated Eth-Trunk links, or dedicated isolated VLANs on intermediate switches. Routing cleartext heartbeats across the public Internet is unsafe and unsupported."),
        ("Active/Standby Mode Features", "Which of the following characteristics describe Active/Standby (1+1 Redundancy) mode on Huawei firewalls?",
         ["One firewall actively forwards all user traffic while the peer remains in standby mode",
          "The standby firewall does not forward user traffic under normal conditions",
          "Configuration commands on the active firewall are automatically replicated to the standby firewall",
          "Both firewalls forward 50% of the traffic simultaneously under normal conditions"], "ABC",
         "In Active/Standby mode, only the active unit forwards user traffic; the standby unit maintains synchronized state tables. Distributing traffic 50/50 is the characteristic of Load Balancing mode."),
        ("Load Balancing Mode Features", "Which of the following statements regarding Load-Balancing (Active/Active) hot standby mode are true?",
         ["Both firewalls forward service traffic simultaneously during normal operation",
          "Typically accomplished by configuring two distinct VRRP groups with alternate Master assignments",
          "Requires Quick Session Backup to mitigate asymmetric routing packet drops",
          "If one firewall fails, the surviving firewall takes over 100% of the service traffic"], "ABCD",
         "In Active/Active mode, both firewalls actively forward traffic across different VRRP groups, use quick session backup to handle asymmetric paths, and provide mutual failover if one unit fails."),
        ("Preemption Parameters", "Which parameters are associated with preemption configuration in firewall hot standby?",
         ["Preemption Mode (Enabled or Disabled)",
          "Preemption Delay Timer (in seconds)",
          "Preemption Cable Thickness",
          "Preemption Fan Speed"], "AB",
         "Preemption settings consist of enabling/disabling preemption mode and configuring the preemption delay timer. Physical cable dimensions and fan speeds are unrelated."),
        ("Heartbeat Link Failure Risks", "What severe risks arise if all heartbeat links between two active clustered firewalls are severed simultaneously?",
         ["Split-Brain scenario where both firewalls assume the Active role",
          "IP address conflicts on the Virtual IP address",
          "MAC address flapping on connected switches due to dual Virtual MAC announcements",
          "Complete disruption of network traffic and intermittent session disconnection"], "ABCD",
         "Severing all heartbeat links causes a split-brain condition: both units become Active, generating duplicate VIPs/VMACs, MAC flapping, ARP conflicts, and session collapse."),
        ("HRP Heartbeat Statuses", "When executing `display hrp state`, which of the following are valid heartbeat link interface statuses?",
         ["running (heartbeat link is normal and communicating)",
          "ready (interface is up and ready to send heartbeats)",
          "down (physical link is disconnected or failed)",
          "invalid (misconfigured or unrouted interface)"], "ABCD",
         "HRP heartbeat interfaces report states: `running` (active communication), `ready` (standby heartbeat link ready), `down` (physical link failure), or `invalid` (configuration error)."),
        ("HRP Configuration Synchronization Triggers", "Through which mechanisms can HRP configuration synchronization take place?",
         ["Real-time automatic synchronization when commands are executed on the active firewall",
          "Manual batch synchronization triggered by the administrator (`hrp sync config`)",
          "Automatic batch synchronization upon initial connection establishment",
          "Weekly scheduled reboot of both firewalls"], "ABC",
         "HRP synchronizes configuration in real-time as commands are typed, upon initial cluster handshake, or upon manual execution of `hrp sync config`."),
        ("VRRP Priority Values Significance", "In standard VRRP, what is the significance of the following priority values?",
         ["Priority 255: IP Address Owner (physical IP matches Virtual IP)",
          "Priority 100: Default priority for standard participating routers",
          "Priority 0: Sent by Master router when relinquishing mastership gracefully",
          "Priority 1-254: Configurable range for standard master/backup election"], "ABCD",
         "VRRP defines priority 255 for the IP address owner, priority 0 for graceful relinquishment, default 100, and 1-254 for administrative tuning."),
        ("VGMP Monitored Object Types", "Which network components can be tracked and monitored by VGMP on Huawei firewalls?",
         ["Physical Ethernet interfaces",
          "Logical VLANIF interfaces",
          "Eth-Trunk aggregated link interfaces",
          "IP-Link connectivity probes checking upstream gateway reachability",
          "BFD (Bidirectional Forwarding Detection) sessions"], "ABCDE",
         "VGMP can track physical interfaces, VLANIFs, Eth-Trunks, IP-Link health probes, and BFD sessions to detect link or upstream router failures."),
        ("HRP Packet Contents", "What types of payload data are encapsulated within HRP UDP 18514 packets?",
         ["Heartbeat keepalive hello messages",
          "VGMP group priority negotiation and state notification messages",
          "Configuration command synchronization strings",
          "Session table synchronization records",
          "High-definition video streaming data"], "ABCD",
         "HRP packets carry heartbeat hellos, VGMP state negotiations, synchronized CLI commands, session tables, Server-Map entries, and IPsec SA states."),
        ("Dual-System Hot Standby Benefits", "What operational benefits does dual-system hot standby provide to enterprise networks?",
         ["High service reliability and uninterrupted business continuity",
          "Seamless failover for ongoing voice and video transactions",
          "Protection against single point of failure (SPOF) on perimeter firewalls",
          "Elimination of the need for data backups on corporate file servers"], "ABC",
         "Clustering eliminates SPOF, provides transparent failover, and protects business continuity. It is an operational redundancy technology and does not replace data backups."),
        ("HRP Command Replication Exclusions", "Which types of commands are intentionally EXCLUDED from HRP automatic synchronization between firewalls?",
         ["Interface IP addresses and physical parameters unique to each firewall",
          "HRP local interface configuration commands (`hrp interface`)",
          "Local device hostnames (`sysname`)",
          "Security policies and NAT policy rules"], "ABC",
         "Device-unique settings (local interface IPs, sysnames, HRP interface declarations) must remain unique per box and are not synchronized. Security policies and NAT rules are synchronized."),
        ("Asymmetric Routing Solutions on Firewalls", "Which methods allow stateful firewalls to successfully forward traffic in asymmetric routing topologies?",
         ["Enabling HRP Quick Session Backup between the dual firewalls",
          "Configuring the firewall to disable stateful inspection for specific asymmetric protocols",
          "Engineering upstream and downstream routing protocols to maintain path symmetry",
          "Disconnecting the standby firewall permanently"], "ABC",
         "Asymmetric traffic is handled by synchronizing sessions in real-time (quick session backup), tuning routing protocols for path symmetry, or relaxing stateful checks on asymmetric flows."),
        ("HRP CLI Verification Commands", "Which commands are used to inspect and diagnose Huawei firewall hot standby operations?",
         ["`display hrp state` (checks HRP state and VGMP priorities)",
          "`display hrp interface` (checks heartbeat link operational status)",
          "`display vrrp brief` (displays summary status of all VRRP groups)",
          "`display firewall session table` (verifies session presence)",
          "`reboot fast` (instantly restarts the firewall)"], "ABCD",
         "Hot standby diagnostics utilize `display hrp state`, `display hrp interface`, `display vrrp brief`, and `display firewall session table`. `reboot fast` is a disruptive restart command."),
        ("Standby Unit Local Policy Locking", "What mechanisms ensure policy consistency on the standby firewall during HRP clustering?",
         ["Locking direct configuration of security policies and NAT rules on the standby unit",
          "Displaying the `HRP_S` prompt prefix to alert administrators that the unit is in standby mode",
          "Overwriting standby configuration with active configuration during batch synchronization",
          "Physically disconnecting the standby console cable"], "ABC",
         "HRP enforces consistency by locking configuration edits on the standby unit, changing the prompt to `HRP_S`, and propagating changes from the active unit."),
        ("Quick Session Backup Protocols Supported", "Which protocols benefit significantly from Quick Session Backup in Active/Active asymmetric routing environments?",
         ["TCP connection sessions (SYN/ACK handshakes)",
          "UDP datagram flows (DNS queries and responses)",
          "ICMP Echo query and reply sessions",
          "Analog AM radio broadcasts"], "ABC",
         "Quick session backup synchronizes TCP, UDP, and ICMP session entries immediately upon creation so return packets arriving on the alternate firewall are forwarded without drops."),
        ("VRRP Virtual MAC Gratuitous ARP", "When a VRRP backup firewall transitions to Master, why does it broadcast a Gratuitous ARP packet for the Virtual IP?",
         ["To update the MAC address tables of connected Layer 2 switches, redirecting traffic to its own physical port",
          "To update the ARP caches of connected host endpoints with the Virtual MAC",
          "To force all connected PCs to shut down",
          "To test the maximum speed of the Ethernet switch fabric"], "AB",
         "The new Master broadcasts a Gratuitous ARP for the VIP with the VMAC so that intermediate switches immediately update their CAM tables, directing frames to the new Master's switch port."),
        ("VRRP Master Duties", "Which of the following responsibilities are executed by the VRRP Master router?",
         ["Responding to ARP Requests targeted at the Virtual IP address",
          "Forwarding IP packets destined to the Virtual IP or Virtual MAC address",
          "Periodically transmitting VRRP Advertisement packets to backup routers",
          "Assigning IP addresses to DHCP clients across the entire Internet"], "ABC",
         "The Master responds to ARP for the VIP, forwards user traffic sent to the VIP/VMAC, and sends periodic heartbeat advertisements to backup routers."),
        ("HRP Network Topologies", "In which networking topologies can Huawei firewall hot standby be deployed?",
         ["Upstream and downstream connected to Layer 3 routers",
          "Upstream and downstream connected to Layer 2 switches",
          "Upstream connected to Layer 3 routers and downstream connected to Layer 2 switches",
          "Suspended without electrical power in space"], "ABC",
         "Huawei firewalls support diverse hot standby topologies: L3 routing on both sides, L2 switching on both sides, or hybrid L3-to-L2 gateway deployments."),
        ("VGMP Priority Inversion", "What causes a VGMP priority inversion leading to an automatic cluster switchover?",
         ["Monitored interface link failure on the Active firewall reducing its priority below the Standby unit",
          "Monitored IP-Link or BFD session failure on the Active firewall",
          "Administrative manual priority adjustment or failover command",
          "Upgrading the RAM on an unrelated client computer"], "ABC",
         "Priority inversion occurs when active firewall interface failures, BFD link drops, or administrator manual commands lower active VGMP priority below the standby firewall."),
        ("Heartbeat Interface Best Practices", "Which of the following are recommended best practices for configuring HRP heartbeat interfaces?",
         ["Use dedicated physical interfaces reserved exclusively for heartbeat traffic",
          "Bundle multiple physical links into an Eth-Trunk for link redundancy and increased bandwidth",
          "Configure an HRP authentication key (`hrp key`) to secure heartbeat communications",
          "Ensure MTU settings are identical on both ends of the heartbeat link",
          "Use a public Wi-Fi hotspot as the primary heartbeat link"], "ABCD",
         "Best practices include dedicated interfaces, Eth-Trunk aggregation, cryptographic authentication, and matching MTUs. Wi-Fi is completely unsuitable for heartbeat links."),
        ("IP-Link Monitoring with VGMP", "What is the primary benefit of associating an IP-Link probe with VGMP on a firewall?",
         ["It allows VGMP to monitor reachability to an upstream gateway across intermediate Layer 2 switches",
          "If the upstream gateway stops responding to IP-Link ICMP probes, VGMP priority is decremented to trigger a switchover",
          "It completely replaces the need for firewall security policies",
          "It increases the physical bandwidth of the ISP fiber"], "AB",
         "When firewalls connect to ISPs via intermediate switches, physical interface tracking cannot detect an ISP router failure. IP-Link sends ICMP probes to the ISP gateway; if probes fail, VGMP triggers failover."),
        ("Dual-System Active/Standby Failover Flow", "When the active firewall fails in an Active/Standby deployment, what sequence of events occurs?",
         ["The standby firewall detects missing advertisements / heartbeat loss",
          "The standby VGMP group transitions to Active, promoting all local VRRP groups to Master",
          "The new active firewall sends Gratuitous ARP packets to update switch MAC tables",
          "The new active firewall begins forwarding traffic using its synchronized session table"], "ABCD",
         "Upon failover: 1. Standby detects heartbeat loss; 2. Standby VGMP becomes Active; 3. Local VRRP groups become Master; 4. Gratuitous ARPs update switches; 5. Traffic is forwarded using pre-synchronized sessions."),
        ("HRP Track BFD Feature", "Why is integrating BFD (Bidirectional Forwarding Detection) with VGMP beneficial compared to standard link tracking?",
         ["BFD provides sub-second (millisecond) fault detection across Layer 2 networks",
          "BFD can detect indirect link failures across multi-hop switch networks",
          "BFD eliminates the need for IP addressing",
          "BFD converts all firewall sessions into UDP"], "AB",
         "BFD provides rapid millisecond-level failure detection and detects indirect link failures across transparent switches where physical carrier loss is not signaled to the firewall interface."),
        ("VRRP Virtual IP Configuration Rules", "Which rules must be followed when configuring Virtual IP addresses in VRRP on Huawei firewalls?",
         ["The Virtual IP address must belong to the same IP subnet as the interface's physical IP address",
          "All routers participating in the same VRRP group must be configured with the identical Virtual IP address",
          "The Virtual IP address cannot conflict with any existing physical host IP on the subnet",
          "The Virtual IP address must always be 127.0.0.1"], "ABC",
         "VRRP Virtual IPs must reside on the same subnet as interface physical IPs, must match across all group members, and must not conflict with active host IPs. 127.0.0.1 is local loopback.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 6,
            "chapter_title": "Firewall Hot Standby Technologies",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 6 TRUE/FALSE (28 questions)
    tf_data = [
        ("Five Nines Availability", "'Five nines' availability represents 99.999% network uptime, equating to less than 6 minutes of unscheduled downtime annually.", "A",
         "True. 99.999% availability translates to approximately 5.26 minutes of downtime per year, the gold standard for carrier-grade network availability."),
        ("VRRP Virtual MAC Byte 6", "In the VRRP Virtual MAC address `00-00-5E-00-01-XX`, the last byte `XX` represents the VRID in hexadecimal.", "A",
         "True. The last octet of the VRRP virtual MAC address corresponds directly to the Virtual Router Identifier (VRID) in hexadecimal."),
        ("VRRP Priority 255 Assignment", "An administrator can manually configure a priority value of 255 on a router that does not own the physical IP matching the Virtual IP.", "B",
         "False. Priority 255 is strictly reserved for the IP address owner. Administrators can configure priorities only between 1 and 254."),
        ("VRRP Multicast 224.0.0.18", "VRRP Advertisement packets are sent to the IPv4 multicast address 224.0.0.18.", "A",
         "True. VRRP uses the dedicated multicast address 224.0.0.18 (IP Protocol 112) for master advertisement broadcasts."),
        ("Standalone VRRP Independence Issue", "Standard standalone VRRP groups on multi-interface firewalls automatically coordinate state changes across different interfaces without any additional protocols.", "B",
         "False. Standalone VRRP groups operate independently per interface. A failure on an uplink interface does not trigger a downlink VRRP state change, creating routing black holes."),
        ("VGMP Proprietary Protocol", "VGMP is a Huawei proprietary protocol developed specifically to coordinate state synchronization across multiple VRRP groups on firewalls.", "A",
         "True. VGMP is Huawei proprietary technology that unifies multi-interface VRRP group failovers on USG firewalls."),
        ("VGMP Default Priority 65000", "The default initial priority of both the Active and Standby VGMP management groups on Huawei firewalls is 65000.", "A",
         "True. Both Active and Standby VGMP groups are initialized with a default priority value of 65000."),
        ("VGMP Unified State Transition", "When a firewall's VGMP group switches from Active to Standby, all VRRP groups associated with it switch from Master to Backup simultaneously.", "A",
         "True. VGMP forces all member VRRP groups to transition states simultaneously, preventing routing black holes."),
        ("HRP Heartbeat UDP 18514", "HRP heartbeat packets and synchronization data are transmitted over UDP port 18514.", "A",
         "True. HRP encapsulates its control messages and synchronization records in UDP datagrams using destination port 18514."),
        ("Session Synchronization Importance", "Without real-time session synchronization by HRP, all active TCP connections are dropped when a firewall hot standby failover occurs.", "A",
         "True. Stateful firewalls require session entries to forward traffic. Without session replication, the new active firewall drops established connections, forcing clients to reconnect."),
        ("HRP Real-Time vs Batch", "HRP Real-Time Backup synchronizes session entries immediately as they are created, whereas Batch Backup bulk-synchronizes tables upon initial peer connection or manual trigger.", "A",
         "True. Real-time backup replicates states dynamically per-session, while batch backup performs full synchronization on boot, recovery, or manual command."),
        ("Quick Session Backup in Active/Active", "Quick Session Backup is designed for Active/Active load-balancing mode to prevent packet drops caused by asymmetric routing.", "A",
         "True. Quick session backup immediately replicates sessions so that return packets taking asymmetric paths on the peer firewall match active sessions and are forwarded."),
        ("Active/Standby Traffic Forwarding", "In Active/Standby mode, both firewalls actively forward user service traffic under normal operating conditions.", "B",
         "False. In Active/Standby mode, only the active unit forwards user traffic; the standby firewall remains idle, ready to take over upon failure."),
        ("Active/Active Dual VRRP Groups", "In Load-Balancing mode, dual firewalls typically act as Master for alternate VRRP groups to distribute traffic across subnets.", "A",
         "True. FW1 is Master for Group 1 (backing up Group 2), and FW2 is Master for Group 2 (backing up Group 1), balancing traffic loads."),
        ("Dedicated Heartbeat Link Best Practice", "It is recommended to run HRP heartbeat communications over a dedicated point-to-point link or link-aggregated Eth-Trunk.", "A",
         "True. Dedicated point-to-point links isolate heartbeat traffic and prevent split-brain conditions caused by intermediate switch failures."),
        ("HRP Enable Command Syntax", "The command `hrp enable` activates HRP hot standby functionality in Huawei VRP system view.", "A",
         "True. `hrp enable` is the master command that initializes the HRP process on Huawei firewalls."),
        ("Standby Configuration Lock", "Directly configuring security policies and NAT rules on the Standby firewall is permitted and recommended by Huawei.", "B",
         "False. Configuration edits are locked on the standby unit to prevent policy divergence; configurations must be made on the active unit and replicated via HRP."),
        ("Preemption Delay Convergence", "A preemption delay allows routing protocols and physical links on a recovered primary firewall to stabilize before reclaiming active traffic forwarding.", "A",
         "True. Preemption delay prevents premature traffic switchback while OSPF, BGP, and interfaces are still converging."),
        ("Split-Brain Dual Master State", "In a Split-Brain condition, both firewalls promote themselves to the Active state, causing IP and MAC conflicts on the virtual gateway addresses.", "A",
         "True. When heartbeat connectivity is severed, both units assume the other has failed, promoting themselves to Active and creating severe IP/MAC conflicts."),
        ("Display HRP State Command Output", "The command `display hrp state` provides information regarding VGMP group priorities, active/standby roles, and heartbeat link status.", "A",
         "True. `display hrp state` is the primary diagnostic command for inspecting firewall clustering health and roles."),
        ("IPsec SA Replication", "HRP synchronizes IPsec Security Associations (SAs) so that VPN tunnels do not need to renegotiate when a firewall failover occurs.", "A",
         "True. Replicating IPsec SAs allows the standby firewall to decrypt and encrypt ongoing VPN traffic immediately upon takeover."),
        ("Server-Map Replication", "Server-Map table entries are not synchronized by HRP because they are purely local to each physical firewall.", "B",
         "False. Server-Map entries (for FTP data channels and NAT Server) are synchronized by HRP to preserve active services across failovers."),
        ("Interface IP Synchronization Exclusion", "HRP automatically synchronizes interface IP addresses so that both firewalls have identical physical IP addresses on their interfaces.", "B",
         "False. Interface physical IP addresses must remain unique to each firewall and are intentionally excluded from HRP configuration synchronization."),
        ("IP-Link Remote Monitoring", "IP-Link allows a firewall to monitor upstream gateway reachability through ICMP probes and trigger VGMP priority reduction if the gateway fails.", "A",
         "True. IP-Link detects remote link failures across intermediate switches, enabling VGMP to initiate failover even when local interfaces remain physically UP."),
        ("HRP Authentication Key Security", "Configuring an HRP key (`hrp key`) secures heartbeat communication by verifying packet authenticity between clustered firewalls.", "A",
         "True. HRP authentication keys prevent unauthorized devices from injecting forged heartbeat packets or disrupting the cluster."),
        ("Asymmetric Routing Drop on Stateful Firewalls", "A stateful firewall will drop return traffic packets if it has no matching session entry and stateful inspection is enabled.", "A",
         "True. Stateful firewalls require return packets to correspond to an existing session entry; unsolicited return packets are discarded as invalid state violations."),
        ("Gratuitous ARP on Failover", "When a standby firewall becomes Master, it sends Gratuitous ARP packets to update MAC tables on connected Layer 2 switches.", "A",
         "True. Gratuitous ARPs notify connected switches to redirect frames destined for the Virtual MAC to the new Master's switch port."),
        ("BFD Sub-Second Detection", "Integrating BFD with VGMP enables millisecond-level fault detection, significantly accelerating failover speed compared to standard keepalive timeouts.", "A",
         "True. BFD provides rapid sub-second failure detection, triggering near-instantaneous VGMP priority adjustment and failover.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 6,
            "chapter_title": "Firewall Hot Standby Technologies",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch6_questions()
    print(f"Chapter 6 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
