# scripts/generate_ch10.py
"""
Generates Chapter 10 data: 34 Single Choice, 26 Multiple Choice, 25 True/False.
Chapter 10: PKI Certificate System
"""
import json

def get_ch10_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 10 SINGLE CHOICE (34 questions)
    s_data = [
        ("PKI Fundamental Problem Solved", "What fundamental security challenge does a Public Key Infrastructure (PKI) solve in public-key cryptography?",
         ["Increasing the physical speed of Ethernet cables",
          "The authenticity and binding problem of public keys (preventing attackers from substituting fake public keys)",
          "Eliminating the need for asymmetric mathematics",
          "Translating IPv4 addresses to IPv6 format"], "B",
         "Public-key cryptography requires verifying that a public key genuinely belongs to the claimed identity. Without PKI, an attacker can perform a Man-in-the-Middle attack by substituting a forged public key. PKI binds identities to public keys via trusted digital certificates."),
        ("Digital Certificate Definition", "What is a Digital Certificate in the context of ITU-T X.509 PKI?",
         ["A physical paper diploma issued by a university",
          "An electronic credential digitally signed by a trusted Certificate Authority (CA) that binds a subject identity to its public key",
          "An unencrypted password file stored on a USB drive",
          "A hardware microchip installed on an Ethernet switch"], "B",
         "A digital certificate is a tamper-evident electronic document signed by a trusted CA. It securely binds an identity (the Subject) to its public key, containing validity dates, serial numbers, and usage constraints."),
        ("CA Core Role", "What is the primary operational role of a Certificate Authority (CA) in a PKI system?",
         ["To manufacture physical fiber optic cables",
          "To issue, sign, manage, and revoke digital certificates as an authoritative trusted third party",
          "To assign IP addresses to DHCP clients",
          "To perform high-speed packet routing between autonomous systems"], "B",
         "The Certificate Authority (CA) is the central trusted authority in PKI. The CA verifies identities (or relies on an RA), signs certificates using its private key, manages certificate lifecycles, and publishes revocation information."),
        ("RA Role", "What is the primary function of a Registration Authority (RA) in a PKI deployment?",
         ["To physically route IP packets across the WAN",
          "To accept certificate requests, verify the applicant's real-world identity and credentials, and forward approved requests to the CA",
          "To sign root certificates using its private key",
          "To provide electrical power to the server room"], "B",
         "The Registration Authority (RA) acts as the front-end identity verification officer for the CA. The RA validates the applicant's credentials, organizational standing, and domain ownership before requesting the CA to sign the certificate."),
        ("CRL Definition", "What is a Certificate Revocation List (CRL)?",
         ["A list of all users who have forgotten their passwords",
          "A digitally signed list published periodically by a CA that catalogs the serial numbers of revoked certificates that should no longer be trusted",
          "A routing table containing blackholed IP addresses",
          "A list of physical hardware MAC addresses"], "B",
         "A CRL is a time-stamped, CA-signed list containing the serial numbers of certificates that have been revoked prior to their scheduled expiration date (e.g. due to private key compromise or organizational departure)."),
        ("X.509 Standard Version", "Which version of the ITU-T X.509 standard is universally used for digital certificates in modern network security and SSL/TLS?",
         ["X.509 Version 1", "X.509 Version 2", "X.509 Version 3", "X.509 Version 4"], "C",
         "X.509 Version 3 (RFC 5280) is the prevailing international standard for digital certificates, introducing flexible Extension fields (such as Key Usage, Subject Alternative Name, and Basic Constraints)."),
        ("X.509 Core Field - Serial Number", "What is the requirement for the 'Serial Number' field in an X.509 digital certificate?",
         ["It must be identical for all certificates issued worldwide",
          "It must be a unique positive integer assigned by the issuing CA to distinguish each certificate it issues",
          "It must match the user's telephone number",
          "It must be written in cleartext ASCII English"], "B",
         "Under RFC 5280, the certificate serial number must be a unique positive integer assigned by the issuing CA. No two distinct certificates issued by the same CA may share the same serial number."),
        ("X.509 Validity Period Fields", "Which two time-stamped fields define the active lifespan of an X.509 digital certificate?",
         ["`Start Time` and `End Time`",
          "`Not Before` and `Not After`",
          "`Creation Date` and `Deletion Date`",
          "`Lease Acquired` and `Lease Expired`"], "B",
         "The Validity field in an X.509 certificate contains two timestamps: `Not Before` (the date/time when the certificate becomes valid) and `Not After` (the date/time when the certificate expires)."),
        ("X.509 Subject Field", "In an X.509 certificate, what entity does the 'Subject' field represent?",
         ["The Certificate Authority that issued the certificate",
          "The specific identity (user, server, domain name, or organization) that owns the certificate and holds the corresponding private key",
          "The physical switch port to which the server is connected",
          "The protocol version of the operating system"], "B",
         "The Subject field identifies the entity holding the private key corresponding to the public key certified in the document. The Issuer field identifies the CA that signed the certificate."),
        ("X.509 Subject Public Key Info", "What information is encapsulated within the 'Subject Public Key Info' field of an X.509 certificate?",
         ["The private key of the user in cleartext",
          "The public key algorithm identifier (e.g., RSA or ECC) and the actual public key bit string",
          "The password used to log in to the workstation",
          "The MAC address of the default gateway"], "B",
         "Subject Public Key Info contains the algorithm identifier (e.g., `rsaEncryption` or `id-ecPublicKey`) along with the mathematical public key bits. Private keys are NEVER stored in a digital certificate!"),
        ("X.509 Extension - Basic Constraints", "In X.509 v3, what does the 'Basic Constraints' extension field indicate?",
         ["The maximum bandwidth of the server interface",
          "Whether the certificate belongs to a Certificate Authority (`cA = TRUE`) and the maximum allowed depth of subordinate certification paths",
          "The operating system version of the client computer",
          "The physical dimensions of the server chassis"], "B",
         "Basic Constraints defines whether the certificate subject is a CA (`cA=TRUE`), authorized to sign other certificates, or an end entity (`cA=FALSE`). It can also specify a `pathLenConstraint` limiting the intermediate CA chain depth."),
        ("X.509 Extension - SAN", "Why is the Subject Alternative Name (SAN) extension essential for modern HTTPS web server certificates?",
         ["It allows a single certificate to secure multiple distinct domain names, subdomains, and IP addresses",
          "It permanently disables all firewall security policies",
          "It stores the company's financial accounting records",
          "It converts RSA keys into AES keys"], "A",
         "The SAN extension allows binding multiple hostnames (e.g. `example.com`, `www.example.com`, `mail.example.com`) and IP addresses to a single certificate, replacing legacy single-domain Common Name (CN) matching."),
        ("X.509 Extension - Key Usage", "What is the purpose of the 'Key Usage' extension in an X.509 certificate?",
         ["To count how many times the user logs in per day",
          "To restrict the specific cryptographic operations for which the certified key may be used (e.g., Digital Signature, Key Encipherment, CRL Sign)",
          "To measure the electrical power consumption of the processor",
          "To record the user's physical office room number"], "B",
         "Key Usage defines permissible cryptographic purposes for the public key (e.g., `digitalSignature`, `keyEncipherment`, `keyCertSign`, `cRLSign`), preventing keys intended for signing from being misused for encryption."),
        ("X.509 Extension - Extended Key Usage (EKU)", "Which of the following is a standard purpose specified under the Extended Key Usage (EKU) extension?",
         ["Server Authentication (TLS Web Server)", "Client Authentication", "Code Signing", "All of the above"], "D",
         "EKU defines specific application purposes: Server Authentication (OID 1.3.6.1.5.5.7.3.1), Client Authentication (OID 1.3.6.1.5.5.7.3.2), Code Signing (OID 1.3.6.1.5.5.7.3.3), and Email Protection (S/MIME)."),
        ("X.509 Extension - CDP", "What information is provided by the CRL Distribution Points (CDP) extension in an X.509 certificate?",
         ["The home address of the user",
          "One or more URIs (HTTP or LDAP) where clients can download the latest Certificate Revocation List to verify revocation status",
          "The IP address of the primary DNS root server",
          "The credit card number of the certificate purchaser"], "B",
         "The CDP extension provides URIs (typically HTTP URLs or LDAP paths) indicating where validation software can retrieve the current CRL published by the issuing CA."),
        ("OCSP Protocol Purpose", "What is the Online Certificate Status Protocol (OCSP, RFC 6960)?",
         ["An online banking protocol for wire transfers",
          "A lightweight, real-time query protocol allowing clients to check the revocation status of a specific certificate directly against an OCSP Responder",
          "A routing protocol used to establish BGP peering",
          "A protocol for synchronizing computer motherboard clocks"], "B",
         "OCSP provides real-time certificate status checks. Instead of downloading large multi-megabyte CRL files, a client queries the OCSP responder with a certificate serial number, receiving an immediate signed status response: 'Good', 'Revoked', or 'Unknown'."),
        ("OCSP vs CRL Advantage", "What is the primary operational advantage of OCSP over traditional CRLs?",
         ["OCSP completely eliminates the need for Certificate Authorities",
          "OCSP provides immediate real-time revocation verification with minimal bandwidth consumption, avoiding large periodic CRL downloads",
          "OCSP works without any network connection",
          "OCSP automatically repairs revoked certificates"], "B",
         "Traditional CRLs suffer from publication delays (a revoked key remains accepted until the next CRL is published) and heavy bandwidth overhead. OCSP queries provide real-time status with tiny request/response packets."),
        ("OCSP Stapling Mechanism", "How does 'OCSP Stapling' (RFC 6066) optimize TLS connection establishment for web clients?",
         ["The web server periodically queries the OCSP responder and attaches ('staples') the time-stamped, CA-signed OCSP response directly into the TLS handshake to the client",
          "The client physically staples a paper certificate to its computer monitor",
          "The client disables certificate validation entirely to accelerate connection speed",
          "The web server forces all clients to download the entire CRL database"], "A",
         "In OCSP Stapling, the web server caches a signed OCSP response from the CA and includes it in the initial TLS handshake. This eliminates client latency from querying external OCSP responders and protects user privacy from tracking."),
        ("Root CA Characteristics", "What is a defining characteristic of a 'Root CA' certificate in a hierarchical PKI?",
         ["It is signed by an external commercial ISP",
          "It is self-signed (the Issuer field matches the Subject field) and serves as the ultimate trust anchor",
          "It must be renewed every 24 hours",
          "It contains the private keys of all subordinate users"], "B",
         "A Root CA sits at the top of the trust tree. Its certificate is self-signed (`Issuer == Subject`) and signed with its own private key. Operating systems and browsers pre-install Root CA certificates as trusted anchors."),
        ("Intermediate CA Role", "Why do enterprise PKI architectures deploy Intermediate (Subordinate) CAs rather than issuing end-entity certificates directly from the Root CA?",
         ["Because Root CAs cannot issue certificates to web servers",
          "To protect the Root CA private key in an offline, physically secured vault, minimizing root compromise risk while the Intermediate CA handles daily operational issuance",
          "To convert public certificates into symmetric keys",
          "To comply with international maritime radio standards"], "B",
         "Best practice keeps the Root CA offline in a secure, air-gapped safe. Intermediate CAs are issued to handle day-to-day certificate signing. If an intermediate CA is compromised, it can be revoked without invalidating the entire root trust anchor."),
        ("Certificate Chain Verification", "How does a client validate a certificate chain presented by a web server (Server Cert -> Intermediate CA -> Root CA)?",
         ["By verifying the digital signature on each certificate in the path using the issuing CA's public key up to a pre-installed trusted Root CA",
          "By sending the server's private key to the FBI for review",
          "By calculating the square root of the certificate serial number",
          "By converting the certificate into an uncompressed audio file"], "A",
         "The client verifies each link in the hierarchical chain: Server Cert signature is verified with Intermediate CA's public key; Intermediate CA signature is verified with Root CA's public key; Root CA is confirmed present in the client's local trust store."),
        ("Certificate Revocation Reasons", "Under which of the following circumstances MUST a digital certificate be immediately revoked by the CA?",
         ["The private key corresponding to the certificate has been stolen or compromised",
          "The employee owning the certificate has resigned or been terminated from the enterprise",
          "The certified fully qualified domain name (FQDN) has been transferred to a different organization",
          "All of the above"], "D",
         "Certificates must be revoked whenever private key compromise occurs, employee affiliation ends, domain ownership shifts, or operational parameters become untrusted."),
        ("Self-Signed Certificate Insecurity", "Why does a web browser display an untrusted security warning when visiting a website using a self-signed certificate?",
         ["The browser cannot calculate the AES encryption algorithm",
          "The self-signed certificate was not signed by a Certificate Authority pre-installed in the browser's trusted root store, meaning its identity cannot be verified against a trusted anchor",
          "Self-signed certificates cannot encrypt network data",
          "The website has physically disconnected its network card"], "B",
         "Self-signed certificates are signed by their own private key, not by an established CA. Because the browser has no pre-existing trust anchor for that signer, it cannot verify the server's identity and warns of potential Man-in-the-Middle spoofing."),
        ("Certificate Signing Request (CSR)", "What is a Certificate Signing Request (CSR) generated by an administrator when applying for a digital certificate?",
         ["A request to purchase new server hardware",
          "A standardized file containing the applicant's public key, distinguished name (DN), and signature proving possession of the private key",
          "A file containing the applicant's secret private key in cleartext",
          "An administrative invoice submitted to the finance department"], "B",
         "A CSR (standardized in PKCS#10) contains the applicant's public key and subject information, signed with the applicant's private key (proving possession of the key). The private key itself remains confidential on the local server."),
        ("PKCS#12 File Format", "What is the standard purpose of the PKCS#12 (`.p12` / `.pfx`) file format?",
         ["A portable, password-encrypted archive format used to store and transfer an entity's private key along with its digital certificate and certificate chain",
          "A cleartext format used to display website logos",
          "An uncompressed video format used in security cameras",
          "A routing protocol configuration file"], "A",
         "PKCS#12 defines an encrypted container format (protected by a symmetric password) designed to bundle private keys, user certificates, and intermediate CA certificates for secure backup and device import."),
        ("PEM File Format", "What is the PEM (Privacy Enhanced Mail) certificate format commonly seen on Linux and Apache servers?",
         ["A binary format that can only be opened with specialized hex editors",
          "A Base64-encoded ASCII text format delimited by header and footer lines (e.g., `-----BEGIN CERTIFICATE-----`)",
          "An encrypted USB dongle",
          "A proprietary database format used by Microsoft Word"], "B",
         "PEM is the most common certificate container format in open systems, encoding binary DER data into ASCII Base64 text framed by headers like `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----`."),
        ("DER File Format", "What is the DER (Distinguished Encoding Rules) certificate format?",
         ["A Base64 ASCII text format used in web emails",
          "A raw binary encoding format for X.509 certificates commonly used in Java and Windows environments",
          "A physical hardware device used to generate random numbers",
          "A script used to configure firewall security policies"], "B",
         "DER is the binary representation of an X.509 certificate according to ASN.1 encoding rules, commonly identified by `.der` or `.cer` extensions in Windows and Java environments."),
        ("Cross-Certification Concept", "What is 'Cross-Certification' in enterprise PKI architectures?",
         ["Two independent CAs issue digital certificates to each other, establishing mutual trust between different organizations or PKI domains",
          "Crossing copper Ethernet cables to create a crossover link",
          "Encrypting data twice using different symmetric keys",
          "Re-installing the operating system on the primary CA server"], "A",
         "Cross-certification allows two distinct PKI hierarchies (e.g. two merging enterprises or government agencies) to establish mutual trust without sharing a common Root CA by having each CA issue a cross-certificate to the other."),
        ("CA Private Key Protection", "Which hardware technology is recommended as best practice for storing and protecting the private key of a high-assurance Root CA?",
         ["A standard unencrypted desktop hard drive",
          "A dedicated tamper-resistant Hardware Security Module (HSM)",
          "A shared network folder accessible by all employees",
          "An unencrypted USB flash drive kept in an unlocked desk drawer"], "B",
         "Hardware Security Modules (HSMs) provide physical tamper resistance, certified cryptographic boundaries (e.g. FIPS 140-2 Level 3), and ensure that private keys can never be exported in plaintext."),
        ("Trust Anchor Definition", "In public key infrastructure, what is a 'Trust Anchor'?",
         ["A heavy iron weight placed on server racks to prevent theft",
          "An authoritative entity (typically a self-signed Root CA certificate) that is trusted by default without requiring an external cryptographic signature",
          "A physical anchor attached to undersea fiber cables",
          "A domain controller with a static IP address"], "B",
         "A Trust Anchor is the foundational root certificate explicitly trusted by an operating system, browser, or device. All certificate validation paths must terminate at an established trust anchor."),
        ("AIA Extension Purpose", "What information does the Authority Information Access (AIA) extension provide to a certificate-validating client?",
         ["The home phone number of the CA administrator",
          "URIs indicating where the client can retrieve the issuing CA's certificate and the location of the CA's OCSP responder service",
          "The internal IP address of the user's default gateway",
          "The physical room temperature of the data center"], "B",
         "The AIA extension provides two critical endpoints: the HTTP URI to fetch the parent/issuing CA certificate (for building chains) and the OCSP responder URI (for real-time status verification)."),
        ("Expired Certificate Behavior", "What happens when a client software attempts to validate an X.509 certificate whose `Not After` date has passed?",
         ["The client automatically updates the date on the certificate",
          "The certificate validation fails immediately with an expired certificate error, and the connection is flagged as untrusted",
          "The client ignores the date and permits the connection with full trust",
          "The computer turns off its network adapter"], "B",
         "During path validation, the client checks current system time against `Not Before` and `Not After`. If current time exceeds `Not After`, the certificate is expired and validation fails, raising security warnings."),
        ("Subject DN Component 'C'", "In an X.509 Distinguished Name (e.g. `C=CN, O=Huawei, CN=www.huawei.com`), what does the attribute 'C' represent?",
         ["City", "Country (two-letter ISO code)", "Company", "Certificate"], "B",
         "In X.500/X.509 Distinguished Name syntax, `C` represents the Country (standard two-letter ISO 3166 code, such as `CN`, `US`, `FR`). City is represented by `L` (Locality), and Company is `O` (Organization)."),
        ("PKI Certificate Repository", "What is the function of a Certificate Repository in PKI?",
         ["A public directory (accessible via LDAP or HTTP) where valid end-entity certificates, CA certificates, and CRLs are stored for public retrieval",
          "A secure vault where private keys are openly published for download",
          "A scrap storage bin for discarded networking cables",
          "A database storing employee salaries"], "A",
         "A Certificate Repository is a publicly accessible directory or web server that stores issued public certificates and published CRLs, enabling communicating parties to discover certificates and verify status.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 10,
            "chapter_title": "PKI Certificate System",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 10 MULTIPLE CHOICE (26 questions)
    m_data = [
        ("PKI Core Entities", "Which of the following entities constitute fundamental components of a Public Key Infrastructure (PKI)?",
         ["Certificate Authority (CA)",
          "Registration Authority (RA)",
          "Certificate Repository / Directory",
          "Certificate Revocation List (CRL) and OCSP Responder",
          "End Entity (Subscribers and Relying Parties)"], "ABCDE",
         "A complete PKI comprises the CA (issuer), RA (identity verifier), Repository/Directory (storage), Revocation mechanisms (CRL/OCSP), and End Entities (certificate holders and relying parties)."),
        ("Standard X.509 v3 Header Fields", "Which of the following fields are defined in the standard X.509 v3 certificate structure?",
         ["Version number",
          "Serial Number",
          "Signature Algorithm Identifier",
          "Issuer Distinguished Name",
          "Validity Period (Not Before, Not After)",
          "Subject Distinguished Name",
          "Subject Public Key Info"], "ABCDEFG",
         "Standard X.509 fields include Version, Serial Number, Signature Algorithm, Issuer, Validity Period, Subject, Subject Public Key Info, and optional Extensions."),
        ("Key X.509 v3 Extensions", "Which of the following are standardized X.509 v3 extension fields commonly used in modern digital certificates?",
         ["Basic Constraints",
          "Key Usage",
          "Extended Key Usage (EKU)",
          "Subject Alternative Name (SAN)",
          "CRL Distribution Points (CDP)",
          "Authority Information Access (AIA)"], "ABCDEF",
         "Crucial v3 extensions include Basic Constraints (CA flag), Key Usage, EKU, SAN (multi-domain bindings), CDP (CRL URIs), and AIA (OCSP URIs)."),
        ("Revocation Checking Mechanisms", "Which two primary mechanisms are utilized in PKI to verify whether a digital certificate has been revoked prior to expiration?",
         ["Certificate Revocation Lists (CRLs)",
          "Online Certificate Status Protocol (OCSP)",
          "BGP Route Withdrawals",
          "ARP Cache Flushing"], "AB",
         "PKI relies on two revocation verification systems: periodic, signed CRLs and real-time interactive OCSP query/response transactions."),
        ("CRL Drawbacks", "What are the primary operational challenges and drawbacks associated with traditional CRLs?",
         ["Time latency between publication intervals (a revoked certificate remains accepted until the next CRL is fetched)",
          "Increasing file size and bandwidth consumption as the list of revoked certificates expands",
          "High network overhead when millions of clients download large CRLs simultaneously",
          "CRLs cannot be verified mathematically"], "ABC",
         "CRLs suffer from latency between update windows, scaling bandwidth bottlenecks as revocation lists expand, and high download overhead across client fleets. CRLs are cryptographically signed by the CA."),
        ("OCSP Operational Advantages", "What operational benefits does OCSP provide compared to traditional CRLs?",
         ["Real-time status verification at the exact moment of connection establishment",
          "Lightweight query and response packet sizes, conserving bandwidth",
          "Reduced client processing overhead compared to parsing massive CRL files",
          "Eliminating the need for Root CAs"], "ABC",
         "OCSP provides instantaneous real-time status with tiny request/response packets, eliminating CRL download overhead. Root CAs are still required as trust anchors."),
        ("Common Reasons for Certificate Revocation", "Under which circumstances should an enterprise administrator request certificate revocation?",
         ["The private key corresponding to the certificate has been stolen or compromised",
          "An employee possessing an individual client certificate has left the organization",
          "The server's fully qualified domain name (FQDN) or IP has changed",
          "The issuing CA's own private key has been compromised"], "ABCD",
         "Revocation is mandatory upon private key loss/compromise, organizational role change, domain reassignment, or CA infrastructure compromise."),
        ("Certificate Chain Path Validation Checks", "When a client verifies a multi-tier certificate chain, which checks must pass successfully for every certificate in the path?",
         ["Cryptographic digital signature verification using the parent CA's public key",
          "Current system date falls within the certificate's `Not Before` and `Not After` validity window",
          "Revocation status check via CRL or OCSP confirms the certificate is not revoked",
          "Basic Constraints confirms that intermediate certificates are authorized CAs (`cA=TRUE`)",
          "The terminal Root CA is present in the client's local trusted root store"], "ABCDE",
         "Full path validation verifies digital signatures, valid date ranges, non-revocation status, proper CA constraints, and linkage to a locally trusted root anchor."),
        ("Key Usage Extension Attributes", "Which of the following specific cryptographic purposes can be designated in the Key Usage extension?",
         ["Digital Signature (verifying software signatures and identity)",
          "Key Encipherment (encrypting symmetric session keys, e.g. RSA key exchange)",
          "Data Encipherment (direct payload encryption)",
          "Certificate Signing (`keyCertSign` - verifying other certificates)",
          "CRL Signing (`cRLSign` - verifying revocation lists)"], "ABCDE",
         "Standard Key Usage bits include `digitalSignature`, `keyEncipherment`, `dataEncipherment`, `keyCertSign`, and `cRLSign`."),
        ("Extended Key Usage (EKU) Standard Purposes", "Which of the following application purposes are defined in the Extended Key Usage (EKU) extension?",
         ["TLS Web Server Authentication (OID 1.3.6.1.5.5.7.3.1)",
          "TLS Web Client Authentication (OID 1.3.6.1.5.5.7.3.2)",
          "Code Signing (OID 1.3.6.1.5.5.7.3.3)",
          "Email Protection / S/MIME (OID 1.3.6.1.5.5.7.3.4)",
          "Automated Teller Machine Currency Dispensing"], "ABCD",
         "EKU defines Server Auth, Client Auth, Code Signing, and Email Protection. ATM currency dispensing is an external physical application."),
        ("Distinguished Name (DN) Common Attributes", "Which of the following naming attributes are commonly included in an X.500/X.509 Distinguished Name (DN)?",
         ["CN: Common Name (e.g. `www.huawei.com`)",
          "O: Organization Name (e.g. `Huawei Technologies`)",
          "OU: Organizational Unit (e.g. `Security Dept`)",
          "C: Country Code (e.g. `CN`)",
          "L: Locality / City (e.g. `Shenzhen`)"], "ABCDE",
         "Standard X.500 DN components include CN (Common Name), O (Organization), OU (Organizational Unit), C (Country), ST (State/Province), and L (Locality/City)."),
        ("PKI Hierarchical Architecture Components", "In a multi-tier hierarchical PKI deployment, which tiers are typically established?",
         ["Offline Root CA (serves as the ultimate trust anchor, kept offline for security)",
          "Online Intermediate / Issuing CAs (issued by Root CA, handles daily certificate issuance)",
          "End Entities (web servers, firewalls, VPN gateways, user workstations)",
          "Quantum Key Distribution Satellite Network"], "ABC",
         "Hierarchical PKIs employ an offline Root CA, online Intermediate/Issuing CAs, and End Entities (servers, gateways, users)."),
        ("CSR Contents", "Which items are packaged inside a standard Certificate Signing Request (CSR, PKCS#10)?",
         ["The applicant's public key",
          "The applicant's Distinguished Name (DN) and subject attributes",
          "A digital signature generated by the applicant's private key to prove key possession",
          "The applicant's secret private key in cleartext"], "ABC",
         "A CSR includes the public key, identity attributes, and a proof-of-possession signature. Private keys are NEVER included in a CSR!"),
        ("Common Certificate File Formats", "Which file extensions and encoding formats are standard in digital certificate management?",
         [".CRT / .CER (X.509 certificate in PEM or DER format)",
          ".KEY (Private key file)",
          ".CSR (Certificate Signing Request)",
          ".PFX / .P12 (PKCS#12 password-protected container holding certificate and private key)",
          ".EXE (Executable malware installer)"], "ABCD",
         "Standard certificate formats: `.crt`/`.cer` (certificates), `.key` (private keys), `.csr` (signing requests), and `.pfx`/`.p12` (encrypted key+cert archives). `.exe` is an executable binary."),
        ("OCSP Response Statuses", "When an OCSP Responder replies to a client certificate status query, which three definitive statuses can it return?",
         ["Good (the certificate is valid and not revoked)",
          "Revoked (the certificate has been revoked)",
          "Unknown (the responder has no record of the certificate)",
          "Encrypted (the certificate is locked)"], "ABC",
         "RFC 6960 mandates three status responses: `Good` (valid), `Revoked` (revoked), and `Unknown` (unrecognized serial number)."),
        ("OCSP Stapling Benefits", "What are the primary operational benefits of implementing OCSP Stapling on web servers?",
         ["Eliminates client-side DNS lookups and latency to external CA OCSP responders",
          "Protects client browsing privacy by preventing the CA from tracking which sites users visit",
          "Reduces the query load on the CA's centralized OCSP infrastructure",
          "Completely removes the need for web servers to use digital certificates"], "ABC",
         "OCSP stapling eliminates client latency, shields client IP privacy from the CA, and reduces load on CA servers. Digital certificates are still required."),
        ("SAN Extension Supported Types", "Which identity types can be embedded within the Subject Alternative Name (SAN) extension?",
         ["DNS Hostnames (e.g. `api.example.com`)",
          "IPv4 and IPv6 Addresses (e.g. `192.168.1.1`, `2001:db8::1`)",
          "Uniform Resource Identifiers (URIs)",
          "Email Addresses (RFC 822 names)",
          "Processor Hardware Clock Frequencies"], "ABCD",
         "SAN supports DNS names, IP addresses, URIs, and email addresses. Processor frequencies are hardware metrics."),
        ("Hardware Security Module (HSM) Benefits", "Why do enterprise CAs utilize Hardware Security Modules (HSMs) to protect their private keys?",
         ["Physical tamper-responsive hardware that zeroizes keys upon physical attack",
          "Private keys are generated and used inside cryptographic boundary and never leave in plaintext",
          "FIPS 140-2 / 140-3 security certification compliance",
          "HSMs convert copper cables into wireless antennas"], "ABC",
         "HSMs provide tamper resistance, secure internal key generation/usage, and cryptographic compliance, preventing private key theft."),
        ("Trust Store Locations", "Where are Root CA certificates typically stored on client operating systems and software?",
         ["Windows Certificate Store (Trusted Root Certification Authorities)",
          "macOS Keychain Access (System Roots)",
          "Mozilla Firefox internal certificate database (NSS store)",
          "Linux `/etc/ssl/certs/` directory",
          "The monitor power cord"], "ABCD",
         "Trusted roots reside in OS stores (Windows Certificate Store, macOS Keychain, Linux `/etc/ssl/certs/`) and independent browser stores (Firefox NSS)."),
        ("Public vs Private Enterprise PKI", "Which statements correctly contrast Public CAs (e.g. DigiCert, Let's Encrypt) and Private Enterprise CAs (e.g. Microsoft AD CS)?",
         ["Public CAs have root certificates pre-installed in global browsers and OSs by default",
          "Private Enterprise CAs require manual or GPO distribution of root certificates to internal endpoints",
          "Private CAs are ideal for internal VPN gateways, intranet servers, and employee 802.1X authentication",
          "Public CAs issue certificates free of charge for internal unroutable `.local` domains"], "ABC",
         "Public CAs are globally trusted out-of-the-box for public websites. Private CAs require internal root distribution (via GPO) and are optimal for internal VPNs, servers, and 802.1X. Public CAs cannot issue certificates for internal `.local` domains."),
        ("Subject Alternative Name (SAN) Multi-Domain", "In which scenarios is a SAN certificate preferable to multiple individual single-domain certificates?",
         ["Securing multiple subdomains (e.g. `mail.corp.com`, `vpn.corp.com`, `portal.corp.com`) under one certificate",
          "Unified Communications environments (e.g. Microsoft Exchange) requiring diverse service FQDNs",
          "Simplifying certificate management, renewal, and deployment across load-balanced clusters",
          "Decreasing the physical weight of server chassis"], "ABC",
         "SAN certificates consolidate multiple domains/services onto one certificate, simplifying deployment across Exchange servers, microservices, and multi-domain web clusters."),
        ("Certificate Lifecycle Stages", "Which of the following are recognized stages in the end-to-end digital certificate lifecycle?",
         ["Key Pair Generation and CSR Submission",
          "Identity Verification and Certificate Issuance",
          "Certificate Installation and Usage Monitoring",
          "Certificate Renewal or Revocation upon Expiration/Compromise"], "ABCD",
         "The certificate lifecycle spans generation/CSR, validation/issuance, deployment/monitoring, and renewal/revocation."),
        ("Reasons for Self-Signed Certificate Warnings", "Why should self-signed certificates be avoided on public-facing corporate web servers?",
         ["Visitors encounter alarming browser security warnings indicating the site is not trusted",
          "Users cannot verify whether the connection is reaching the genuine server or an MitM attacker",
          "It harms organizational brand reputation and deters customer engagement",
          "Self-signed certificates cannot encrypt data using AES"], "ABC",
         "Self-signed certificates trigger browser untrusted warnings, leave users vulnerable to MitM attacks, and degrade brand trust. They can still technically perform AES encryption, but lack trust verification."),
        ("Authority Information Access (AIA) Pointers", "Which critical URLs are discovered by client software via the AIA extension?",
         ["The URL of the issuing CA certificate (allowing the client to fetch missing intermediate CAs)",
          "The URL of the issuing CA's OCSP responder service",
          "The URL of the client's home social media feed",
          "The URL to download free computer games"], "AB",
         "AIA specifies where to fetch missing intermediate CA certificates (`id-ad-caIssuers`) and the OCSP responder URL (`id-ad-ocsp`)."),
        ("Cross-Certification Use Cases", "When is cross-certification implemented between distinct PKI infrastructures?",
         ["Corporate mergers and acquisitions between companies with existing internal PKIs",
          "Government inter-agency secure communications across different departmental CAs",
          "B2B secure supply chain electronic data exchange",
          "Connecting a microwave oven to the Internet"], "ABC",
         "Cross-certification enables mutual trust between merging enterprises, inter-governmental agencies, and B2B federations without replacing existing Root CAs."),
        ("Certificate Renewal vs Re-Keying", "How does Certificate Re-Keying differ from standard Certificate Renewal?",
         ["Renewal extends the validity period using the existing public/private key pair",
          "Re-Keying generates a brand new cryptographic key pair while issuing an updated certificate",
          "Re-Keying is recommended if an existing key has been in use for an extended duration or if policy mandates key rotation",
          "Renewal permanently erases the server operating system"], "ABC",
         "Renewal extends dates with the same key. Re-keying generates a fresh key pair, recommended periodically to limit exposure against cryptanalytic attacks.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 10,
            "chapter_title": "PKI Certificate System",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 10 TRUE/FALSE (25 questions)
    tf_data = [
        ("PKI Public Key Binding", "A primary function of PKI is to securely bind an identity (Subject) to its public key using a digitally signed certificate.", "A",
         "True. PKI establishes identity verification by linking public keys to verified entities through signed X.509 certificates."),
        ("Private Key in Certificate", "An X.509 digital certificate contains both the subject's Public Key and their secret Private Key.", "B",
         "False. A digital certificate contains ONLY the Public Key. The Private Key must remain strictly confidential and is never stored in a certificate."),
        ("CA Signs with Private Key", "A Certificate Authority signs issued digital certificates using its own CA Private Key.", "A",
         "True. The CA uses its private key to generate the digital signature on certificates, which clients verify using the CA's public key."),
        ("Registration Authority Signing", "A Registration Authority (RA) is responsible for signing certificates with its own root private key.", "B",
         "False. The RA verifies applicant identities and approves requests; the Certificate Authority (CA) signs and issues certificates."),
        ("X.509 Serial Number Uniqueness", "Under the X.509 standard, a CA must assign a unique serial number to every certificate it issues.", "A",
         "True. RFC 5280 requires that each certificate issued by a CA possess a unique positive serial number within that CA's domain."),
        ("Certificate Lifespan Validity", "A certificate is considered valid only when the current system time falls between its `Not Before` and `Not After` timestamps.", "A",
         "True. Certificates are valid strictly within the designated validity period; before `Not Before` or after `Not After`, validation fails."),
        ("Basic Constraints CA Flag", "The Basic Constraints extension in an end-entity server certificate typically has `cA = TRUE`.", "B",
         "False. End-entity certificates have `cA = FALSE` (not a CA). Only Root and Intermediate CAs have `cA = TRUE` allowing them to sign other certificates."),
        ("SAN Multi-Domain Support", "The Subject Alternative Name (SAN) extension allows a single certificate to protect multiple distinct domain names and IP addresses.", "A",
         "True. SAN binds multiple hostnames, subdomains, and IP addresses to a single certificate."),
        ("CRL Periodic Publishing", "A Certificate Revocation List (CRL) is published periodically by the CA to list certificates that have been revoked before expiration.", "A",
         "True. CRLs are signed lists published at regular intervals cataloging serial numbers of revoked certificates."),
        ("OCSP Real-Time Query", "OCSP provides real-time certificate status checks by sending a lightweight query to an OCSP responder for a specific certificate serial number.", "A",
         "True. OCSP queries verify status on the fly with tiny packets, eliminating large CRL download overhead."),
        ("OCSP Stapling Server Role", "In OCSP Stapling, the web server queries the OCSP responder and attaches the signed OCSP response directly into the TLS handshake.", "A",
         "True. OCSP stapling delivers a cached, signed OCSP response from the server during the handshake, improving client speed and privacy."),
        ("Root CA Self-Signed Anchor", "A Root CA certificate is self-signed, meaning its Issuer field is identical to its Subject field.", "A",
         "True. Root CAs are self-signed trust anchors where Issuer and Subject distinguished names match."),
        ("Intermediate CA Offline Requirement", "Best security practice mandates keeping Intermediate CAs offline in an air-gapped vault while the Root CA is online 24/7.", "B",
         "False. The Root CA is kept offline for maximum security, while Intermediate CAs remain online to handle routine certificate issuance."),
        ("Certificate Chain Verification Top-Down", "Clients verify certificate chains by establishing mathematical trust links from the server certificate up to a trusted Root CA anchor.", "A",
         "True. Path validation verifies digital signatures sequentially up the chain to a pre-installed trusted root anchor."),
        ("Private Key Compromise Revocation", "If a server's private key is stolen, the administrator must immediately request certificate revocation from the CA.", "A",
         "True. Private key theft compromises data confidentiality and authentication; immediate revocation prevents impersonation."),
        ("CSR Private Key Cleartext", "A Certificate Signing Request (CSR) file sent to a commercial CA contains the applicant's unencrypted private key.", "B",
         "False. A CSR contains the public key and subject details, signed by the private key as proof of possession. Private keys are NEVER transmitted in a CSR!"),
        ("PKCS#12 Encrypted Container", "A PKCS#12 file (`.pfx` or `.p12`) can package a private key and its corresponding digital certificate inside a password-protected archive.", "A",
         "True. PKCS#12 archives bundle certificates and private keys securely using symmetric password encryption."),
        ("PEM ASCII Base64 Encoding", "PEM format certificates are Base64-encoded ASCII text files framed by `-----BEGIN CERTIFICATE-----` headers.", "A",
         "True. PEM is a standardized ASCII Base64 encoding format widely used across open systems."),
        ("Key Usage Digital Signature", "The Key Usage extension can restrict a public key to digital signatures only, prohibiting it from being used for key encipherment.", "A",
         "True. Key Usage enforces least privilege for cryptographic keys, separating signing capabilities from encryption capabilities."),
        ("CDP Extension URI", "The CRL Distribution Points (CDP) extension provides URIs where clients can download updated CRLs.", "A",
         "True. The CDP extension guides client software to HTTP or LDAP locations where the issuing CA publishes CRLs."),
        ("AIA Missing Intermediate Fetching", "The AIA extension enables validating clients to automatically download missing intermediate CA certificates from specified URLs.", "A",
         "True. AIA provides pointers to issuing CA certificates, allowing clients to reconstruct incomplete certificate chains."),
        ("Expired Certificate Warning", "Web browsers ignore certificate expiration dates if the website's domain name matches the certificate Subject CN.", "B",
         "False. Browsers enforce strict validity checks; an expired certificate triggers immediate security warning pages regardless of domain match."),
        ("Wildcard Certificate Subdomain Matching", "A wildcard certificate issued for `*.example.com` automatically protects multi-level subdomains like `dev.mail.example.com`.", "B",
         "False. Standard wildcard certificates protect only a single subdomain level (e.g. `mail.example.com`), not nested multi-level subdomains (`dev.mail.example.com`)."),
        ("Cross-Certification Mutual Trust", "Cross-certification enables two separate PKI hierarchies to trust each other's certificates without creating a new shared Root CA.", "A",
         "True. Mutual cross-certification creates trust bridges between distinct organizations' existing PKI domains."),
        ("Hardware Security Module (HSM) Key Export", "A certified Hardware Security Module (HSM) allows anyone on the local network to export CA root private keys in cleartext.", "B",
         "False. HSMs enforce physical tamper resistance and strictly prevent private keys from being extracted in cleartext.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 10,
            "chapter_title": "PKI Certificate System",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch10_questions()
    print(f"Chapter 10 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
