# scripts/generate_ch2.py
"""
Generates Chapter 2 data: 44 Single Choice, 34 Multiple Choice, 32 True/False.
"""
import json

def get_ch2_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 2 SINGLE CHOICE (44 questions)
    s_data = [
        ("OSI Model Layers", "How many layers are defined in the Open Systems Interconnection (OSI) reference model?",
         ["4 layers", "5 layers", "7 layers", "8 layers"], "C",
         "The OSI reference model standardizes network communication into 7 distinct layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application."),
        ("OSI Layer 3 PDU", "What is the Protocol Data Unit (PDU) termed at Layer 3 (Network Layer) of the OSI model?",
         ["Bit", "Frame", "Packet", "Segment"], "C",
         "PDUs across OSI layers: Layer 1 = Bit; Layer 2 = Frame; Layer 3 = Packet; Layer 4 = Segment; Layers 5-7 = Data."),
        ("OSI vs TCP/IP Mapping", "Which OSI layers are consolidated into the single Application layer in the 4-layer TCP/IP model?",
         ["Physical and Data Link layers", "Data Link and Network layers", "Session, Presentation, and Application layers", "Transport and Session layers"], "C",
         "The TCP/IP model merges the functions of OSI Layer 5 (Session), Layer 6 (Presentation), and Layer 7 (Application) into a single Application Layer."),
        ("Ethernet Frame MAC Length", "In a standard Ethernet II frame, what is the length in bytes of the Destination MAC address field?",
         ["4 bytes", "6 bytes", "8 bytes", "16 bytes"], "B",
         "An Ethernet MAC address is 48 bits (6 bytes) long. An Ethernet II frame header contains a 6-byte Destination MAC followed by a 6-byte Source MAC and a 2-byte Type field."),
        ("Ethernet EtherType IPv4", "What is the hexadecimal EtherType value indicating that the payload of an Ethernet II frame is an IPv4 packet?",
         ["0x0806", "0x0800", "0x86DD", "0x8100"], "B",
         "Standard EtherType values: 0x0800 indicates IPv4; 0x0806 indicates ARP; 0x86DD indicates IPv6; 0x8100 indicates an IEEE 802.1Q tagged frame."),
        ("Ethernet EtherType ARP", "Which EtherType value indicates an Address Resolution Protocol (ARP) frame?",
         ["0x0800", "0x0806", "0x86DD", "0x8847"], "B",
         "EtherType 0x0806 is assigned specifically to the Address Resolution Protocol (ARP)."),
        ("Ethernet MTU", "What is the standard default Maximum Transmission Unit (MTU) size for an Ethernet interface payload?",
         ["576 bytes", "1480 bytes", "1500 bytes", "9000 bytes"], "C",
         "The standard default MTU for Ethernet is 1500 bytes. This defines the maximum size of the Layer 3 packet (IP header + payload) that can be encapsulated into an Ethernet frame without fragmentation."),
        ("IPv4 Header Minimum Size", "What is the minimum length of an IPv4 packet header when no optional fields are present?",
         ["16 bytes", "20 bytes", "32 bytes", "40 bytes"], "B",
         "The standard base IPv4 header with no options contains 5 rows of 32 bits (4 bytes) each, resulting in a minimum length of 20 bytes."),
        ("IPv4 Header IHL Field", "In an IPv4 header, the Internet Header Length (IHL) field has a value of 5. How many total bytes does the IP header contain?",
         ["5 bytes", "10 bytes", "20 bytes", "25 bytes"], "C",
         "The IHL field specifies the IP header length in 32-bit (4-byte) words. Therefore, an IHL of 5 represents 5 * 4 = 20 bytes."),
        ("IPv4 Header TTL Purpose", "What is the primary function of the Time to Live (TTL) field in an IPv4 header?",
         ["To record the exact timestamp when the packet was created",
          "To prevent packets from circulating endlessly in routing loops",
          "To calculate the round-trip latency between source and destination hosts",
          "To negotiate the maximum TCP sliding window buffer size"], "B",
         "The TTL field is decremented by 1 at each router hop. When TTL reaches 0, the packet is discarded and an ICMP Time Exceeded (Type 11) message is generated, preventing persistent routing loops."),
        ("IPv4 Header Protocol TCP", "In the IPv4 header, what protocol value in the 'Protocol' field designates TCP?",
         ["1", "6", "17", "47"], "B",
         "Common IP Protocol numbers: 1 = ICMP; 6 = TCP; 17 = UDP; 47 = GRE; 50 = ESP; 51 = AH; 89 = OSPF."),
        ("IPv4 Header Protocol UDP", "Which value in the IPv4 Protocol field identifies the payload as a User Datagram Protocol (UDP) segment?",
         ["6", "17", "1", "88"], "B",
         "Protocol number 17 designates UDP, while 6 designates TCP and 1 designates ICMP."),
        ("IPv4 Header DF Flag", "Which flag in the IPv4 header instructs intermediate routers NOT to fragment the packet?",
         ["MF (More Fragments)", "DF (Don't Fragment)", "URG (Urgent)", "SYN (Synchronize)"], "B",
         "The DF (Don't Fragment) flag, when set to 1, instructs routers to drop the packet and send an ICMP Destination Unreachable (Fragmentation Needed, Type 3 Code 4) message if the packet exceeds the outgoing link's MTU."),
        ("IPv4 RFC 1918 Private Ranges", "Which of the following IPv4 address blocks is designated as a private address space under RFC 1918?",
         ["100.64.0.0/10", "172.16.0.0/12", "192.0.2.0/24", "169.254.0.0/16"], "B",
         "RFC 1918 defines three private IPv4 address blocks: 10.0.0.0/8 (10.0.0.0 - 10.255.255.255), 172.16.0.0/12 (172.16.0.0 - 172.31.255.255), and 192.168.0.0/16 (192.168.0.0 - 192.168.255.255)."),
        ("IPv4 Class C Private Range", "What is the valid RFC 1918 private IPv4 range for Class C addresses?",
         ["10.0.0.0 - 10.255.255.255", "172.16.0.0 - 172.31.255.255", "192.168.0.0 - 192.168.255.255", "192.168.1.0 - 192.168.1.255"], "C",
         "The Class C private address space defined in RFC 1918 is 192.168.0.0/16, spanning from 192.168.0.0 to 192.168.255.255."),
        ("IPv4 Loopback Address", "Which IPv4 address block is reserved by IANA for host internal loopback testing?",
         ["0.0.0.0/8", "127.0.0.0/8", "169.254.0.0/16", "224.0.0.0/4"], "B",
         "The entire 127.0.0.0/8 block is reserved for loopback operations. Traffic sent to 127.0.0.1 is looped back internally within the host IP stack without reaching physical media."),
        ("Subnetting Usable Hosts /27", "How many usable host IP addresses are available in an IPv4 subnet with a /27 prefix (mask 255.255.255.224)?",
         ["14", "30", "32", "62"], "B",
         "A /27 subnet has 32 - 27 = 5 host bits. Total addresses = 2^5 = 32. Subtracting the network address and directed broadcast address yields 32 - 2 = 30 usable host IP addresses."),
        ("Subnetting Broadcast Address", "What is the directed broadcast address for the subnet 192.168.1.64/26?",
         ["192.168.1.64", "192.168.1.127", "192.168.1.128", "192.168.1.255"], "B",
         "A /26 subnet has block size 256 - 192 = 64. Subnet range: 192.168.1.64 to 192.168.1.127. The first address (.64) is network ID, and the last (.127) is the directed broadcast address."),
        ("ARP Request Mode", "How is an initial ARP Request frame transmitted across a local broadcast domain to resolve a target IP address?",
         ["Unicast to the default gateway", "Broadcast (Destination MAC FF:FF:FF:FF:FF:FF)", "Multicast to 224.0.0.1", "Anycast across all router ports"], "B",
         "Because the sending host does not know the destination MAC address, it broadcasts the ARP Request with Destination MAC FF:FF:FF:FF:FF:FF so all hosts on the local link process it."),
        ("ARP Reply Mode", "How does the target host respond to an ARP Request?",
         ["It broadcasts the ARP Reply to all hosts", "It transmits a unicast ARP Reply directly to the requester's MAC address", "It transmits an ICMP Echo Reply", "It registers its MAC address with the DNS server"], "B",
         "The target host learned the requester's MAC and IP addresses from the ARP Request header. Thus, it responds with a unicast ARP Reply directly addressed to the requester."),
        ("Gratuitous ARP Function", "What is a primary purpose of transmitting a Gratuitous ARP packet?",
         ["To query the DNS root server for top-level domains",
          "To detect duplicate IP address conflicts and update neighbors' ARP mapping caches",
          "To authenticate user credentials against a RADIUS server",
          "To establish an encrypted IPsec tunnel across the WAN"], "B",
         "A host broadcasts a Gratuitous ARP (where source IP and target IP are its own address) upon interface activation to check if another device is already using that IP address (conflict detection) and to update MAC-to-IP tables on switches and neighbors."),
        ("Proxy ARP Function", "What is the function of Proxy ARP on a router or firewall interface?",
         ["To encrypt all ARP queries using AES-128",
          "To respond with its own MAC address to an ARP request on behalf of a target host located on another subnet",
          "To permanently block all ARP traffic entering the interface",
          "To translate IPv4 addresses to IPv6 addresses"], "B",
         "Proxy ARP allows a router or firewall to reply with its own MAC address to an ARP Request sent by a local host seeking a destination host on a different subnet/network, enabling communication without configuring default gateways on legacy hosts."),
        ("ICMP Protocol Layer", "At which OSI layer does the Internet Control Message Protocol (ICMP) logically operate, and how is it encapsulated?",
         ["Layer 2, encapsulated directly inside Ethernet frames",
          "Layer 3, encapsulated directly inside IPv4 packets (Protocol 1)",
          "Layer 4, encapsulated inside TCP segments",
          "Layer 7, encapsulated inside HTTP requests"], "B",
         "ICMP is an integral part of the Network Layer (Layer 3). Its messages are encapsulated directly within IP datagrams with the IP header Protocol field set to 1."),
        ("ICMP Ping Echo Request", "What are the ICMP Type and Code values for an ICMP Echo Request (Ping request)?",
         ["Type 0, Code 0", "Type 8, Code 0", "Type 3, Code 1", "Type 11, Code 0"], "B",
         "An ICMP Echo Request utilizes Type 8, Code 0. The responding device replies with an ICMP Echo Reply using Type 0, Code 0."),
        ("ICMP Destination Unreachable", "Which ICMP Type indicates that a destination network, host, port, or protocol is unreachable?",
         ["Type 0", "Type 3", "Type 8", "Type 11"], "B",
         "ICMP Type 3 represents 'Destination Unreachable'. Specific codes include Code 0 (Network Unreachable), Code 1 (Host Unreachable), Code 3 (Port Unreachable), and Code 4 (Fragmentation Needed and DF set)."),
        ("ICMP Traceroute Type", "Which ICMP message is generated by intermediate routers when their TTL counter reaches zero, enabling the 'tracert' / 'traceroute' command?",
         ["Type 0 Echo Reply", "Type 3 Destination Unreachable", "Type 11 Time Exceeded", "Type 5 Redirect"], "C",
         "Traceroute transmits packets with incrementing TTL values starting at 1. When a router decrements TTL to 0, it drops the packet and sends an ICMP Type 11 (Time Exceeded) message back to the source, revealing that hop's IP address."),
        ("TCP Characteristics", "Which of the following is a key operational characteristic of Transmission Control Protocol (TCP)?",
         ["Connectionless, best-effort delivery without acknowledgments",
          "Connection-oriented, reliable byte-stream service with error recovery and flow control",
          "Stateless broadcast transmission across local networks",
          "Fixed 8-byte header size with no options"], "B",
         "TCP (RFC 793) is a connection-oriented, reliable transport protocol that provides sequencing, acknowledgments, sliding-window flow control, congestion avoidance, and retransmission of lost segments."),
        ("TCP Handshake Flags", "What is the correct sequence of TCP flag exchanges during connection establishment?",
         ["ACK -> SYN -> FIN", "SYN -> SYN-ACK -> ACK", "SYN -> ACK-FIN -> RST", "RST -> SYN -> ACK"], "B",
         "The TCP 3-way handshake begins with the client sending a SYN segment, the server responding with SYN-ACK, and the client confirming with an ACK segment, transitioning the connection to the ESTABLISHED state."),
        ("TCP Termination Segments", "How many segments are typically exchanged to gracefully close a bidirectional TCP connection?",
         ["2 segments", "3 segments", "4 segments (FIN -> ACK -> FIN -> ACK)", "6 segments"], "C",
         "Because TCP is full-duplex, each direction of data transfer closes independently. Host A sends FIN, Host B sends ACK (closing A->B); then Host B sends FIN, and Host A sends ACK (closing B->A), totaling 4 segments."),
        ("TCP TIME_WAIT Rationale", "What is the primary reason the TCP active close endpoint remains in the TIME_WAIT state for 2 MSL (Maximum Segment Lifetime)?",
         ["To immediately renegotiate encryption keys for the next connection",
          "To ensure the final ACK is received by the peer and allow old duplicate segments to expire in the network",
          "To allow the server to recharge its hardware interface buffers",
          "To force the client to restart its operating system"], "B",
         "The 2 MSL TIME_WAIT state ensures that if the final ACK is lost, the retransmitted FIN can be acknowledged. It also guarantees that all delayed segments from the closed connection expire and cannot corrupt future connections using the same socket pair."),
        ("TCP RST Flag", "What is the function of the RST (Reset) flag in a TCP header?",
         ["To request dynamic routing table updates from adjacent firewalls",
          "To abort an abnormal connection immediately and reject invalid connection attempts",
          "To initiate the graceful 3-way handshake",
          "To indicate that urgent out-of-band data is present"], "B",
         "The RST flag resets an invalid connection, aborts an active session due to errors, or rejects an incoming SYN directed to an inactive/closed port."),
        ("UDP Header Length", "What is the fixed header size of a standard User Datagram Protocol (UDP) segment?",
         ["8 bytes", "16 bytes", "20 bytes", "32 bytes"], "A",
         "A UDP header contains exactly four 16-bit fields: Source Port (2 bytes), Destination Port (2 bytes), Length (2 bytes), and Checksum (2 bytes), totaling 8 bytes."),
        ("UDP Real-Time Media", "Why is UDP preferred over TCP for real-time voice and video streaming (e.g., VoIP, video conferencing)?",
         ["UDP provides stronger encryption algorithms than TCP",
          "UDP has low latency and no retransmission delays, prioritizing timely delivery over perfect reliability",
          "UDP guarantees 100% loss-free packet delivery across congested links",
          "UDP automatically modifies router forwarding tables to prevent jitter"], "B",
         "Real-time media applications prioritize low latency and predictable jitter. Retransmitting dropped audio/video frames via TCP causes noticeable lag and freezes; dropping occasional packets is preferable."),
        ("DNS Query Transport", "Which transport protocol and port number are predominantly used by standard DNS client queries?",
         ["TCP port 25", "UDP port 53", "TCP port 80", "UDP port 67"], "B",
         "Standard DNS queries and responses utilize UDP port 53 for speed. DNS uses TCP port 53 for responses exceeding 512 bytes (or EDNS0 limits) and for zone transfers between DNS servers."),
        ("DNS Record Type A", "Which DNS resource record type maps a fully qualified domain name (FQDN) to an IPv4 address?",
         ["AAAA record", "A record", "CNAME record", "PTR record"], "B",
         "An 'A' record maps a hostname to an IPv4 address. 'AAAA' maps to IPv6; 'CNAME' maps an alias to a canonical name; 'PTR' provides reverse resolution from IP to domain name."),
        ("HTTP HTTPS Default Ports", "What are the default standard TCP ports for unencrypted HTTP and encrypted HTTPS, respectively?",
         ["HTTP: 21, HTTPS: 22", "HTTP: 80, HTTPS: 443", "HTTP: 8080, HTTPS: 8443", "HTTP: 25, HTTPS: 587"], "B",
         "Standard HTTP communicates over cleartext TCP port 80, whereas HTTPS encrypts HTTP traffic inside TLS/SSL over TCP port 443."),
        ("FTP Control and Data Ports", "In traditional Active Mode File Transfer Protocol (FTP), which port is used for control commands and which for data transfer?",
         ["Port 21 for Control; Port 20 for Data", "Port 22 for Control; Port 21 for Data", "Port 80 for Control; Port 443 for Data", "Port 69 for Control; Port 68 for Data"], "A",
         "FTP separates control commands from data transfer. Port 21 is the command/control port, while the FTP server initiates data connections from port 20 in Active FTP mode."),
        ("FTP Active Mode NAT Problem", "Why does Active FTP fail when the FTP client is located behind a standard NAT router/firewall?",
         ["The client refuses to communicate with servers running Linux",
          "The FTP server initiates an inbound connection from port 20 to the client's high port, which the client firewall blocks",
          "Active FTP requires uncompressed video streaming bandwidth",
          "NAT devices are physically prohibited from handling TCP port 21"], "B",
         "In Active FTP, the client sends a PORT command specifying its internal IP and high port, then listens. The server initiates an incoming connection from port 20 to that port. A stateful firewall or NAT device at the client border blocks this unsolicited incoming connection unless an FTP ALG/ASPF is active."),
        ("FTP Passive Mode Solution", "How does Passive FTP (PASV) resolve client-side firewall and NAT traversal issues?",
         ["The server initiates the data connection directly to port 80",
          "The server opens a random high port and the client initiates the outbound data connection to that port",
          "Passive FTP disables encryption and authentication entirely",
          "The client and server communicate exclusively over ICMP echo packets"], "B",
         "In Passive FTP, the client sends the PASV command. The server opens a random unprivileged high port and returns the IP and port to the client. The client then initiates the outbound data connection, which client firewalls permit as outbound traffic."),
        ("SSH vs Telnet Security", "Why is SSH (TCP port 22) universally recommended over Telnet (TCP port 23) for device management?",
         ["Telnet is restricted to connecting only to printers",
          "Telnet transmits usernames, passwords, and commands in cleartext, vulnerable to packet sniffing; SSH encrypts all session data",
          "Telnet requires hardware dongles for terminal emulation",
          "SSH uses connectionless UDP broadcast frames to reach remote routers"], "B",
         "Telnet transmits all data, including administrative credentials, in unencrypted plaintext across the network. Anyone intercepting traffic with a packet sniffer can read passwords. SSH encrypts the entire channel and authenticates server and client."),
        ("DHCP DORA Sequence", "What is the correct sequence of the four DHCP broadcast/unicast messages exchanged during dynamic host IP address allocation?",
         ["Discover -> Offer -> Request -> Acknowledge (DORA)",
          "Request -> Offer -> Discover -> Acknowledge",
          "Dial -> Open -> Ready -> Accept",
          "Detect -> Order -> Receive -> Authenticate"], "A",
         "The four-step DHCP process is DORA: 1. DHCP Discover (client broadcasts looking for a server); 2. DHCP Offer (server proposes IP configuration); 3. DHCP Request (client formally requests the offered IP); 4. DHCP ACK (server confirms lease)."),
        ("DHCP UDP Ports", "Which UDP ports are utilized by DHCP servers and DHCP clients, respectively?",
         ["Server: UDP 67, Client: UDP 68", "Server: UDP 68, Client: UDP 67", "Server: UDP 53, Client: UDP 53", "Server: UDP 161, Client: UDP 162"], "A",
         "DHCP server listens on UDP port 67, and DHCP client listens on UDP port 68."),
        ("DHCP Relay Agent Role", "When DHCP clients and the DHCP server reside in different IP subnets, which device feature must be configured on the local router/switch interface?",
         ["DNS Dynamic Update", "DHCP Relay Agent", "ARP Proxy", "NAT ALG"], "B",
         "Because initial DHCP Discover messages are Layer 2 broadcasts (255.255.255.255), routers drop them by default. A DHCP Relay agent intercepts these broadcasts and forwards them as unicast packets across routers to the centralized DHCP server."),
        ("VLAN 802.1Q Header Size", "What is the size in bytes of the IEEE 802.1Q VLAN tag inserted into an Ethernet frame?",
         ["2 bytes", "4 bytes", "6 bytes", "8 bytes"], "B",
         "An 802.1Q tag is 4 bytes (32 bits) long, comprising a 2-byte Tag Protocol Identifier (TPID = 0x8100) and a 2-byte Tag Control Information (TCI, which contains 3-bit Priority, 1-bit CFI/DEI, and 12-bit VLAN ID).")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 2,
            "chapter_title": "Network Basics",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 2 MULTIPLE CHOICE (34 questions)
    m_data = [
        ("OSI 7 Layers Identification", "Which of the following are recognized layers in the ISO 7-layer OSI reference model?",
         ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer", "Cloud Layer"], "ABCD",
         "The 7 OSI layers in order are: Physical, Data Link, Network, Transport, Session, Presentation, and Application. 'Cloud Layer' does not exist in the OSI model."),
        ("TCP Header Flags", "Which of the following are valid control flag bits defined in the standard TCP header?",
         ["SYN (Synchronize)", "ACK (Acknowledgment)", "FIN (Finish)", "RST (Reset)", "EXP (Explore)"], "ABCD",
         "Standard 6 TCP control flags: URG (Urgent), ACK (Acknowledgment), PSH (Push), RST (Reset), SYN (Synchronize), and FIN (Finish). 'EXP' is not a TCP flag."),
        ("IPv4 Header Fields", "Which of the following fields are present in a standard 20-byte IPv4 header?",
         ["Time to Live (TTL)", "Protocol", "Header Checksum", "Source IP Address", "Flow Label"], "ABCD",
         "The IPv4 header includes Version, IHL, DSCP/ECN, Total Length, Identification, Flags, Fragment Offset, TTL, Protocol, Header Checksum, Source IP, and Destination IP. 'Flow Label' is unique to IPv6 headers."),
        ("RFC 1918 Private Ranges", "Which of the following IPv4 address prefixes are reserved strictly for private network addressing under RFC 1918?",
         ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "203.0.113.0/24"], "ABC",
         "RFC 1918 defines three private blocks: 10.0.0.0/8 (10.0.0.0 - 10.255.255.255), 172.16.0.0/12 (172.16.0.0 - 172.31.255.255), and 192.168.0.0/16 (192.168.0.0 - 192.168.255.255)."),
        ("Ethernet Frame Fields", "Which of the following components are part of an Ethernet II data frame?",
         ["Destination MAC Address", "Source MAC Address", "Type (EtherType)", "Frame Check Sequence (FCS)", "Hop Limit"], "ABCD",
         "An Ethernet II frame comprises: Preamble/SFD, Destination MAC (6B), Source MAC (6B), Type (2B), Payload Data (46-1500B), and FCS/CRC-32 (4B). 'Hop Limit' is an IPv6 network layer field."),
        ("TCP Reliability Features", "Which mechanisms allow TCP to provide reliable end-to-end data delivery?",
         ["Sequence numbers for in-order packet reassembly",
          "Cumulative positive acknowledgments (ACK)",
          "Retransmission timers for lost segments",
          "Sliding-window flow control to prevent buffer overrun"], "ABCD",
         "TCP achieves reliability via sequence numbering, explicit acknowledgments, timeout/retransmission algorithms, checksum error detection, and sliding window flow control."),
        ("UDP Operational Features", "Which of the following statements accurately describe the User Datagram Protocol (UDP)?",
         ["UDP is a connectionless transport protocol with low processing overhead",
          "UDP guarantees that packets arrive in the exact order they were sent",
          "UDP headers have a fixed size of 8 bytes",
          "UDP does not implement sliding-window flow control or congestion avoidance"], "ACD",
         "UDP is connectionless, lightweight, has a fixed 8-byte header, and lacks sequencing, retransmission, flow control, and congestion control."),
        ("DNS Resource Record Types", "Which of the following are valid DNS resource record types?",
         ["A (IPv4 host address)", "AAAA (IPv6 host address)", "MX (Mail Exchange)", "CNAME (Canonical Name)", "MAC (Hardware Address)"], "ABCD",
         "Common DNS records: A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail server), PTR (reverse lookup), NS (name server), and TXT. There is no 'MAC' record type in DNS."),
        ("ICMP Error Messages", "Which of the following represent standard ICMP error or control message types?",
         ["Type 0: Echo Reply", "Type 3: Destination Unreachable", "Type 8: Echo Request", "Type 11: Time Exceeded", "Type 50: Security Encapsulation"], "ABCD",
         "Key ICMP message types: Type 0 (Echo Reply), Type 3 (Destination Unreachable), Type 8 (Echo Request), Type 11 (Time Exceeded), and Type 5 (Redirect). IP Protocol 50 is ESP, not an ICMP type."),
        ("HTTP Methods", "Which of the following are standard HTTP request methods defined in RFC specifications?",
         ["GET", "POST", "PUT", "DELETE", "CONNECT"], "ABCDE",
         "Standard HTTP methods include GET (retrieve data), POST (submit data), PUT (replace data), DELETE (remove resource), HEAD (headers only), OPTIONS, and CONNECT (proxy tunneling)."),
        ("FTP Transmission Modes", "Which of the following are the two primary data transfer modes utilized in File Transfer Protocol (FTP)?",
         ["Active Mode (PORT mode)", "Passive Mode (PASV mode)", "Stealth Mode", "Tunnel Mode"], "AB",
         "FTP operates in two data connection modes: Active Mode (client issues PORT; server initiates data channel from port 20) and Passive Mode (client issues PASV; server opens dynamic port and client initiates data channel)."),
        ("DHCP Messages", "Which of the following messages are exchanged during the initial standard DHCP address acquisition process?",
         ["DHCP Discover", "DHCP Offer", "DHCP Request", "DHCP ACK", "DHCP Encrypt"], "ABCD",
         "The standard 4-step DHCP address allocation process (DORA) consists of: DHCP Discover, DHCP Offer, DHCP Request, and DHCP ACK."),
        ("VLAN Characteristics", "Which of the following are operational benefits of implementing Virtual Local Area Networks (VLANs)?",
         ["Isolating broadcast domains to improve network performance",
          "Enhancing departmental security by restricting Layer 2 traffic between VLANs",
          "Simplifying network management and logical project grouping",
          "Automatically converting IPv4 packets into IPv6 format"], "ABC",
         "VLANs segment broadcast domains, improve switch bandwidth utilization, enforce logical security boundaries between departments, and simplify moves/adds/changes."),
        ("ARP Table Attributes", "Which of the following statements regarding the ARP table on hosts and switches are correct?",
         ["Dynamic ARP entries have an aging timer and are flushed when idle",
          "Static ARP entries do not age out automatically and persist until manual removal or reboot",
          "An ARP table maps Layer 3 IP addresses to Layer 2 MAC addresses",
          "An ARP table is used by routers to decide the next-hop BGP autonomous system"], "ABC",
         "ARP maps Layer 3 IP addresses to Layer 2 physical MAC addresses. Dynamic entries age out automatically, whereas static entries remain fixed. Routing decisions use routing tables, not ARP tables."),
        ("TCP Connection States", "Which of the following are valid states in the TCP finite state machine?",
         ["LISTEN", "SYN_SENT", "ESTABLISHED", "TIME_WAIT", "TRANSLATING"], "ABCD",
         "Standard TCP states: LISTEN, SYN_SENT, SYN_RECEIVED, ESTABLISHED, FIN_WAIT_1, FIN_WAIT_2, CLOSE_WAIT, CLOSING, LAST_ACK, TIME_WAIT, and CLOSED."),
        ("Application Layer Protocols over TCP", "Which of the following application layer protocols typically rely on TCP as their transport layer protocol?",
         ["HTTP / HTTPS (Web)", "FTP (File Transfer)", "SSH (Secure Shell)", "Telnet (Remote Terminal)", "TFTP (Trivial File Transfer)"], "ABCD",
         "HTTP (80), HTTPS (443), FTP (20/21), SSH (22), and Telnet (23) require reliable stream transport and use TCP. TFTP uses UDP port 69."),
        ("Application Layer Protocols over UDP", "Which of the following network services predominantly utilize UDP as their underlying transport protocol?",
         ["DNS (standard name resolution queries)",
          "DHCP (Dynamic Host Configuration)",
          "SNMP (Simple Network Management)",
          "TFTP (Trivial File Transfer)",
          "BGP (Border Gateway Protocol)"], "ABCD",
         "DNS queries (port 53), DHCP (ports 67/68), SNMP (ports 161/162), and TFTP (port 69) run over UDP. BGP utilizes TCP port 179."),
        ("IPv4 Address Classes", "Which of the following statements regarding IPv4 address classes are correct?",
         ["Class A addresses use a default /8 mask (1.0.0.0 - 126.255.255.255)",
          "Class B addresses use a default /16 mask (128.0.0.0 - 191.255.255.255)",
          "Class C addresses use a default /24 mask (192.0.0.0 - 223.255.255.255)",
          "Class D addresses (224.0.0.0 - 239.255.255.255) are reserved for multicast"], "ABCD",
         "Standard classful IPv4 divisions: Class A (1-126, /8), Class B (128-191, /16), Class C (192-223, /24), Class D (224-239, Multicast), and Class E (240-255, Experimental)."),
        ("ICMP Destination Unreachable Codes", "Under ICMP Type 3 (Destination Unreachable), which of the following are valid code values?",
         ["Code 0: Network unreachable",
          "Code 1: Host unreachable",
          "Code 2: Protocol unreachable",
          "Code 3: Port unreachable",
          "Code 4: Fragmentation needed and DF set"], "ABCDE",
         "Common ICMP Type 3 codes: Code 0 (Net Unreachable), Code 1 (Host Unreachable), Code 2 (Protocol Unreachable), Code 3 (Port Unreachable), Code 4 (Fragmentation Needed and DF set)."),
        ("TCP Flow Control Mechanisms", "Which mechanisms are employed by TCP to manage congestion and flow control?",
         ["Advertised Receive Window (rwnd) for receiver flow control",
          "Slow Start and Congestion Avoidance algorithms",
          "Fast Retransmit triggered by three duplicate ACKs",
          "Fast Recovery algorithm",
          "Automatic MAC address rewriting"], "ABCD",
         "TCP flow control uses the advertised receive window (rwnd). Congestion control uses Congestion Window (cwnd) with Slow Start, Congestion Avoidance, Fast Retransmit, and Fast Recovery."),
        ("Subnet Mask Properties", "Which of the following statements about IPv4 subnet masks are correct?",
         ["A subnet mask is a 32-bit value consisting of contiguous 1s followed by contiguous 0s",
          "The 1-bits identify the network and subnet portion of the IP address",
          "The 0-bits identify the host portion of the IP address",
          "A /28 subnet mask corresponds to 255.255.255.240 in dotted-decimal notation"], "ABCD",
         "A subnet mask consists of continuous binary 1s (network bits) followed by continuous binary 0s (host bits). A /28 prefix has 28 ones: 255.255.255.240."),
        ("Traceroute Mechanics", "Which of the following statements regarding the operation of the traceroute utility are true?",
         ["It discovers router hops by sending probe packets with sequentially increasing TTL values",
          "Intermediate routers decrement TTL to 0 and reply with ICMP Type 11 Time Exceeded messages",
          "On Windows systems, 'tracert' primarily uses ICMP Echo Request probes",
          "On traditional Unix/Linux systems, 'traceroute' default probes use high-port UDP datagrams"], "ABCD",
         "Traceroute transmits probes with TTL=1, 2, 3... Intermediate routers reply with ICMP Type 11 (Time Exceeded). Windows tracert uses ICMP echo requests; Linux traceroute defaults to UDP high ports."),
        ("ARP Spoofing Risks", "Which of the following security risks are caused by ARP spoofing / poisoning attacks on a local LAN?",
         ["Man-in-the-Middle (MitM) eavesdropping of unencrypted traffic",
          "Denial of Service (DoS) by pointing gateway IP to a non-existent MAC address",
          "Session hijacking and unauthorized packet modification",
          "Hardware destruction of switch power supplies"], "ABC",
         "ARP poisoning tricks victims into mapping target IPs (like the default gateway) to the attacker's MAC, enabling MitM eavesdropping, credential theft, session tampering, or blackholing (DoS)."),
        ("Proxy ARP Use Cases", "Under which conditions is Proxy ARP typically utilized?",
         ["When hosts on the same logical subnet are separated by a router and lack default gateways",
          "In dial-up or remote access VPN scenarios where remote hosts share an intranet IP pool",
          "To secure database servers by encrypting SQL queries",
          "To translate IPv4 packets into ATM cells"], "AB",
         "Proxy ARP enables routers to respond to ARP requests on behalf of destination hosts located in different subnets or physical segments, common in legacy flat-network designs and remote dial-in setups."),
        ("SSH Security Features", "Which security mechanisms are provided by Secure Shell (SSHv2)?",
         ["Server authentication using public-key cryptography to prevent spoofing",
          "User authentication via password or client public-key certificates",
          "Confidentiality through symmetric session encryption (e.g., AES)",
          "Integrity protection using HMAC algorithms"], "ABCD",
         "SSHv2 delivers comprehensive security: host authentication (preventing MitM), user authentication (passwords/keys), symmetric payload encryption (AES/ChaCha20), and cryptographic integrity verification (HMAC)."),
        ("Telnet Insecurities", "Which of the following vulnerabilities are inherent to the Telnet protocol?",
         ["Usernames and passwords are transmitted in cleartext",
          "Commands and session outputs are vulnerable to passive network sniffing",
          "Lack of cryptographic integrity checking permits packet injection and tampering",
          "Telnet packets cannot be routed across standard IP networks"], "ABC",
         "Telnet (port 23) operates entirely in plaintext. Anyone with packet capture access can view credentials and commands, and tamper with sessions. Telnet routes over standard IP without issue."),
        ("HTTP Status Code Categories", "Which of the following HTTP status code classifications are correct according to RFC standards?",
         ["1xx: Informational - Request received, continuing process",
          "2xx: Success - The action was successfully received and accepted",
          "3xx: Redirection - Further action must be taken to complete the request",
          "4xx: Client Error - The request contains bad syntax or cannot be fulfilled",
          "5xx: Server Error - The server failed to fulfill an apparently valid request"], "ABCDE",
         "HTTP status codes are divided into: 1xx (Informational), 2xx (Success, e.g. 200 OK), 3xx (Redirection, e.g. 301/302), 4xx (Client Error, e.g. 403/404), and 5xx (Server Error, e.g. 500/502)."),
        ("HTTPS Security Architecture", "What components are utilized by HTTPS to secure HTTP communications?",
         ["Transport Layer Security (TLS) protocol",
          "Digital certificates issued by trusted Certificate Authorities (CAs)",
          "Asymmetric encryption for initial key exchange and server authentication",
          "Symmetric encryption for high-speed session data transmission",
          "Unencrypted Telnet control sessions"], "ABCD",
         "HTTPS layers HTTP over TLS. It uses digital certificates and asymmetric ciphers to authenticate the server and negotiate keys, followed by symmetric ciphers for fast bulk encryption."),
        ("DNS Resolution Methods", "Which resolution methods are used during DNS domain name resolution?",
         ["Recursive Query: The queried DNS server must return the final IP or an error",
          "Iterative Query: The queried DNS server returns the best referral to another server",
          "Multicast Query: Querying all hosts across the global Internet simultaneously",
          "Loopback Query: Generating continuous DNS loops to test server memory"], "AB",
         "DNS resolution uses Recursive queries (typically client-to-resolver, where the resolver does all the work) and Iterative queries (resolver queries Root, TLD, and Authoritative servers successively)."),
        ("DHCP Lease Renewal", "Which of the following events occur during the DHCP client lease lifecycle?",
         ["At 50% of lease time (T1), the client sends a unicast DHCP Request to the leasing server",
          "At 87.5% of lease time (T2), if T1 renewal failed, the client broadcasts a DHCP Request to any server",
          "If the lease expires without renewal, the client immediately stops using the IP address",
          "The client retains the IP address permanently even after lease expiration"], "ABC",
         "DHCP clients attempt lease renewal at T1 (50% lease time) via unicast DHCP Request. If unacknowledged, at T2 (87.5% lease time) they broadcast DHCP Request. If expired, the IP is immediately released."),
        ("Ethernet Frame Types", "Which of the following are valid frame encapsulation types utilized in Ethernet networking?",
         ["Ethernet II (DIX Ethernet)", "IEEE 802.3 with 802.2 LLC", "IEEE 802.3 with SNAP", "Ethernet IV High-Speed"], "ABC",
         "Ethernet frame formats in historical and current networking include Ethernet II (most common today), IEEE 802.3 LLC, and IEEE 802.3 SNAP. There is no 'Ethernet IV' specification."),
        ("IPv4 Header Flags Identification", "Which of the following represent the 3 bits of the Flags field in an IPv4 packet header?",
         ["Reserved bit (must be 0)",
          "Don't Fragment (DF) bit",
          "More Fragments (MF) bit",
          "Urgent Pointer (URG) bit"], "ABC",
         "The 3 bits of the IPv4 Flags field are: Bit 0 (Reserved, must be 0), Bit 1 (DF - Don't Fragment), and Bit 2 (MF - More Fragments). URG is a TCP control flag, not an IP header flag."),
        ("Well-Known Port Numbers", "Which of the following port assignments are correct for well-known Internet services?",
         ["SSH: TCP port 22",
          "DNS: UDP/TCP port 53",
          "HTTP: TCP port 80",
          "HTTPS: TCP port 443",
          "FTP Control: TCP port 21"], "ABCDE",
         "Standard well-known ports: SSH = 22, DNS = 53, HTTP = 80, HTTPS = 443, FTP Control = 21, and FTP Data = 20."),
        ("Ethernet Broadcast MAC", "Which of the following MAC addresses represent Ethernet broadcast or multicast addresses?",
         ["FF:FF:FF:FF:FF:FF (Layer 2 broadcast)",
          "01:00:5E:00:00:01 (IPv4 multicast MAC mapping)",
          "33:33:00:00:00:01 (IPv6 multicast MAC mapping)",
          "00:00:00:00:00:00 (Standard default router unicast MAC)"], "ABC",
         "FF:FF:FF:FF:FF:FF is the all-ones Layer 2 broadcast address. Addresses starting with 01:00:5E are reserved for IPv4 multicast. Addresses starting with 33:33 are reserved for IPv6 multicast. All-zeros is not a valid unicast host address.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 2,
            "chapter_title": "Network Basics",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 2 TRUE/FALSE (32 questions)
    tf_data = [
        ("Layer 2 Frame PDU", "The Protocol Data Unit (PDU) at the Data Link layer of the OSI model is called a packet.", "B",
         "False. The PDU at the Data Link layer is called a Frame. A Packet is the PDU at Layer 3 (Network layer)."),
        ("Ethernet MAC Length", "An Ethernet MAC address consists of 48 bits, typically displayed as 12 hexadecimal characters.", "A",
         "True. Ethernet MAC addresses are 48-bit (6-byte) physical hardware identifiers, typically written as six pairs of hexadecimal digits (e.g., 00:e0:fc:12:34:56)."),
        ("IPv4 Header Options", "The minimum length of an IPv4 header is 20 bytes, but it can expand up to 60 bytes if optional fields are included.", "A",
         "True. With no options, IHL=5 (20 bytes). The 4-bit IHL field maximum value is 15 (15 * 4 = 60 bytes), allowing up to 40 bytes of optional parameters."),
        ("IPv4 Protocol Number 6", "In the IPv4 header, a Protocol field value of 6 specifies that the encapsulated payload is UDP.", "B",
         "False. Protocol number 6 designates TCP. UDP is designated by Protocol number 17."),
        ("Loopback IP Routing", "Packets addressed to 127.0.0.1 are transmitted out onto the physical local area network media before returning.", "B",
         "False. Loopback packets are handled entirely within the host's internal software networking stack and are never transmitted out of physical network interfaces."),
        ("Usable Hosts /24 Subnet", "A standard Class C /24 subnet provides 256 usable IP addresses for assigning to host network interfaces.", "B",
         "False. A /24 subnet contains 256 total addresses (2^8), but 2 addresses are reserved: the network address (.0) and directed broadcast address (.255). This leaves 254 usable host IP addresses."),
        ("ARP Request Broadcast", "An initial ARP Request packet is sent as a Layer 2 unicast frame directed exclusively to the destination host's MAC address.", "B",
         "False. Because the sender does not yet know the destination MAC address, the ARP Request is broadcast to MAC FF:FF:FF:FF:FF:FF so all hosts on the segment receive and process it."),
        ("Gratuitous ARP Conflict Check", "Gratuitous ARP is used by a device to verify that its newly configured IP address does not conflict with another device on the network.", "A",
         "True. By broadcasting an ARP Request for its own IP address, a host detects IP address conflicts if another device replies, preventing duplicate IP assignments."),
        ("ICMP Protocol Number", "ICMP messages are encapsulated directly inside IPv4 datagrams using Protocol number 1.", "A",
         "True. ICMP is encapsulated directly within IP packets with the Protocol field set to 1."),
        ("Ping Echo Reply Type", "An ICMP Echo Reply packet uses Type 8 and Code 0.", "B",
         "False. An ICMP Echo Request uses Type 8, Code 0. An ICMP Echo Reply uses Type 0, Code 0."),
        ("Traceroute TTL Mechanism", "Traceroute relies on intermediate routers decrementing the IP TTL to zero and returning ICMP Type 11 Time Exceeded messages.", "A",
         "True. Traceroute sends packets with incrementing TTL values. Each router that decrements TTL to 0 drops the packet and responds with an ICMP Type 11 message, identifying the hop."),
        ("TCP Reliable Delivery", "TCP guarantees reliable, ordered, and error-checked delivery of a stream of octets between applications.", "A",
         "True. TCP employs sequence numbers, acknowledgments, checksums, and retransmission mechanisms to provide reliable, ordered stream delivery."),
        ("TCP 3-Way Handshake First Step", "The first segment sent during a TCP 3-way handshake is an ACK segment sent from server to client.", "B",
         "False. The client initiates the 3-way handshake by transmitting a SYN segment (with its initial sequence number) to the server."),
        ("TCP TIME_WAIT Duration", "The TCP TIME_WAIT state lasts for twice the Maximum Segment Lifetime (2 MSL) to ensure that delayed segments from the previous connection dissipate.", "A",
         "True. 2 MSL allows late-arriving duplicate segments to expire in the network so they cannot interfere with a subsequent connection using the same socket pair."),
        ("TCP RST Graceful Close", "A TCP RST (Reset) segment is used to negotiate a polite, graceful shutdown of a bidirectional session.", "B",
         "False. Graceful connection termination is performed using FIN segments. An RST segment immediately aborts an abnormal connection without waiting for outstanding data."),
        ("UDP Checksum Mandatory IPv4", "In standard IPv4 datagrams, calculating and verifying the UDP checksum is strictly mandatory for all implementations.", "B",
         "False. In IPv4, the UDP checksum field is optional (if not computed, it is filled with all zeros). In IPv6, however, computing the UDP checksum is mandatory."),
        ("DNS Port TCP 53 Usage", "DNS servers use TCP port 53 exclusively for all standard name lookup queries from desktop web browsers.", "B",
         "False. Standard desktop DNS queries use UDP port 53 for speed. TCP port 53 is used for DNS zone transfers between servers and when query responses exceed 512 bytes."),
        ("HTTPS Encryption Layer", "HTTPS operates by executing the HTTP protocol directly over a Transport Layer Security (TLS) encrypted session.", "A",
         "True. HTTPS is not a separate application protocol; it is standard HTTP layered over an encrypted TLS/SSL transport channel (default TCP port 443)."),
        ("Active FTP Server Data Port", "In Active FTP mode, the FTP server initiates data connections to the client from TCP port 20.", "A",
         "True. In Active FTP, the server uses TCP port 20 as the source port when connecting outbound to the client's negotiated high data port."),
        ("Passive FTP Client Initiation", "In Passive FTP mode, the client initiates both the control connection and the data connection.", "A",
         "True. In Passive FTP (PASV), the server opens an unprivileged high listening port and sends it to the client. The client then initiates the outbound data connection to that port."),
        ("Telnet Password Sniffing", "Because Telnet transmits data in plaintext, an attacker capturing traffic on an intermediate switch can view administrative passwords in cleartext.", "A",
         "True. Telnet lacks encryption; usernames, passwords, and command keystrokes are transmitted as unencrypted ASCII characters, vulnerable to network sniffing."),
        ("DHCP Discover Broadcast", "A newly booted DHCP client sends its initial DHCP Discover message as an IP broadcast to 255.255.255.255.", "A",
         "True. Because the client does not yet possess an IP address or know the server's IP, it broadcasts the DHCP Discover packet to 255.255.255.255 with source 0.0.0.0."),
        ("DHCP Server Default Port", "A DHCP server listens for incoming client requests on UDP port 68.", "B",
         "False. The DHCP server listens on UDP port 67. The DHCP client receives server messages on UDP port 68."),
        ("DHCP Relay Broadcast Forwarding", "A router configured as a DHCP Relay agent forwards DHCP Discover packets as Layer 2 broadcasts across all its interfaces.", "B",
         "False. A DHCP Relay converts the incoming broadcast Discover message into a Layer 3 unicast packet and forwards it directly to the designated DHCP server IP."),
        ("VLAN 802.1Q Tag Location", "The IEEE 802.1Q tag is inserted between the Source MAC address and the EtherType/Length field in an Ethernet frame.", "A",
         "True. An 802.1Q tag (4 bytes) is inserted immediately after the Source MAC address, with TPID 0x8100 indicating the presence of the VLAN tag."),
        ("IPv4 DF Flag Dropping", "If a packet with the DF (Don't Fragment) bit set encounters a router link where MTU is smaller than packet size, the router fragments the packet anyway.", "B",
         "False. If DF=1 and the packet exceeds the link MTU, the router must drop the packet and return an ICMP Type 3 Code 4 (Fragmentation Needed) error message."),
        ("Private IP Internet Routing", "RFC 1918 private IP addresses are globally routed across public Internet service provider backbones without NAT.", "B",
         "False. RFC 1918 private addresses are strictly non-routable on the public Internet. Internet routers filter and discard private IP ranges; NAT is required for Internet access."),
        ("Default Gateway Role", "A host uses its configured default gateway only when transmitting packets destined to IP addresses located outside its local subnet.", "A",
         "True. For hosts on the local subnet, the sender delivers packets directly using local ARP. For destinations on different subnets, packets are addressed to the default gateway's MAC address."),
        ("TCP Sliding Window Flow Control", "TCP uses the sliding window mechanism primarily to protect the receiver's buffer from being overwhelmed by a fast sender.", "A",
         "True. The receiver advertises its available buffer space (Receive Window, rwnd) in TCP acknowledgments, enabling flow control by restricting the sender's unacknowledged data volume."),
        ("Proxy ARP Disables Routing", "Proxy ARP replaces the need for IP routing tables on enterprise core routers.", "B",
         "False. Proxy ARP only helps hosts resolve MAC addresses when they lack default gateways; routers still rely completely on IP routing tables to forward packets across interfaces."),
        ("TCP Sequence Numbers Counting", "TCP sequence numbers count the number of segments transmitted rather than the number of data bytes.", "B",
         "False. TCP sequence numbers are byte-oriented; each sequence number corresponds to a specific byte in the data stream, not the segment count."),
        ("Ethernet FCS Error Detection", "The Frame Check Sequence (FCS) at the end of an Ethernet frame uses a 32-bit Cyclic Redundancy Check (CRC-32) to detect transmission errors.", "A",
         "True. The 4-byte FCS field contains a CRC-32 checksum calculated across the frame. If the receiving NIC computes a mismatched CRC, the corrupted frame is dropped.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 2,
            "chapter_title": "Network Basics",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch2_questions()
    print(f"Chapter 2 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
