# scripts/generate_ch9.py
"""
Generates Chapter 9 data: 34 Single Choice, 26 Multiple Choice, 25 True/False.
Chapter 9: Fundamentals of Encryption and Decryption Technologies
"""
import json

def get_ch9_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 9 SINGLE CHOICE (34 questions)
    s_data = [
        ("Kerckhoffs's Principle", "According to Kerckhoffs's Principle in modern cryptography, what should the security of a cryptosystem depend on?",
         ["Keeping the mathematical algorithm secret from the public",
          "The secrecy of the key alone, assuming the algorithm is completely public knowledge",
          "The physical thickness of the computer chassis",
          "Changing the computer operating system every 30 days"], "B",
         "Kerckhoffs's Principle states that the design of a cryptosystem must not require secrecy; the system must remain secure even if everything about the algorithm is known to the adversary, provided only the key is kept secret."),
        ("Symmetric Encryption Definition", "What is the defining operational characteristic of a symmetric encryption algorithm?",
         ["It uses completely different, mathematically unrelated keys for encryption and decryption",
          "The exact same secret key (or easily derived keys) is used for both encryption and decryption",
          "It can only encrypt data during nighttime hours",
          "It requires physical paper keys delivered by postal courier"], "B",
         "In symmetric cryptography, both communicating parties share a single secret key ($K_e = K_d$) utilized for both encrypting plaintext into ciphertext and decrypting ciphertext back into plaintext."),
        ("Symmetric Encryption Strength", "What is the primary operational advantage of symmetric encryption algorithms compared to asymmetric algorithms?",
         ["They completely eliminate the need for key distribution",
          "High computational speed, low processing overhead, and high throughput, making them ideal for bulk data encryption",
          "They provide legal non-repudiation without digital signatures",
          "They do not require any computer memory"], "B",
         "Symmetric ciphers use fast hardware-friendly bitwise operations, making them hundreds to thousands of times faster than asymmetric ciphers, perfectly suited for high-speed transmission of large data streams."),
        ("Symmetric Key Scalability Problem", "If an enterprise network has $N$ participating entities that all need to communicate securely with each other using unique symmetric keys, how many total keys must be generated and managed?",
         ["$N$ keys", "$2N$ keys", "$N(N-1)/2$ keys", "$N^2$ keys"], "C",
         "Because every pair of participants requires a unique shared secret key, the total number of keys scales quadratically as $N(N-1)/2$, creating severe key distribution and storage challenges at scale."),
        ("Stream vs Block Cipher", "How does a Block Cipher process plaintext compared to a Stream Cipher?",
         ["A block cipher encrypts data bit-by-bit continuously",
          "A block cipher divides plaintext into fixed-size blocks (e.g. 64 or 128 bits) and encrypts each block as a discrete unit",
          "A block cipher does not use any keys",
          "A block cipher operates only on analog voice audio"], "B",
         "Block ciphers divide plaintext into discrete blocks of fixed length (e.g., 64 bits for DES, 128 bits for AES) and apply rounds of substitution and permutation. Stream ciphers encrypt continuous streams bit-by-bit or byte-by-byte (e.g., RC4)."),
        ("DES Key Length", "What is the effective cryptographic key length of the standard Data Encryption Standard (DES) algorithm?",
         ["32 bits", "56 bits", "64 bits", "128 bits"], "B",
         "DES uses a 64-bit key, but 8 bits are parity bits used for error checking. Therefore, the effective cryptographic key strength is only 56 bits, which is insecure against modern brute-force computing."),
        ("3DES Operational Structure", "In Triple DES (3DES), what is the sequence of cryptographic operations applied to each 64-bit plaintext block using three keys ($K_1, K_2, K_3$)?",
         ["Encrypt with K1 -> Encrypt with K2 -> Encrypt with K3",
          "Encrypt with K1 -> Decrypt with K2 -> Encrypt with K3 (EDE mode)",
          "Decrypt with K1 -> Decrypt with K2 -> Decrypt with K3",
          "Hash with K1 -> Sign with K2 -> Encrypt with K3"], "B",
         "Standard 3DES uses Encrypt-Decrypt-Encrypt (EDE) processing: $C = E_{K1}(D_{K2}(E_{K3}(P)))$. This ensures backward compatibility with single DES when $K_1 = K_2 = K_3$."),
        ("AES Block Size", "What is the fixed block size processed by the Advanced Encryption Standard (AES) algorithm?",
         ["56 bits", "64 bits", "128 bits", "256 bits"], "C",
         "Under the official FIPS 197 standard (Rijndael cipher), AES has a fixed block size of 128 bits, regardless of whether the key length is 128, 192, or 256 bits."),
        ("AES Key Length Options", "Which three key lengths are officially supported by the standard AES algorithm?",
         ["56, 112, and 168 bits", "64, 128, and 256 bits", "128, 192, and 256 bits", "256, 512, and 1024 bits"], "C",
         "AES officially supports three cryptographic key lengths: 128 bits (10 transformation rounds), 192 bits (12 rounds), and 256 bits (14 rounds)."),
        ("Asymmetric Cryptography Concept", "What key pair structure is utilized in Asymmetric (Public-Key) cryptography?",
         ["A single shared symmetric key",
          "Two mathematically related keys: a Public Key (distributed openly) and a Private Key (kept strictly secret by the owner)",
          "Three identical keys stored on three separate servers",
          "An unencrypted password sent in cleartext"], "B",
         "Asymmetric cryptography uses key pairs. The Public Key is shared openly for encryption or signature verification; the Private Key is kept secret by the owner for decryption or signature generation."),
        ("Asymmetric Key Count Scalability", "In a network with $N$ participants using asymmetric public-key cryptography, how many total keys are required across the entire system?",
         ["$N(N-1)/2$ keys", "$2N$ keys (one public key and one private key per user)", "$N^2$ keys", "Exactly 1 key"], "B",
         "Because each participant generates one public key and one private key, a system of $N$ users requires only $2N$ keys, completely solving the quadratic key-management scalability issue of symmetric ciphers."),
        ("RSA Mathematical Foundation", "What underlying mathematical problem provides the cryptographic security of the RSA algorithm?",
         ["The difficulty of solving linear algebraic equations",
          "The computational difficulty of factoring the product of two very large prime numbers",
          "The speed of calculating square roots of even numbers",
          "The physical distance between two fiber optic endpoints"], "B",
         "RSA security relies on the prime factorization trapdoor problem: multiplying two large prime numbers ($p$ and $q$) is computationally simple, but factoring their large composite product ($n = p \times q$) is computationally infeasible with classical algorithms."),
        ("RSA Recommended Key Length", "What is the minimum key length generally recommended for secure enterprise RSA implementations today?",
         ["512 bits", "768 bits", "1024 bits", "2048 bits or higher"], "D",
         "RSA keys of 512 and 1024 bits are considered deprecated and vulnerable to factoring attacks. National and international standards mandate 2048-bit or 4096-bit RSA keys for secure enterprise deployments."),
        ("Elliptic Curve Cryptography (ECC) Advantage", "What is the primary technical advantage of Elliptic Curve Cryptography (ECC) compared to traditional RSA?",
         ["ECC can be decrypted without any keys",
          "ECC provides equivalent cryptographic strength with significantly shorter key lengths (e.g. 256-bit ECC provides security equivalent to 3072-bit RSA), reducing processing overhead and bandwidth",
          "ECC does not use any mathematical equations",
          "ECC can only be executed on supercomputers"], "B",
         "Based on the discrete logarithm problem over elliptic curves, ECC delivers equivalent cryptographic security with much smaller key sizes (e.g., 256-bit ECC roughly equivalent to 3072-bit RSA), resulting in faster computations and lower bandwidth/memory footprints."),
        ("Diffie-Hellman (DH) Function", "What is the primary operational capability provided by the Diffie-Hellman (DH) algorithm in network protocols like IPsec?",
         ["Direct bulk file encryption of multi-gigabyte databases",
          "Allowing two parties to securely negotiate and establish a shared secret key over an insecure, public communication channel",
          "Creating digital signatures to provide legal non-repudiation",
          "Formatting hard drives remotely across the Internet"], "B",
         "Diffie-Hellman is a key agreement/exchange protocol. It enables two communicating entities to derive a shared symmetric secret key across an untrusted network without transmitting the secret itself. DH cannot directly encrypt data or produce digital signatures."),
        ("Diffie-Hellman MitM Vulnerability", "What critical vulnerability does basic unauthenticated Diffie-Hellman exhibit if an active attacker intercepts communications?",
         ["It causes physical overheating of the network switch",
          "Vulnerability to Man-in-the-Middle (MitM) attacks where the attacker negotiates independent keys with both endpoints",
          "It forces both endpoints to reveal their private passwords",
          "It permanently disables the IP routing protocol"], "B",
         "Standard DH does not authenticate peer identities. An active attacker can intercept the exchange, negotiate separate DH keys with each endpoint, and transparently decrypt, read, and re-encrypt all traffic in a classic Man-in-the-Middle attack. Authentication (via PSK or certificates) is required to secure DH."),
        ("Cryptographic Hash Definition", "What is a One-Way Cryptographic Hash Function?",
         ["An encryption algorithm that can be reversed using a secret key",
          "A mathematical algorithm that takes an arbitrary-length input and transforms it into a fixed-length digest, such that reversing the operation is computationally infeasible",
          "A protocol that accelerates physical optical signal propagation",
          "A software tool that formats USB flash drives"], "B",
         "A one-way hash function maps variable-length input data to a fixed-size output digest. It is irreversible (pre-image resistant), meaning the original message cannot be reconstructed from the hash value alone."),
        ("Hash Avalanche Effect", "What does the 'Avalanche Effect' signify in cryptographic hash functions?",
         ["Changing even a single bit in the input message completely and unpredictably alters more than half of the bits in the output digest",
          "The hash algorithm runs twice as fast when processing large files",
          "The server chassis temperature drops below freezing",
          "The output digest length expands continuously as more data is processed"], "A",
         "The avalanche effect ensures that minor modifications to input data (such as flipping a single bit) produce a drastically and unpredictably different digest, making it impossible to detect patterns or predict hash variations."),
        ("MD5 Digest Length", "What is the fixed output digest length produced by the MD5 (Message Digest 5) algorithm?",
         ["64 bits", "128 bits", "160 bits", "256 bits"], "B",
         "MD5 produces a fixed 128-bit (16-byte) hash digest, commonly displayed as a 32-character hexadecimal string. MD5 is cryptographically broken due to demonstrated collision attacks."),
        ("SHA-1 Digest Length", "What is the fixed output digest length produced by the SHA-1 algorithm?",
         ["128 bits", "160 bits", "256 bits", "512 bits"], "B",
         "SHA-1 produces a 160-bit (20-byte) hash digest, displayed as a 40-character hexadecimal string. SHA-1 is deprecated due to practical collision attacks."),
        ("SHA-2 Family Members", "Which of the following hash algorithms belongs to the SHA-2 family and is universally deployed in modern network security protocols?",
         ["MD5", "SHA-1", "SHA-256", "DES"], "C",
         "The SHA-2 family (defined in FIPS 180-4) comprises SHA-224, SHA-256, SHA-384, and SHA-512. SHA-256 produces a 256-bit digest and is the modern benchmark for data integrity."),
        ("Hash Pre-Image Resistance", "What does 'Pre-Image Resistance' (One-Way Property) mean for a cryptographic hash function $H$?",
         ["Given an input $M$, it is impossible to calculate $H(M)$",
          "Given a hash digest $Y$, it is computationally infeasible to find any original message $M$ such that $H(M) = Y$",
          "Finding two messages with the same hash is instantaneous",
          "The hash algorithm can only process plaintext shorter than 10 bytes"], "B",
         "Pre-image resistance (first pre-image resistance) ensures that given an output hash $Y$, it is computationally impossible to reverse-engineer any valid plaintext $M$ that hashes to $Y$."),
        ("Hash Collision Definition", "In cryptographic hashing, what is a 'Collision'?",
         ["Two physical network cables touching each other",
          "Two completely different input messages that produce the exact same output hash digest ($H(M_1) = H(M_2)$ where $M_1 \\neq M_2$)",
          "An IP address conflict between two workstations",
          "A corrupted Ethernet frame header"], "B",
         "A hash collision occurs when two distinct input messages yield the identical hash digest. Secure cryptographic hash functions must be collision-resistant to prevent attackers from substituting forged messages."),
        ("HMAC Definition", "What is a Hash-Based Message Authentication Code (HMAC)?",
         ["An unencrypted text message sent across the Internet",
          "A cryptographic construction that combines a secret key with a hash function (e.g., HMAC-SHA256) to provide both data integrity and origin authentication",
          "A physical hardware token used to unlock server doors",
          "A method of formatting hard drives using hashes"], "B",
         "HMAC incorporates a secret cryptographic key into the hashing process ($H((K \\oplus opad) \\parallel H((K \\oplus ipad) \\parallel M))$). Only entities possessing the shared secret can generate or verify the HMAC, confirming both integrity and origin authenticity."),
        ("Digital Signature Signing Key", "When an entity creates a digital signature on a document, which key is used to generate the signature?",
         ["The recipient's public key",
          "The sender's private key",
          "The sender's public key",
          "A shared symmetric pre-shared key"], "B",
         "A digital signature is created when the sender encrypts a hash digest of the document using the sender's own PRIVATE key. Because only the sender possesses this private key, it uniquely authenticates the sender."),
        ("Digital Signature Verification Key", "Which key does the recipient use to verify a sender's digital signature?",
         ["The sender's private key",
          "The recipient's private key",
          "The sender's public key",
          "The ISP router's MAC address"], "C",
         "The recipient verifies the signature by decrypting it using the sender's openly available PUBLIC key to retrieve the original digest, comparing it with a locally computed hash of the received message."),
        ("Digital Signature Core Guarantees", "Which three fundamental security guarantees are simultaneously provided by a digital signature?",
         ["Confidentiality, Physical Security, and Port Redundancy",
          "Authenticity (origin verification), Integrity (tamper detection), and Non-repudiation",
          "Bandwidth acceleration, Compression, and Low latency",
          "Anonymity, Deniability, and Plausible erasure"], "B",
         "A digital signature mathematically guarantees: 1. Authenticity (proves who sent it); 2. Integrity (detects alterations); and 3. Non-repudiation (sender cannot deny having signed it)."),
        ("Digital Signature and Confidentiality", "Does digitally signing an email message automatically encrypt the message body to provide confidentiality?",
         ["Yes, digital signatures always encrypt the entire message body",
          "No, a digital signature provides authenticity and integrity, but does not encrypt the message plaintext unless separate encryption is applied",
          "Yes, but only if the recipient uses Linux",
          "Yes, by converting the message into an uncompressed ZIP archive"], "B",
         "A digital signature signs a hash digest; it does not encrypt the underlying plaintext message. The message can still be read by eavesdroppers unless an encryption cipher is layered with the signature."),
        ("Hybrid Cryptosystem Architecture", "How does a 'Hybrid Cryptosystem' (such as TLS or IPsec) combine symmetric and asymmetric cryptography effectively?",
         ["It uses asymmetric encryption to encrypt bulk user files and symmetric encryption to exchange keys",
          "It uses asymmetric cryptography (e.g. RSA or DH) to authenticate entities and securely negotiate a shared session key, which is then used by fast symmetric cryptography (e.g. AES) to encrypt bulk data",
          "It alternates between symmetric and asymmetric ciphers on every odd-numbered second",
          "It disables encryption entirely to maximize speed"], "B",
         "Hybrid cryptosystems capture the best of both worlds: asymmetric ciphers solve key distribution and authentication, while high-throughput symmetric ciphers encrypt the actual high-volume data payloads."),
        ("Message Digest Invertibility", "Can a 256-bit SHA-256 hash digest of a 10-megabyte video file be decrypted to recreate the original video file?",
         ["Yes, using the sender's private RSA key",
          "No, hashing is a one-way mathematical reduction; the original data cannot be reconstructed from the digest",
          "Yes, if the firewall has at least 64 GB of RAM",
          "Yes, by reversing the MD5 algorithm"], "B",
         "A hash is a fixed-length mathematical compression, not an encrypted file. Enormous amounts of original data are irreversibly discarded during hashing; a digest cannot be 'decrypted' into the original file."),
        ("RC4 Cipher Type", "What type of cryptographic algorithm is RC4, and what is its current security status?",
         ["A 128-bit block cipher that is widely recommended for banking",
          "A stream cipher that has been proven insecure due to statistical keystream biases and is deprecated across modern protocols",
          "An asymmetric public-key algorithm based on elliptic curves",
          "A one-way cryptographic hash function producing 512-bit digests"], "B",
         "RC4 is a variable key-size stream cipher. Due to severe cryptographic vulnerabilities (keystream biases and plaintext recovery attacks), RC4 is prohibited by IETF RFCs and deprecated in modern TLS and VPNs."),
        ("Symmetric Key Exchange Challenge", "What is the fundamental operational dilemma of pure symmetric cryptography in widespread communications?",
         ["Symmetric algorithms are too slow to run on modern computers",
          "How to securely transmit the secret key to the remote party across an untrusted network before encrypted communication can begin",
          "Symmetric ciphers can only encrypt text written in English",
          "Symmetric keys cannot exceed 8 bits in length"], "B",
         "The fundamental challenge of symmetric encryption is the 'Key Distribution Problem': both parties must share a secret key before communicating securely, but transmitting the key across an insecure channel risks interception."),
        ("AES Key Expansion", "In AES encryption, what is the purpose of the Key Expansion (Key Schedule) algorithm?",
         ["To increase the size of the ciphertext file on disk",
          "To generate a series of round keys from the initial cipher key for use in each round of transformation",
          "To translate the key into a public digital certificate",
          "To send the key to an external NTP server"], "B",
         "AES takes the primary cipher key (128, 192, or 256 bits) and runs it through a key expansion routine to derive multiple 128-bit 'round keys' applied during each successive round of substitution and permutation."),
        ("Digital Signature Verification Failure", "If an attacker intercepts a digitally signed message in transit and alters a single letter in the text before it reaches the recipient, what will happen during verification?",
         ["The recipient's computer will catch fire",
          "The recipient's locally computed hash will not match the decrypted signature hash, and the signature verification will fail, detecting the tampering",
          "The signature will automatically fix the letter back to its original state",
          "The verification will succeed because signatures ignore text changes"], "B",
         "Because of the avalanche effect, altering even one character produces a totally different hash digest. When the recipient computes the hash of the tampered text, it fails to match the digest decrypted from the signature, exposing the alteration.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 9,
            "chapter_title": "Fundamentals of Encryption and Decryption Technologies",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 9 MULTIPLE CHOICE (26 questions)
    m_data = [
        ("Symmetric Algorithms Identification", "Which of the following cryptographic algorithms are categorized as Symmetric encryption algorithms?",
         ["DES (Data Encryption Standard)",
          "3DES (Triple DES)",
          "AES (Advanced Encryption Standard)",
          "RC4",
          "RSA (Rivest-Shamir-Adleman)"], "ABCD",
         "DES, 3DES, AES, and RC4 are symmetric ciphers (using the same key for encryption and decryption). RSA is an asymmetric public-key cipher."),
        ("Asymmetric Algorithms Identification", "Which of the following algorithms belong to Asymmetric (Public-Key) cryptography?",
         ["RSA",
          "ECC (Elliptic Curve Cryptography)",
          "Diffie-Hellman (DH Key Agreement)",
          "AES-256",
          "Blowfish"], "ABC",
         "RSA, ECC, and Diffie-Hellman utilize asymmetric public/private key mathematics. AES and Blowfish are symmetric block ciphers."),
        ("One-Way Hash Algorithms Identification", "Which of the following algorithms are cryptographic One-Way Hash functions?",
         ["MD5", "SHA-1", "SHA-256", "SHA-512", "AES-128"], "ABCD",
         "MD5, SHA-1, SHA-256, and SHA-512 are one-way hash functions producing fixed-length digests. AES-128 is a symmetric block cipher."),
        ("Symmetric Cipher Modes of Operation", "Which of the following are recognized modes of operation for symmetric block ciphers like AES?",
         ["Electronic Codebook (ECB - insecure, leaks patterns)",
          "Cipher Block Chaining (CBC - uses Initialization Vector)",
          "Counter Mode (CTR - turns block cipher into stream cipher)",
          "Galois/Counter Mode (GCM - provides authenticated encryption with AEAD)",
          "Dynamic Quantum Routing Mode"], "ABCD",
         "Standard block cipher modes include ECB, CBC, CFB, OFB, CTR, and GCM (AEAD). 'Dynamic Quantum Routing' is fictional."),
        ("Hash Function Mathematical Properties", "Which of the following are essential mathematical properties required of secure cryptographic hash functions?",
         ["Pre-image Resistance (One-way property: infeasible to invert hash to find input)",
          "Second Pre-image Resistance (Weak collision resistance: given input, infeasible to find matching second input)",
          "Collision Resistance (Strong collision resistance: infeasible to find any two inputs with identical hash)",
          "Avalanche Effect (Minor input change produces radical digest change)",
          "Reversibility using a private key"], "ABCD",
         "Secure hash functions require pre-image resistance, second pre-image resistance, collision resistance, and the avalanche effect. Hash functions are strictly irreversible and cannot be reversed with any key."),
        ("Digital Signature Capabilities", "Which security guarantees are mathematically provided by a digital signature?",
         ["Data Origin Authentication (verifies the identity of the signer)",
          "Data Integrity (detects any unauthorized modification since signing)",
          "Non-repudiation (prevents the signer from denying the transaction)",
          "Automatic payload encryption ensuring confidentiality from all observers"], "ABC",
         "Digital signatures provide authentication, integrity, and non-repudiation. They do NOT provide confidentiality unless explicit message encryption is also performed."),
        ("Symmetric vs Asymmetric Comparison", "Which of the following statements correctly compare symmetric and asymmetric encryption?",
         ["Symmetric encryption is significantly faster and uses less CPU power than asymmetric encryption",
          "Asymmetric encryption requires only $2N$ keys for $N$ users, whereas symmetric requires $N(N-1)/2$ keys",
          "Asymmetric algorithms are commonly used for key exchange and digital signatures",
          "Symmetric algorithms are used for bulk data encryption in VPNs and TLS sessions",
          "Symmetric encryption can easily provide non-repudiation by itself"], "ABCD",
         "Symmetric is fast and used for bulk data ($N(N-1)/2$ keys); asymmetric is slower, scales at $2N$, and handles key exchange and signatures. Symmetric alone cannot provide non-repudiation."),
        ("AES Transformation Rounds", "In the AES cipher algorithm, which operations are performed in standard transformation rounds?",
         ["SubBytes (non-linear byte substitution using S-box)",
          "ShiftRows (transposition step shifting rows of the state array)",
          "MixColumns (linear mixing operation combining column bytes)",
          "AddRoundKey (XORing round subkey into the state array)",
          "FormatDrive (erasing physical storage sectors)"], "ABCD",
         "A standard AES round consists of SubBytes, ShiftRows, MixColumns, and AddRoundKey transformations. Drive formatting is unrelated."),
        ("Diffie-Hellman Key Exchange Steps", "Which steps occur during a Diffie-Hellman key exchange between Alice and Bob?",
         ["Both parties agree on public domain parameters (a large prime $p$ and base generator $g$)",
          "Alice selects a secret private integer $a$ and sends public value $A = g^a \\bmod p$ to Bob",
          "Bob selects a secret private integer $b$ and sends public value $B = g^b \\bmod p$ to Alice",
          "Both parties compute the identical shared secret key $K = g^{ab} \\bmod p$ independently",
          "Both parties transmit their secret private integers $a$ and $b$ across the network in cleartext"], "ABCD",
         "DH allows Alice and Bob to compute $g^{ab} \\bmod p$ without transmitting private values $a$ or $b$ across the network. Transmitting private integers would defeat the entire security of the exchange."),
        ("HMAC Construction Elements", "Which elements are required to compute a Hash-Based Message Authentication Code (HMAC)?",
         ["A cryptographic hash function (e.g. SHA-256 or SHA-512)",
          "A shared secret cryptographic key",
          "The arbitrary-length message data payload",
          "Inner and outer padding constants (ipad and opad)",
          "A digital certificate signed by a root CA"], "ABCD",
         "HMAC requires a hash algorithm, a shared secret key, the message payload, and fixed padding constants ($ipad=0x36$, $opad=0x5c$). It does not require X.509 digital certificates."),
        ("Cryptanalytic Attack Types", "Which of the following are recognized attack models used in cryptanalysis?",
         ["Ciphertext-Only Attack (attacker possesses only intercepted ciphertexts)",
          "Known-Plaintext Attack (attacker possesses ciphertexts and matching plaintexts)",
          "Chosen-Plaintext Attack (attacker can choose plaintexts and obtain resulting ciphertexts)",
          "Brute-Force Attack (trying all possible keys sequentially)",
          "Physical Optical Cable Bending Attack"], "ABCD",
         "Standard cryptanalytic attack models include Ciphertext-Only, Known-Plaintext, Chosen-Plaintext, Chosen-Ciphertext, and Brute-Force key exhaustion."),
        ("Block Cipher Padding Schemes", "Why is padding required in block ciphers like AES-CBC, and which padding schemes are standard?",
         ["Plaintext messages are rarely an exact multiple of the block size (128 bits / 16 bytes)",
          "Padding appends structured bytes to fill the final block to the required length",
          "PKCS#7 (or PKCS#5) padding is widely used in standard cryptographic libraries",
          "Padding is used to convert binary data into audible sound waves"], "ABC",
         "Block ciphers operate on fixed block sizes (16 bytes for AES). If plaintext is not an exact multiple, padding (such as PKCS#7) fills the remaining bytes."),
        ("Initialization Vector (IV) Purpose", "What is the function of an Initialization Vector (IV) in block cipher modes like CBC?",
         ["It ensures that identical plaintext blocks encrypt to completely different ciphertext blocks",
          "It prevents pattern analysis and dictionary attacks against encrypted communications",
          "It must be random or non-repeating (nonce) for each encryption session",
          "It is kept secret and never transmitted with the ciphertext"], "ABC",
         "An IV introduces randomness into CBC mode, ensuring identical plaintexts produce distinct ciphertexts. The IV is not a secret; it is transmitted in the clear alongside the ciphertext."),
        ("Digital Signature Verification Steps", "When a client verifies an RSA digital signature on a downloaded file, which operations occur?",
         ["The client decrypts the digital signature using the signer's public key to extract the original digest ($H_1$)",
          "The client independently calculates the cryptographic hash of the downloaded file ($H_2$)",
          "The client compares $H_1$ and $H_2$; if they match, the signature is mathematically valid",
          "The client formats its operating system if the hashes match"], "ABC",
         "Verification decrypts the signature with the sender's public key to retrieve $H_1$, computes hash $H_2$ over the file, and confirms $H_1 == H_2$."),
        ("Security Weaknesses of Legacy Algorithms", "Why have algorithms like DES, MD5, and SHA-1 been officially deprecated by security standards?",
         ["DES effective key length (56 bits) is vulnerable to complete brute-force exhaustion within hours",
          "MD5 is vulnerable to practical collision generation attacks created in seconds",
          "SHA-1 has demonstrated practical collision attacks (e.g. SHAttered attack)",
          "They cannot run on 64-bit microprocessors"], "ABC",
         "DES is vulnerable to brute-force due to its short 56-bit key. MD5 and SHA-1 have broken collision resistance, making them unsafe for digital signatures or certificates."),
        ("ECC Cryptographic Advantages", "Which benefits make Elliptic Curve Cryptography (ECC) superior for mobile and IoT devices?",
         ["Much smaller key sizes compared to RSA for equivalent security (256-bit ECC vs 3072-bit RSA)",
          "Significantly lower computational power and battery consumption",
          "Reduced network transmission bandwidth for keys and digital certificates",
          "ECC eliminates the need for mathematical calculations entirely"], "ABC",
         "ECC delivers high security with tiny keys, drastically cutting CPU cycles, battery drain, and certificate sizes on constrained mobile/IoT platforms."),
        ("Cryptographic Key Management Lifecycle", "Which stages are recognized in the comprehensive cryptographic key management lifecycle?",
         ["Key Generation (using cryptographically secure pseudo-random number generators)",
          "Key Distribution and Storage (secure transfer and hardware protection via HSMs)",
          "Key Usage and Rotation (periodic key renewal)",
          "Key Revocation and Destruction (secure sanitization of expired keys)"], "ABCD",
         "Key management spans generation, distribution, storage, rotation, revocation, and zeroization/destruction."),
        ("Symmetric Key Agreement Protocols", "Which protocols or mechanisms are used to establish shared symmetric keys between communicating parties?",
         ["Diffie-Hellman (DH) key exchange",
          "Elliptic Curve Diffie-Hellman (ECDH)",
          "RSA key transport (encrypting symmetric session key with recipient's public key)",
          "Pre-Shared Key (PSK) manual out-of-band configuration"], "ABCD",
         "Shared session keys are established via DH/ECDH key agreement, RSA public key encryption/transport, or manual pre-shared key (PSK) provisioning."),
        ("Authenticated Encryption (AEAD)", "What is Authenticated Encryption with Associated Data (AEAD), such as AES-GCM?",
         ["A cryptographic mode that provides confidentiality, data integrity, and authenticity simultaneously",
          "It eliminates the need to apply separate HMAC hashing operations over ciphertext",
          "It allows associated unencrypted data (e.g. packet headers) to be authenticated alongside encrypted payloads",
          "It converts all ciphertext into plain ASCII text for easy reading"], "ABC",
         "AEAD (e.g. AES-GCM) integrates encryption and MAC generation in one pass, protecting confidentiality while authenticating both the ciphertext and unencrypted headers (associated data)."),
        ("Man-in-the-Middle on Diffie-Hellman", "In an unauthenticated Diffie-Hellman exchange, how does an attacker execute a Man-in-the-Middle attack?",
         ["The attacker intercepts Alice's public value $g^a$ and substitutes their own value $g^e$",
          "The attacker intercepts Bob's public value $g^b$ and substitutes their own value $g^e$",
          "The attacker establishes shared secret $K_1 = g^{ae}$ with Alice and shared secret $K_2 = g^{be}$ with Bob",
          "The attacker decrypts, reads, modifies, and re-encrypts messages passing between Alice and Bob transparently"], "ABCD",
         "Without authentication, the attacker impersonates Bob to Alice and Alice to Bob, establishing separate keys ($K_1, K_2$) with each party to intercept and tamper with all communications."),
        ("Collision Resistance Categories", "In cryptographic literature, how is collision resistance categorized?",
         ["Weak Collision Resistance (Second Pre-image Resistance: hard to find $M_2 \\neq M_1$ such that $H(M_1) = H(M_2)$ for a given $M_1$)",
          "Strong Collision Resistance (hard to find ANY two messages $M_1, M_2$ such that $H(M_1) = H(M_2)$)",
          "Zero Collision Resistance (collisions occur on every packet)",
          "Physical Collision Resistance (preventing cables from tangling)"], "AB",
         "Collision resistance is bifurcated into Weak (Second Pre-image Resistance for a given input) and Strong (finding any arbitrary collision pair)."),
        ("Hybrid Cryptography Benefits", "Why do protocols like SSL/TLS, IPsec, and SSH rely on hybrid cryptography rather than using only asymmetric encryption?",
         ["Asymmetric encryption is too computationally slow to encrypt gigabytes of bulk data in real time",
          "Symmetric encryption alone cannot solve the secure key exchange problem across untrusted networks",
          "Combining both yields the speed of symmetric ciphers and the security/key management of asymmetric ciphers",
          "International law strictly forbids using symmetric encryption alone"], "ABC",
         "Pure asymmetric encryption is too slow for bulk streaming; pure symmetric encryption lacks key exchange. Hybrid cryptography combines the strengths of both paradigms."),
        ("Cryptographically Secure PRNG (CSPRNG)", "Why is a Cryptographically Secure Pseudo-Random Number Generator (CSPRNG) critical in security systems?",
         ["Predictable random numbers allow attackers to guess encryption keys and nonces easily",
          "CSPRNGs pass statistical randomness tests and exhibit unpredictability (next-bit test resistance)",
          "They are used to generate high-entropy keys, initialization vectors, and salt values",
          "They accelerate physical network line speeds"], "ABC",
         "Cryptographic keys, nonces, and IVs depend on true unpredictability. Weak random generators allow attackers to predict keys, breaking systems even when strong ciphers like AES are used."),
        ("Non-Repudiation Practical Applications", "In which real-world digital applications is cryptographic Non-Repudiation essential?",
         ["Online banking and financial wire transfers (preventing customers from falsely denying authorization)",
          "Legally binding electronic contracts and digital signatures (e.g. DocuSign)",
          "Government tax filing and regulatory compliance submissions",
          "Anonymous web browsing in public Internet cafes"], "ABC",
         "Non-repudiation is indispensable for commercial contracts, banking transactions, and regulatory filings where parties must not be able to dispute originating transactions."),
        ("AES Key Sizes and Rounds Mapping", "Which mappings between AES key lengths and transformation rounds are correct?",
         ["AES-128 uses 10 transformation rounds",
          "AES-192 uses 12 transformation rounds",
          "AES-256 uses 14 transformation rounds",
          "AES-512 uses 30 transformation rounds"], "ABC",
         "AES defines: 128-bit key = 10 rounds; 192-bit key = 12 rounds; 256-bit key = 14 rounds. There is no official AES-512 specification."),
        ("One-Way Hash Practical Uses", "Which of the following are standard real-world uses of one-way hash functions in network security?",
         ["Verifying file integrity after downloading software ISOs (e.g., comparing SHA-256 checksums)",
          "Storing user passwords securely in operating system databases using salted hashes",
          "Generating message digests for digital signatures",
          "Constructing Hash-Based Message Authentication Codes (HMAC) for packet integrity",
          "Recovering forgotten plaintext passwords by decrypting hash digests"], "ABCD",
         "Hashes are used for file integrity checksums, salted password storage, digital signatures, and HMAC. Hashes cannot be decrypted to recover original plaintext.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 9,
            "chapter_title": "Fundamentals of Encryption and Decryption Technologies",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 9 TRUE/FALSE (25 questions)
    tf_data = [
        ("Kerckhoffs's Principle Secrecy", "Kerckhoffs's Principle states that a cryptosystem must be kept secret and proprietary to ensure maximum security.", "B",
         "False. Kerckhoffs's Principle asserts that a cryptosystem's security should rely solely on keeping the key secret, assuming the algorithm is public knowledge."),
        ("Symmetric Key Shared", "In symmetric encryption, the sender and the receiver use the exact same secret key for both encryption and decryption.", "A",
         "True. Symmetric cryptography is defined by the use of an identical shared secret key ($K_e = K_d$) for both operations."),
        ("Symmetric Speed Advantage", "Symmetric encryption algorithms are generally much faster and less computationally intensive than asymmetric encryption algorithms.", "A",
         "True. Symmetric algorithms rely on fast hardware-friendly bitwise operations, making them orders of magnitude faster than asymmetric algorithms."),
        ("DES 56-Bit Key Insecurity", "The effective key length of DES is 56 bits, which is considered cryptographically insecure today due to brute-force vulnerability.", "A",
         "True. A 56-bit key can be exhaustively brute-forced in hours with modern hardware, rendering single DES obsolete."),
        ("AES 128-Bit Block Size", "The block size of the AES algorithm is fixed at 128 bits, regardless of whether a 128-bit, 192-bit, or 256-bit key is used.", "A",
         "True. Under FIPS 197, AES has a fixed block size of 128 bits across all supported key lengths (128, 192, 256 bits)."),
        ("Asymmetric Key Pair Roles", "In asymmetric cryptography, a message encrypted with an entity's Public Key can only be decrypted by the matching Private Key.", "A",
         "True. The mathematical relationship ensures that data encrypted with the public key can be decrypted exclusively by the corresponding private key."),
        ("Asymmetric Key Count Formula", "A network of 100 users utilizing asymmetric cryptography requires 100 * 99 / 2 = 4,950 total keys across the system.", "B",
         "False. Asymmetric systems require $2N$ keys (one public and one private key per user), totaling $2 \\times 100 = 200$ keys. $N(N-1)/2$ applies to symmetric ciphers."),
        ("Diffie-Hellman Direct Encryption", "The Diffie-Hellman algorithm can be used directly to encrypt large database files and generate digital signatures.", "B",
         "False. Diffie-Hellman is strictly a key agreement protocol; it cannot directly encrypt data or produce digital signatures."),
        ("Diffie-Hellman MitM Risk", "Unauthenticated Diffie-Hellman key exchange is vulnerable to Man-in-the-Middle (MitM) attacks.", "A",
         "True. Without authentication (via pre-shared keys or digital certificates), an attacker can intercept and establish separate keys with both endpoints."),
        ("Hash Reversibility", "A cryptographic hash function can be easily inverted using a private key to recover the original plaintext message.", "B",
         "False. Hash functions are strictly one-way mathematical reductions; they do not have keys and cannot be inverted to recover original data."),
        ("Avalanche Effect Bit Change", "The avalanche effect ensures that changing a single bit in the input message completely alters the resulting hash digest.", "A",
         "True. The avalanche effect guarantees that small input changes produce radical, unpredictable changes across the entire output digest."),
        ("MD5 Collision Vulnerability", "MD5 is still recommended for generating secure digital signatures because no collisions have ever been found in MD5.", "B",
         "False. MD5 has been completely broken by practical collision attacks and is strictly deprecated for digital signatures and security certificates."),
        ("SHA-256 Digest Length", "The SHA-256 hash algorithm produces a fixed-length output digest of 256 bits.", "A",
         "True. SHA-256 (part of the SHA-2 family) consistently outputs a 256-bit (32-byte) digest."),
        ("HMAC Shared Key Authentication", "An HMAC provides data integrity AND origin authentication because only parties possessing the shared secret key can generate a valid MAC.", "A",
         "True. By combining a shared key with a hash function, HMAC confirms that data was not altered and was generated by a holder of the secret key."),
        ("Digital Signature Signing Key Check", "A digital signature is created by encrypting the message hash using the RECIPIENT'S public key.", "B",
         "False. A digital signature is generated by encrypting the hash with the SENDER'S private key, proving the sender's identity."),
        ("Digital Signature Verification Key Check", "A recipient verifies a digital signature using the SENDER'S public key.", "A",
         "True. The sender's public key decrypts the signature to extract the original digest for comparison against the newly computed hash."),
        ("Digital Signature Confidentiality", "Digitally signing an email ensures that unauthorized eavesdroppers cannot read the plaintext content of the email.", "B",
         "False. A digital signature provides authenticity and integrity, not confidentiality. Plaintext remains readable unless separate encryption is applied."),
        ("Non-Repudiation Sender Denial", "Non-repudiation prevents the sender of a signed document from falsely denying that they created and transmitted the document.", "A",
         "True. Because only the sender possesses their unique private key, a valid digital signature provides indisputable proof of authorship."),
        ("Hybrid Cryptosystem Performance", "Hybrid cryptosystems use asymmetric ciphers for secure key exchange and symmetric ciphers for high-speed bulk data encryption.", "A",
         "True. Hybrid architectures leverage asymmetric algorithms for key distribution and fast symmetric ciphers for line-rate data encryption."),
        ("Symmetric Cipher Non-Repudiation", "Symmetric key encryption alone provides legal non-repudiation because the key is secret.", "B",
         "False. Because both sender and receiver share the identical symmetric key, either party could have created the ciphertext, failing non-repudiation."),
        ("ECC Key Length Efficiency", "A 256-bit ECC key provides cryptographic strength roughly comparable to a 3072-bit RSA key.", "A",
         "True. Elliptic Curve Cryptography provides equivalent security with dramatically shorter key lengths than RSA."),
        ("Block Cipher ECB Mode Security", "Electronic Codebook (ECB) mode is considered secure for encrypting complex images because it hides all visual patterns.", "B",
         "False. ECB encrypts identical plaintext blocks into identical ciphertext blocks, preserving visual patterns and structural data, making it insecure."),
        ("CBC Mode IV Requirement", "Cipher Block Chaining (CBC) mode requires an Initialization Vector (IV) to ensure identical plaintext blocks produce different ciphertext blocks.", "A",
         "True. An IV randomizes the initial block, ensuring that identical plaintexts yield completely different ciphertexts."),
        ("RC4 Stream Cipher Deprecation", "RC4 is officially deprecated across modern security standards due to discovered vulnerabilities and keystream biases.", "A",
         "True. RC4 is prohibited by IETF RFCs and modern TLS specifications due to statistical biases and plaintext recovery attacks."),
        ("Salted Hash Password Storage", "Adding a unique cryptographic 'salt' to passwords before hashing prevents attackers from using precomputed rainbow tables to crack passwords.", "A",
         "True. Salting introduces unique random strings per user, invalidating precomputed rainbow tables and forcing attackers to brute-force each password individually.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 9,
            "chapter_title": "Fundamentals of Encryption and Decryption Technologies",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch9_questions()
    print(f"Chapter 9 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
