# scripts/generate_ch01_to_ch03.py
"""
Generates complete exam questions for Chapters 1, 2, and 3:
Chapter 1: Network Security Concepts and Specifications
  - 36 Single Choice
  - 26 Multiple Choice
  - 26 True/False
Chapter 2: Network Basics
  - 44 Single Choice
  - 34 Multiple Choice
  - 32 True/False
Chapter 3: Common Network Security Threats and Threat Prevention
  - 36 Single Choice
  - 28 Multiple Choice
  - 26 True/False

Outputs JSON objects for these chapters.
"""
import json
import os

CHAPTER_NAMES = {
    1: "Network Security Concepts and Specifications",
    2: "Network Basics",
    3: "Common Network Security Threats and Threat Prevention"
}

def build_ch1():
    single = []
    multi = []
    tf = []

    # --- CH1 SINGLE CHOICE (36 questions) ---
    s_items = [
        ("CIA - Confidentiality", "Which security attribute ensures that sensitive information is not disclosed to unauthorized entities or eavesdropped during transmission?",
         ["Integrity", "Confidentiality", "Availability", "Non-repudiation"], "B",
         "Confidentiality ensures that information can be accessed and viewed only by authorized personnel. Cryptographic encryption is the primary mechanism to enforce confidentiality across untrusted networks."),
        ("CIA - Integrity", "Which security property guarantees that transmitted data has not been altered, deleted, or forged in transit?",
         ["Availability", "Integrity", "Confidentiality", "Authenticity"], "B",
         "Integrity guarantees that data has not been tampered with or modified during transit or storage. Cryptographic hash functions (such as SHA-256) and message authentication codes are primary mechanisms to verify integrity."),
        ("CIA - Availability", "An enterprise web service is taken down by a volumetric SYN flood attack, preventing legitimate clients from accessing their accounts. Which principle of the CIA triad has been violated?",
         ["Confidentiality", "Integrity", "Availability", "Controllability"], "C",
         "Availability ensures that authorized users have prompt and reliable access to information assets and network services. DoS/DDoS attacks specifically target availability by exhausting network bandwidth or server compute resources."),
        ("Security Era - 1940s", "In the evolution of information security, what was the primary characteristic of the 'Communication Security' era during the 1940s?",
         ["Focus on cyberspace sovereignty and IoT devices",
          "Protection was primarily confined to physical security and cipher-based transmission (mainly stream ciphers)",
          "Emphasis on multi-dimensional active defense and SIEM orchestration",
          "Standardization of enterprise security architectures such as ISO 27001"], "B",
         "During the 1940s Communication Security era, communication technologies were underdeveloped. Information security focused on physical security and point-to-point cipher transmission (primarily stream ciphers) to protect confidential military and diplomatic telegrams."),
        ("Security Era - 1990s", "During the 1990s Information Assurance period, which two new security principles were emphasized alongside the traditional CIA triad?",
         ["Simplicity and Scalability", "Controllability and Non-repudiation", "Virtualization and Micro-segmentation", "Resilience and Fault-tolerance"], "B",
         "In the 1990s Information Assurance era, as the Internet expanded rapidly, Controllability (ability to monitor and control information systems) and Non-repudiation (inability to deny transmitted actions/data) joined the CIA triad to form the five core security principles."),
        ("Non-repudiation Mechanism", "Which cryptographic technology is primarily utilized to provide non-repudiation in electronic transactions?",
         ["Symmetric block ciphers like AES-256", "Pre-shared keys (PSK)", "Digital signatures using asymmetric private keys", "Stream ciphers like RC4"], "C",
         "Non-repudiation prevents a sender from denying having sent a message. It is achieved through digital signatures, where only the sender possesses the unique private key required to generate the signature."),
        ("ISO Standards - ISO 27001", "Which of the following standards specifies requirements for establishing, implementing, maintaining, and continually improving an Information Security Management System (ISMS) and is used for organizational certification?",
         ["ISO/IEC 27002", "ISO/IEC 27001", "ISO/IEC 27005", "RFC 1918"], "B",
         "ISO/IEC 27001 provides the formal normative specification for an enterprise Information Security Management System (ISMS) and serves as the certification benchmark. ISO 27002 provides guidance and codes of practice for implementing security controls."),
        ("ISO Standards - ISO 27002", "What is the primary role of ISO/IEC 27002 within the ISO 27000 series?",
         ["A formal audit standard against which an enterprise receives an accredited certificate",
          "A code of practice containing reference control objectives and actionable security controls",
          "A hardware encryption standard for high-speed fiber communications",
          "A regulatory framework for national critical infrastructure penal sanctions"], "B",
         "ISO/IEC 27002 provides a comprehensive code of practice and implementation guidelines for information security controls, helping organizations select and implement controls defined in Annex A of ISO 27001."),
        ("Classified Protection - Levels Count", "Under Cybersecurity Classified Protection 2.0 (China's National Standard MLPS 2.0), how many security protection levels are defined?",
         ["Three levels", "Four levels", "Five levels", "Seven levels"], "C",
         "Classified Protection 2.0 defines five security levels: Level 1 (User Autonomy), Level 2 (System Audit), Level 3 (Supervised Protection), Level 4 (Mandatory Protection), and Level 5 (Special Control Protection)."),
        ("Classified Protection - Level 3 Impact", "In Classified Protection 2.0, Level 3 protection applies to information systems whose compromise would cause which severity of impact?",
         ["Slight harm to legitimate rights of citizens, but no harm to social order or public interest",
          "Serious harm to social order and public interest, or harm to national security",
          "Extremely serious harm to national security directly causing collapse of state governance",
          "General harm to enterprise profitability without any public impact"], "B",
         "Level 3 (Supervised Protection) applies to critical networks where security incidents cause serious harm to social order and public interests, or significant harm to national security. Most government and financial online systems require Level 3 compliance."),
        ("TCSEC - Highest Division", "In the Trusted Computer System Evaluation Criteria (TCSEC, Orange Book), which division represents the highest level of security evaluation?",
         ["Division D", "Division C", "Division B", "Division A"], "D",
         "TCSEC categorizes systems into four divisions: D (Minimal protection), C (Discretionary protection: C1, C2), B (Mandatory protection: B1, B2, B3), and A (Verified protection: A1), where Division A is the highest verified security level."),
        ("TCSEC - Class C2", "Which TCSEC division and class introduced individual user identification and auditing requirements (Discretionary Access Control)?",
         ["Class D", "Class C2", "Class B2", "Class A1"], "B",
         "Class C2 (Controlled Access Protection) enforces individual login accountability, discretionary access control (DAC), and comprehensive audit trail logging, making it the historical baseline for commercial operating systems."),
        ("APT Characteristics", "Which of the following is a prominent characteristic of an Advanced Persistent Threat (APT)?",
         ["Uncoordinated, short-duration high-volume automated ping sweeps",
          "Highly organized, stealthy, customized, and persistent attack targeting high-value assets over an extended period",
          "Purely accidental misconfigurations caused by novice network operators",
          "Public Wi-Fi packet sniffing without target selection"], "B",
         "An APT is characterized by advanced attack techniques, persistent reconnaissance, stealthy lateral movement, and evasion of conventional defenses, sustained over long durations to extract intellectual property or sabotage operations."),
        ("Zero Trust Philosophy", "What is the foundational philosophy of the Zero Trust security model?",
         ["Trust internal network traffic by default; inspect only perimeter traffic",
          "Never trust, always verify; inspect and authenticate every request regardless of network location",
          "Rely solely on hardware border firewalls to defend the trusted core",
          "Grant unrestricted administrative privileges once user identity is validated at login"], "B",
         "Zero Trust operates under the tenet 'Never Trust, Always Verify'. It assumes breaches are inevitable, eliminating implicit trust based on network locality and requiring continuous verification of identity, device, and context."),
        ("SDP Connectivity", "In a Software-Defined Perimeter (SDP) framework, how is network connectivity established?",
         ["Servers broadcast their IP and open ports publicly to allow direct client discovery",
          "The infrastructure remains invisible ('dark') until an SDP controller validates user and device identity",
          "Static security policies are permanently mapped to physical switch ports",
          "All communications bypass encryption to accelerate line-rate throughput"], "B",
         "SDP follows a 'Need-to-Know' paradigm where protected servers and services remain invisible behind Gateways. Connectivity is dynamically granted only after the centralized SDP Controller verifies client identity and device posture."),
        ("Cybersecurity Legislation", "What is the primary objective of national cybersecurity laws and data security regulations?",
         ["To eliminate the need for enterprise firewalls and antivirus software",
          "To safeguard cyberspace sovereignty, national security, public interest, and lawful citizen data rights",
          "To mandate that all enterprise networks use unencrypted communication protocols",
          "To replace internal enterprise security audits with foreign third-party certification"], "B",
         "National cybersecurity regulations establish statutory obligations for network operators to protect critical infrastructure, maintain operational continuity, prevent cybercrimes, and protect citizens' personal privacy."),
        ("Social Engineering - Phishing", "An attacker posing as an IT support engineer contacts an employee to obtain their domain credentials under the guise of an urgent security upgrade. What attack type is this?",
         ["Port scanning", "Smurf attack", "Social engineering / Phishing", "Buffer overflow"], "C",
         "Social engineering exploits human psychology rather than software vulnerabilities. Attackers use impersonation, pretexts, urgency, or deception to trick authorized personnel into disclosing credentials or sensitive data."),
        ("Defense in Depth", "What is the fundamental benefit of implementing a 'Defense-in-Depth' architecture?",
         ["It guarantees 100% immunity against zero-day malware without software updates",
          "If a single defensive mechanism fails, multiple subsequent layers continue to protect critical assets",
          "It eliminates the need for user authentication and authorization",
          "It consolidates all security functions onto a single border router"], "B",
         "Defense-in-Depth deploys multiple overlapping security controls across physical, perimeter, network, host, application, and data tiers, ensuring that compromise of any single layer does not compromise the entire enterprise."),
        ("PDCA Cycle", "Which sequence correctly describes the continuous improvement lifecycle for enterprise security management?",
         ["Execute -> Terminate -> Delete -> Ignore",
          "Plan -> Do -> Check -> Act (PDCA)",
          "Attack -> Defend -> Forget -> Re-install",
          "Inspect -> Block -> Allow -> Reset"], "B",
         "The PDCA (Plan-Do-Check-Act) Deming cycle is the standard management framework adopted by ISO 27001 for establishing, maintaining, and continually optimizing organizational information security policies."),
        ("Classified Protection - Tech Domains", "Which of the following is NOT one of the four general technical requirement domains in Classified Protection 2.0?",
         ["Physical and Environmental Security", "Network and Communication Security", "Equipment and Computing Security", "Marketing and Public Relations Security"], "D",
         "The four core technical requirement areas in Classified Protection 2.0 are: Physical and Environmental Security, Network and Communication Security, Equipment and Computing Security, and Application and Data Security."),
        ("Classified Protection - Management Domains", "Which of the following belongs to the general security management requirements in Classified Protection 2.0?",
         ["Security Management System, Organization, Personnel, Construction, and Operation",
          "Hardware BIOS Flashing and CPU Overclocking",
          "External Advertising and Social Media Marketing",
          "Quarterly Revenue Reporting and Tax Filing"], "A",
         "The five management requirement domains under Classified Protection 2.0 comprise: Security Management System, Security Management Organization, Security Management Personnel, Security Construction Management, and Security Operation Management."),
        ("Security Intelligence Center", "What is the primary function of a Security Intelligence Center (such as Huawei Cloud Security Intelligence)?",
         ["To remotely format local enterprise hard drives during high load",
          "To aggregate global threat feeds, analyze zero-day exploits, and distribute real-time signature updates",
          "To replace local enterprise network switches with software emulators",
          "To permanently assign public IPv4 addresses to unauthorized mobile devices"], "B",
         "Security Intelligence Centers analyze global telemetry, malware binaries, and emerging exploits using big data analytics and AI, producing up-to-date threat feeds, IPS/AV signatures, and malicious IP/domain blacklists."),
        ("Cyberspace Characteristics", "Why is cyberspace considered an artificial, man-made operational domain compared to land, sea, air, and space?",
         ["It exists purely as a natural physical phenomenon without hardware",
          "It is built upon physical microelectronics, logical network protocols, and software created by human engineering",
          "It operates entirely without electrical power or telecommunication links",
          "It is governed solely by international maritime law"], "B",
         "Cyberspace is an engineered domain consisting of physical network infrastructure, logical software architectures, and cognitive human interaction, making it inherently dynamic and constantly evolving."),
        ("Controllability Definition", "Under the five-pillar information security framework, what does 'Controllability' refer to?",
         ["Ensuring network bandwidth is throttled to 56 kbps at all times",
          "Controlling information dissemination and maintaining administrative authority over information systems",
          "Preventing any user from ever accessing external web servers",
          "Eliminating all logging and auditing mechanisms on border firewalls"], "B",
         "Controllability ensures that security administrators can monitor, audit, and regulate the lifecycle, flow, content, and system access of information assets, preventing unauthorized operations and policy violations."),
        ("Ransomware Mechanism", "What is the primary economic extortion technique utilized by modern ransomware families?",
         ["Flooding target routers with ICMP echo requests until bandwidth saturation occurs",
          "Silently modifying website HTML source code to display jokes without data loss",
          "Encrypting critical organizational files with strong ciphers and demanding cryptocurrency for the private key",
          "Stealing physical server chassis from locked enterprise datacenter racks"], "C",
         "Ransomware uses high-grade symmetric and asymmetric cryptographic algorithms (e.g., AES-256 + RSA-2048) to encrypt user data in place, coercing victims into paying ransoms to obtain the decryption key."),
        ("Vulnerability vs Exploit", "What is the technical distinction between a 'Vulnerability' and an 'Exploit'?",
         ["A vulnerability is malicious software code, whereas an exploit is a security standard",
          "A vulnerability is a defect/weakness in software or hardware; an exploit is code or technique used to take advantage of it",
          "A vulnerability only affects physical cables, while an exploit only affects web browsers",
          "There is no distinction; both terms are exact synonyms in network engineering"], "B",
         "A vulnerability is a flaw, bug, or design weakness present in software, protocols, or firmware. An exploit is a crafted payload, tool, or sequence of commands specifically constructed to take advantage of that vulnerability."),
        ("Residual Risk", "What is 'Residual Risk' in enterprise risk management?",
         ["The initial risk measured before any security countermeasures are considered",
          "The remaining risk that persists after appropriate security controls have been implemented",
          "The risk that only affects obsolete hardware discarded in storage rooms",
          "Risk that has been 100% eliminated through cyber insurance"], "B",
         "Residual risk is the remaining risk level after security controls, safeguards, and mitigation policies have been deployed. An organization must determine whether residual risk falls within its acceptable risk appetite."),
        ("Security Awareness", "Why is regular security awareness training considered a critical component of enterprise security?",
         ["It completely replaces the need for technical controls like firewalls and IPS",
          "Human errors and social engineering remain major attack vectors; user awareness mitigates phishing and policy violations",
          "It guarantees that network equipment will never experience hardware power outages",
          "It allows regular employees to rewrite firewall kernel code without supervision"], "B",
         "Humans are frequently the weakest link in the security perimeter. Attackers leverage phishing and social engineering to bypass perimeter defenses; continuous training develops vigilance and adherence to security protocols."),
        ("Asset Classification", "What is the first fundamental step in conducting an enterprise information security risk assessment?",
         ["Purchasing the most expensive firewall available on the market",
          "Identifying and classifying organizational information assets based on business value and sensitivity",
          "Disabling all incoming and outgoing Internet traffic across all branch offices",
          "Assigning equal public administrative access to all internal and external users"], "B",
         "Before risks can be assessed or mitigated, an organization must identify and catalog its critical assets (hardware, software, data, personnel) and categorize them according to confidentiality, integrity, and availability impact."),
        ("Cyberspace Sovereignty", "How does the concept of national cyberspace sovereignty apply to digital communications?",
         ["Nation-states have independent jurisdiction over network infrastructure, data, and cyber activities within their sovereign territory",
          "No government has the authority to regulate or protect domestic telecommunication systems",
          "All data packets traversing global fiber optics are owned exclusively by international software vendors",
          "Cyber activities are strictly exempt from domestic legal compliance"], "A",
         "Cyberspace sovereignty reflects a state's independent jurisdiction and authority over its sovereign territory's cyber infrastructure, facilities, data governance, and legal accountability in cyberspace."),
        ("Risk Transfer", "An enterprise decides to purchase cyber insurance to compensate for potential financial losses from data breaches. Which risk treatment strategy is being applied?",
         ["Risk Avoidance", "Risk Mitigation", "Risk Transfer", "Risk Acceptance"], "C",
         "Risk Transfer involves shifting financial liability or risk consequences to an external third party, commonly accomplished through cyber insurance policies or contractual outsourcing."),
        ("Risk Acceptance", "When an organization formally decides to take no further action regarding an identified low-impact vulnerability because the cost of fixing it exceeds potential loss, this strategy is called:",
         ["Risk Avoidance", "Risk Acceptance", "Risk Transfer", "Risk Exploitation"], "B",
         "Risk Acceptance occurs when management formally acknowledges an identified risk and decides not to deploy countermeasures because the risk falls within acceptable tolerance or mitigation costs exceed the value of the asset."),
        ("Defense in Depth - IAM", "In a multi-tier defense architecture, which security mechanism operates at the identity and access management layer?",
         ["Fiber optic intrusion detection sensor", "Multi-Factor Authentication (MFA) and Least Privilege RBAC", "BGP Route Reflector filtering", "Shielded twisted pair copper grounding"], "B",
         "Identity and Access Management (IAM) controls operate at the logical user tier, employing Multi-Factor Authentication (MFA), role-based access control (RBAC), and least privilege to enforce access boundaries."),
        ("ISMS Purpose", "What is the core purpose of establishing an ISMS according to ISO 27001?",
         ["To build a systematic, ongoing management framework that identifies, manages, and minimizes security risks to corporate data",
          "To replace all human employees with automated AI bots",
          "To mandate the exclusive use of proprietary networking hardware",
          "To produce marketing materials for social media advertising"], "A",
         "An ISMS is a systematic framework comprising policies, processes, procedures, organizational structures, and software/hardware controls designed to manage and protect an organization's sensitive information assets."),
        ("TCSEC B1 Mandatory Access Control", "What significant capability was introduced at the TCSEC Division B (specifically B1) level compared to Division C?",
         ["Elimination of all password authentication mechanisms",
          "Mandatory Access Control (MAC) based on security labels and sensitivity levels",
          "Unrestricted file sharing across all military networks without classification",
          "Use of wireless Ethernet transmission without authentication"], "B",
         "TCSEC Division B introduced Mandatory Access Control (MAC), where data objects and subjects carry formal security labels (e.g., Unclassified, Confidential, Secret, Top Secret), enforcing the Bell-LaPadula mathematical security model."),
        ("Physical Security Priority", "Why does Classified Protection 2.0 list 'Physical and Environmental Security' as a mandatory technical domain?",
         ["Because physical access to server hardware bypasses logical controls, allowing direct storage extraction or hardware compromise",
          "Because physical cables are immune to eavesdropping and environmental fire hazards",
          "Because physical security replaces the necessity of IP routing protocols",
          "Because server racks cannot operate unless painted in certified colors"], "A",
         "Physical security is the bedrock of information assurance. If an adversary gains physical access to a server or network switch, logical controls (passwords, firewalls) can be circumvented via local console access, hardware implants, or direct drive extraction.")
    ]

    for item in s_items:
        single.append({
            "chapter_num": 1,
            "chapter_title": CHAPTER_NAMES[1],
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # --- CH1 MULTI CHOICE (26 questions) ---
    m_items = [
        ("CIA Triad Components", "Which of the following are the three fundamental pillars that constitute the classic CIA Triad in information security?",
         ["Confidentiality", "Integrity", "Availability", "Centralization", "Scalability"], "ABC",
         "The traditional Information Security Triad consists of Confidentiality (preventing unauthorized disclosure), Integrity (preventing unauthorized modification), and Availability (ensuring accessible services)."),
        ("1990s Information Security Principles", "Which of the following principles were introduced during the 1990s Information Assurance era to expand upon the traditional CIA triad?",
         ["Controllability", "Non-repudiation", "Anonymity", "Decentralization"], "AB",
         "The five pillars of the 1990s Information Assurance era are Confidentiality, Integrity, Availability, Controllability (supervising and regulating information), and Non-repudiation (preventing denial of actions)."),
        ("Enterprise Information Assurance Aspects", "From which of the following perspectives was an enterprise information assurance system constructed during the Information Assurance era?",
         ["Services", "Security system", "Management", "Physical real estate"], "ABC",
         "Enterprise information assurance systems were comprehensively established across three dimensions: Services (risk mitigation for diverse business traffic), Security Systems (technical controls and proactive defense), and Management (personnel and administrative policies)."),
        ("Cybersecurity Objectives", "Which of the following are primary objectives of modern cyberspace security?",
         ["Safeguarding critical information infrastructure",
          "Ensuring personal data privacy and digital rights",
          "Protecting national security and economic stability in digital domains",
          "Permanently disabling Internet connectivity between enterprise branch offices"], "ABC",
         "Cyberspace security aims to defend critical information infrastructure, safeguard digital privacy, prevent cyber attacks, and maintain national security and economic prosperity across the digital space."),
        ("ISO 27000 Series Family", "Which of the following statements regarding the ISO 27000 family of information security standards are true?",
         ["ISO/IEC 27001 specifies normative requirements for establishing and certifying an ISMS",
          "ISO/IEC 27002 provides a comprehensive code of practice and control guidelines",
          "ISO/IEC 27002 can be used directly by an enterprise to obtain accredited third-party certification",
          "The standards follow the Plan-Do-Check-Act (PDCA) continuous improvement framework"], "ABD",
         "ISO 27001 is the formal certifiable specification for an ISMS, while ISO 27002 is an advisory code of practice (not directly certifiable). Both align with the PDCA continual improvement cycle."),
        ("Classified Protection 2.0 Levels", "Which of the following are valid security protection levels defined in China's Cybersecurity Classified Protection 2.0?",
         ["Level 1: User Autonomy Protection",
          "Level 2: System Audit Protection",
          "Level 3: Supervised Protection",
          "Level 4: Mandatory Protection",
          "Level 5: Special Control Protection"], "ABCDE",
         "Classified Protection 2.0 formally establishes five levels: Level 1 (User Autonomy), Level 2 (System Audit), Level 3 (Supervised Protection), Level 4 (Mandatory Protection), and Level 5 (Special Control Protection)."),
        ("Classified Protection Technical Requirements", "Under Classified Protection 2.0, which of the following are designated as the general technical requirement categories?",
         ["Physical and Environmental Security",
          "Network and Communication Security",
          "Equipment and Computing Security",
          "Application and Data Security",
          "Customer Service Feedback Tracking"], "ABCD",
         "The four technical domains in Classified Protection 2.0 are Physical and Environmental Security, Network and Communication Security, Equipment and Computing Security, and Application and Data Security."),
        ("Classified Protection Management Requirements", "Which of the following domains are included under the general security management requirements of Classified Protection 2.0?",
         ["Security Management System",
          "Security Management Organization",
          "Security Management Personnel",
          "Security Construction Management",
          "Security Operation Management"], "ABCDE",
         "All five domains represent the official security management requirements in Classified Protection 2.0: System, Organization, Personnel, Construction, and Operation Management."),
        ("TCSEC Divisions", "Which of the following are primary security divisions defined in the TCSEC (Orange Book) standard?",
         ["Division D: Minimal Protection",
          "Division C: Discretionary Protection",
          "Division B: Mandatory Protection",
          "Division A: Verified Protection",
          "Division E: Open Source Protection"], "ABCD",
         "TCSEC defines four hierarchical divisions: Division D (Minimal), Division C (Discretionary: C1, C2), Division B (Mandatory: B1, B2, B3), and Division A (Verified: A1). There is no Division E."),
        ("APT Attack Stages", "Which of the following stages are typically observed in a sophisticated Advanced Persistent Threat (APT) campaign?",
         ["Reconnaissance and initial penetration (e.g., spear phishing)",
          "Establishing persistent backdoors and Command-and-Control (C2) communication",
          "Internal network discovery, lateral movement, and privilege escalation",
          "Data staging and stealthy exfiltration",
          "Immediate self-destruction of all target server power supplies on day one"], "ABCD",
         "An APT campaign progresses methodically through reconnaissance, initial infiltration, establishing command-and-control persistence, lateral propagation, privilege escalation, data collection, and covert exfiltration over weeks or months."),
        ("Zero Trust Core Principles", "Which of the following are core architectural principles of the Zero Trust model?",
         ["Explicit verification based on all available data points (identity, location, device health)",
          "Enforce least privilege access using just-in-time and just-enough access controls",
          "Assume breach and minimize blast radius through micro-segmentation",
          "Implicitly trust any device connected directly to an internal switch port"], "ABC",
         "Zero Trust relies on three guiding tenets: Verify Explicitly, Use Least Privilege Access, and Assume Breach. Traffic from internal network ports is never implicitly trusted."),
        ("Future Security Technology Trends", "Which of the following technologies reflect major trends shaping future enterprise network security architectures?",
         ["Artificial Intelligence (AI) and machine learning for automated anomaly detection",
          "Cloud-native security and Security Access Service Edge (SASE)",
          "Software-Defined Perimeter (SDP) and Zero Trust micro-segmentation",
          "Returning exclusively to 1980s unencrypted cleartext terminal protocols"], "ABC",
         "The future of network security centers on AI/ML threat analysis, cloud-delivered security frameworks (SASE/SSE), automated incident orchestration (SOAR), and Zero Trust/SDP architectures."),
        ("Information Asset Categories", "In an enterprise risk assessment, which of the following are considered critical information assets requiring protection?",
         ["Proprietary software applications and source code repositories",
          "Confidential customer records and financial transaction databases",
          "Physical servers, networking equipment, and security appliances",
          "Qualified cybersecurity personnel and domain administrators",
          "Obsolete promotional flyers displayed in the visitor lobby"], "ABCD",
         "Information assets encompass hardware infrastructure, software applications, electronic data, intellectual property, and key human personnel who operate and manage the infrastructure."),
        ("Risk Treatment Options", "Which of the following are recognized risk treatment strategies in information security risk management?",
         ["Risk Mitigation (Reduction)",
          "Risk Avoidance",
          "Risk Transfer (Sharing)",
          "Risk Acceptance (Retention)",
          "Risk Fabricating"], "ABCD",
         "The four standard risk treatment options under ISO 27005 and NIST frameworks are Risk Mitigation (applying controls), Risk Avoidance (stopping the risky activity), Risk Transfer (insurance/outsourcing), and Risk Acceptance (tolerating residual risk)."),
        ("Social Engineering Vectors", "Which of the following techniques are commonly classified under social engineering attacks?",
         ["Spear phishing emails containing malicious attachments",
          "Vishing (voice phishing phone calls impersonating corporate officers)",
          "Baiting using malware-infected USB drives left in parking lots",
          "Overwriting router flash memory using laser drilling"], "ABC",
         "Social engineering leverages cognitive deception against humans, encompassing phishing, spear phishing, vishing (voice), smishing (SMS), pretexting, and baiting with physical media."),
        ("Threat Actors Classification", "Which of the following are common threat actor categories recognized in cybersecurity threat modeling?",
         ["Organized cybercrime syndicates seeking financial gain",
          "Nation-state Advanced Persistent Threat (APT) groups",
          "Malicious insiders with authorized credentials",
          "Hacktivists motivated by political or ideological causes"], "ABCD",
         "Threat actors span cybercriminals (financial extortion), state-sponsored advanced threat actors (espionage/sabotage), insider threats (disgruntled employees), and hacktivists (ideological disruption)."),
        ("Defense in Depth Layers", "A comprehensive Defense-in-Depth architecture includes security controls across which of the following structural layers?",
         ["Physical perimeter and facility security",
          "Network perimeter and boundary firewalls",
          "Host operating systems and endpoint detection and response (EDR)",
          "Data-level encryption and access auditing"], "ABCD",
         "Defense-in-Depth organizes multi-layered barriers spanning physical security, network perimeter defenses, endpoint/host hardening, application security, and data-centric cryptographic controls."),
        ("Physical Security Threats", "Which of the following are considered physical and environmental security threats to enterprise data centers?",
         ["Power failure and electrical surges",
          "Fire, flooding, and HVAC temperature extremes",
          "Unauthorized physical intrusion into server rooms",
          "Cross-Site Scripting (XSS) in a web form"], "ABC",
         "Physical and environmental threats include environmental disasters (fire, flood, overheating), utility disruptions (blackouts, surges), and unauthorized physical entry. XSS is an application-layer logical vulnerability."),
        ("Non-repudiation Guarantees", "What primary guarantees are provided when a sender digitally signs an electronic document using their private key?",
         ["Proof of the sender's authentic identity (Data Origin Authentication)",
          "Proof that the document content was not altered since signature generation (Integrity)",
          "Inability of the sender to falsely deny having generated the document (Non-repudiation)",
          "Automatic encryption of the document so that the receiver cannot read it"], "ABC",
         "A digital signature provides origin authentication, data integrity, and legal non-repudiation. It does not by itself encrypt the plaintext document unless an encryption operation is explicitly paired with it."),
        ("Security Policy Hierarchy", "An enterprise information security governance structure typically includes which of the following documentation levels?",
         ["Top-level Information Security Policies approved by executive leadership",
          "Topic-specific Security Standards and baselines",
          "Detailed Security Operating Procedures (SOPs) and Work Instructions",
          "Security Guidelines and best practices recommendations"], "ABCD",
         "Enterprise security policy hierarchy descends from high-level Policies (mandatory executive directives), to Standards (mandatory specific configurations), Procedures (step-by-step instructions), and Guidelines (advisory recommendations)."),
        ("Common Security Compliance Drivers", "Which of the following factors drive enterprise investments in network security compliance?",
         ["Legal and regulatory mandates (e.g., national cybersecurity laws, data protection acts)",
          "Industry standard mandates (e.g., PCI-DSS for credit card processing)",
          "Mitigating severe financial liabilities from security breaches and ransomware",
          "Protecting corporate brand reputation and customer trust"], "ABCD",
         "Security compliance is driven by statutory regulations, industry standards, financial risk mitigation, business continuity requirements, and brand trust preservation."),
        ("Impact of Security Incidents", "Severe cybersecurity breaches can inflict which of the following negative impacts on an enterprise?",
         ["Direct financial loss from theft, ransom payments, and forensic remediation",
          "Regulatory fines and sanctions from government supervisory bodies",
          "Operational service interruption and supply chain paralysis",
          "Loss of intellectual property, trade secrets, and competitive advantage"], "ABCD",
         "Cyber breaches cause cascading damage including direct monetary losses, legal penalties, operational downtime, reputational damage, and forfeiture of intellectual property."),
        ("Data Security Lifecycle", "Which of the following represent recognized stages of the data security lifecycle?",
         ["Data Creation and Collection",
          "Data Storage and Transmission",
          "Data Processing and Sharing",
          "Data Destruction and Sanitization"], "ABCD",
         "The end-to-end data security lifecycle consists of Creation/Collection, Storage, Transmission, Processing/Use, Sharing, and Destruction/Disposal, requiring security controls at every phase."),
        ("Threat Intelligence Types", "In modern cyber defense, threat intelligence is commonly classified into which of the following levels?",
         ["Strategic Threat Intelligence (high-level risk trends for executives)",
          "Operational Threat Intelligence (details on threat actor TTPs)",
          "Tactical Threat Intelligence (Indicators of Compromise: IPs, hashes, domains)",
          "Fictional Threat Intelligence (creative storytelling for movie scripts)"], "ABC",
         "Cyber threat intelligence is structured into Strategic (business impact and threat landscape), Operational (adversary tactics, techniques, and procedures - TTPs), and Tactical (technical IoCs like IP blacklists and file hashes)."),
        ("TCSEC Division C Classes", "Which of the following evaluation classes belong to TCSEC Division C (Discretionary Protection)?",
         ["Class C1: Discretionary Security Protection",
          "Class C2: Controlled Access Protection",
          "Class C3: Complete Mandatory Encryption",
          "Class C4: Quantum Key Distribution"], "AB",
         "TCSEC Division C contains exactly two classes: Class C1 (Discretionary Security Protection) and Class C2 (Controlled Access Protection). There are no C3 or C4 classes."),
        ("Controllability Safeguards", "Which technical mechanisms contribute directly to maintaining 'Controllability' over corporate networks?",
         ["Centralized security logging, SIEM, and SOC auditing",
          "Network access control (NAC) enforcing endpoint compliance",
          "Firewall security policies regulating protocol and application flows",
          "Allowing all internal users unrestricted root access to production databases"], "ABC",
         "Controllability is sustained through continuous logging/auditing, Network Access Control (NAC), granular firewall filtering, and behavioral monitoring. Granting unrestricted root access severely destroys controllability.")
    ]

    for item in m_items:
        multi.append({
            "chapter_num": 1,
            "chapter_title": CHAPTER_NAMES[1],
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # --- CH1 TRUE/FALSE (26 questions) ---
    tf_items = [
        ("ISO 27002 Certification", "ISO/IEC 27002 can be used directly to certify an enterprise's information security management system (ISMS).",
         "B",
         "False. ISO/IEC 27001 is the normative specification used for ISMS certification. ISO/IEC 27002 is an advisory code of practice providing guidance on implementing security controls and cannot be certified against directly."),
        ("Confidentiality and Plaintext", "If an attacker intercepts an encrypted ciphertext message across the Internet but cannot decrypt it, confidentiality has been successfully preserved.",
         "A",
         "True. Confidentiality ensures that unauthorized entities cannot access the plaintext meaning of the information. Intercepting encrypted ciphertext without the key preserves confidentiality."),
        ("Availability and Hardware Redundancy", "Deploying redundant power supplies and clustered firewalls helps safeguard the Availability attribute of the CIA triad.",
         "A",
         "True. Hardware redundancy, uninterruptible power supplies (UPS), and dual-system firewall clustering ensure that services continue running reliably without disruption, directly protecting Availability."),
        ("Communication Security Era Focus", "In the 1940s Communication Security era, information security primarily focused on software-defined wide area network (SD-WAN) encryption.",
         "B",
         "False. In the 1940s, modern computer networks did not exist. Information security was restricted to physical security and basic cipher communications (such as manual stream ciphers for telegraph and radio)."),
        ("Non-repudiation with Symmetric Keys", "Symmetric key encryption alone provides non-repudiation because both communication parties share the exact same key.",
         "B",
         "False. Because both sender and receiver share the identical secret symmetric key, either party could have generated the message. Therefore, symmetric encryption cannot mathematically prove which party originated the data, failing to provide non-repudiation."),
        ("Classified Protection 2.0 Scope", "Cybersecurity Classified Protection 2.0 applies only to traditional isolated PC workstations and excludes cloud computing, IoT, and industrial control systems.",
         "B",
         "False. Classified Protection 2.0 (MLPS 2.0) significantly expanded its scope beyond traditional networks to explicitly cover Cloud Computing, Mobile Internet, Internet of Things (IoT), Industrial Control Systems (ICS), and Big Data."),
        ("TCSEC Division D", "In TCSEC (Orange Book), Division D represents systems that have been evaluated and verified to provide the highest cryptographic security.",
         "B",
         "False. In TCSEC, Division D is labeled 'Minimal Protection' and represents systems that have failed security evaluation or provide no effective security controls. Division A is the highest verified tier."),
        ("Zero Trust Perimeter Assumption", "The Zero Trust model assumes that internal corporate networks are inherently safe and free from threat actors.",
         "B",
         "False. The core assumption of Zero Trust is 'Assume Breach'. It posits that threats already exist inside the perimeter and that no user, device, or packet should be trusted by default."),
        ("SDP Architecture Model", "A Software-Defined Perimeter (SDP) makes server infrastructure completely invisible to unauthorized users until mutual identity authentication is completed.",
         "A",
         "True. SDP enforces a 'Black Cloud' / invisible infrastructure model where gateway ports remain closed to the public Internet and open only after the centralized controller authenticates the connecting user and device."),
        ("Classified Protection Level 5", "Level 5 in Classified Protection 2.0 is termed 'Special Control Protection' and is applied to systems critical to national security with the highest protection requirements.",
         "A",
         "True. Level 5 is the maximum classification under MLPS 2.0, reserved for systems vital to state sovereignty, national defense, and critical national security infrastructure."),
        ("Integrity and Hashing", "A cryptographic hash function can guarantee confidentiality because the hash value cannot be reversed to derive the original plaintext.",
         "B",
         "False. A cryptographic hash function guarantees Integrity (tamper detection), not confidentiality. While hashes are irreversible one-way functions, hashing is not an encryption mechanism because the original plaintext cannot be recovered from the digest."),
        ("APT Attack Stealth", "APT attacks frequently utilize zero-day vulnerabilities and customized malware to remain undetected inside enterprise networks for months or years.",
         "A",
         "True. A hallmark of Advanced Persistent Threats is stealthy persistence, leveraging zero-day exploits, living-off-the-land techniques, and custom backdoors to evade signature-based detection."),
        ("Cybersecurity Sovereignty Principle", "Under the principle of cyberspace sovereignty, an enterprise operates completely outside the jurisdiction of domestic laws when handling digital data.",
         "B",
         "False. Cyberspace sovereignty establishes that state laws and regulatory authority extend directly over all cyber infrastructure, data processing, and digital operations conducted within national boundaries."),
        ("Risk Avoidance Definition", "Disconnecting a vulnerable legacy server from the corporate network and decommissioning its service is an example of Risk Avoidance.",
         "A",
         "True. Risk Avoidance involves eliminating the risk by completely terminating or avoiding the activity, system, or process that gives rise to the risk."),
        ("Risk Transfer via Insurance", "Purchasing cyber insurance completely eliminates all technical vulnerabilities from an organization's network infrastructure.",
         "B",
         "False. Cyber insurance is a financial Risk Transfer mechanism that offsets monetary liabilities and recovery costs; it does not repair technical vulnerabilities or prevent network attacks."),
        ("Security Awareness and Humans", "Human error and credential phishing remain among the most frequent initial entry vectors for corporate cyber breaches.",
         "A",
         "True. Industry statistics consistently confirm that social engineering, phishing, and human errors account for the majority of initial security compromises, making ongoing security training essential."),
        ("ISO 27001 PDCA Applicability", "The Plan-Do-Check-Act (PDCA) model in ISO 27001 means security policies are written once and never require subsequent audit or revision.",
         "B",
         "False. The PDCA model requires continuous, iterative improvement: Plan (design ISMS), Do (implement controls), Check (monitor and review effectiveness), and Act (maintain and optimize continuously)."),
        ("Physical Access Danger", "An attacker who obtains direct physical access to an enterprise server chassis can easily bypass operating system authentication by booting from external media.",
         "A",
         "True. Physical possession allows attackers to boot alternative operating systems, extract unencrypted hard drives, clear firmware passwords, or attach hardware sniffers, completely bypassing OS-level logical controls."),
        ("Classified Protection Level 1 Certification", "Information systems classified at Level 1 under Classified Protection 2.0 require mandatory annual third-party audits and supervision by national regulatory bodies.",
         "B",
         "False. Level 1 is 'User Autonomy Protection'. Organizations can autonomously design and maintain their systems without mandatory periodic government audits. Regulatory supervision begins at Level 3."),
        ("Social Engineering Defense", "Technical firewalls and antivirus software alone are sufficient to protect an enterprise against all social engineering attacks.",
         "B",
         "False. Social engineering targets human psychology (authority, fear, curiosity). While technical filters block some phishing links, educating employees is critical to thwarting social manipulation."),
        ("Controllability and Auditing", "A system where administrators have no ability to view user activity logs or enforce access policies complies fully with the Controllability principle.",
         "B",
         "False. Controllability requires the capability to supervise, monitor, and regulate information flows and user actions. Without logging or access enforcement, Controllability is entirely lost."),
        ("Residual Risk Tolerance", "An organization can achieve zero residual risk across all business systems if sufficient security budget is allocated.",
         "B",
         "False. Zero risk is practically impossible in complex connected environments. Residual risk always remains due to unknown vulnerabilities, emerging threat vectors, and human factors; organizations must manage risk within acceptable thresholds."),
        ("TCSEC Class C1 DAC", "In TCSEC Class C1, Discretionary Access Control allows object owners to determine which users can read or modify their files.",
         "A",
         "True. Discretionary Access Control (DAC) permits the owner or creator of a file/object to grant or restrict access permissions to other users at their own discretion."),
        ("Cyberspace Engineered Domain", "Unlike land, sea, and air, cyberspace was entirely designed and constructed by human beings.",
         "A",
         "True. Cyberspace is the only operational domain created artificially through computer engineering, telecommunications, microprocessors, and software protocols."),
        ("Threat Intelligence Value", "Subscribing to real-time threat intelligence feeds allows border firewalls to automatically block known command-and-control (C2) IP addresses and malicious domains.",
         "A",
         "True. Modern firewalls dynamically consume threat intelligence feeds to block traffic associated with known botnet controllers, phishing domains, and malicious IP addresses before attacks succeed."),
        ("Narrow vs Broad Network Security", "In a narrow sense, network security focuses on network security devices and architectures (such as firewalls and VPNs) protecting enterprise networks.",
         "A",
         "True. In a narrow sense, network security encompasses technical products and defensive solutions (firewalls, IDS/IPS, VPNs) ensuring the secure operation of enterprise data networks, as taught in HCIA-Security.")
    ]

    for item in tf_items:
        tf.append({
            "chapter_num": 1,
            "chapter_title": CHAPTER_NAMES[1],
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = build_ch1()
    print(f"Chapter 1 complete: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
