# scripts/generate_ch8.py
"""
Generates Chapter 8 data: 38 Single Choice, 28 Multiple Choice, 28 True/False.
Chapter 8: Firewall User Management Technologies
"""
import json

def get_ch8_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 8 SINGLE CHOICE (38 questions)
    s_data = [
        ("AAA Framework - Three Pillars", "In the network security AAA architecture, which of the following represents the core question addressed by 'Authentication'?",
         ["What did you do on the network?",
          "Who are you (identity verification)?",
          "What resources are you permitted to access?",
          "How much bandwidth did you consume?"], "B",
         "Authentication verifies the identity claimed by an entity (answering 'Who are you?'). Authorization determines access rights ('What can you do?'), and Accounting tracks resource consumption ('What did you do?')."),
        ("AAA Framework - Authorization", "Which component of AAA determines whether a validated user has permission to access a specific network segment or execute administrative commands?",
         ["Authentication", "Authorization", "Accounting", "Auditing"], "B",
         "Authorization grants or restricts permissions, service privileges, and resource access levels to an authenticated user based on policy."),
        ("AAA Framework - Accounting", "Which component of AAA is responsible for logging user session start and stop times, duration, and transmitted byte volumes for billing and auditing?",
         ["Authentication", "Authorization", "Accounting", "Attestation"], "C",
         "Accounting collects session metrics, timestamps, and resource consumption data used for billing, capacity planning, and forensic auditing."),
        ("User Categories - Local Users", "What defines a 'Local User' on a Huawei firewall?",
         ["A user whose account credentials and privilege levels are configured and stored directly in the firewall's local database",
          "A user who connects to the firewall using an analog dial-up modem",
          "A user whose identity is validated by an external RADIUS server",
          "A guest user accessing the network without a password"], "A",
         "Local users are configured and maintained in the local database of the firewall. They are ideal for local administrators or small branch deployments that lack external identity servers."),
        ("User Categories - Server Users", "When a firewall acts as a Network Access Server (NAS) and queries an external RADIUS or LDAP server to authenticate users, these users are classified as:",
         ["Local Users", "Server Users", "Anonymous Users", "Hardware Users"], "B",
         "Server users reside on external centralized authentication servers (RADIUS, HWTACACS, LDAP, Active Directory). The firewall relays authentication queries to these servers."),
        ("RADIUS Transport and Standard Ports", "Which transport protocol and standard default UDP ports are utilized by the RADIUS protocol for Authentication/Authorization and Accounting, respectively?",
         ["TCP port 49 for all functions",
          "UDP port 1812 for Authentication/Authorization, and UDP port 1813 for Accounting",
          "TCP port 80 for Authentication, and TCP port 443 for Accounting",
          "UDP port 53 for Authentication, and UDP port 67 for Accounting"], "B",
         "Standard RADIUS (RFC 2865 / RFC 2866) operates over UDP, using destination port 1812 for Authentication and Authorization, and port 1813 for Accounting (legacy RFCs used 1645 and 1646)."),
        ("RADIUS Packet Encryption Scope", "How does the RADIUS protocol protect sensitive user credentials during transmission between the NAS and the RADIUS server?",
         ["It encrypts the entire packet body and all attributes using AES-256",
          "It encrypts ONLY the User-Password attribute using an MD5-based algorithm; the rest of the packet (including username) is transmitted in cleartext",
          "It does not encrypt any part of the packet; all data is cleartext",
          "It converts the packet into an encrypted SSL VPN tunnel"], "B",
         "In standard RADIUS, only the User-Password attribute is encrypted (using an MD5 shared secret hash). The username, header, and other RADIUS attributes are sent in cleartext, making RADIUS vulnerable to username sniffing on untrusted networks."),
        ("RADIUS Auth and Authz Coupling", "How does RADIUS handle Authentication and Authorization in its protocol message exchange?",
         ["Authentication and Authorization are strictly separated into two independent TCP exchanges",
          "Authentication and Authorization are bundled together in the single `Access-Accept` response packet",
          "Authorization must always be performed before Authentication",
          "RADIUS does not support Authorization"], "B",
         "RADIUS couples Authentication and Authorization together. When the server validates credentials and sends an `Access-Accept` message, it includes authorization attributes (such as user group, VLAN, or ACL assignments) in the same packet."),
        ("HWTACACS Transport Protocol", "Which transport layer protocol and destination port are utilized by Huawei's HWTACACS protocol?",
         ["UDP port 1812", "TCP port 49", "TCP port 389", "UDP port 18514"], "B",
         "HWTACACS (based on TACACS+, RFC 1492) uses reliable TCP transport over destination port 49."),
        ("HWTACACS Encryption Scope", "What is the primary security advantage of HWTACACS encryption compared to standard RADIUS?",
         ["HWTACACS encrypts the entire packet body (payload) except the standard 12-byte header, protecting usernames and commands from eavesdropping",
          "HWTACACS uses unencrypted cleartext for maximum speed",
          "HWTACACS encrypts only the destination IP address",
          "HWTACACS uses physical quantum key encryption"], "A",
         "Unlike RADIUS which encrypts only the password, HWTACACS encrypts the entire body of the packet following the 12-byte header. This conceals usernames, authorization commands, and accounting parameters from passive sniffing."),
        ("HWTACACS Separation of AAA", "How does HWTACACS handle the relationship between Authentication, Authorization, and Accounting?",
         ["It merges all three functions into a single packet",
          "It strictly separates Authentication, Authorization, and Accounting into distinct, independent client-server exchanges",
          "It supports Authentication only and eliminates Authorization completely",
          "It requires all three functions to be performed on separate physical days"], "B",
         "A defining strength of HWTACACS is the strict separation of AAA functions. A network device can perform authentication against one server, authorize individual CLI commands against a second server, and log accounting records to a third."),
        ("HWTACACS Primary Use Case", "For which network operational scenario is HWTACACS predominantly deployed in enterprise networks?",
         ["Consumer public Wi-Fi guest portal logins",
          "Administrative device access and per-command authorization for routers, switches, and firewalls",
          "Dial-up residential Internet access billing",
          "Streaming video media delivery"], "B",
         "Due to per-command authorization, reliable TCP delivery, and full payload encryption, HWTACACS is the enterprise standard for administrative access control (TACACS+) over network infrastructure devices."),
        ("LDAP Directory Standard", "The Lightweight Directory Access Protocol (LDAP) is based on which international directory service architecture?",
         ["ITU-T X.500 directory model", "IEEE 802.11 wireless standard", "ISO 27001 ISMS model", "IETF RFC 1918 addressing model"], "A",
         "LDAP is a streamlined software protocol developed to provide lightweight network access to hierarchical directory information trees structured according to the ITU-T X.500 standard."),
        ("LDAP Transport Ports", "What are the standard TCP port numbers used for unencrypted LDAP and encrypted LDAPS (LDAP over SSL/TLS), respectively?",
         ["LDAP: TCP 80, LDAPS: TCP 443",
          "LDAP: TCP 389, LDAPS: TCP 636",
          "LDAP: TCP 23, LDAPS: TCP 22",
          "LDAP: TCP 1812, LDAPS: TCP 1813"], "B",
         "Standard LDAP communicates over cleartext TCP port 389, whereas encrypted LDAPS secures directory communications over TCP port 636 using TLS/SSL."),
        ("LDAP Distinguished Name Components", "In an LDAP directory tree, what do the abbreviations 'DC', 'OU', and 'CN' represent?",
         ["Data Center, Operating Unit, Computer Node",
          "Domain Component, Organizational Unit, Common Name",
          "Domain Controller, Open User, Certified Network",
          "Dynamic Configuration, Optical Unit, Core Network"], "B",
         "In LDAP Distinguished Names (DN), DC = Domain Component (e.g. `dc=example,dc=com`), OU = Organizational Unit (e.g. `ou=Engineering`), and CN = Common Name (e.g. `cn=Alice Smith`)."),
        ("Active Directory Integration", "How does a Huawei firewall integrate with Microsoft Active Directory (AD) for centralized user management?",
         ["By acting as the primary domain controller and deleting existing domain accounts",
          "By querying the AD domain controller via LDAP/LDAPS to authenticate domain users and synchronize organizational unit (OU) user groups",
          "By formatting the AD server hard drives",
          "By replacing all Windows domain workstations with Linux terminals"], "B",
         "Huawei firewalls integrate with Microsoft Active Directory using LDAP/LDAPS queries to validate user credentials and import/synchronize domain user groups, mapping enterprise domain structures directly into firewall policies."),
        ("User-Based Security Policy Advantage", "What is the primary advantage of applying security policies to 'User/User Group' objects rather than static IP addresses?",
         ["It reduces the physical power consumption of network switches",
          "Security policies dynamically follow the user regardless of which physical workstation or dynamic DHCP IP address they use",
          "It eliminates the need for user passwords",
          "It permanently disables all firewall session logging"], "B",
         "In modern enterprise networks with DHCP, Wi-Fi roaming, and mobile devices, a user's IP changes frequently. User-based policies bind access rules to the user's identity, ensuring appropriate permissions apply consistently wherever the user connects."),
        ("Portal Authentication Definition", "What is 'Portal Authentication' (Captive Portal) on a Huawei firewall?",
         ["A physical door lock opened using an RFID badge",
          "A web-based authentication method where unauthenticated users attempting HTTP browsing are redirected to a captive web login page to enter credentials",
          "An administrative terminal session using Telnet",
          "A dynamic routing protocol used between autonomous systems"], "B",
         "Portal authentication intercepts unauthenticated HTTP/HTTPS web requests from guest or employee devices and redirects them to a web captive portal, prompting users to authenticate before granting network access."),
        ("Single Sign-On (SSO) Goal", "What is the primary operational objective of Single Sign-On (SSO) on an enterprise firewall?",
         ["Requiring users to enter their credentials separately for every single website they visit",
          "Allowing users to authenticate once (e.g. at Windows domain workstation login) and have the firewall transparently identify them without prompted re-authentication",
          "Eliminating the need for firewalls on the network perimeter",
          "Forcing all employee computers to reboot every hour"], "B",
         "SSO allows users to authenticate once against an enterprise identity provider (e.g. Active Directory). The firewall transparently learns the user's IP-to-username mapping, applying user-specific security policies without interrupting user workflow."),
        ("AD SSO Event Monitoring", "How does Active Directory Single Sign-On (AD SSO) transparently map IP addresses to usernames without user intervention on Huawei firewalls?",
         ["The firewall monitors or queries Windows Domain Controller security event logs (specifically Event ID 4624 successful logon events) to correlate workstation IP with domain username",
          "The firewall installs a keylogger on the user's keyboard",
          "The firewall captures cleartext Telnet sessions",
          "The firewall asks the user to send an email every morning"], "A",
         "When a user logs into a Windows domain computer, the Domain Controller logs Event ID 4624 (Successful Logon) containing the user's account name and workstation IP. The firewall (or an SSO agent) monitors these security logs to dynamically build IP-to-user bindings."),
        ("RADIUS SSO Mechanism", "How does RADIUS Single Sign-On (RADIUS SSO) operate in campus wireless networks?",
         ["By transmitting user passwords over unencrypted broadcast radio",
          "The firewall intercepts (snoops) RADIUS Accounting-Request packets sent between wireless access controllers and the RADIUS server to learn IP-to-username bindings",
          "By disabling all wireless encryption on corporate access points",
          "By requiring users to manually configure firewall routing tables"], "B",
         "When users authenticate to 802.1X enterprise Wi-Fi, the Wireless Access Controller sends RADIUS Accounting-Request packets (containing username and assigned IP) to the RADIUS server. The firewall snoops these accounting packets to seamlessly register user-to-IP mappings."),
        ("Local User Service Types", "In Huawei VRP CLI, which command configures the allowed service types (e.g. SSH, HTTP, Telnet) for a local user account?",
         ["local-user <name> service-type { http | ssh | telnet | terminal }",
          "user-interface vty service enable",
          "firewall service user <name>",
          "aaa service start <name>"], "A",
         "In Huawei VRP AAA view, the command `local-user <name> service-type <types>` defines which access methods (HTTP web management, SSH, Telnet, or console terminal) the account can utilize."),
        ("Local User Privilege Level Range", "What is the standard administrator privilege level range for local users on Huawei network devices?",
         ["0 to 3 (or 0 to 15 on extended VRP systems)",
          "1 to 100",
          "0 to 65535",
          "Only level 1 and level 2"], "A",
         "Huawei VRP supports user privilege levels ranging from 0 (Visit), 1 (Monitor), 2 (Configuration), to 3 (Management), expandable up to level 15 for granular role-based access control."),
        ("User Group Hierarchy", "How are User Groups structured on Huawei NGFWs to simplify security policy administration?",
         ["All users must belong to exactly one flat group with no nesting",
          "User groups can be organized hierarchically into parent and child groups, mirroring enterprise organizational departments (e.g., Company -> R&D -> Software)",
          "User groups can only be assigned to physical switch ports",
          "User groups are limited to a maximum of 3 users per group"], "B",
         "Huawei NGFW supports hierarchical user groups with multi-level parent/child inheritance. Policies applied to a parent group automatically apply to members of subordinate child groups, matching enterprise organizational trees."),
        ("Guest User Management", "What capability is typically provided by Huawei firewall Guest User Management for temporary visitors?",
         ["Granting permanent unrestricted access to confidential source code databases",
          "Self-service registration, SMS verification code login, administrator approval workflows, and automatic account expiration",
          "Disabling all firewall security rules for visitor IP addresses",
          "Permanently burning visitor MAC addresses into the motherboard ROM"], "B",
         "Guest management provides self-service portal registration, one-time SMS verification codes, sponsor approval, and automatic expiration timers (e.g., access expires after 8 hours), securing visitor access."),
        ("Security Policy with User Matching", "When a security policy rule is configured with both an IP Address condition AND a User condition, how does the firewall evaluate traffic?",
         ["Both conditions must match (the traffic must originate from the specified IP AND belong to the specified authenticated user)",
          "The firewall ignores the user condition and checks only the IP address",
          "The firewall randomly selects one of the two conditions to evaluate",
          "The firewall drops the packet automatically as a configuration conflict"], "A",
         "Security policy conditions are combined using logical AND. For the rule to match, the packet must satisfy all specified criteria: it must originate from the defined IP range AND be mapped to the specified authenticated user."),
        ("IP-to-User Mapping Table Display", "Which Huawei VRP CLI command displays the active IP-to-user mapping table currently learned by the firewall?",
         ["display user-manage online-user", "display ip routing-table", "display firewall session table", "display mac-address"], "A",
         "The command `display user-manage online-user` outputs the current active online users, including their authenticated usernames, mapped IP addresses, authentication mode, and group memberships."),
        ("Authentication Domain Concept", "What is an 'Authentication Domain' in Huawei firewall AAA configuration?",
         ["A physical geographic territory where firewalls are sold",
          "An administrative container that binds authentication schemes, authorization schemes, accounting schemes, and server templates together for a category of users",
          "A DNS top-level domain ending in .org",
          "A hardware ASIC chip on the motherboard"], "B",
         "An Authentication Domain is a logical AAA management entity. It links specific authentication schemes (local/RADIUS/LDAP), authorization rules, and accounting servers, allowing different user groups (e.g., staff vs guests) to use distinct AAA pipelines."),
        ("Default Authentication Domain", "In Huawei firewall AAA architecture, which domain is utilized if a user logs in with a plain username without specifying a domain suffix (e.g., logging in as 'john' rather than 'john@corp')?",
         ["The guest domain", "The default domain (default to 'default' or configured default domain)", "The connection is rejected immediately", "The local loopback domain"], "B",
         "When credentials omit a domain suffix, the firewall automatically evaluates the login against the designated Default Domain (named `default` unless altered by administrators)."),
        ("Accounting Interim Update Interval", "Why do enterprise AAA deployments configure periodic 'Accounting Interim Updates' between the firewall and RADIUS accounting server?",
         ["To prevent the RADIUS server from entering sleep mode",
          "To provide regular ongoing session health checks and volume updates, ensuring accurate billing and detecting abrupt connection drops",
          "To change the user's password every 10 minutes",
          "To test the maximum throughput of the firewall backplane"], "B",
         "Interim accounting updates (sent periodically, e.g. every 15 minutes) inform the billing/auditing server that the session remains active and report cumulative data usage, preventing orphan sessions if a client disconnects without a formal stop message."),
        ("Password Storage Security in VRP", "How should passwords for local user accounts be configured in Huawei VRP CLI to prevent cleartext exposure in configuration files?",
         ["local-user <name> password plain <pwd>",
          "local-user <name> password cipher <pwd> (or using modern irreversible hashing like PBKDF2/SHA-256)",
          "local-user <name> password cleartext <pwd>",
          "Passwords cannot be stored in Huawei VRP"], "B",
         "Configuring `password cipher` (or newer secure hash keywords) ensures that passwords are encrypted or irreversibly hashed in configuration files, preventing exposure during administrative reviews or configuration exports."),
        ("Multi-Factor Authentication (MFA)", "How does Multi-Factor Authentication (MFA) enhance user authentication security on Huawei firewalls?",
         ["By requiring users to type their password twice on the same screen",
          "By requiring two or more independent credential categories (e.g., something you know [password], something you have [token/SMS code], something you are [biometric])",
          "By doubling the CPU clock frequency during authentication",
          "By requiring authentication exclusively during daylight hours"], "B",
         "MFA enforces defense-in-depth for user identity, requiring verification across distinct authentication factors (knowledge, possession, inherence), neutralizing threats from stolen or leaked passwords."),
        ("Online User Aging Mechanism", "What happens to an IP-to-user mapping in the firewall's online user table when a user's idle timeout elapses?",
         ["The user's workstation is automatically formatted",
          "The online user entry ages out and is cleared from the table, requiring the user to re-authenticate before accessing protected resources",
          "The firewall converts the user's account into a local administrator",
          "All firewall security policies are permanently disabled"], "B",
         "To maintain accurate bindings and reclaim resources, an aging timer monitors traffic from mapped IPs. If no traffic is detected within the idle timeout window, the user is logged out and removed from the active table."),
        ("LDAP Search Filter", "What is an LDAP Search Filter used for when the firewall queries an Active Directory server?",
         ["To restrict the search query to specific object classes and attributes (e.g., `(&(objectClass=user)(sAMAccountName=%u))` to locate a specific user)",
          "To filter out high-frequency electrical interference from Ethernet cables",
          "To delete unauthorized email messages on the exchange server",
          "To calculate the subnet mask of the domain controller"], "A",
         "LDAP search filters define precise criteria (using standardized RFC LDAP filter syntax) that instruct the directory server to return only matching user or group objects, optimizing query performance."),
        ("HWTACACS Command Authorization", "How does HWTACACS command authorization operate during an administrator's CLI session?",
         ["The administrator must reboot the switch after every command",
          "Each time the administrator enters a command at the CLI prompt, the firewall sends a separate authorization request to the HWTACACS server to verify if that user has permission to execute that specific command string",
          "The firewall executes all commands without checking permissions",
          "Commands are authorized only once at initial login"], "B",
         "With per-command authorization enabled, the firewall intercepts each command entered by the administrator and sends an authorization query to the HWTACACS server in real time. The command executes only if the server returns `PASS`."),
        ("Local User Account Locking", "What security feature protects local user accounts against online brute-force password guessing attacks on Huawei firewalls?",
         ["Automatic account lockout after a configurable number of consecutive failed authentication attempts (e.g., locked for 10 minutes after 3 failures)",
          "Permanently destroying the firewall flash storage after 5 failures",
          "Converting failed passwords into valid root passwords",
          "Disabling power to the enterprise building"], "A",
         "Account lockout policies automatically lock user accounts for a specified duration after consecutive failed login attempts, rendering automated brute-force credential attacks ineffective."),
        ("MAC-Address-Based Authentication", "In environments with non-interactive devices (such as IP cameras, printers, and IoT sensors) that lack web browsers, which authentication mode is commonly used?",
         ["Portal web browser authentication",
          "MAC Address Authentication (or 802.1X MAC bypass) where the device's physical MAC address serves as the authentication credential against a RADIUS server",
          "Requiring printers to type their passwords using touchscreens",
          "Disabling all network access for non-PC devices"], "B",
         "Headless IoT devices (printers, cameras, badge readers) cannot complete interactive web portal logins. MAC Authentication (MAB) automatically authenticates devices by using their hardware MAC address as the username and password against a RADIUS server."),
        ("Display User Status Command", "Which command is used in Huawei VRP to view the configuration and operational status of a specific local user account?",
         ["display local-user username <name>", "display current-user", "display password", "display interface"], "A",
         "The command `display local-user username <name>` outputs configuration parameters for the specified account, including privilege level, account state (active/locked), expiration time, and allowed service types.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 8,
            "chapter_title": "Firewall User Management Technologies",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 8 MULTIPLE CHOICE (28 questions)
    m_data = [
        ("AAA Core Functions", "Which of the following functions constitute the AAA security model in network management?",
         ["Authentication (verifying user identity)",
          "Authorization (granting resource access permissions)",
          "Accounting (tracking resource usage and session activity)",
          "Auditing (forensic review of system events)",
          "Attenuation (reducing electrical signal strength)"], "ABC",
         "The AAA model consists of Authentication, Authorization, and Accounting. While auditing is an associated security function, the three defining pillars of AAA are Authentication, Authorization, and Accounting."),
        ("User Types on Huawei Firewalls", "Which of the following are recognized user classifications managed by Huawei USG firewalls?",
         ["Local Users (stored in firewall local database)",
          "Server Users (stored on RADIUS, HWTACACS, LDAP, or AD servers)",
          "Third-Party / Guest Users (authenticated via web portals or external tokens)",
          "Virtual Machine Hypervisor Users"], "ABC",
         "Huawei firewalls classify users into Local Users, Server Users, and Third-Party/Guest Users based on their storage and authentication source."),
        ("RADIUS Operational Features", "Which of the following statements accurately characterize the RADIUS protocol?",
         ["It operates over UDP transport (ports 1812 and 1813)",
          "It couples Authentication and Authorization together in the `Access-Accept` message",
          "It encrypts only the User-Password attribute; usernames and other attributes are cleartext",
          "It strictly separates Authentication and Authorization into distinct TCP exchanges"], "ABC",
         "RADIUS uses UDP (1812/1813), combines authentication with authorization, and encrypts only the password attribute using MD5. Separating auth/authz is a characteristic of HWTACACS/TACACS+, not RADIUS."),
        ("HWTACACS Operational Features", "Which of the following statements accurately characterize Huawei's HWTACACS protocol?",
         ["It operates over reliable TCP transport on port 49",
          "It strictly separates Authentication, Authorization, and Accounting into distinct exchanges",
          "It encrypts the entire packet body following the standard header",
          "It is ideally suited for device administrative management and per-command authorization"], "ABCD",
         "HWTACACS runs over TCP port 49, separates all three AAA phases, encrypts the entire packet body, and is optimized for administrative command authorization."),
        ("LDAP Architecture Characteristics", "Which of the following statements regarding LDAP directory services are correct?",
         ["LDAP organizes directory data in a hierarchical tree structure called a Directory Information Tree (DIT)",
          "Standard cleartext LDAP uses TCP port 389, while encrypted LDAPS uses TCP port 636",
          "Common LDAP naming components include DC (Domain Component), OU (Organizational Unit), and CN (Common Name)",
          "LDAP is used exclusively to translate IP addresses into MAC addresses"], "ABC",
         "LDAP uses hierarchical DIT structures, communicates over TCP 389 (LDAP) and TCP 636 (LDAPS), and utilizes DC/OU/CN naming attributes. MAC address translation is handled by ARP, not LDAP."),
        ("User Identity Integration Advantages", "What advantages are gained by integrating user identities into Next-Generation Firewall security policies?",
         ["Security policies remain effective regardless of dynamic IP address changes caused by DHCP",
          "Administrators can assign permissions based on employee roles and organizational departments",
          "User activity auditing and forensic threat logs display actual usernames rather than anonymous IP addresses",
          "It completely eliminates the necessity for border firewalls"], "ABC",
         "User-aware policies decouple access control from volatile IP addresses, align rules with corporate roles, and provide clear user-attributed audit trails for security operations."),
        ("Single Sign-On (SSO) Methods", "Which SSO methods are supported by Huawei firewalls to automatically learn user-to-IP bindings without prompting users for credentials?",
         ["Active Directory SSO (monitoring AD domain controller security event logs)",
          "RADIUS SSO (snooping RADIUS accounting packets from switches or wireless controllers)",
          "Portal SSO via integrated web portal agents",
          "Acoustic Speech Recognition SSO"], "ABC",
         "Huawei NGFWs support AD SSO (monitoring event logs), RADIUS SSO (snooping accounting packets), and Portal SSO agents. Voice acoustic matching is not a network SSO protocol."),
        ("Portal Authentication Components", "Which entities are typically involved in a complete Portal authentication system architecture?",
         ["Client Web Browser (User equipment)",
          "Network Access Server / Gateway (Firewall or Switch)",
          "Portal Web Server (Hosting login pages and authentication interfaces)",
          "Authentication Server (RADIUS or LDAP backend database)"], "ABCD",
         "Portal authentication involves four interacting entities: the Client browser, the NAS/Gateway (firewall), the Portal Web Server, and the backend AAA Authentication Server."),
        ("Local User Service Types in VRP", "Which service types can be assigned to a local user account in Huawei VRP AAA view?",
         ["`http` (Web GUI management access)",
          "`ssh` (Secure Shell CLI management access)",
          "`telnet` (Telnet terminal access)",
          "`terminal` (Physical console port access)",
          "`ftp` (File transfer access)"], "ABCDE",
         "Huawei VRP supports diverse service types for local users: HTTP/HTTPS, SSH, Telnet, Terminal (console), FTP, and PPP."),
        ("AD Domain Controller Event Logs for SSO", "Which security events on a Microsoft Active Directory Domain Controller are typically monitored by AD SSO solutions?",
         ["Event ID 4624 (An account was successfully logged on)",
          "Event ID 4634 (An account was logged off)",
          "Event ID 4768 (A Kerberos authentication ticket was requested)",
          "Event ID 1102 (The audit log was cleared)"], "ABC",
         "AD SSO solutions monitor successful logon events (4624), logoff events (4634), and Kerberos ticket requests (4768) to dynamically maintain active IP-to-username mappings."),
        ("RADIUS Accounting Packet Types", "Which message types are exchanged in the RADIUS accounting process?",
         ["Accounting-Request (Start)",
          "Accounting-Request (Interim-Update)",
          "Accounting-Request (Stop)",
          "Accounting-Response",
          "Accounting-Decline"], "ABCD",
         "RADIUS accounting uses Accounting-Request messages with status types Start, Interim-Update, and Stop, all acknowledged by the server via Accounting-Response. There is no 'Accounting-Decline' packet."),
        ("HWTACACS Packet Types", "Which of the following represent core message types defined in HWTACACS communication?",
         ["Authentication Start / Continue / Reply",
          "Authorization Request / Response",
          "Accounting Request / Response",
          "Optical Wavelength Modulation Request"], "ABC",
         "HWTACACS defines separate message structures for Authentication (Start/Continue/Reply), Authorization (Request/Response), and Accounting (Request/Response)."),
        ("AAA Authentication Schemes in VRP", "Which authentication methods can be specified within an Authentication Scheme on a Huawei firewall?",
         ["Local authentication (using the local user database)",
          "RADIUS authentication (querying external RADIUS servers)",
          "HWTACACS authentication (querying external TACACS servers)",
          "LDAP authentication (querying external directory servers)",
          "None (bypassing authentication completely)"], "ABCDE",
         "Huawei VRP authentication schemes support Local, RADIUS, HWTACACS, LDAP, and 'None' (allowing unauthenticated access)."),
        ("Active Directory Hierarchy Objects", "In Microsoft Active Directory, which organizational structures are mapped into Huawei firewall user hierarchies?",
         ["Organizational Units (OUs)",
          "Security Groups and Distribution Groups",
          "User Accounts",
          "Physical Computer Objects"], "ABC",
         "Firewalls import OUs, security groups, and individual user accounts from Active Directory to recreate organizational trees in firewall policy configurations."),
        ("Guest Authentication Features", "Which capabilities are provided by modern Guest Management systems on Huawei NGFWs?",
         ["Self-service guest portal registration",
          "SMS-based one-time passcode (OTP) verification",
          "Employee sponsor approval workflows for external visitors",
          "Time-limited access accounts that expire automatically after a predefined duration",
          "Unrestricted permanent administrative access to firewall configurations"], "ABCD",
         "Guest management supports self-registration, SMS OTPs, employee sponsor approvals, and automated account expiration. Unrestricted administrative access is never granted to guests."),
        ("Online User Table Attributes", "When viewing online users (`display user-manage online-user`), which attributes are displayed for each active user?",
         ["Username and User Group membership",
          "Mapped IPv4 or IPv6 address",
          "Authentication Mode (e.g. Local, RADIUS, SSO)",
          "Online duration and idle time elapsed",
          "Client computer physical weight"], "ABCD",
         "The online user table displays username, group, IP address, MAC address, authentication mode, connection duration, and idle timers."),
        ("Multi-Factor Authentication (MFA) Factors", "Which of the following represent recognized independent authentication factor categories in MFA?",
         ["Knowledge Factor: Something you know (e.g., password, PIN)",
          "Possession Factor: Something you have (e.g., hardware token, mobile phone for SMS OTP)",
          "Inherence Factor: Something you are (e.g., fingerprint, facial recognition)",
          "Locational Factor: Somewhere you are (e.g., GPS location, corporate subnet)",
          "Imaginary Factor: Something you dream"], "ABCD",
         "MFA leverages three primary factors: Knowledge (passwords), Possession (tokens/devices), and Inherence (biometrics), supplemented by context/location factors."),
        ("RADIUS Attributes in Access-Accept", "Which authorization parameters can a RADIUS server return to a firewall NAS inside an `Access-Accept` packet?",
         ["Assigned User Group / Role",
          "Authorized VLAN ID",
          "Filter-Id (referencing a local firewall ACL or policy)",
          "Session-Timeout and Idle-Timeout values",
          "Physical motherboard voltage settings"], "ABCD",
         "A RADIUS server returns authorization parameters including user group, assigned VLAN, Filter-Id (ACL), and session/idle timeouts."),
        ("HWTACACS Per-Command Authorization Flow", "During HWTACACS per-command authorization, what steps take place when an administrator enters a command?",
         ["The firewall intercepts the command string entered in the terminal",
          "The firewall transmits an Authorization Request containing the username, privilege level, and command string to the HWTACACS server",
          "The HWTACACS server checks its policy and returns an Authorization Response (PASS or FAIL)",
          "If authorized, the firewall executes the command; if denied, an error message is displayed"], "ABCD",
         "Per-command authorization sends each command string to the server; the server evaluates user permissions and returns PASS or FAIL before the command executes."),
        ("Authentication Domain Configuration Parameters", "Which schemes and server templates are linked within an Authentication Domain on a Huawei firewall?",
         ["Authentication Scheme",
          "Authorization Scheme",
          "Accounting Scheme",
          "RADIUS Server Template or HWTACACS Server Template",
          "Fiber Optic Transceiver Serial Number"], "ABCD",
         "An Authentication Domain links an Authentication Scheme, Authorization Scheme, Accounting Scheme, and associated RADIUS/HWTACACS/LDAP server templates."),
        ("Local User Account Security Settings", "Which security constraints can be configured on local user accounts in Huawei VRP?",
         ["Account expiration date and time",
          "Maximum allowed concurrent online sessions per account",
          "Account lockout threshold after consecutive failed login attempts",
          "Time-range restrictions specifying permitted login hours"], "ABCD",
         "Local user accounts support account expiration dates, concurrent session limits, brute-force lockout thresholds, and schedule-based login restrictions."),
        ("Password Complexity Policies in VRP", "Which password policy enforcement settings are supported on Huawei firewalls to enforce strong passwords?",
         ["Minimum password length requirement",
          "Mandatory inclusion of diverse character types (uppercase, lowercase, digits, special characters)",
          "Preventing password reuse from recent history",
          "Mandatory password expiration and aging intervals"], "ABCD",
         "VRP enforces password complexity: minimum length, character diversity requirements, history tracking to prevent reuse, and maximum password validity periods."),
        ("RADIUS vs HWTACACS Differences", "Which of the following statements correctly highlight differences between RADIUS and HWTACACS?",
         ["RADIUS uses UDP transport, whereas HWTACACS uses TCP transport",
          "RADIUS encrypts only the password, whereas HWTACACS encrypts the entire packet body",
          "RADIUS combines authentication and authorization, whereas HWTACACS separates them",
          "RADIUS is standard IETF RFC, whereas HWTACACS is Huawei's enhancement based on TACACS+"], "ABCD",
         "RADIUS uses UDP, encrypts only the password, and bundles auth/authz. HWTACACS uses TCP, encrypts the entire payload, and separates all three AAA phases."),
        ("User-Based Security Policy Elements", "When writing a user-aware security policy rule, which user identity entities can be selected as matching sources?",
         ["Individual specific user accounts",
          "User Groups (including parent and child groups)",
          "Security Groups imported from Active Directory",
          "Anonymous / Unregistered guest users",
          "Physical copper wiring categories"], "ABCD",
         "User-based policies can match specific user accounts, local user groups, imported Active Directory groups, and unregistered guest profiles."),
        ("Reasons for IP-to-User Mapping Expiration", "Under which conditions will an active IP-to-user mapping be removed from the firewall's online user table?",
         ["The user's idle timeout interval elapses without active network traffic",
          "The user explicitly logs out via the captive portal logout interface",
          "An Active Directory logoff event (Event ID 4634) is detected by AD SSO",
          "An administrator manually forces the user offline using CLI commands"], "ABCD",
         "Online user entries expire upon idle timeout, explicit portal logout, AD SSO logoff event detection, or administrative manual termination."),
        ("Portal Web Server Deployment Models", "Which deployment architectures are supported for Portal Web Servers in Huawei firewall deployments?",
         ["Built-In Portal Server (the firewall itself hosts the web portal login pages)",
          "External Portal Server (a dedicated external web server, e.g. Huawei Agile Controller / iMaster NCE, hosts the login portal)",
          "Satellite Relay Portal Server",
          "Analog Telegraph Portal Server"], "AB",
         "Huawei firewalls support Built-in Portal servers (hosted directly on the firewall for small networks) and External Portal servers (such as iMaster NCE / Agile Controller for large campuses)."),
        ("Non-Interactive Device Authentication Methods", "Which authentication methods are suitable for IoT endpoints, network printers, and IP security cameras?",
         ["MAC Address Authentication (MAB)",
          "Pre-Shared Key (PSK) or Static IP binding with port security",
          "Certificate-Based 802.1X Authentication (using device certificates)",
          "Interactive Web Captive Portal where the camera types its password"], "ABC",
         "Non-interactive devices use MAC Authentication Bypass (MAB), static IP/MAC bindings, or machine certificate-based 802.1X. They cannot navigate interactive web portals."),
        ("Troubleshooting AAA Commands", "Which CLI commands assist administrators in troubleshooting AAA, RADIUS, and user management issues on Huawei firewalls?",
         ["`display user-manage online-user` (view active user mappings)",
          "`display radius-server configuration` (verify RADIUS template settings)",
          "`display local-user` (check local user account status)",
          "`debugging radius packet` (inspect live RADIUS protocol message exchanges)",
          "`format sdcard:` (delete memory storage cards)"], "ABCD",
         "AAA diagnostics use `display user-manage online-user`, `display radius-server`, `display local-user`, and `debugging radius packet`. Formatting storage is destructive.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 8,
            "chapter_title": "Firewall User Management Technologies",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 8 TRUE/FALSE (28 questions)
    tf_data = [
        ("Authentication Definition", "Authentication in the AAA framework verifies the identity claimed by an entity, answering the question 'Who are you?'.", "A",
         "True. Authentication establishes identity verification through credentials like passwords, tokens, or digital certificates."),
        ("Authorization Definition", "Authorization is responsible for calculating network bandwidth usage and billing information for user accounts.", "B",
         "False. Calculating usage and billing is the role of Accounting. Authorization determines which services and permissions the user is permitted to access."),
        ("Local User Storage Location", "Local user accounts are stored directly within the internal database of the Huawei firewall.", "A",
         "True. Local users reside on the local storage of the firewall, requiring no external authentication server."),
        ("RADIUS Transport UDP", "The standard RADIUS protocol operates over TCP transport using destination port 49.", "B",
         "False. RADIUS operates over UDP (ports 1812 and 1813). HWTACACS / TACACS+ operates over TCP port 49."),
        ("RADIUS Password Only Encryption", "Standard RADIUS encrypts the entire packet including usernames and accounting attributes.", "B",
         "False. RADIUS encrypts only the User-Password attribute using MD5; usernames and other attributes are transmitted in cleartext."),
        ("RADIUS Bundled Auth and Authz", "RADIUS bundles Authentication and Authorization together in the single `Access-Accept` response packet.", "A",
         "True. RADIUS delivers authorization attributes (VLAN, user group, ACL) alongside authentication acceptance in the `Access-Accept` message."),
        ("HWTACACS Transport TCP 49", "HWTACACS utilizes TCP port 49 to provide reliable communication between the client NAS and the server.", "A",
         "True. HWTACACS runs over reliable connection-oriented TCP transport on port 49."),
        ("HWTACACS Full Body Encryption", "HWTACACS encrypts the entire body of the packet following the 12-byte header, protecting usernames and commands from network sniffing.", "A",
         "True. HWTACACS encrypts all payload data, ensuring usernames, command strings, and authorization attributes are confidential."),
        ("HWTACACS AAA Separation", "HWTACACS strictly separates Authentication, Authorization, and Accounting into distinct, independent exchanges.", "A",
         "True. HWTACACS separates all three AAA phases, allowing independent server assignments and per-command authorization."),
        ("LDAP Standard Ports", "Standard unencrypted LDAP uses TCP port 389, while encrypted LDAPS uses TCP port 636.", "A",
         "True. LDAP operates over TCP port 389, and LDAPS (over TLS/SSL) uses TCP port 636."),
        ("Active Directory Integration via LDAP", "Huawei firewalls can query Microsoft Active Directory domain controllers using the LDAP protocol to authenticate domain users.", "A",
         "True. Huawei firewalls use LDAP/LDAPS queries to validate domain user credentials and synchronize Active Directory user groups."),
        ("User-Based Policy IP Independence", "User-based security policies allow access control rules to follow the user dynamically, regardless of changes to their assigned DHCP IP address.", "A",
         "True. User-aware policies bind permissions to identity rather than volatile IP addresses, ensuring consistent access across mobile and roaming devices."),
        ("Portal Captive Redirection", "Portal authentication intercepts unauthenticated HTTP requests and redirects users to a captive web login page.", "A",
         "True. Captive portal authentication intercepts initial HTTP/HTTPS traffic and redirects the browser to a login portal for credential verification."),
        ("AD SSO Event ID 4624", "Active Directory SSO can monitor Event ID 4624 (Successful Logon) on domain controllers to transparently learn user-to-IP mappings.", "A",
         "True. Event ID 4624 records successful domain logons with username and workstation IP, which AD SSO monitors to create transparent user mappings."),
        ("RADIUS SSO Accounting Snooping", "RADIUS SSO learns user IP mappings by snooping RADIUS Accounting-Request packets exchanged between network access devices and the RADIUS server.", "A",
         "True. RADIUS SSO monitors accounting start/update packets to extract assigned IPs and usernames without requiring separate user authentication prompts."),
        ("Local User Password Plaintext Best Practice", "Configuring passwords using `local-user password plain` is recommended as best practice for enterprise production networks.", "B",
         "False. Using `plain` stores passwords in readable cleartext in configuration files. Best practice mandates using `cipher` or irreversible cryptographic hashes."),
        ("User Group Hierarchical Inheritance", "On Huawei NGFWs, child user groups inherit security policies and permissions assigned to their parent user groups.", "A",
         "True. Hierarchical group modeling allows child groups to inherit parent policies, simplifying multi-level departmental access management."),
        ("Guest Account Auto-Expiration", "Guest user accounts can be configured to automatically expire and deactivate after a specific duration, such as 8 hours.", "A",
         "True. Automatic expiration ensures temporary visitor credentials do not remain valid indefinitely, closing security risks."),
        ("Policy Logical AND for IP and User", "If a security policy rule specifies both a source IP address range and a user group, matching traffic must satisfy BOTH criteria simultaneously.", "A",
         "True. Policy conditions are evaluated using logical AND; matching packets must originate from the specified IP range AND belong to the specified user group."),
        ("Display Online User Command", "The command `display user-manage online-user` displays active online users and their mapped IP addresses on a Huawei firewall.", "A",
         "True. `display user-manage online-user` is the standard VRP command to view currently authenticated online users and their session bindings."),
        ("Authentication Domain Definition", "An Authentication Domain in Huawei VRP links authentication schemes, authorization schemes, and server templates together.", "A",
         "True. Authentication Domains encapsulate complete AAA service pipelines for specific user communities."),
        ("Default Domain Usage", "When a user logs in without typing a domain suffix (e.g., logging in simply as 'alice'), the firewall processes the login using the default domain.", "A",
         "True. Logins lacking an explicit `@domain` suffix are automatically routed to the designated default authentication domain."),
        ("Interim Accounting Purpose", "Interim accounting updates are sent periodically by the NAS to verify ongoing session activity and report cumulative volume usage.", "A",
         "True. Interim accounting updates prevent orphaned sessions and provide periodic billing and bandwidth telemetry."),
        ("MFA Two-Factor Requirement", "Multi-Factor Authentication (MFA) requires presenting two or more credentials belonging to completely independent authentication factor categories.", "A",
         "True. True MFA mandates combining distinct categories (knowledge, possession, inherence), such as a password plus an SMS OTP or hardware token."),
        ("Online User Idle Timeout Aging", "When an authenticated user remains idle with no active traffic for longer than the idle timeout, their entry is automatically removed from the online user table.", "A",
         "True. Idle timers flush inactive mappings to free connection resources and force re-authentication upon return."),
        ("HWTACACS Per-Command Authorization Capability", "HWTACACS allows an enterprise to authorize or deny individual administrative CLI commands entered by an operator in real time.", "A",
         "True. Per-command authorization intercepts each typed command and queries the HWTACACS server before execution."),
        ("Account Lockout Brute Force Defense", "Enabling account lockout policies on local user accounts protects the firewall against automated password brute-force guessing attacks.", "A",
         "True. Account lockout temporarily disables accounts after consecutive failed attempts, thwarting automated password guessing."),
        ("IoT Device Web Portal Authentication", "Headless IoT endpoints such as network printers and CCTV cameras can easily navigate complex web portal captive login pages.", "B",
         "False. Headless devices lack web browsers and cannot complete portal logins; they require MAC Authentication Bypass (MAB) or certificate-based 802.1X.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 8,
            "chapter_title": "Firewall User Management Technologies",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch8_questions()
    print(f"Chapter 8 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
