# scripts/generate_ch4.py
"""
Generates Chapter 4 data: 40 Single Choice, 30 Multiple Choice, 30 True/False.
Chapter 4: Firewall Security Policies
"""
import json

def get_ch4_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 4 SINGLE CHOICE (40 questions)
    s_data = [
        ("Security Zone - Local Priority", "In Huawei USG series firewalls, what is the default fixed security priority of the Local security zone?",
         ["5", "50", "85", "100"], "D",
         "The Local zone represents the firewall device itself and has the highest fixed priority value of 100. All management traffic, routing protocol packets, and VPN tunnels terminate in the Local zone."),
        ("Security Zone - Trust Priority", "What is the default security priority assigned to the predefined Trust zone on a Huawei firewall?",
         ["5", "50", "85", "100"], "C",
         "The predefined Trust zone has a priority of 85, representing the internal secure enterprise network."),
        ("Security Zone - DMZ Priority", "What is the default security priority of the Demilitarized Zone (DMZ) in Huawei firewalls?",
         ["5", "50", "85", "100"], "B",
         "The DMZ zone has a fixed default priority of 50. It is designed to host public-facing enterprise servers (e.g., Web, Mail, FTP) that require controlled access from both internal and external networks."),
        ("Security Zone - Untrust Priority", "What is the default security priority of the Untrust zone in Huawei firewalls?",
         ["5", "50", "85", "100"], "A",
         "The Untrust zone has the lowest default priority of 5, representing untrusted external networks such as the public Internet."),
        ("Traffic Direction - Outbound", "When traffic flows from an internal network (Trust zone, priority 85) to the Internet (Untrust zone, priority 5), what is the direction of this traffic?",
         ["Inbound", "Outbound", "Bidirectional", "Loopback"], "B",
         "On Huawei firewalls, traffic traveling from a zone with a higher security priority to a zone with a lower security priority is defined as Outbound traffic."),
        ("Traffic Direction - Inbound", "Traffic originating from the Internet (Untrust, priority 5) destined for an internal web server in the DMZ (priority 50) is classified as:",
         ["Outbound traffic", "Inbound traffic", "Intra-zone traffic", "Pass-through traffic"], "B",
         "Traffic traveling from a zone with a lower security priority to a zone with a higher security priority is defined as Inbound traffic."),
        ("Intra-zone Default Action", "By default, what is the default forwarding behavior for traffic between two interfaces assigned to the SAME security zone (intra-zone traffic)?",
         ["Permanently blocked and discarded",
          "Permitted without requiring inter-zone security policies",
          "Subject to mandatory deep packet antivirus scanning only",
          "Automatically mirrored to all physical switch ports"], "B",
         "On Huawei firewalls, intra-zone traffic (traffic between interfaces within the identical security zone) is permitted by default, although administrators can configure intra-zone policies to restrict it if necessary."),
        ("Inter-zone Default Action", "What is the default security behavior for inter-zone traffic (traffic between different security zones) when no matching security policy rule is found?",
         ["It matches the predefined default policy and is denied (dropped)",
          "It is automatically forwarded using standard IP routing",
          "It is forwarded only after stripping all TCP options",
          "It triggers a broadcast ARP request across all interfaces"], "A",
         "Huawei firewalls enforce an implicit 'deny-all' model for inter-zone traffic. If packets between different zones do not match any explicit permit policy, they match the predefined bottom 'default' policy and are silently discarded."),
        ("Security Policy Matching Order", "In what order does a Huawei firewall evaluate security policy rules when a new connection arrives?",
         ["Random order based on hash values",
          "Sequentially from top to bottom; the first rule that matches terminates policy evaluation",
          "Rules are evaluated from bottom to top, prioritizing the default rule",
          "Simultaneously across all rules, executing the rule with the highest ID number"], "B",
         "Security policy rules are evaluated sequentially from top to bottom. The firewall checks matching criteria one by one, and upon encountering the first matching rule, it executes the specified action (permit/deny) and ceases further policy evaluation."),
        ("Default Policy Customization", "Which of the following operations is permitted on the predefined 'default' security policy rule in a Huawei firewall?",
         ["Deleting the rule completely",
          "Changing the default action from 'deny' to 'permit' (though not recommended for security)",
          "Moving the default rule to the top of the policy list",
          "Renaming the default rule to 'Corporate_Main_Rule'"], "B",
         "The predefined 'default' rule cannot be deleted, moved, or renamed. However, its default action can be toggled between 'deny' and 'permit' (default is deny)."),
        ("Session Table 5-Tuple", "Which five parameters constitute the fundamental 5-tuple used to identify a network flow in a firewall session table?",
         ["Source IP, Destination IP, Source Port, Destination Port, Transport Protocol",
          "Source MAC, Destination MAC, VLAN ID, TTL, Window Size",
          "Source IP, Destination IP, Security Zone, Application ID, User ID",
          "Egress Interface, Ingress Interface, Next Hop, DSCP, Packet Length"], "A",
         "The fundamental 5-tuple of a session entry comprises: Source IP Address, Destination IP Address, Transport Layer Protocol, Source Port, and Destination Port."),
        ("Fast Forwarding Mechanism", "How does a stateful inspection firewall process subsequent packets belonging to an already established permitted connection?",
         ["It re-evaluates all security policy rules from top to bottom for every single packet",
          "It matches the session table directly, bypassing the security policy engine for fast-path forwarding",
          "It re-authenticates the user credentials against the RADIUS server",
          "It broadcasts the packets to all security zones simultaneously"], "B",
         "Only the initial packet of a connection undergoes complete security policy matching. Once permitted, a session table entry is created. All subsequent forward and return packets match the session table directly, enabling line-rate fast-path forwarding."),
        ("Session Table Aging Timer", "Why do firewall session table entries have associated aging timers?",
         ["To periodically refresh the firewall's hardware MAC address",
          "To automatically purge inactive or terminated connections, freeing up system memory and resources",
          "To force users to re-enter their passwords every 60 seconds",
          "To synchronize the firewall clock with an external NTP server"], "B",
         "If sessions remained in memory indefinitely, stale connections would exhaust the session table capacity, preventing new connections. Aging timers ensure that idle, closed, or aborted connections are reclaimed."),
        ("TCP Established Aging Timer", "Compared to the aging timer for a TCP SYN packet, the aging timer for a TCP connection in the ESTABLISHED state is typically:",
         ["Much shorter (e.g., 5 seconds)",
          "Much longer (e.g., several hours / 10,000 seconds by default)",
          "Exactly 0 seconds (disabled)",
          "Identical to the ICMP aging timer"], "B",
         "Initial handshake states (like TCP SYN or FIN) have short timers (e.g., 20 seconds) to prevent SYN flood resource exhaustion. Once ESTABLISHED, long timers (default ~10,000s or 20 minutes on Huawei firewalls) allow idle business sessions to persist."),
        ("ASPF Protocol Purpose", "What is the primary technical problem solved by Application Specific Packet Filter (ASPF) on a firewall?",
         ["Encrypting HTTP web pages using 2048-bit RSA keys",
          "Dynamically opening pinholes for multi-channel protocols (like FTP) that negotiate dynamic data ports during control sessions",
          "Converting IPv4 packets into IPv6 format without translation",
          "Increasing the physical link speed of Ethernet interfaces"], "B",
         "Multi-channel protocols (e.g., FTP active mode, SIP, H.323) negotiate secondary data connections using unpredictable dynamic ports. ASPF inspects control channel payloads and dynamically creates temporary Server-Map entries to allow the secondary channels without broadly opening static firewall ports."),
        ("Server-Map Table Function", "How does a Server-Map table differ from a standard Session table on a Huawei firewall?",
         ["A Server-Map table permanently stores historical network packets on the hard disk",
          "A Server-Map table dynamically generates temporary pass-through pinholes for anticipated secondary channels or static NAT server mappings",
          "A Server-Map table is used exclusively to record physical hardware serial numbers",
          "A Server-Map table replaces the need for an IP routing table"], "B",
         "A Server-Map table is a specialized forwarding table that stores pre-allocated pinholes (e.g., dynamic pinholes generated by ASPF for FTP data channels, or static pinholes generated by NAT Server). When matching packets arrive, a standard session entry is formed, and the dynamic server-map entry expires."),
        ("First Generation Firewall", "What is the defining operational characteristic of a first-generation Packet Filtering Firewall?",
         ["Deep packet inspection of application layer payloads and user identities",
          "Stateless inspection of Layer 3 and Layer 4 headers against access control lists without tracking connection state",
          "Terminating TCP connections completely and acting as an application gateway proxy",
          "Using artificial intelligence to detect behavioral zero-day exploits"], "B",
         "First-generation packet filters operate statelessly. They examine individual packets in isolation against rules based on 5-tuple headers, unable to correlate packets to ongoing connections or detect dynamic port negotiations."),
        ("Second Generation Firewall", "What was a major operational drawback of second-generation Application Proxy Firewalls?",
         ["They were incapable of inspecting application layer headers",
          "They suffered from high latency, significant compute resource consumption, and poor scalability for new protocols",
          "They allowed all external Internet users unrestricted access to internal subnets",
          "They could only be deployed on token ring network topologies"], "B",
         "Application proxies terminate client connections and initiate new connections to servers, performing deep Layer 7 inspection. While secure, this introduced severe latency, high CPU overhead, and required dedicated proxy code for every supported application."),
        ("Next-Generation Firewall (NGFW)", "What is a core capability that differentiates a Next-Generation Firewall (NGFW) from a traditional stateful firewall?",
         ["The ability to forward packets based solely on destination MAC addresses",
          "Integrated application identification (independent of port), user awareness, and unified content security inspection (IPS/AV)",
          "Eliminating the need for IP routing and security zones",
          "Operating purely at the physical layer of the OSI model"], "B",
         "An NGFW integrates Layer 7 application awareness (identifying applications regardless of port/protocol), user identity integration, and unified threat inspection (IPS, Antivirus, URL filtering) in a single-pass processing architecture."),
        ("Security Zone Interface Mapping", "In Huawei firewall configuration, what is the relationship between physical/logical interfaces and security zones?",
         ["A single interface can belong to multiple security zones simultaneously",
          "An interface can belong to only one security zone at any given time",
          "An interface must always belong to all four default security zones",
          "Security zones can only be applied to wireless loopback interfaces"], "B",
         "In Huawei USG firewalls, each interface (physical interface, VLANIF, sub-interface, or tunnel interface) can be assigned to only ONE security zone at a time."),
        ("Security Policy Matching Criteria", "Which of the following is NOT a standard matching criterion supported in a Huawei NGFW security policy rule?",
         ["Source and Destination Security Zones",
          "Source and Destination IP Addresses / Subnets / Address Sets",
          "Physical room temperature of the client workstation",
          "Application identification and Time Range (Schedule)"], "C",
         "Firewall security policies match network parameters: source/destination zones, IP addresses, services/ports, user identities, application IDs, and schedules. Physical environmental conditions of endpoints are not network policy criteria."),
        ("Security Policy Action - Deny", "When a security policy rule's action is configured as 'Deny', what does the firewall do with matching traffic?",
         ["It forwards the packet to the DMZ zone for manual review",
          "It discards the packet (and optionally returns a TCP RST or ICMP unreachable if configured)",
          "It converts the packet into an unencrypted HTTP request",
          "It permanently disables the ingress physical switch port"], "B",
         "When a rule action is 'Deny', matching packets are discarded by the firewall. Depending on configuration, the firewall may silently drop the packet or generate an active reset (TCP RST) or ICMP unreachable notification."),
        ("Custom Security Zone Priority Range", "What is the valid priority range for creating custom user-defined security zones on a Huawei firewall?",
         ["0 to 255", "1 to 100 (excluding priorities already assigned to active zones)", "100 to 1000", "Only priorities 10, 20, 30, and 40"], "B",
         "Custom security zones can be configured with priority values between 1 and 100. By default, priorities cannot overlap with existing zones (e.g., default priorities 5, 50, 85, 100 are already reserved)."),
        ("Security Policy Rule Optimization", "Why is it best practice to place specific, high-frequency rules near the top of the security policy list?",
         ["To prevent the firewall's flash storage from fragmenting",
          "Because top-down matching stops upon the first match; placing high-volume rules early minimizes CPU processing and matching latency",
          "Because lower rules are permanently ignored after 5:00 PM",
          "To automatically encrypt all low-priority traffic"], "B",
         "Since firewalls evaluate rules sequentially, placing rules for frequent traffic near the top reduces the number of rule comparisons the CPU must perform before finding a match, optimizing forwarding throughput."),
        ("Session Table Inspection Command", "Which Huawei VRP CLI command displays the active session table on a USG series firewall?",
         ["display current-configuration", "display firewall session table", "display ip routing-table", "display mac-address"], "B",
         "The command `display firewall session table` displays active connection states, 5-tuples, zones, and timers currently tracked by the firewall."),
        ("Session Table 'verbose' Keyword", "What additional information is displayed when executing `display firewall session table verbose` on a Huawei firewall?",
         ["The physical MAC address of the firewall manufacturer",
          "Detailed session attributes including ingress/egress interfaces, zone IDs, application IDs, packet/byte counters, and NAT translation details",
          "The cleartext passwords of all domain administrators",
          "The internal CPU register assembly code"], "B",
         "The `verbose` keyword expands the session display to show detailed flow parameters: application identification, NAT translations, input/output interface, TTL/aging timers, zone mappings, and packet/byte counters."),
        ("Stateful Inspection Security Benefit", "Why is stateful inspection superior to simple packet filtering in defending against external network scans?",
         ["Stateful inspection automatically doubles the link bandwidth",
          "It permits return traffic only if it matches an existing session initiated from the inside, blocking unsolicited external packets without broad inbound port openings",
          "It translates all external IP addresses into private addresses",
          "It replaces all external routers with optical splitters"], "B",
         "Because stateful firewalls track connection states, return traffic for an internally initiated connection is automatically permitted via the session table. Inbound unsolicited connection attempts from the outside are dropped unless explicitly permitted by policy."),
        ("FTP Control Session Port", "When an internal client accesses an external FTP server, the initial control session is established to which destination port?",
         ["TCP port 20", "TCP port 21", "UDP port 69", "TCP port 22"], "B",
         "FTP control commands (USER, PASS, PORT, PASV) are transmitted over TCP port 21. Data connections use port 20 (Active mode) or negotiated dynamic ports (Passive mode)."),
        ("Firewall Policy Schedule", "What is the function of associating a 'Time Range' (schedule) with a firewall security policy rule?",
         ["To automatically change the firewall's system clock",
          "To activate the security policy rule only during specified dates, days of the week, or hours of the day",
          "To measure the round-trip latency of user packets",
          "To limit user connection durations to exactly 15 seconds"], "B",
         "A Time Range schedule allows administrators to restrict the validity of a security rule to specific working hours, weekdays, or promotional periods, automatically deactivating the rule outside the designated window."),
        ("Address Object Set", "What is the administrative benefit of defining an 'Address Set' object and referencing it within security policies?",
         ["It allows multiple IP addresses or subnets to be managed collectively, simplifying policy rules and ongoing maintenance",
          "It eliminates the need for subnet masks across all enterprise servers",
          "It forces all referenced IP addresses to use identical MAC addresses",
          "It converts private IP addresses directly into public DNS domain names"], "A",
         "Address Sets group multiple IP addresses, ranges, or subnets into a single logical object. When IP addresses change, updating the object automatically updates all associated security policies without modifying individual rules."),
        ("Service Object Group", "What information is encapsulated within a custom 'Service Object' on a Huawei firewall?",
         ["The physical location and room number of a server",
          "Transport protocol (TCP/UDP/ICMP) and source/destination port ranges",
          "The monthly billing cost of an enterprise application",
          "The firmware revision of connected switches"], "B",
         "A Service Object defines network protocols and port parameters (e.g., protocol TCP, destination port 8080-8088), allowing custom enterprise applications to be referenced cleanly in security policies."),
        ("Application Identification (SA)", "How does Huawei NGFW Service Awareness (SA) identify network applications regardless of the port number used?",
         ["By reading the destination port number only",
          "Through deep packet inspection (DPI) analyzing application-layer packet payload signatures and behavioral features",
          "By contacting the software developer over the telephone",
          "By randomly assigning application names based on IP addresses"], "B",
         "Huawei NGFW employs Deep Packet Inspection (DPI) and behavioral heuristics to inspect application-layer payloads and protocol handshakes, accurately identifying applications (e.g., BitTorrent, WeChat, Facebook) even when they run over non-standard ports or port 80/443."),
        ("Security Policy Counter Feature", "Why would an administrator enable the 'traffic statistics' (counter) feature on a security policy rule?",
         ["To calculate employee salaries based on bandwidth usage",
          "To verify if the policy rule is actually matching traffic and monitor the volume of permitted/denied packets and bytes",
          "To permanently store all transmitted files in the cloud",
          "To disable the rule automatically when traffic reaches 100 megabytes"], "B",
         "Policy counters track the number of matching packets and bytes. This is crucial for verifying policy effectiveness, troubleshooting rule ordering issues, and identifying unused legacy rules for decommissioning."),
        ("Management Access Control", "How does a firewall regulate administrative access (HTTPS, SSH, Ping) to its own physical interfaces?",
         ["Management traffic to the firewall interface terminates in the Local zone and is controlled via interface access management or Local zone security policies",
          "Management access is permitted automatically on all interfaces without restriction",
          "Management traffic cannot be processed by firewalls",
          "By disabling all IP routing on management ports"], "A",
         "Interface management services (Ping, SSH, HTTPS, NETCONF) are governed by interface access management settings and security policies between the originating zone (e.g., Trust) and the Local zone (priority 100)."),
        ("Intra-Zone Traffic Security Policy", "If an administrator desires to block communication between two departments whose interfaces reside in the same Trust zone, what must be done?",
         ["The firewall hardware must be replaced with two physical firewalls",
          "An intra-zone security policy with the action 'Deny' must be configured, or intra-zone inter-interface filtering must be enabled",
          "Intra-zone traffic can never be blocked under any circumstances",
          "All departmental PCs must be powered off"], "B",
         "Although intra-zone traffic is permitted by default, administrators can enforce security by creating explicit intra-zone security policies (Source Zone: Trust, Destination Zone: Trust) with 'Deny' actions or enabling intra-zone packet filtering."),
        ("Stateful Firewall and Asymmetric Routing", "What issue arises when asymmetric routing causes outbound packets to traverse Firewall A but return packets to traverse Firewall B?",
         ["Firewall B drops the return packets because it lacks an existing session table entry for the connection",
          "Firewall A immediately powers off its cooling fans",
          "The client's network interface card is permanently damaged",
          "The destination server sends duplicate SYN packets indefinitely"], "A",
         "In asymmetric routing, Firewall B receives return packets without having seen the initial SYN packet that creates the session. Because stateful detection is enabled, Firewall B drops the unsolicited return packet as an invalid state transition unless session synchronization or stateful inspection exceptions are configured."),
        ("Session Table Limit", "What happens when a firewall's session table reaches its maximum hardware capacity during a severe connection flood?",
         ["The firewall begins formatting its hard drives",
          "New connection requests cannot be established and are discarded, resulting in denial of service for new users",
          "The firewall converts all TCP traffic into unencrypted UDP broadcasts",
          "Existing established sessions are immediately deleted"], "B",
         "The session table has a finite maximum capacity dictated by available memory. When full, the firewall cannot allocate new session entries, causing all subsequent new connection requests to be dropped."),
        ("Disabling Stateful Inspection", "If stateful inspection is globally disabled on a firewall interface, how does the firewall behave?",
         ["It functions like a stateless packet filter, requiring explicit policy rules for both forward and return traffic flows",
          "It permanently blocks 100% of all IP traffic",
          "It automatically encrypts all traffic using IPsec",
          "It forwards all packets exclusively to the DMZ zone"], "A",
         "When stateful inspection is disabled, the firewall stops creating session tables. It evaluates every single packet in isolation like a traditional stateless packet filter, requiring administrators to write explicit rules for both forward request and return response traffic."),
        ("Security Policy Profile Association", "In Huawei NGFWs, which security features are attached to a permitted security policy rule as 'Security Profiles'?",
         ["Antivirus, IPS, URL Filtering, File Filtering, Content Filtering, and Mail Filtering",
          "BGP, OSPF, RIP, and IS-IS routing tables",
          "DHCP Server address pool ranges and lease timers",
          "Interface physical duplex and speed settings"], "A",
         "Security Profiles (IPS, Antivirus, URL Filtering, File/Content Filtering, Application Control) are bound to 'Permit' security policy rules to perform deep Layer 7 content inspection on traffic that passes basic 5-tuple filtering."),
        ("Policy Logging Best Practice", "Why is it recommended to enable session logging only on specific critical policies rather than logging every single permitted packet in high-throughput environments?",
         ["Because logging is prohibited by international networking RFCs",
          "To avoid exhausting firewall CPU, disk I/O, and log server storage caused by billions of routine session logs",
          "Because session logs contain unencrypted passwords",
          "To prevent the firewall from generating IP routing updates"], "B",
         "Generating logs for every permitted connection in a multi-gigabit data center creates massive CPU overhead and storage exhaustion. Best practice is to log denied traffic, threat alerts, and critical business policies.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 4,
            "chapter_title": "Firewall Security Policies",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 4 MULTIPLE CHOICE (30 questions)
    m_data = [
        ("Predefined Security Zones", "Which of the following are predefined default security zones available out-of-the-box on Huawei USG firewalls?",
         ["Local Zone (Priority 100)", "Trust Zone (Priority 85)", "DMZ Zone (Priority 50)", "Untrust Zone (Priority 5)", "Public Zone (Priority 200)"], "ABCD",
         "Huawei firewalls feature four factory-predefined security zones: Local (100), Trust (85), DMZ (50), and Untrust (5). There is no default 'Public' zone with priority 200."),
        ("Security Policy Matching Conditions", "Which of the following parameters can be configured as matching conditions in a Huawei NGFW security policy rule?",
         ["Source and Destination Security Zones",
          "Source and Destination IP Addresses or Address Groups",
          "Services (Protocols and Port numbers)",
          "Users or User Groups",
          "Applications identified by DPI",
          "Time Range / Schedule"], "ABCDEF",
         "Huawei NGFW security policies support comprehensive matching dimensions: Zones, IP addresses, Services/Ports, Users/Groups, Applications (L7), and Time schedules."),
        ("Firewall Evolution Generations", "Which of the following are recognized generations in the historical development of firewall technology?",
         ["First Generation: Packet Filtering Firewall",
          "Second Generation: Application Proxy Firewall",
          "Third Generation: Stateful Inspection Firewall",
          "Modern Generation: Next-Generation Firewall (NGFW)",
          "Wireless Radio Analog Firewall"], "ABCD",
         "Firewall technology evolved across: 1. Packet Filtering; 2. Application Proxy; 3. Stateful Inspection; and 4. Next-Generation Firewalls (NGFW)."),
        ("Session Table Attributes", "Which of the following pieces of information are recorded within an active Huawei firewall session entry?",
         ["5-tuple (Source/Dest IP, Source/Dest Port, Protocol)",
          "Current connection state (e.g., ESTABLISHED)",
          "Source and Destination security zone IDs",
          "Ingress and Egress interface names",
          "Remaining aging time before expiration"], "ABCDE",
         "A session table entry tracks the 5-tuple, connection state, zone IDs, ingress/egress interfaces, application identity, NAT translation parameters, and aging timers."),
        ("ASPF Supported Protocols", "Which of the following multi-channel or dynamic port protocols are commonly inspected by firewall ASPF engines?",
         ["File Transfer Protocol (FTP)",
          "Session Initiation Protocol (SIP)",
          "H.323 (VoIP protocol suite)",
          "Real-Time Streaming Protocol (RTSP)",
          "Static Unencrypted Telnet"], "ABCD",
         "ASPF specifically inspects multi-channel protocols that negotiate secondary data ports inside control payloads: FTP, SIP, H.323, RTSP, and QQ. Static single-channel protocols like Telnet do not require ASPF."),
        ("NGFW Core Capabilities", "Which of the following are core characteristics that define a Next-Generation Firewall (NGFW)?",
         ["Application awareness independent of port numbers",
          "Integration of User identity into policy enforcement",
          "Unified threat prevention engine (IPS, AV, URL Filtering)",
          "High performance single-pass parallel inspection architecture",
          "Requirement to deploy external physical hubs on all ports"], "ABCD",
         "NGFWs feature application identification, user awareness, unified deep content inspection, and high-performance single-pass architecture."),
        ("Security Policy Actions", "What are the two primary forwarding actions that can be configured on a firewall security policy rule?",
         ["Permit (allow traffic to pass and inspect)",
          "Deny (discard and block matching traffic)",
          "Loopback (bounce packet between interfaces)",
          "Duplicate (send two copies to Internet)"], "AB",
         "The fundamental actions of a firewall security policy rule are 'Permit' (forward and apply security profiles) and 'Deny' (drop traffic)."),
        ("Default Security Policy Characteristics", "Which of the following statements regarding the predefined 'default' security policy on a Huawei firewall are true?",
         ["It is permanently located at the very bottom of the rule list",
          "Its default action is set to 'Deny'",
          "It cannot be deleted or moved by administrators",
          "Its action can be modified from Deny to Permit if desired",
          "It matches only UDP traffic destined to port 53"], "ABCD",
         "The default rule is fixed at the bottom, defaults to Deny, cannot be deleted or reordered, and matches all remaining traffic regardless of protocol."),
        ("Traffic Direction Rules", "Based on Huawei firewall zone priority rules, which of the following traffic flows are correctly classified as 'Outbound'?",
         ["Trust (85) -> Untrust (5)",
          "Trust (85) -> DMZ (50)",
          "DMZ (50) -> Untrust (5)",
          "Local (100) -> Trust (85)",
          "Untrust (5) -> DMZ (50)"], "ABCD",
         "Outbound traffic flows from higher priority to lower priority: 85->5, 85->50, 50->5, and 100->85 are all Outbound. Untrust (5) to DMZ (50) is Inbound."),
        ("Traffic Direction Inbound Examples", "Which of the following traffic paths represent 'Inbound' traffic flows on a Huawei firewall?",
         ["Untrust (5) -> DMZ (50)",
          "Untrust (5) -> Trust (85)",
          "DMZ (50) -> Trust (85)",
          "Untrust (5) -> Local (100)",
          "Local (100) -> Untrust (5)"], "ABCD",
         "Inbound traffic flows from lower priority to higher priority: 5->50, 5->85, 50->85, and 5->100 are all Inbound. Local (100) to Untrust (5) is Outbound."),
        ("Security Profiles on NGFW", "Which of the following security inspection profiles can be associated with a 'Permit' rule in a Huawei NGFW security policy?",
         ["Intrusion Prevention System (IPS) Profile",
          "Antivirus (AV) Profile",
          "URL Filtering Profile",
          "File Filtering Profile",
          "Data Loss Prevention (DLP) / Content Filtering Profile"], "ABCDE",
         "Huawei NGFW allows associating IPS, Antivirus, URL Filtering, File Filtering, Content/Data Filtering, and Mail Filtering profiles with permitted policy rules for deep inspection."),
        ("Session Table Aging Time Reasons", "Why do different protocols have distinct session aging timers on firewalls?",
         ["TCP handshake states (SYN_SENT) have short timers to prevent SYN flood resource starvation",
          "Established TCP connections have long timers because business transactions may have idle periods between requests",
          "UDP is connectionless, so moderate timers (e.g. 120s) ensure return packets pass without leaving permanent stale entries",
          "ICMP sessions are short-lived query/reply transactions requiring only brief aging times (e.g. 20s)"], "ABCD",
         "Timers reflect protocol semantics: TCP connection states use short timers during setup/teardown and long timers when established; connectionless UDP and ICMP use fixed expiration timers."),
        ("Server-Map Entry Generation Sources", "On a Huawei firewall, Server-Map entries can be dynamically or statically generated by which of the following features?",
         ["ASPF inspection of multi-channel protocols (e.g. FTP active mode)",
          "NAT Server (static destination IP/port mapping)",
          "NAT No-PAT (source address translation without port translation)",
          "Physical link speed auto-negotiation on Ethernet ports"], "ABC",
         "Server-Map entries are generated by ASPF (dynamic secondary channels), NAT Server (static server mapping), and NAT No-PAT (mapping public IP to private IP). Physical auto-negotiation operates at Layer 1."),
        ("Stateful Firewall Advantages", "Which of the following are major advantages of stateful inspection firewalls compared to stateless packet filters?",
         ["Automatic tracking of connection state allows return traffic without opening broad static inbound ports",
          "Verification of sequence numbers and TCP flags protects against spoofed packets and out-of-sequence attacks",
          "Significantly higher throughput for established flows via session table fast-forwarding",
          "Complete elimination of the need for routing tables"], "ABC",
         "Stateful inspection provides robust security (inspects state, sequence numbers, return traffic) and high performance (session fast path). Routing tables are still required for packet forwarding."),
        ("Security Policy Optimization Strategies", "Which of the following practices are recommended when configuring firewall security policies?",
         ["Place specific, high-frequency rules near the top of the policy list",
          "Group related IP addresses and ports into Address Sets and Service Objects for readability and maintainability",
          "Avoid configuring overly broad rules such as 'Permit Any Any Any'",
          "Periodically review policy hit counts to identify and decommission obsolete rules",
          "Set the default policy action to 'Permit' on perimeter firewalls"], "ABCD",
         "Best practices include top placement for frequent rules, object reuse, least privilege (avoiding permit any), and auditing hit counters. Setting the default policy to Permit breaks perimeter security."),
        ("Firewall Local Zone Functions", "Which of the following traffic types originate from or terminate in the Local security zone?",
         ["SSH or HTTPS administrative management sessions to the firewall itself",
          "OSPF or BGP dynamic routing protocol hello and update packets exchanged with neighbor routers",
          "IPsec VPN or SSL VPN tunnels terminated directly on the firewall",
          "SNMP queries polling firewall operational metrics",
          "Direct client browsing to external Internet web servers traversing through the firewall"], "ABCD",
         "The Local zone covers traffic terminating on or originating from the firewall: management (SSH/HTTPS), routing protocols (OSPF/BGP), VPN endpoints, and SNMP. Transit traffic traversing between interfaces does NOT enter the Local zone."),
        ("Time Range Types", "In Huawei firewall configuration, what types of Time Ranges can be configured for security policy scheduling?",
         ["Periodic Time Range (repeating on specific days of the week, e.g. Monday-Friday 08:00-18:00)",
          "Absolute Time Range (spanning a specific calendar date window, e.g. 2026-01-01 to 2026-01-15)",
          "Infinite Time Range that ignores the system clock completely",
          "Quantum Time Range that shifts backwards in time"], "AB",
         "Huawei VRP supports Periodic Time Ranges (recurring weekly schedules) and Absolute Time Ranges (specific calendar date/time intervals)."),
        ("Address Object Types", "Which of the following address representations can be configured within an Address Object on a Huawei firewall?",
         ["A single host IPv4 address (e.g., 192.168.1.10/32)",
          "An IP address range (e.g., 192.168.1.50 to 192.168.1.100)",
          "A subnet prefix with subnet mask (e.g., 10.1.0.0/16)",
          "A Domain Name / FQDN (e.g., www.huawei.com)",
          "A physical hard drive partition serial number"], "ABCD",
         "Firewall address objects support single IPs, IP ranges, subnets, and FQDN domain names. Hard drive serial numbers are storage identifiers, not network address objects."),
        ("Service Object Predefined Services", "Which of the following are predefined standard Service Objects available in Huawei USG firewalls?",
         ["HTTP (TCP port 80)",
          "HTTPS (TCP port 443)",
          "DNS (UDP/TCP port 53)",
          "TELNET (TCP port 23)",
          "PING (ICMP Echo)"], "ABCDE",
         "Huawei firewalls include standard predefined services for well-known protocols: HTTP, HTTPS, DNS, FTP, TELNET, SSH, SMTP, and PING/ICMP."),
        ("Firewall Session Fast Path Steps", "During session table fast-path forwarding, which operations does the firewall perform for subsequent packets?",
         ["Matches the 5-tuple against the active session table",
          "Refreshes the session aging timer",
          "Applies NAT translation if configured on the session",
          "Directly forwards the packet to the egress interface pipeline without re-evaluating security policy rules",
          "Prompts the user to re-enter their username"], "ABCD",
         "Fast-path matching checks the session table, refreshes the aging timer, executes NAT rewrite if applicable, and forwards packets directly, bypassing security policy rule evaluation."),
        ("Asymmetric Routing Mitigation", "Which configuration techniques can resolve packet drops caused by asymmetric routing on stateful firewalls?",
         ["Deploying Dual-system Hot Standby with session table synchronization (HRP)",
          "Adjusting routing metrics to ensure symmetric forward and return routing paths",
          "Disabling stateful inspection (or enabling loose state checking) for specific asymmetric flows",
          "Permanently disconnecting all WAN interfaces"], "ABC",
         "Asymmetric drops are mitigated by route symmetry engineering, HRP hot-standby session synchronization between dual firewalls, or enabling loose stateful checking for affected flows."),
        ("Session Table Exhaustion Consequences", "What are the direct consequences if a firewall's session table is completely exhausted by a DDoS flood?",
         ["New legitimate user connection attempts are rejected and dropped",
          "Network services become inaccessible, causing a Denial of Service (DoS)",
          "Firewall CPU utilization increases significantly due to memory management overhead",
          "The firewall converts into a Layer 1 repeater"], "ABC",
         "Session exhaustion prevents new TCP/UDP connections from forming, causing severe service outages and driving up CPU load as the kernel attempts to manage connection table limits."),
        ("Intra-Zone vs Inter-Zone Security Differences", "Which of the following statements correctly contrast intra-zone and inter-zone traffic on Huawei firewalls?",
         ["Intra-zone traffic travels between interfaces within the same security zone",
          "Inter-zone traffic travels between interfaces belonging to different security zones",
          "By default, intra-zone traffic is permitted, while inter-zone traffic is denied",
          "Inter-zone traffic requires explicit security policies to be permitted",
          "Intra-zone traffic can never be filtered or inspected"], "ABCD",
         "Intra-zone traffic occurs within a zone (permitted by default, but filterable if configured); inter-zone traffic traverses between distinct zones (denied by default, requiring explicit permit policies)."),
        ("CLI Commands for Security Policy", "Which of the following CLI commands are used in Huawei VRP to configure and inspect security policies?",
         ["`security-policy` (enters the security policy configuration view)",
          "`rule name <name>` (creates a security policy rule)",
          "`action { permit | deny }` (specifies the policy action)",
          "`display security-policy rule all` (displays configured security policy rules)",
          "`format flash:` (deletes all system software)"], "ABCD",
         "In Huawei VRP, `security-policy`, `rule name`, `action permit/deny`, and `display security-policy rule all` are standard commands for managing security policies. `format flash:` erases storage."),
        ("Security Policy Hit Count Utility", "How do policy hit count statistics assist security administrators?",
         ["They confirm whether a newly created security rule is actively matching traffic",
          "They help detect shadow rules that are never matched because an earlier rule supersedes them",
          "They assist in capacity planning and performance auditing",
          "They automatically reboot the firewall at midnight"], "ABC",
         "Hit count metrics verify rule activation, identify overshadowed/duplicate rules, assist in cleaning obsolete configurations, and inform traffic profiling."),
        ("Custom Security Zones Use Cases", "For which network scenarios would an administrator create custom security zones beyond the four default zones?",
         ["Creating a dedicated 'Guest_Wi-Fi' zone with priority 30 to isolate visitor traffic",
          "Creating a dedicated 'Management_OAM' zone with priority 95 for out-of-band network operations",
          "Creating an 'Extranet_Partners' zone with priority 60 for B2B VPN connections",
          "Creating a zone exclusively to increase the physical weight of the firewall chassis"], "ABC",
         "Custom zones provide granular zoning for distinct business segments: Guest Wi-Fi (low trust), Partner Extranets (intermediate trust), and Out-of-Band Management (high trust)."),
        ("Application Layer Identification Benefits", "Why is application identification (L7 awareness) crucial in modern NGFWs compared to traditional L4 port filtering?",
         ["Evasive applications (e.g. BitTorrent, Tor) dynamically hop ports to bypass static port filters",
          "Many diverse applications (e.g. webmail, video streaming, SaaS apps) share common ports like 80 and 443",
          "Application awareness allows granular control (e.g. permitting Facebook browsing while blocking Facebook Chat)",
          "It eliminates the need for physical Ethernet cables"], "ABC",
         "Modern applications mask traffic over standard ports (80/443) or hop dynamic ports. L7 application control identifies true application signatures, enabling fine-grained behavioral policies (e.g., allow LinkedIn, block LinkedIn messaging)."),
        ("Session Table Fast-Path Bypass Conditions", "Which packets cannot use session table fast-path forwarding and MUST undergo policy/slow-path inspection?",
         ["The first packet of a connection (e.g. TCP SYN) attempting to initiate a new session",
          "Packets that do not match any existing session table entry",
          "Packets whose transport layer headers are malformed or violate protocol state rules",
          "Established return packets that match a valid active session entry"], "ABC",
         "Initial connection packets, packets without matching session entries, and state-violating packets are processed via the slow path. Packets matching active sessions use the fast path."),
        ("Firewall Deployment Modes", "In which operational modes can a Huawei USG series firewall be deployed within an enterprise topology?",
         ["Routing Mode (Layer 3 gateway with IP interfaces and routing)",
          "Transparent / Bridge Mode (Layer 2 bump-in-the-wire without changing existing IP subnetting)",
          "Hybrid Mode (some interfaces operate in Layer 3 while others operate in Layer 2)",
          "Satellite Wireless Relay Mode"], "ABC",
         "Huawei firewalls support Routing Mode (Layer 3 routing/NAT), Transparent Mode (Layer 2 bridging, preserving IP schema), and Hybrid Mode (combining L2 and L3 interfaces)."),
        ("Security Policy Logging Options", "When configuring logging on a Huawei security policy rule, which logging options can be toggled?",
         ["Session Start Logging (logs when a session is initially created)",
          "Session End Logging (logs when a session terminates, including duration and byte counts)",
          "Policy Hit Logging (logs rule execution events)",
          "Hardware Fan Speed Logging"], "ABC",
         "Huawei firewalls support Session Start logging, Session End logging (capturing total duration and volume metrics), and Policy Hit logging. Fan speed is managed under system environment monitoring.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 4,
            "chapter_title": "Firewall Security Policies",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 4 TRUE/FALSE (30 questions)
    tf_data = [
        ("Local Zone Priority Fixed", "In Huawei firewalls, the priority of the predefined Local security zone is fixed at 100 and cannot be modified by the administrator.", "A",
         "True. The Local zone priority is permanently fixed at 100, representing the firewall itself."),
        ("Untrust Zone Priority Value", "The default priority of the Untrust security zone is 85.", "B",
         "False. The Untrust zone priority is 5. The Trust zone priority is 85."),
        ("DMZ Zone Priority Value", "The default priority of the DMZ security zone is 50.", "A",
         "True. The DMZ zone has a fixed default priority of 50."),
        ("Interface Zone Exclusivity", "A single physical Ethernet interface on a Huawei firewall can be assigned to multiple security zones simultaneously.", "B",
         "False. An interface can belong to only one security zone at a time."),
        ("Inter-Zone Traffic Default Allow", "By default, inter-zone traffic between different security zones is permitted without any security policy configuration.", "B",
         "False. Inter-zone traffic is denied by default; explicit security policy rules with the action 'Permit' must be configured to allow communication."),
        ("Intra-Zone Traffic Default Allow", "Traffic between two interfaces assigned to the same security zone is permitted by default on Huawei firewalls.", "A",
         "True. Intra-zone traffic is permitted by default, though administrators can configure intra-zone policies to restrict it if required."),
        ("Outbound Direction Definition", "Traffic flowing from the Trust zone (85) to the Untrust zone (5) is classified as Inbound traffic.", "B",
         "False. Traffic flowing from higher priority (85) to lower priority (5) is Outbound traffic."),
        ("Default Policy Deletion", "Administrators can delete the predefined 'default' security policy rule to optimize firewall performance.", "B",
         "False. The predefined default rule cannot be deleted or reordered; it is permanently situated at the bottom of the policy list."),
        ("Security Policy Top-Down Matching", "Huawei firewalls match security policy rules sequentially from top to bottom, stopping evaluation as soon as the first matching rule is found.", "A",
         "True. Rule matching is top-down and terminates on the first match (first-match-wins principle)."),
        ("Session Table Fast-Forwarding", "Once a session is established on a stateful firewall, subsequent packets in that connection match the session table directly, bypassing security policy re-evaluation.", "A",
         "True. Fast-path forwarding utilizes the session table to forward packets without re-matching the entire security policy rulebase."),
        ("Session Aging Timer Memory Reclaim", "The primary purpose of session aging timers is to prevent stale or inactive sessions from permanently exhausting firewall memory.", "A",
         "True. Aging timers automatically flush dead or idle sessions to maintain available connection capacity."),
        ("TCP Established vs SYN Timer", "On Huawei firewalls, the default aging timer for a TCP connection in the ESTABLISHED state is much shorter than the timer for a TCP SYN packet.", "B",
         "False. TCP SYN aging timers are short (e.g., 20 seconds) to resist SYN floods, whereas ESTABLISHED timers are long (e.g., 10,000 seconds / ~20 minutes) to sustain idle business sessions."),
        ("ASPF Multi-Channel Support", "ASPF dynamically generates temporary Server-Map entries to allow dynamic secondary data channels for protocols like FTP active mode.", "A",
         "True. ASPF inspects application-layer payloads and dynamically opens temporary Server-Map pinholes for secondary data connections."),
        ("Server-Map vs Session Table", "A Server-Map entry is identical to a Session table entry and never expires.", "B",
         "False. A Server-Map entry is a temporary pre-allocation pinhole. Once matching traffic arrives and establishes a standard session entry, the dynamic server-map entry expires."),
        ("First Generation Stateless Inspection", "First-generation packet filtering firewalls track the connection state of every packet in a dynamic session table.", "B",
         "False. First-generation packet filters are stateless; they inspect packets in isolation against 5-tuple ACLs without tracking connection states."),
        ("NGFW Port Independence", "Next-Generation Firewalls can identify application types (e.g. BitTorrent, SSL) even when they communicate over non-standard or unusual port numbers.", "A",
         "True. NGFWs utilize deep packet inspection (DPI) and protocol signature analysis to identify applications independent of transport port numbers."),
        ("Custom Security Zone Overlap", "A custom security zone can be configured with the exact same priority value as an already existing security zone without restriction.", "B",
         "False. Priority values must be unique per security zone; two active security zones on the same firewall cannot share the identical priority value."),
        ("Security Policy Rule Order Significance", "Placing an overly broad 'Permit Any Any' rule at the top of the security policy list renders all subsequent specific deny rules ineffective.", "A",
         "True. Because evaluation stops on the first match, placing a broad permit rule at the top matches all traffic immediately, preventing subsequent specific deny rules from ever being evaluated."),
        ("Local Zone Transit Traffic", "Traffic traveling from an internal client in Trust (85) to an external web server in Untrust (5) passes through the Local zone (100).", "B",
         "False. Transit traffic passes directly from Trust to Untrust. The Local zone is involved only when traffic originates from or terminates on the firewall itself."),
        ("Security Policy Schedule Control", "Associating a Time Range with a security policy rule ensures that the rule is active and enforced only during specified time windows.", "A",
         "True. Schedules restrict policy rule activation to specified recurring days, hours, or absolute date ranges."),
        ("Address Object Set Maintenance", "Modifying an Address Set object automatically updates all security policies referencing that object without needing to edit each policy individually.", "A",
         "True. Address Sets provide modular abstraction; modifying the object dynamically updates all referencing security policies."),
        ("Security Profile Binding", "Security profiles (such as IPS and Antivirus) can be attached to rules whose action is configured as 'Deny'.", "B",
         "False. Security profiles perform deep packet inspection on allowed traffic and can only be bound to rules whose action is 'Permit'."),
        ("Stateful Firewall Asymmetric Drop", "If return traffic enters a stateful firewall that has no existing session entry for that flow, the firewall drops the return packets by default.", "A",
         "True. A stateful firewall expects return traffic to match an existing session. Unsolicited return packets violate stateful checks and are discarded."),
        ("Disabling Stateful Inspection Behavior", "When stateful inspection is disabled on a firewall interface, administrators must write explicit security policy rules for both forward and return traffic flows.", "A",
         "True. Without session state tracking, the firewall behaves like a stateless packet filter, requiring explicit policy rules in both directions."),
        ("Session Table Capacity Exhaustion", "When a firewall's session table reaches maximum hardware capacity, the firewall automatically shuts down all its physical power supplies.", "B",
         "False. The firewall remains powered on, but it cannot allocate new session entries, causing new incoming connection requests to be dropped."),
        ("Display Session Table Command", "The command `display firewall session table` is used in Huawei VRP to inspect active connection sessions on the firewall.", "A",
         "True. `display firewall session table` is the standard VRP command for viewing active session entries."),
        ("Service Object Port Customization", "Administrators can create custom Service Objects to define non-standard TCP or UDP port numbers used by proprietary enterprise applications.", "A",
         "True. Custom Service Objects allow administrators to define specific protocol types and port ranges for internal business software."),
        ("Hit Counter Policy Troubleshooting", "Monitoring security policy hit counters helps administrators detect unused or obsolete rules that never match real traffic.", "A",
         "True. Zero hit counts over an extended period indicate that a rule may be shadowed, misconfigured, or obsolete, aiding rulebase cleanup."),
        ("Firewall Transparent Mode Subnetting", "Deploying a Huawei firewall in Transparent Mode requires re-addressing all servers and reconfiguring the existing IP subnets.", "B",
         "False. Transparent Mode functions as a Layer 2 bridge ('bump in the wire'), filtering traffic without modifying existing IP addressing or subnet configurations."),
        ("Management Access via Interface Settings", "Administrative access services (such as SSH, HTTPS, and Ping) on a firewall interface can be controlled directly through interface service configuration.", "A",
         "True. Huawei firewalls allow administrators to enable or disable specific management services (Ping, SSH, HTTPS) directly on individual interfaces via `service-manage` commands.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 4,
            "chapter_title": "Firewall Security Policies",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch4_questions()
    print(f"Chapter 4 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
