# scripts/generate_ch7.py
"""
Generates Chapter 7 data: 38 Single Choice, 30 Multiple Choice, 28 True/False.
Chapter 7: Firewall IPS and Content Security
"""
import json

def get_ch7_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 7 SINGLE CHOICE (38 questions)
    s_data = [
        ("IDS vs IPS Deployment Mode", "What is the fundamental difference in physical network deployment between an Intrusion Detection System (IDS) and an Intrusion Prevention System (IPS)?",
         ["IDS is deployed inline, whereas IPS is deployed out-of-path",
          "IDS is deployed out-of-path (via port mirroring/TAP), whereas IPS is deployed in-line directly in the traffic forwarding path",
          "IDS operates only over wireless networks, whereas IPS operates only over copper cabling",
          "There is no difference in deployment; both are deployed exclusively on client desktops"], "B",
         "An IDS is deployed out-of-path (out-of-band) using switch port mirroring (SPAN) or physical TAPs to passively inspect copies of traffic. An IPS is deployed in-line directly in the live forwarding path to inspect and actively block malicious traffic in real time."),
        ("IPS Active Mitigation Capability", "Why can an inline IPS actively block an exploit packet before it reaches the victim, whereas an out-of-path IDS cannot?",
         ["The IPS has faster electrical cables than the IDS",
          "Because the IPS sits directly in the transmission path, it can drop malicious packets or reset connections immediately before forwarding; the IDS receives only a passive mirrored copy after the packet has already traveled to the victim",
          "The IDS is prohibited by international standards from sending alert emails",
          "The IPS converts all TCP packets into unencrypted UDP broadcasts"], "B",
         "Because an inline IPS sits directly in the data flow, it inspects packets before forwarding them and can immediately drop malicious packets or inject TCP resets. An out-of-path IDS receives only a mirrored copy; the original packet has already reached the target host."),
        ("Signature-Based Detection", "What is the primary operational mechanism of signature-based intrusion detection in an IPS?",
         ["Comparing network traffic payloads and headers against a database of known attack patterns and vulnerability characteristics",
          "Measuring ambient server room temperature fluctuations",
          "Randomly dropping 10% of all incoming packets to deter attackers",
          "Converting all web traffic into binary morse code"], "A",
         "Signature-based detection compares packet payloads, protocol fields, and behavioral sequences against a curated database of known vulnerability exploits and attack signatures, offering high detection accuracy and low false-positive rates for known threats."),
        ("Signature-Based Detection Weakness", "What is the principal operational limitation of signature-based intrusion detection?",
         ["It consumes excessive electrical power",
          "It is fundamentally incapable of detecting novel, previously unknown zero-day attacks for which no signature has been created",
          "It can only inspect packets transmitted over dial-up modems",
          "It permanently disables all firewall routing capabilities"], "B",
         "Signature detection relies on prior knowledge. When a completely new exploit or zero-day vulnerability emerges, no signature exists in the database, allowing the attack to bypass signature inspection undetected until a vendor signature update is released."),
        ("Anomaly-Based Detection Strength", "What is the major technical advantage of anomaly-based intrusion detection over signature-based detection?",
         ["It requires zero CPU or memory resources on the firewall",
          "It can detect novel, unknown zero-day attacks and abnormal behavioral deviations by comparing real-time traffic against an established baseline of normal network activity",
          "It guarantees a 0% false-positive rate under all network conditions",
          "It eliminates the need for user passwords across the enterprise"], "B",
         "Anomaly detection constructs a mathematical profile of normal baseline behavior (bandwidth, protocol distribution, connection rates). Statistically significant deviations trigger alerts, enabling the detection of previously unseen zero-day attacks and stealthy worms."),
        ("Anomaly-Based Detection Challenge", "What is the primary operational drawback associated with anomaly-based detection mechanisms?",
         ["It can only inspect ICMP echo packets",
          "It tends to produce higher false-positive rates because legitimate but unusual business traffic spikes may be flagged as attacks",
          "It requires physical hardware replacement every 30 days",
          "It is incompatible with standard Ethernet frames"], "B",
         "Defining 'normal' network behavior is difficult in dynamic enterprise environments. Legitimate events (e.g., sudden software rollouts, marketing campaigns, large backups) can deviate from the baseline, generating false-positive alarms."),
        ("Huawei IPS Predefined Signatures", "What are 'Predefined Signatures' in a Huawei USG series firewall IPS?",
         ["Signatures that must be written manually by the enterprise network administrator in C++",
          "Built-in threat signatures created, tested, and regularly updated by Huawei security research teams via online intelligence updates",
          "Signatures stored exclusively on local USB flash drives",
          "Signatures that expire after exactly 60 seconds of use"], "B",
         "Predefined signatures are vendor-provided signatures shipped with the firewall firmware and continually updated via Huawei Security Intelligence Center online feeds to protect against emerging CVEs and exploits."),
        ("Huawei IPS User-Defined Signatures", "Under what circumstances would an enterprise administrator create 'User-Defined Signatures' on an IPS?",
         ["To protect proprietary internal enterprise applications or address custom threats not covered by predefined vendor signatures",
          "Because predefined signatures cannot be used on firewalls",
          "To format the firewall's internal solid-state storage",
          "To disable all IP routing on the border router"], "A",
         "User-defined signatures allow security teams to create custom snort-like rules or regular expressions tailored to proprietary enterprise software, localized malware variants, or immediate hotfixes before official vendor signatures are published."),
        ("IPS Action - Block", "When a Huawei IPS signature detects an active remote code execution attack and its configured action is 'Block', what does the firewall do?",
         ["It logs the event but forwards the packet to the destination server",
          "It discards the malicious packet and can optionally reset the TCP connection or blacklist the attacking source IP",
          "It encrypts the packet and sends it to the cloud",
          "It permanently disables the firewall's cooling fan"], "B",
         "The 'Block' action terminates the threat by dropping the malicious packet, terminating the TCP session (via TCP RST), and optionally placing the attacking source IP into a temporary blacklist to prevent subsequent connection attempts."),
        ("IPS Action - Alert", "When an IPS signature's action is configured as 'Alert', how is matching traffic handled?",
         ["The packet is dropped and deleted immediately",
          "The firewall generates a security event log/alarm, but allows the packet to pass through to the destination",
          "The firewall automatically reboots into safe mode",
          "The packet is converted into a DNS query"], "B",
         "The 'Alert' action produces an audit log entry or security alarm while permitting the traffic to proceed without interruption, commonly used during initial IPS deployment tuning to evaluate potential false positives."),
        ("Antivirus Detection - Flow-Based", "What is the primary technical advantage of the Flow-Based (Stream-Based) antivirus scanning method utilized in Huawei USG firewalls?",
         ["It can inspect files larger than 100 gigabytes without using memory",
          "It inspects data streams in real time on the fly as packets transit the firewall without caching entire files in memory, delivering high throughput and low latency",
          "It completely replaces the need for endpoint antivirus software",
          "It does not require virus signature database updates"], "B",
         "Flow-based antivirus scans packet streams in real time using specialized hardware and pattern matching algorithms without buffering complete multi-megabyte files in RAM, enabling multi-gigabit line-rate throughput."),
        ("Antivirus Detection - File-Based", "What is a characteristic disadvantage of traditional File-Based antivirus inspection compared to Flow-Based inspection?",
         ["File-based inspection cannot detect known viruses",
          "The firewall must buffer and reassemble the entire file in memory before scanning, resulting in higher memory consumption, increased latency, and potential buffer exhaustion on large files",
          "File-based inspection operates only on wireless access points",
          "File-based inspection is prohibited by national cybersecurity standards"], "B",
         "File-based scanning reconstructs the entire file in RAM before scanning. For multi-gigabit gateways handling millions of concurrent flows, buffering complete files introduces substantial latency and can overwhelm firewall memory buffers."),
        ("Antivirus Supported Protocols", "Which of the following application layer protocols is commonly supported for malware inspection by Huawei firewall Antivirus engines?",
         ["HTTP, FTP, SMTP, POP3, IMAP, and SMB",
          "BGP, OSPF, and RIP routing updates",
          "Ethernet CRC checksum frames",
          "Physical Layer optical laser pulses"], "A",
         "Huawei NGFW Antivirus inspects prominent file transfer and communication protocols: Web (HTTP), File transfer (FTP, SMB), and Email (SMTP, POP3, IMAP)."),
        ("Antivirus Action - Declare", "In Huawei firewall antivirus configuration, what does the 'Declare' action signify for email protocols?",
         ["Deleting the recipient's entire mailbox",
          "Permitting the email attachment to pass through while inserting a warning notification or modifying the email subject header to alert the recipient",
          "Sending a physical letter to the sender's postal address",
          "Disabling all incoming email for 30 days"], "B",
         "The 'Declare' action allows an infected email to be delivered but modifies the message (e.g., adding a warning banner to the subject or body, or stripping the infected attachment) to inform the user of the threat."),
        ("URL Filtering Purpose", "What is the primary operational objective of implementing URL Filtering on an enterprise firewall?",
         ["To accelerate DNS caching speed across local servers",
          "To regulate, monitor, and restrict employee web browsing to specific categories of websites (e.g., blocking adult, gambling, or phishing sites)",
          "To replace web servers with firewall hardware",
          "To force all web browsers to use the same font size"], "B",
         "URL Filtering controls employee web access, preventing visits to malicious websites (phishing, malware distribution), non-work-related sites (gambling, gaming), or high-bandwidth consumption portals (video streaming)."),
        ("URL Filtering Category - Predefined", "What are Predefined URL Categories in Huawei USG firewalls?",
         ["Categories that must be typed manually by the administrator one URL at a time",
          "A comprehensive, cloud-updated classification database (e.g., Finance, Education, Adult, Malicious) maintained by Huawei Security Intelligence",
          "Categories stored on read-only optical discs inside the firewall chassis",
          "Categories that only apply during nighttime hours"], "B",
         "Predefined categories group millions of global URLs into structured classifications (Business, Social, Entertainment, Security Threats). The database is dynamically updated via cloud intelligence."),
        ("URL Filtering - Whitelist Priority", "On a Huawei firewall configured with URL Filtering, what is the evaluation priority of the URL Whitelist compared to category rules and blacklists?",
         ["Lowest priority; evaluated only if all other rules fail",
          "Highest priority; if a requested URL matches the Whitelist, it is permitted immediately without checking blacklists or category rules",
          "Equal priority; resolved by coin toss",
          "Whitelists are evaluated only on alternate days of the week"], "B",
         "The Whitelist has the highest precedence in URL filtering. Any URL matching a whitelist entry is immediately permitted, bypassing category inspection and blacklists."),
        ("URL Filtering - Blacklist Action", "When a user attempts to browse a website whose domain name matches the configured URL Blacklist, what is the default result?",
         ["The request is permitted with high priority",
          "The connection is blocked immediately and a block notification page is presented to the user",
          "The user's computer monitor is turned off",
          "The web page is translated into Latin"], "B",
         "The Blacklist has absolute blocking priority. Any request matching a blacklist pattern is blocked immediately, terminating the connection and displaying a customizable warning/block page."),
        ("File Filtering Technology", "How does Huawei NGFW File Filtering accurately identify file types even if a malicious user renames an executable file from `malware.exe` to `document.txt`?",
         ["By reading only the file extension characters in the file name",
          "By analyzing the true file type through file header magic numbers and binary structural signatures, independent of the file extension",
          "By contacting the user to ask for the genuine file type",
          "By converting all files into PDF documents"], "B",
         "Attackers frequently rename malicious executables (`.exe`) to harmless extensions (`.txt`, `.jpg`). Huawei File Filtering inspects the binary file header magic bytes (e.g., `MZ` for PE executables, `%PDF` for PDFs) to identify the true file type."),
        ("Content Filtering - Keyword Matching", "What is the primary function of Content Filtering on an enterprise firewall?",
         ["To measure the physical length of network cables",
          "To scan application payloads (web pages, web posts, emails) for sensitive keywords (e.g., proprietary project names, confidential data) to prevent data leakage",
          "To format the hard drives of internal servers",
          "To change the color scheme of corporate websites"], "B",
         "Content Filtering performs deep text analysis on transmitted data (HTTP posts, email text, search queries) to detect and block predefined sensitive keywords, preventing data exfiltration and policy violations."),
        ("IPS Signature Severity Levels", "Which of the following represents a valid severity level for an IPS signature on a Huawei firewall?",
         ["High, Medium, Low, and Informational",
          "Atomic, Molecular, Cellular, and Organism",
          "Alpha, Beta, Gamma, and Delta",
          "Gold, Silver, Bronze, and Platinum"], "A",
         "Huawei IPS signatures are categorized by threat impact into four standardized severity ratings: High (critical exploits, RCE), Medium (privilege escalation), Low (information disclosure), and Informational (scanning, protocol anomaly)."),
        ("IPS Exception Signature Configuration", "Why would an administrator configure an 'Exception' within an IPS profile?",
         ["To permanently disable the entire IPS engine",
          "To override the default action or severity of a specific signature (e.g., changing action from Block to Alert) without altering the global signature database",
          "To delete the firewall operating system",
          "To allow unauthorized users to log in as root"], "B",
         "An Exception rule allows administrators to customize the behavior of individual signatures. If a specific signature triggers false positives on an internal business application, changing its action to Alert or Pass in the Exception list prevents business interruption."),
        ("Protocol Anomaly Detection", "What does Protocol Anomaly Detection verify when inspecting network traffic?",
         ["It checks whether the user is wearing an official uniform",
          "It verifies whether traffic strictly conforms to standardized RFC specifications (e.g., legal HTTP request lengths, valid header formatting, valid DNS transaction fields)",
          "It measures the electrical resistance of the network interface",
          "It counts the number of letters in the user's password"], "B",
         "Protocol Anomaly Detection checks incoming packets against official RFC standards, flagging malformed headers, illegal field lengths, or unexpected command sequences that indicate fuzzing, exploit payloads, or protocol abuse."),
        ("IPS Profile Association", "How is an IPS Profile activated to inspect live production traffic on a Huawei NGFW?",
         ["By typing `ips start` in user view",
          "By binding the configured IPS Profile to a Security Policy rule whose action is 'Permit'",
          "By assigning the IPS Profile to an empty USB storage port",
          "By rebooting all connected desktop computers"], "B",
         "In Huawei NGFWs, security inspection profiles (IPS, AV, URL filtering) are applied by associating them with a 'Permit' rule in the Security Policy. Traffic matching the policy is then passed through the assigned IPS engine."),
        ("Antivirus Signature Database Update", "Why is it essential for an enterprise firewall to maintain regular, automated updates of its Antivirus signature database?",
         ["Because thousands of new malware variants and ransomware strains emerge daily across the global Internet",
          "Because the firewall hardware automatically deletes all signatures every 24 hours",
          "To prevent Ethernet cables from corroding",
          "Because older signatures increase the weight of the firewall"], "A",
         "Cyber threat actors continuously develop new malware variants, obfuscated packers, and zero-day trojans. Without daily or real-time signature updates, the antivirus engine cannot identify the latest malicious binaries."),
        ("Mail Filtering - Spam Defense", "Which technique is commonly employed by Huawei firewall Mail Filtering engines to combat unsolicited commercial email (spam)?",
         ["RBL (Real-time Blackhole List) server IP reputation querying and keyword filtering",
          "Disconnecting all incoming email servers permanently",
          "Converting all incoming emails into unencrypted audio files",
          "Requiring email senders to visit the company in person"], "A",
         "Mail filtering uses Real-time Blackhole Lists (RBL), sender IP reputation databases, SPF/DKIM verification, and body keyword analysis to classify and block spam emails before delivery."),
        ("URL Filtering Search Keyword Auditing", "How does a firewall inspect search engine queries (e.g. Google or Bing searches) when HTTPS inspection is enabled?",
         ["By guessing the user's thoughts",
          "By decrypting the SSL session using SSL Decryption / SSL Proxy and inspecting the HTTP GET parameters for the search keyword string",
          "By modifying the DNS records of all search engine companies",
          "By physically monitoring the user's keyboard"], "B",
         "Because modern search engines use HTTPS, inspection requires an SSL Decryption Policy (SSL Proxy). The firewall decrypts the TLS session, inspects the plaintext HTTP URI parameters (e.g. `?q=keyword`), and applies content/URL policies before re-encrypting."),
        ("False Positive Definition", "What is a 'False Positive' in the context of IPS security monitoring?",
         ["An attack that is correctly detected and blocked by the IPS",
          "Legitimate, benign network traffic that is incorrectly flagged and blocked by the IPS as malicious",
          "An attack that passes through the IPS completely undetected",
          "A hardware power failure on the firewall chassis"], "B",
         "A False Positive occurs when benign, legitimate network traffic is erroneously classified as an attack and blocked or alerted by the IPS, potentially disrupting normal business applications."),
        ("False Negative Definition", "What is a 'False Negative' in IPS operational terminology?",
         ["Benign traffic that is allowed to pass normally",
          "A real, malicious attack that the IPS fails to detect and allows to pass through to the target",
          "An attack that triggers an alarm on all enterprise monitors",
          "A software update that installs successfully"], "B",
         "A False Negative occurs when a genuine malicious exploit slips through the IPS completely undetected, often due to missing signatures, evasion techniques, or zero-day vulnerabilities."),
        ("Flow-Based AV Resource Advantage", "Why is Flow-Based antivirus particularly advantageous on border firewalls handling heavy user downloads?",
         ["It requires zero megabytes of storage on user PCs",
          "It avoids holding multi-megabyte files in firewall RAM buffers, preserving system memory and ensuring consistent forwarding latency during large file transfers",
          "It allows the firewall to mine Bitcoin during quiet periods",
          "It doubles the physical speed of the fiber optic link"], "B",
         "Flow-based scanning examines packet streams on the fly without holding whole files in memory, avoiding memory exhaustion and high latency when hundreds of concurrent users download large files."),
        ("URL Category Action - Force Redirect", "What occurs when a URL Filtering rule action is set to 'Force Redirect'?",
         ["The user is redirected to a different specified URL (such as a corporate policy reminder page or secondary proxy)",
          "The user's computer is rebooted into safe mode",
          "The user is disconnected from the local network permanently",
          "The web server is powered off"], "A",
         "Force Redirect intercepts the user's HTTP request and returns an HTTP 302 redirect response pointing the browser to a designated warning page, compliance portal, or corporate intranet URL."),
        ("File Filtering Direction", "In Huawei firewall configuration, can File Filtering rules be configured with directional granularity?",
         ["No, File Filtering applies identically in all directions without distinction",
          "Yes, File Filtering can be configured specifically for Uploads (outbound data loss prevention) or Downloads (inbound malware prevention)",
          "File Filtering works only for internal server backups",
          "Direction is determined by the physical tilt of the firewall rack"], "B",
         "File filtering can be applied directionally: inspecting Inbound downloads (blocking executable downloads or malicious PDFs) and Outbound uploads (preventing proprietary document exfiltration)."),
        ("IPS Signature Evasion - Fragmentation", "How do attackers attempt to evade simple signature matching using IP packet fragmentation?",
         ["By splitting the malicious exploit string across multiple small IP fragments so that neither fragment alone contains the full recognizable signature pattern",
          "By setting the IP TTL to 255",
          "By using wireless transmission instead of copper",
          "By deleting the IP checksum"], "A",
         "Attackers fragment packets so that exploit strings (e.g. `/bin/sh`) are split across separate fragment boundaries. To prevent evasion, modern NGFWs reassemble IP fragments before performing deep packet signature inspection."),
        ("Firewall DPI Performance Engine", "What architectural design in Huawei NGFWs enables simultaneous execution of IPS, Antivirus, and URL Filtering without compounding latency?",
         ["Single-pass parallel processing engine that inspects packet contents against multiple security signature engines simultaneously in a single scan",
          "Passing the packet through five separate physical hardware firewalls connected in series",
          "Disabling all IP routing while security engines are running",
          "Using mechanical relays to switch packets between hard drives"], "A",
         "Huawei NGFW uses an integrated single-pass architecture. Packets are parsed once, and the data stream is evaluated in parallel against IPS, Antivirus, and URL filtering engines simultaneously, eliminating serial processing latency."),
        ("IPS Bypass Mode on Overload", "What is the purpose of an 'IPS Bypass' or 'Fail-Open' mechanism during extreme hardware overload or failure?",
         ["To ensure business network traffic continues to flow without interruption, trading security inspection for operational availability",
          "To permanently delete all firewall operating system files",
          "To force all employee computers to disconnect from the LAN",
          "To convert the firewall into an optical amplifier"], "A",
         "If the firewall or inline IPS engine experiences severe hardware failure or unmanageable traffic saturation, a bypass switch (fail-open) allows packets to bypass the inspection engine, prioritizing business continuity over security inspection."),
        ("URL Filtering Domain vs Path Matching", "How does URL filtering distinguish between domain matching and URL path matching?",
         ["Domain matching evaluates only the host FQDN (e.g., `example.com`), whereas path matching evaluates the complete resource URI (e.g., `example.com/downloads/file.zip`)",
          "Domain matching works only for IPv6, and path matching works only for IPv4",
          "Domain matching works only over Telnet",
          "There is no difference; domain and path are identical"], "A",
         "Domain filtering matches the server host name (e.g., `www.example.com`), while complete URL filtering inspects the protocol, host, port, directory path, and query parameters, allowing granular rules (e.g., allow `example.com`, block `example.com/games`)."),
        ("Antivirus File Extension Deception", "An attacker changes the file name of `trojan.exe` to `invoice.pdf` and sends it via email. How does Huawei NGFW Antivirus prevent infection?",
         ["It relies on the recipient noticing the wrong icon",
          "It analyzes the internal file header and binary stream to recognize that the file is actually a Portable Executable (PE) binary, applying EXE inspection rules regardless of the PDF extension",
          "It deletes the email server",
          "It asks the sender to resend the email in cleartext"], "B",
         "The AV engine performs true file type identification by reading internal file signatures (magic bytes) rather than trusting superficial file extensions, ensuring that masked executables are scanned with appropriate executable signatures."),
        ("Threat Log Viewing Command", "Which command is used in Huawei VRP to view intrusion prevention threat log records?",
         ["display security-policy rule", "display logbuffer", "display ip routing-table", "display version"], "B",
         "The command `display logbuffer` (or viewing dedicated threat logs in the web GUI / eLog server) displays real-time security events, including IPS signature hits, blocked source IPs, and antivirus detections.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 7,
            "chapter_title": "Firewall IPS",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 7 MULTIPLE CHOICE (30 questions)
    m_data = [
        ("IDS vs IPS Comparison", "Which of the following statements correctly compare an IDS and an IPS?",
         ["An IDS is typically deployed out-of-path via mirror ports, while an IPS is deployed in-line in the traffic path",
          "An IDS passively monitors traffic and generates alerts, while an IPS can actively drop malicious packets in real time",
          "An IDS has zero impact on network forwarding latency, whereas an IPS introduces minimal processing latency",
          "An IDS can actively modify live packet headers before they reach target hosts",
          "An IPS is deployed exclusively on wireless mice and keyboards"], "ABC",
         "An IDS is passive and out-of-path with zero inline latency impact, generating alerts only. An IPS is inline, actively inspects and drops threats, introducing minor processing latency. An IDS cannot modify live packets."),
        ("IPS Detection Methodologies", "Which of the following are primary detection methodologies employed by modern Intrusion Prevention Systems?",
         ["Signature-Based Detection",
          "Anomaly-Based / Behavioral Detection",
          "Protocol Anomaly Detection",
          "Acoustic Room Resonance Detection"], "ABC",
         "IPS engines combine signature detection (known exploits), anomaly detection (baseline deviations), and protocol anomaly detection (RFC non-compliance). Acoustic resonance is not a network detection method."),
        ("Huawei IPS Signature Classifications", "On a Huawei USG series firewall, IPS signatures are categorized into which of the following groups?",
         ["Predefined Signatures (vendor-supplied and updated via cloud intelligence)",
          "User-Defined Signatures (custom-authored by enterprise administrators)",
          "Hardware Optical Signatures",
          "Mechanical Relaying Signatures"], "AB",
         "Huawei IPS signatures comprise Predefined signatures (supplied and updated by Huawei) and User-Defined signatures (custom crafted for enterprise-specific rules)."),
        ("Huawei IPS Actions Available", "Which of the following actions can be configured when an IPS signature matches traffic on a Huawei firewall?",
         ["Alert (generate a log and allow packet to pass)",
          "Block (drop the malicious packet and optionally reset the connection)",
          "Pass (permit the traffic without logging)",
          "Format (erase all firewall storage)"], "ABC",
         "The standard IPS response actions on Huawei firewalls are Alert, Block (with optional TCP RST), and Pass."),
        ("Antivirus Scanning Methods", "Which two primary scanning architectures are utilized in network antivirus engines?",
         ["File-Based Antivirus Scanning (buffers and reassembles entire file in memory)",
          "Flow-Based / Stream-Based Antivirus Scanning (scans packet data streams on the fly)",
          "Manual Microscopic Chip Scanning",
          "Electromagnetic Radiation Scanning"], "AB",
         "The two core network antivirus approaches are File-based (full reassembly, high memory) and Flow-based (real-time stream scanning, low latency, high throughput)."),
        ("Antivirus Supported Application Protocols", "Huawei NGFW Antivirus engines can inspect which of the following application layer protocols for malware?",
         ["HTTP / HTTPS (Web traffic)",
          "FTP (File Transfer Protocol)",
          "SMTP (Simple Mail Transfer Protocol)",
          "POP3 / IMAP (Mail retrieval protocols)",
          "SMB / CIFS (Windows file sharing)"], "ABCDE",
         "Huawei firewall AV inspects HTTP/HTTPS, FTP, SMTP, POP3, IMAP, and SMB/CIFS protocols for viruses, trojans, worms, and ransomware."),
        ("URL Filtering Predefined Categories", "Which of the following represent common predefined URL categories in Huawei cloud threat intelligence?",
         ["Malicious Websites (Phishing, Malware distribution, C2 domains)",
          "Adult and Pornographic Content",
          "Gambling and Illegal Gaming",
          "Social Networking and Media Streaming",
          "Physical Hardware Circuit Schematics"], "ABCD",
         "Predefined categories group URLs into Malicious, Adult, Gambling, Social Media, Gaming, Financial, and Entertainment categories."),
        ("URL Filtering Processing Elements", "When evaluating a user web request, in what order does Huawei URL Filtering evaluate matching elements?",
         ["Blacklist (highest blocking priority)",
          "Whitelist (highest permitting priority)",
          "User-defined URL categories",
          "Predefined cloud URL categories"], "ABCD",
         "URL filtering precedence evaluates Whitelists and Blacklists first, followed by User-Defined categories, and finally Predefined cloud categories."),
        ("File Filtering Control Capabilities", "Which of the following control capabilities are provided by Huawei NGFW File Filtering?",
         ["Filtering files based on true file type (identifying magic bytes, e.g. EXE, PDF, ZIP)",
          "Filtering files based on declared file name and extension",
          "Applying directional control (Upload vs Download)",
          "Taking actions such as Alert or Block on matching file transfers"], "ABCD",
         "File filtering accurately identifies true file types via magic bytes, evaluates extensions, applies directional rules (upload/download), and enforces Alert or Block actions."),
        ("Content Filtering Applications", "Content Filtering on Huawei firewalls can perform deep inspection on which of the following traffic types?",
         ["Web page text content and user web form submissions (HTTP POST)",
          "Email body text and subject lines (SMTP/POP3/IMAP)",
          "Search engine query parameter text",
          "Physical fiber optic core refractive indexes"], "ABC",
         "Content filtering scans HTTP web posts, search queries, and email bodies/subjects for confidential keywords or prohibited terms."),
        ("Benefits of Flow-Based AV", "Why is Flow-Based AV inspection particularly suited for enterprise gateway firewalls?",
         ["High packet processing throughput with minimal line-rate latency",
          "Low RAM footprint because complete multi-gigabyte files are not cached in memory",
          "Immediate inspection and drop of infected streams before complete file transmission",
          "Complete elimination of the need for an operating system on servers"], "ABC",
         "Flow-based scanning provides high throughput, low memory usage, and immediate detection without waiting for complete file downloads."),
        ("IPS Evasion Techniques", "Which of the following evasion techniques are historically attempted by attackers to bypass simple IPS inspection?",
         ["IP Packet Fragmentation (splitting signatures across small fragments)",
          "TCP Segmentation (splitting exploit strings across multiple TCP segments)",
          "URL Encoding and Unicode Obfuscation (e.g., `%20`, `%2F`)",
          "Overwriting physical switch power transformers"], "ABC",
         "Attackers attempt evasion via IP fragmentation, TCP segmentation, URL hex encoding, and polymorphic payload encryption. Modern NGFWs de-obfuscate and reassemble flows before scanning."),
        ("Single-Pass Inspection Advantages", "What are the core operational benefits of Huawei's Unified Single-Pass Inspection architecture?",
         ["Packets are decoded and parsed once, rather than repeated per security engine",
          "Signatures for IPS, Antivirus, and URL Filtering are evaluated in parallel simultaneously",
          "Drastically reduces processing latency and CPU utilization compared to serial multi-engine scanning",
          "Eliminates the requirement for security policies"], "ABC",
         "Single-pass architecture decodes packets once and scans payloads in parallel across IPS, AV, and URL engines, maximizing throughput and minimizing latency."),
        ("IPS Signature Severity Classifications", "Which of the following are valid severity levels defined for Huawei IPS signatures?",
         ["High (critical severity, high risk of remote compromise)",
          "Medium (moderate severity, privilege escalation)",
          "Low (low severity, information gathering)",
          "Informational (benign protocol anomalies, reconnaissance)",
          "Galactic (cosmic solar radiation impact)"], "ABCD",
         "Huawei IPS signatures are categorized into High, Medium, Low, and Informational severity ratings."),
        ("Protocol Anomaly Inspection Checks", "Which anomalies are detected by Protocol Anomaly Inspection engines?",
         ["HTTP requests containing excessively long headers or illegal URI characters violating RFC 2616",
          "DNS query packets with invalid transaction IDs or malformed resource record lengths",
          "FTP commands containing non-ASCII control characters",
          "Unencrypted physical cables installed in office ceilings"], "ABC",
         "Protocol anomaly engines verify RFC compliance, detecting illegal field lengths, malformed structures, and invalid command sequences in HTTP, DNS, FTP, and SMTP."),
        ("Antivirus Actions Available", "Which actions can be configured in a Huawei Antivirus profile for infected traffic?",
         ["Block (discard the packet/connection)",
          "Alert (generate a security log and allow the file to pass)",
          "Declare (allow the email message but attach a warning banner)",
          "Overclock (accelerate the client CPU frequency)"], "ABC",
         "Antivirus response actions include Block, Alert, and Declare (for email protocols). 'Overclock' is hardware tuning."),
        ("URL Filtering Whitelist Benefits", "In which situations is adding an internal or partner domain to the URL Whitelist recommended?",
         ["To guarantee uninterrupted access to mission-critical business partner portals",
          "To prevent critical corporate web applications from being accidentally blocked by cloud category updates",
          "To accelerate browsing by bypassing deep category lookups for trusted internal portals",
          "To permit employees to download unrestricted torrents"], "ABC",
         "Whitelisting ensures essential business portals and partner applications remain accessible and bypass categorization delays or accidental blocks."),
        ("Reasons for IPS False Positives", "Which factors commonly contribute to false-positive detections in an enterprise IPS deployment?",
         ["Poorly written custom enterprise software that violates RFC protocol standards",
          "Overly aggressive anomaly detection thresholds set without adequate baseline training",
          "Vulnerability scanner traffic performing authorized security audits",
          "Physical grounding of server racks"], "ABC",
         "False positives stem from non-RFC compliant internal applications, uncalibrated anomaly baselines, and authorized penetration test scans."),
        ("Mitigating IPS False Positives", "Which actions should an administrator take when a critical business application is blocked by an IPS false positive?",
         ["Add an Exception rule in the IPS profile to change the signature action from Block to Alert or Pass",
          "Fine-tune the signature matching criteria if it is a user-defined signature",
          "Temporarily deactivate the specific signature while contacting vendor support for signature refinement",
          "Format all hard drives in the enterprise data center"], "ABC",
         "False positives are resolved by creating signature Exceptions (changing action to Alert/Pass), tuning custom rules, or reporting false signatures to vendor threat research."),
        ("Mail Filtering Capabilities", "Which defensive features are provided by Huawei firewall Mail Filtering?",
         ["Spam filtering based on Real-Time Blackhole Lists (RBL)",
          "Sender IP reputation checking and sender address filtering",
          "Mail attachment filtering by file extension and true file type",
          "Mail content keyword scanning and filtering",
          "Automatically generating marketing emails to customers"], "ABCD",
         "Mail filtering provides RBL lookup, sender IP reputation, attachment type filtering, and body keyword analysis. It does not generate marketing emails."),
        ("SSL Decryption Necessity for Content Security", "Why is SSL Decryption (SSL Proxy) becoming essential for effective IPS, Antivirus, and URL filtering?",
         ["Over 80% of modern Internet web traffic is encrypted using HTTPS / TLS",
          "Without decryption, the firewall can only inspect the outer TCP/IP headers and SNI domain, unable to view the encrypted payload for viruses or exploit signatures",
          "Malware authors increasingly use HTTPS for C2 communication and malicious payload delivery",
          "SSL decryption makes fiber optic cables immune to physical bending"], "ABC",
         "Because TLS encrypts packet payloads, inline security engines cannot inspect data for viruses or exploit signatures without SSL Decryption, leaving encrypted malware invisible."),
        ("True File Type vs Extension Matching", "Why does Huawei NGFW File Filtering analyze magic numbers rather than just file extensions?",
         ["Users can easily rename file extensions (e.g. `trojan.exe` to `photo.jpg`)",
          "Malware frequently disguises itself as innocuous office documents to bypass basic perimeter checks",
          "Magic numbers provide mathematically verifiable identification of binary file structures",
          "File extensions require 128-bit encryption keys to read"], "ABC",
         "File extensions are easily forged by users or attackers. Magic numbers (file headers) provide reliable identification of binary file types regardless of file name."),
        ("Content Filtering Data Loss Prevention (DLP) Use Cases", "For which data protection goals is Content Filtering deployed on corporate firewalls?",
         ["Preventing the unauthorized leakage of intellectual property (source code, schematics)",
          "Detecting and blocking the transmission of sensitive personal data (credit card numbers, social security IDs)",
          "Enforcing acceptable use policies regarding prohibited or offensive language",
          "Accelerating the download speed of video files"], "ABC",
         "Content filtering prevents data exfiltration (trade secrets, PII, financial records) and enforces corporate acceptable use standards in web and email transmissions."),
        ("IPS Tuning Best Practices", "Which of the following are recommended best practices when initially rolling out IPS in an enterprise network?",
         ["Deploy the IPS profile in 'Alert Only' mode initially for 1-2 weeks to observe baseline traffic and identify potential false positives",
          "Review alert logs daily and configure signature exceptions for legitimate internal business software",
          "Transition critical signatures to 'Block' mode after tuning is verified",
          "Immediately set all 10,000 signatures to Block without testing"], "ABC",
         "Initial IPS deployments should run in Alert mode to identify false positives on business applications, configure exceptions, and transition signatures to Block mode incrementally."),
        ("URL Filtering Deployment Modes", "Which lookup methods are supported by Huawei firewalls for URL category classification?",
         ["Local URL Cache lookup (checking frequently accessed URLs stored in local memory)",
          "Cloud-based URL Category query (querying Huawei Security Intelligence Center for uncached domains)",
          "User-Defined Category matching",
          "Satellite Television Teletext query"], "ABC",
         "URL classification utilizes local memory caches for speed, user-defined rules, and real-time queries to Huawei Cloud Security Intelligence for uncached sites."),
        ("IPS Signature Attributes", "Which parameters define an individual IPS signature on a Huawei firewall?",
         ["Unique Signature Identifier (Signature ID)",
          "Target OS / Application Protocol (e.g. HTTP, SMB, Windows, Linux)",
          "Severity Level (High, Medium, Low, Informational)",
          "Default Action (Block, Alert)",
          "Physical weight of the firewall chassis"], "ABCD",
         "Signatures are identified by Signature ID, protocol/OS classification, CVE reference, severity level, and default action."),
        ("Antivirus Stream Scanning Protocols", "Flow-based antivirus scanning can be applied to which protocols on Huawei NGFWs?",
         ["HTTP file downloads and web browsing",
          "FTP active and passive file transfers",
          "SMTP outbound email attachments",
          "SMB Windows file sharing transfers",
          "Analog AM radio voice broadcasts"], "ABCD",
         "Flow-based AV scans HTTP, FTP, SMTP, POP3, IMAP, and SMB. AM radio is an analog broadcast medium unrelated to digital IP networks."),
        ("Network Security Profile Types", "Which of the following security inspection profiles are supported on Huawei USG series firewalls?",
         ["IPS Profile", "Antivirus Profile", "URL Filtering Profile", "File Filtering Profile", "Content Filtering Profile", "Rocket Propulsion Profile"], "ABCDE",
         "Huawei firewalls support IPS, Antivirus, URL Filtering, File Filtering, Content Filtering, and Mail Filtering profiles. 'Rocket Propulsion' is fictional."),
        ("Hardware Fail-Open Bypass Mechanism", "What are the benefits of deploying an external optical or electrical Bypass Switch with an inline IPS?",
         ["If the IPS firewall experiences a complete power failure, the bypass switch automatically connects the physical link directly, preserving network continuity",
          "It allows maintenance and firmware updates on the IPS without causing scheduled network downtime",
          "It permanently blocks all computer viruses automatically",
          "It converts copper cabling into single-mode fiber"], "AB",
         "Bypass switches provide hardware fail-open capability, bridging traffic across links during power failures or maintenance windows, ensuring zero service disruption."),
        ("Threat Event Log Information", "When an IPS signature blocks an attack, which details are recorded in the resulting threat log?",
         ["Attacking Source IP Address and Port",
          "Target Destination IP Address and Port",
          "Signature ID, Attack Name, and Severity Level",
          "Action taken (e.g. Block/Dropped)",
          "The color of the attacker's physical keyboard"], "ABCD",
         "IPS threat logs record 5-tuple socket details (source/dest IP and port), signature ID, attack name, CVE reference, severity, and action taken.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 7,
            "chapter_title": "Firewall IPS",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 7 TRUE/FALSE (28 questions)
    tf_data = [
        ("IDS Inline Deployment", "An Intrusion Detection System (IDS) is deployed in-line in the traffic forwarding path to actively block malicious packets.", "B",
         "False. An IDS is deployed out-of-path via port mirroring or TAPs; it cannot actively drop packets in-line. An IPS is deployed in-line to actively block threats."),
        ("IPS Real-Time Dropping", "Because an IPS sits in-line directly in the traffic path, it can inspect packets and drop malicious flows before they reach target servers.", "A",
         "True. Inline positioning enables an IPS to analyze packets and actively drop or reset malicious connections in real time."),
        ("Signature Zero-Day Detection", "Signature-based intrusion detection can reliably detect novel zero-day attacks without requiring any signature updates.", "B",
         "False. Signature detection relies on known attack patterns; novel zero-day exploits lack pre-existing signatures and bypass signature inspection."),
        ("Anomaly Detection Zero-Day Advantage", "Anomaly-based intrusion detection can detect unknown zero-day attacks by identifying statistical deviations from established normal network behavior baselines.", "A",
         "True. By monitoring baseline traffic patterns and flagging unusual deviations, anomaly detection can catch novel attacks that lack signatures."),
        ("Anomaly False Positive Rate", "A significant challenge of anomaly-based detection is that unusual but legitimate business traffic can be incorrectly flagged as an attack (false positive).", "A",
         "True. Dynamic business environments generate legitimate traffic spikes and non-standard flows that anomaly detection models may misidentify as malicious."),
        ("Predefined Signatures Cloud Update", "Predefined IPS signatures on Huawei firewalls are maintained and updated via Huawei Security Intelligence Center online feeds.", "A",
         "True. Huawei continually updates its predefined signature database to provide protection against newly discovered vulnerabilities and exploits."),
        ("User-Defined Custom Signatures", "Administrators can write User-Defined IPS signatures using custom regular expressions to protect proprietary enterprise applications.", "A",
         "True. Huawei firewalls allow administrators to create custom user-defined signatures tailored to internal systems and specific threat patterns."),
        ("IPS Action Alert Behavior", "When an IPS signature's action is set to 'Alert', the firewall drops the packet and resets the TCP connection.", "B",
         "False. The 'Alert' action generates a security log entry but allows the packet to pass through to the destination without blocking."),
        ("Flow-Based AV Line Rate Throughput", "Flow-based antivirus scans data streams in real time as packets transit the firewall without caching entire files in memory, delivering high throughput.", "A",
         "True. Flow-based AV evaluates packet streams on the fly, avoiding memory exhaustion and delivering low-latency, multi-gigabit inspection."),
        ("File-Based AV Full Reassembly", "File-based antivirus scanning reconstructs the entire file in memory before scanning, which can cause significant latency on large file transfers.", "A",
         "True. Buffering complete multi-megabyte files in firewall RAM introduces substantial latency and can exhaust memory buffers under high concurrency."),
        ("Antivirus Protocol Coverage", "Huawei firewall Antivirus can inspect file transfers across HTTP, FTP, SMTP, POP3, IMAP, and SMB protocols.", "A",
         "True. Huawei NGFW AV provides comprehensive coverage across web, file transfer, and mail protocols."),
        ("Antivirus Declare Action", "The 'Declare' action in Huawei Antivirus allows an infected email to be delivered while inserting a warning notification to alert the recipient.", "A",
         "True. 'Declare' permits email delivery but alerts the user by modifying the subject line or body with a warning notification."),
        ("URL Whitelist Precedence", "On Huawei firewalls, a URL matching the configured Whitelist is permitted immediately, taking precedence over blacklists and category rules.", "A",
         "True. Whitelists have top evaluation priority in URL filtering, ensuring trusted business domains are never blocked."),
        ("URL Blacklist Precedence", "A URL matching the configured URL Blacklist is immediately blocked, taking precedence over category-based filtering rules.", "A",
         "True. Blacklists have absolute blocking priority over standard category rules; matching requests are dropped immediately."),
        ("File Filtering True File Type", "Huawei File Filtering identifies true file types by analyzing internal file header magic bytes rather than relying merely on file extension names.", "A",
         "True. File filtering reads binary header magic numbers, preventing attackers from disguising executable binaries (`.exe`) as text or image files."),
        ("Content Filtering Keyword Matching", "Content Filtering inspects application payloads (such as web form submissions and email text) to detect and block confidential keywords.", "A",
         "True. Content filtering performs deep text inspection to prevent sensitive data exfiltration (e.g. credit card numbers, intellectual property)."),
        ("IPS Exception Signature Override", "Configuring an Exception in an IPS profile allows an administrator to change the action of a specific signature (e.g. from Block to Alert) without disabling the entire profile.", "A",
         "True. Exceptions permit granular rule overrides for specific signatures to eliminate false positives on critical business systems."),
        ("Protocol Anomaly RFC Compliance", "Protocol Anomaly Detection verifies that network traffic conforms to official RFC specifications, detecting malformed headers and illegal field lengths.", "A",
         "True. Protocol anomaly checking enforces strict RFC standard compliance, catching protocol fuzzing, header overflows, and malformed exploit vectors."),
        ("IPS Profile Security Policy Binding", "An IPS profile is activated on a Huawei firewall by binding it to a Security Policy rule whose action is configured as 'Permit'.", "A",
         "True. Security profiles are applied to traffic permitted by security policy rules for deep Layer 7 threat inspection."),
        ("Daily AV Database Updates", "Maintaining automated daily updates of the antivirus signature database is critical because thousands of new malware strains emerge every day.", "A",
         "True. Daily signature updates ensure the firewall can detect the latest ransomware, trojans, and polymorphic malware variants."),
        ("HTTPS Encryption Inspection Challenge", "Without SSL Decryption, an IPS or Antivirus engine cannot inspect encrypted payload data inside HTTPS web connections.", "A",
         "True. TLS encryption conceals payload contents; an SSL proxy / decryption policy is required to decrypt and inspect HTTPS payloads for threats."),
        ("False Positive Definition Check", "A False Positive occurs when an IPS correctly detects and blocks an actual malware attack.", "B",
         "False. A False Positive occurs when benign, legitimate traffic is incorrectly flagged and blocked as an attack."),
        ("False Negative Definition Check", "A False Negative occurs when an IPS fails to detect a real attack and allows the malicious packet to pass through to the target.", "A",
         "True. False negatives represent missed attacks that evade detection, passing through defenses unhindered."),
        ("Directional File Filtering", "Huawei firewalls allow File Filtering rules to be applied specifically to Uploads (outbound) or Downloads (inbound).", "A",
         "True. Directional controls enable separate policies for inbound malware prevention (downloads) and outbound data loss prevention (uploads)."),
        ("Single-Pass Architecture Parallelism", "Huawei's Single-Pass architecture evaluates packets in parallel across IPS, Antivirus, and URL filtering engines simultaneously in a single scan.", "A",
         "True. Single-pass inspection parses packet streams once and evaluates multiple threat engines in parallel, minimizing latency."),
        ("Hardware Bypass Fail-Open", "An external optical bypass switch allows traffic to pass uninterrupted across a physical link if the inline IPS firewall suffers a complete power loss.", "A",
         "True. Hardware bypass switches provide fail-open reliability, bridging physical links during power failures to ensure business continuity."),
        ("Display Logbuffer Threat Viewing", "The command `display logbuffer` can be used on a Huawei firewall to inspect recent security event logs and IPS signature alerts.", "A",
         "True. `display logbuffer` displays operational logs, including real-time threat detection alerts and security policy hits."),
        ("IPS Tuning Alert-Only Phase", "Best practice for deploying IPS in production networks involves running in Alert-only mode initially to detect false positives before switching to Block mode.", "A",
         "True. Running in Alert mode initially allows administrators to observe traffic, identify false positives, configure exceptions, and ensure business applications run smoothly before enforcing blocks.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 7,
            "chapter_title": "Firewall IPS",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch7_questions()
    print(f"Chapter 7 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
