# scripts/generate_ch5.py
"""
Generates Chapter 5 data: 42 Single Choice, 32 Multiple Choice, 30 True/False.
Chapter 5: Firewall NAT Technologies
"""
import json

def get_ch5_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 5 SINGLE CHOICE (42 questions)
    s_data = [
        ("NAT Purpose - Primary Driver", "What was the primary initial driver for the invention and widespread adoption of Network Address Translation (NAT)?",
         ["To increase the physical clock speed of network switches",
          "To mitigate the rapid exhaustion of the public IPv4 address space",
          "To eliminate the need for routing tables in wide area networks",
          "To encrypt all web traffic using SSL/TLS"], "B",
         "The rapid depletion of the 32-bit IPv4 address space was the primary catalyst for NAT, enabling multiple private internal hosts to share one or a few public IP addresses for Internet access."),
        ("NAT Classification - No-PAT", "In which type of Source NAT is only the private IP address translated to a public IP address from a pool, WITHOUT translating transport layer port numbers?",
         ["NAPT", "NAT No-PAT", "Easy IP", "Smart NAT"], "B",
         "NAT No-PAT (No Port Address Translation) performs 1-to-1 IP address translation without modifying source port numbers. The number of concurrent external connections is strictly limited to the number of public IPs in the address pool."),
        ("NAT No-PAT Concurrency Limit", "If an enterprise configures a NAT No-PAT address pool containing 5 public IPv4 addresses, how many internal hosts can concurrently access the Internet simultaneously?",
         ["5 hosts", "500 hosts", "65,535 hosts", "Unlimited hosts"], "A",
         "Because NAT No-PAT does not multiplex sessions using transport layer port numbers, each concurrent internal host requires a dedicated public IP address. Thus, 5 public IPs can support at most 5 concurrent hosts."),
        ("NAT Classification - NAPT", "Which Source NAT technology translates both the private IP address and the source port number into a public IP address and a unique public port number?",
         ["NAT No-PAT", "NAPT (Network Address Port Translation)", "NAT Server", "Static 1-to-1 NAT"], "B",
         "NAPT translates both source IP addresses and source port numbers. By mapping internal sockets (IP:Port) to public sockets, thousands of internal hosts can simultaneously share a single public IP address."),
        ("NAT Classification - Easy IP", "What is the defining characteristic of the Easy IP translation technology in Huawei firewalls?",
         ["It requires a pre-allocated pool of at least 16 public IP addresses",
          "It directly utilizes the public IP address configured on the firewall's egress interface for translation, eliminating the need for an address pool",
          "It translates destination IP addresses exclusively for database servers",
          "It disables stateful session table creation"], "B",
         "Easy IP is a specialized form of NAPT that uses the public IP address dynamically or statically assigned to the firewall's egress interface. It requires no address pool configuration, making it ideal for PPPoE dial-up or DHCP WAN connections."),
        ("Easy IP Ideal Deployment Scenario", "For which network environment is Easy IP predominantly recommended?",
         ["Data centers hosting 500 public-facing web servers",
          "Small office / home office (SOHO) or enterprise branch locations with dynamic WAN IP addresses obtained via PPPoE or DHCP",
          "Internal corporate subnets communicating with isolated DMZ servers",
          "Core ISP backbones routing BGP full tables"], "B",
         "Because SOHO and branch networks frequently obtain dynamic, changing public IP addresses from ISPs via DHCP or PPPoE, Easy IP automatically tracks the interface IP without requiring static address pool adjustments."),
        ("Smart NAT Operational Behavior", "How does Smart NAT operate on a Huawei firewall when the public IP address pool is under heavy load?",
         ["It drops all new incoming and outgoing packets immediately",
          "It initially performs 1-to-1 No-PAT translation; when pool addresses are exhausted, it uses a reserved public IP to perform NAPT for remaining hosts",
          "It reboots the firewall into recovery mode",
          "It converts all TCP sessions into unencrypted UDP broadcasts"], "B",
         "Smart NAT combines No-PAT and NAPT. High-priority or initial users receive dedicated 1-to-1 No-PAT translations from the pool. When available IPs run out, a designated reserved IP in the pool performs NAPT for all remaining hosts."),
        ("NAT Server Primary Function", "What is the primary function of the 'NAT Server' feature on a Huawei firewall?",
         ["To translate internal client source IPs when browsing external websites",
          "To statically map a public IP address and port to an internal server's private IP address and port, allowing Internet users to access intranet servers",
          "To provide automatic DHCP address leases to local PCs",
          "To act as an authoritative DNS root nameserver"], "B",
         "NAT Server (Destination NAT with port mapping) publishes intranet servers to the Internet. It maps public IP:Port combinations to private server IP:Port combinations, enabling external users to reach internal web, mail, or FTP servers."),
        ("NAT Server Table Generation", "Which forwarding table entry is automatically created when a 'NAT Server' rule is configured on a Huawei firewall?",
         ["A dynamic ARP table entry", "A static Server-Map table entry", "A BGP routing table entry", "An OSPF link-state advertisement"], "B",
         "Configuring a `nat server` rule automatically creates a permanent, static Server-Map table entry that stores the mapping between the public IP/port and private IP/port."),
        ("Bidirectional NAT - Scenario 1", "Which NAT technique simultaneously translates BOTH the source IP address and destination IP address of the same packet?",
         ["NAT No-PAT", "Easy IP", "Bidirectional NAT", "NAT ALG"], "C",
         "Bidirectional NAT performs Source NAT and Destination NAT concurrently on a single packet flow. It is essential when internal hosts access internal servers using the server's public IP (NAT hairpinning) or to prevent asymmetric routing."),
        ("NAT Hairpinning / Loopback Problem", "When an intranet client attempts to access an intranet server using the server's public IP address without Bidirectional NAT, why does the connection fail?",
         ["The server replies directly to the client's private IP, causing the client to discard the response due to socket address mismatch",
          "The firewall physically powers off its egress interface",
          "The DNS server refuses to resolve domain names ending in .com",
          "The Ethernet frame size exceeds 9000 bytes"], "A",
         "When Destination NAT translates the public IP to the server's private IP, the server receives a packet with the client's private source IP. The server replies directly via the local switch to the client's private IP. The client, expecting a reply from the public IP, drops the packet because the source socket does not match."),
        ("NAT Hairpinning Solution with SNAT", "How does Bidirectional NAT resolve the NAT hairpinning problem for intranet clients accessing intranet servers via public IP?",
         ["It translates the destination IP to the server's private IP AND translates the client's source IP to a firewall interface IP",
          "It forces all traffic to route across the public Internet to the ISP before returning",
          "It disables TCP checksum validation on the server",
          "It converts all HTTP requests to FTP downloads"], "A",
         "By applying Destination NAT (public server IP -> private server IP) and Source NAT (client private IP -> firewall IP), the server replies back to the firewall. The firewall reverses both translations and sends the reply to the client from the expected public IP."),
        ("NAT ALG - Multi-Channel Problem", "Why is standard NAT incapable of successfully translating multi-channel protocols like FTP active mode without an Application Level Gateway (ALG)?",
         ["FTP packets are encrypted using 4096-bit RSA keys",
          "Standard NAT translates only IP/port headers; it cannot inspect or modify IP addresses and port numbers embedded inside the application-layer payload (e.g. PORT commands)",
          "FTP cannot operate over IPv4 networks",
          "Standard NAT automatically deletes all files being transferred"], "B",
         "Standard NAT rewrites Layer 3 IP headers and Layer 4 TCP/UDP headers. In FTP active mode, the client transmits its private IP and data port as text inside the application-layer payload (`PORT h1,h2,h3,h4,p1,p2`). Without ALG, the server attempts to connect to the unreachable private IP."),
        ("NAT ALG Operational Mechanism", "What actions does a NAT ALG perform when inspecting an FTP active mode control connection?",
         ["It translates the private IP and port embedded inside the application payload to the public IP/port AND creates a dynamic Server-Map entry for the data connection",
          "It blocks the connection and alerts the domain administrator",
          "It converts the FTP transfer into an email attachment",
          "It forces the client to use Telnet instead"], "A",
         "NAT ALG parses the application payload, rewrites the embedded IP/port string to the corresponding public IP/port, and generates a dynamic Server-Map entry to allow the server's incoming data connection through the firewall."),
        ("NAT Blackhole Route Purpose", "What is the primary technical reason for configuring a NAT Blackhole Route (`ip route-static <pool-ip> 32 NULL0`) on a Huawei firewall?",
         ["To prevent routing loops between the firewall and upstream ISP gateway when packets arrive for unused addresses in the NAT pool",
          "To permanently delete all infected malware files",
          "To prevent internal users from accessing social media websites",
          "To test the maximum bandwidth throughput of the firewall backplane"], "A",
         "If public address pool IPs are not assigned to the firewall interface, an incoming packet destined to an idle pool IP is bounced between the upstream ISP router (which routes the pool to the firewall) and the firewall (which has a default route back to the ISP), creating an infinite routing loop. A blackhole route drops the packet immediately."),
        ("NAT Address Pool Configuration Command", "Which Huawei VRP CLI command creates an address pool for Source NAT?",
         ["nat address-group <group-number> <start-ip> <end-ip>", "ip pool <name>", "dhcp server ip-pool", "firewall nat-pool create"], "A",
         "In Huawei firewalls, the command `nat address-group <group-id> <start-ip> <end-ip>` (or in newer USG models `nat address-group <name>`) defines the pool of public IPv4 addresses available for translation."),
        ("NAT Policy Matching Sequence", "In what order are rules evaluated within a Huawei firewall's NAT Policy rulebase?",
         ["Alphabetical order by rule name",
          "Top-to-bottom sequential matching; the first matching rule is executed and matching terminates",
          "Bottom-to-top reverse matching",
          "Random selection based on CPU load"], "B",
         "Similar to security policies, NAT policies are evaluated sequentially from top to bottom. Once a packet matches a NAT rule's conditions, the translation action is executed and evaluation stops."),
        ("NAT Policy Action - No-NAT", "What is the purpose of configuring a NAT policy rule with the action 'no-nat' on a Huawei firewall?",
         ["To disable the firewall's routing engine",
          "To exempt specific traffic (such as branch-to-branch IPsec VPN traffic) from undergoing NAT translation",
          "To format the firewall's solid-state drive",
          "To force all traffic to be logged in cleartext"], "B",
         "When an enterprise establishes an IPsec tunnel between branches, traffic between internal private subnets must not be translated to public IPs. A high-priority 'no-nat' rule exempts VPN traffic from standard Internet Source NAT."),
        ("Destination NAT vs NAT Server", "How does general Destination NAT differ from NAT Server in Huawei firewall configuration?",
         ["NAT Server statically maps specific public ports to specific private servers, whereas general Destination NAT translates destination IPs to a pool of addresses (often with port preservation or load balancing)",
          "Destination NAT only works for IPv6 packets",
          "NAT Server works only when the firewall is powered off",
          "There is no difference; they are exact synonyms"], "A",
         "NAT Server provides 1-to-1 static port and IP mapping for publishing internal servers. General Destination NAT maps traffic destined for public IPs to an internal address pool, commonly utilized for server farm load balancing."),
        ("Port Overloading in NAPT", "Approximately how many concurrent translation sessions can theoretically be supported per public IPv4 address in NAPT?",
         ["Only 1 session", "Approximately 60,000 to 64,000 concurrent sessions (bounded by 16-bit transport port range)", "Exactly 256 sessions", "Unlimited sessions without memory usage"], "B",
         "Transport layer source ports are 16-bit integers (ports 1024 to 65535, minus reserved ports), allowing roughly 60,000 concurrent translated flows per transport protocol per public IP address."),
        ("NAT No-PAT Address Release", "In NAT No-PAT, when is a public IP address released back to the address pool for another internal host to use?",
         ["Never; once assigned, it is permanently locked to that host MAC",
          "When all session table entries for that internal host expire or age out",
          "Every 60 seconds regardless of active traffic",
          "Only when the firewall is manually rebooted"], "B",
         "In No-PAT, a public IP is allocated to an internal host and mapped in the Server-Map table. When all active connection sessions for that host terminate and the Server-Map aging timer expires, the public IP returns to the free pool."),
        ("NAT Multipool Use Case", "Why would an enterprise deploy NAT Multipool configuration on a border firewall?",
         ["To map different internal departments or user groups to distinct public IP address pools for traffic separation, auditing, and QoS",
          "To allow internal users to share identical MAC addresses",
          "To replace BGP routing across multiple ISPs",
          "To convert copper Ethernet interfaces into optical ports"], "A",
         "NAT Multipool allows an enterprise to direct traffic from different departments, guest Wi-Fi networks, or business units to separate public IP address pools, enabling granular billing, ISP policy routing, and security isolation."),
        ("NAT Session Table Display", "Which command displays the active NAT translation mappings and session details on a Huawei USG firewall?",
         ["display firewall session table verbose", "display ip interface brief", "display version", "display device"], "A",
         "Executing `display firewall session table verbose` displays detailed session records, including the original 5-tuple and the translated NAT 5-tuple (`-->` translation indicators)."),
        ("NAT Server Configuration Syntax", "In Huawei VRP CLI, which command correctly configures a static NAT Server rule publishing an internal web server?",
         ["nat server protocol tcp global 203.0.113.10 80 inside 192.168.1.100 80",
          "firewall web publish 203.0.113.10 to 192.168.1.100",
          "ip route-static 203.0.113.10 32 192.168.1.100",
          "nat address-group 1 203.0.113.10 192.168.1.100"], "A",
         "The standard Huawei VRP command syntax is: `nat server [zone <zone>] protocol tcp global <public-ip> <public-port> inside <private-ip> <private-port>`."),
        ("NAT ALG Enabled Protocols by Default", "On many Huawei firewalls, for which protocol is NAT ALG typically enabled by default due to its widespread operational necessity?",
         ["FTP", "BGP", "RIP", "OSPF"], "A",
         "FTP is the classic multi-channel protocol with ubiquitous enterprise usage; firewalls commonly have FTP ALG enabled by default (`firewall detect ftp`)."),
        ("Source IP vs Destination IP Translation", "When an internal host (192.168.1.10) browses an external website (93.184.216.34) through Source NAT (public IP 203.0.113.5), what does the packet header look like as it leaves the firewall's egress interface?",
         ["Source IP: 192.168.1.10, Destination IP: 203.0.113.5",
          "Source IP: 203.0.113.5, Destination IP: 93.184.216.34",
          "Source IP: 93.184.216.34, Destination IP: 192.168.1.10",
          "Source IP: 203.0.113.5, Destination IP: 192.168.1.10"], "B",
         "Source NAT replaces the private source IP (192.168.1.10) with the public IP (203.0.113.5). The destination IP remains the external web server's IP (93.184.216.34)."),
        ("Destination NAT Packet Header", "When an external client (198.51.100.25) accesses an internal web server published via NAT Server (public IP 203.0.113.10 -> private IP 192.168.1.100), what does the packet header look like after leaving the firewall towards the server?",
         ["Source IP: 198.51.100.25, Destination IP: 192.168.1.100",
          "Source IP: 203.0.113.10, Destination IP: 192.168.1.100",
          "Source IP: 192.168.1.100, Destination IP: 198.51.100.25",
          "Source IP: 198.51.100.25, Destination IP: 203.0.113.10"], "A",
         "NAT Server performs Destination NAT: the destination IP is translated from the public address (203.0.113.10) to the internal private address (192.168.1.100). The original client source IP (198.51.100.25) is preserved."),
        ("Bidirectional NAT Header Translation", "In Bidirectional NAT, after translation by the firewall, what happens to both Source and Destination IP fields?",
         ["Neither field is modified",
          "Both the Source IP and Destination IP addresses are rewritten to new values",
          "Only the TCP checksum is recalculated without IP changes",
          "The packet is converted to an unroutable broadcast frame"], "B",
         "In Bidirectional NAT, the firewall translates the Source IP (e.g., from client private IP to firewall interface IP) AND translates the Destination IP (from public server IP to private server IP) simultaneously."),
        ("Server-Map Entry for NAT No-PAT", "Why does NAT No-PAT generate a Server-Map entry upon the first packet translation?",
         ["To track the 1-to-1 mapping between the private host IP and assigned public pool IP, ensuring subsequent inbound or outbound packets from that host use the same public IP",
          "To permanently disable all firewall security policies for that host",
          "To record the user's keystrokes for forensic logging",
          "To translate the host's operating system language"], "A",
         "NAT No-PAT creates a dynamic Server-Map entry binding the host's private IP to the allocated public IP. This ensures all concurrent flows from that host share the identical public IP and permits incoming sessions if configured."),
        ("NAT Policy vs Security Policy Processing Order", "On a Huawei firewall processing an OUTBOUND packet from Trust to Untrust with Source NAT, what is the correct processing order between Security Policy and NAT Policy?",
         ["The packet is translated by NAT Policy first, and then matches Security Policy based on the translated public IP",
          "The packet matches Security Policy first based on its original private IP; if permitted, it is then processed by NAT Policy for source translation",
          "Security Policy and NAT Policy are evaluated by separate physical processors at the same time",
          "NAT Policy is evaluated only after the packet reaches the destination web server"], "B",
         "On outbound flows, the firewall first checks Security Policy against the original private source IP and destination IP. If traffic is permitted, the packet enters the NAT pipeline where Source NAT translates the source IP address."),
        ("Inbound Traffic Policy Processing Order", "When an external Internet user accesses an internal server published via NAT Server, what is the processing order between Destination NAT and Security Policy?",
         ["Security Policy is evaluated using the public IP; destination translation never occurs",
          "Destination NAT translation occurs first (or server-map matches), and the Security Policy is evaluated using the translated private IP address",
          "Security Policy is bypassed completely for all inbound traffic",
          "The packet is held in storage for 24 hours before inspection"], "B",
         "For inbound traffic targeting a NAT Server, destination translation (Server-Map matching) occurs before security policy evaluation. Therefore, the security policy rule permitting inbound traffic must specify the internal private IP address of the server as the destination!"),
        ("NAT Table Capacity Impact", "What impact does running heavy NAPT translation have on a firewall's hardware resources?",
         ["It has zero impact because translation is done on the client NIC",
          "It consumes CPU cycles for port allocation/checksum recalculation and memory for maintaining stateful session and NAT mapping tables",
          "It permanently damages the optical fiber transceivers",
          "It reduces the physical storage capacity of the hard drive"], "B",
         "NAPT requires tracking port states, rewriting IP/TCP/UDP headers, recalculating checksums, and managing session memory, imposing higher compute and memory overhead than stateless routing."),
        ("NAT IPsec Incompatibility (AH)", "Why is the IPsec Authentication Header (AH) protocol fundamentally incompatible with NAT?",
         ["AH uses 56-bit DES encryption",
          "AH calculates its cryptographic integrity check value (ICV) over the entire IP packet including the outer IP header; NAT alters IP addresses, causing AH integrity verification to fail",
          "AH operates only over dial-up telephone lines",
          "AH packets cannot be routed across Ethernet switches"], "B",
         "AH provides data integrity by hashing the entire packet, including IP source and destination addresses. When NAT translates an IP address, the receiver's computed hash fails to match the transmitted ICV, causing the packet to be dropped."),
        ("NAT Traversal (NAT-T) Solution", "How does NAT Traversal (NAT-T) resolve the problem of passing IPsec ESP traffic through a NAT router/firewall?",
         ["By converting the entire packet into cleartext HTTP",
          "By encapsulating the IPsec ESP packet inside a UDP header using port 4500, allowing NAT devices to translate ports normally",
          "By disabling encryption on the IPsec tunnel",
          "By forcing the NAT router to adopt an IPv6 address"], "B",
         "Because standard ESP lacks transport layer ports, NAPT devices cannot translate multiple ESP streams. NAT-T encapsulates ESP packets inside UDP datagrams using port 4500, enabling standard NAPT port translation and preserving encryption integrity."),
        ("NAT Address Group Mode - No-PAT Keyword", "In Huawei VRP CLI, which keyword is appended to the address group configuration to enforce 1-to-1 translation without port multiplexing?",
         ["pat", "no-pat", "easy-ip", "smart"], "B",
         "In Huawei firewall configuration, the keyword `no-pat` (e.g., `section 0 203.0.113.10 203.0.113.20 no-pat`) specifies that the address pool operates in No-PAT mode."),
        ("NAT Server 'no-reverse' Keyword", "What is the effect of configuring the `no-reverse` keyword in a Huawei `nat server` declaration?",
         ["It prevents the firewall from generating a reverse Server-Map entry, ensuring internal server outbound connections do not automatically use this public IP",
          "It disables the server's network adapter",
          "It blocks all inbound traffic to the server",
          "It reverses the polarity of the Ethernet cable"], "A",
         "By default, `nat server` creates forward and reverse mappings. When the internal server initiates outbound connections, it is translated to the public server IP. The `no-reverse` keyword disables reverse translation, allowing outbound server traffic to match general Internet NAT policies."),
        ("Dynamic NAT vs Static NAT", "What is the primary operational difference between Static NAT and Dynamic NAT?",
         ["Static NAT establishes a permanent, fixed 1-to-1 mapping between a private IP and public IP, whereas Dynamic NAT assigns public IPs dynamically from a pool on a first-come, first-served basis",
          "Static NAT only works during daytime hours",
          "Dynamic NAT requires unshielded twisted pair copper cabling",
          "Static NAT disables firewall routing capabilities"], "A",
         "Static NAT maps a specific private IP to a specific public IP permanently. Dynamic NAT draws public IPs dynamically from an address pool when active traffic arrives, releasing them when connections expire."),
        ("NAT Loopback Prevention", "Why is Bidirectional NAT commonly configured on the DMZ interface for internal users accessing intranet servers?",
         ["To ensure the internal server sends return packets back through the firewall rather than directly across the local switch to the client",
          "To force all traffic to be logged by the ISP",
          "To accelerate DNS resolution speed",
          "To convert TCP packets into SCTP format"], "A",
         "Translating the client's source IP to a firewall interface IP forces the server to return packets to the firewall. The firewall untranslates both source and destination IPs, ensuring the client receives return packets matching its original public destination IP."),
        ("Twice NAT Concept", "In industry terminology, what is 'Twice NAT' another name for?",
         ["Applying NAT twice in series across two separate firewalls",
          "Bidirectional NAT (translating both source and destination addresses on the same device simultaneously)",
          "Translating only the TCP sequence numbers",
          "Formatting the firewall configuration twice"], "B",
         "Twice NAT is standard industry terminology for Bidirectional NAT, where an appliance rewrites both the source and destination IP addresses of a single packet flow."),
        ("Display NAT Address Group Command", "Which command is used on a Huawei firewall to verify configured NAT address groups and their utilization?",
         ["display nat address-group", "display ip pool", "display current-nat", "display memory nat"], "A",
         "The command `display nat address-group` displays configured NAT address pools, start/end IP addresses, assigned modes (PAT or No-PAT), and current IP allocation status."),
        ("NAT ALG Supported Multi-Media Protocol", "Which of the following multimedia signaling protocols requires NAT ALG on firewalls to negotiate audio/video RTP streaming channels across NAT boundaries?",
         ["SIP (Session Initiation Protocol)", "SNMP", "NTP", "Syslog"], "A",
         "SIP embeds private IP addresses and dynamic RTP media ports inside its Session Description Protocol (SDP) payload. A SIP ALG translates these embedded addresses and creates Server-Map pinholes for the voice/video media streams."),
        ("Address Pool Overlap Warning", "What happens if an administrator configures a NAT address pool with an IP range that overlaps with the IP assigned to an active interface on the firewall?",
         ["The firewall will produce a configuration error or warning because overlapping IP assignments cause ARP and routing conflicts",
          "The firewall automatically doubles the interface speed to compensate",
          "All firewall interfaces are permanently disabled",
          "The firewall converts into a wireless access point"], "A",
         "Public address pool IPs must not conflict with interface IPs unless Easy IP is explicitly configured. Overlapping addresses cause IP conflicts and ARP broadcast anomalies.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 5,
            "chapter_title": "Firewall NAT Technologies",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 5 MULTIPLE CHOICE (32 questions)
    m_data = [
        ("Source NAT Flavors", "Which of the following are recognized forms of Source NAT supported on Huawei firewalls?",
         ["NAT No-PAT", "NAPT (Network Address Port Translation)", "Easy IP", "Smart NAT", "NAT Quad-Port"], "ABCD",
         "Huawei firewalls support four primary Source NAT modes: NAT No-PAT, NAPT, Easy IP, and Smart NAT. There is no 'NAT Quad-Port' specification."),
        ("NAPT Advantages", "What are the primary operational advantages of NAPT compared to NAT No-PAT?",
         ["Significantly higher public IP utilization efficiency",
          "Enabling thousands of internal hosts to share one or a few public IP addresses",
          "Lower public IP procurement and leasing costs from ISPs",
          "Complete elimination of transport layer port numbers"], "ABC",
         "NAPT multiplexes connections over port numbers, allowing thousands of hosts to share minimal public IPs, drastically reducing IP costs. Transport layer ports are retained and translated, not eliminated."),
        ("NAT Policy Matching Conditions", "Which of the following parameters can be configured as matching conditions in a Huawei NAT Policy rule?",
         ["Source Security Zone",
          "Destination Security Zone",
          "Source IP Address / Subnet / Address Set",
          "Destination IP Address / Subnet / Address Set",
          "Service Object (Protocol and Port)",
          "Hard drive serial number"], "ABCDE",
         "NAT policies match traffic based on: Source/Destination Zones, Source/Destination IPs, and Services (protocols/ports). Hardware serial numbers are not policy matching parameters."),
        ("NAT ALG Protocols", "Which of the following application protocols typically require NAT ALG support on firewalls due to embedded IP/port information in payloads?",
         ["FTP (File Transfer Protocol in active mode)",
          "SIP (Session Initiation Protocol for VoIP)",
          "RTSP (Real-Time Streaming Protocol)",
          "H.323 (Video conferencing protocol suite)",
          "Standard cleartext HTTP GET requests"], "ABCD",
         "Multi-channel protocols embedding IP addresses/ports in payloads require ALG: FTP, SIP, RTSP, H.323, and DNS. Standard HTTP GET requests do not embed Layer 3/4 socket parameters in payloads."),
        ("NAT Server Key Parameters", "When configuring a static `nat server` rule on a Huawei firewall, which parameters are typically specified?",
         ["Global (Public) IP Address",
          "Global (Public) Port Number",
          "Inside (Private) Server IP Address",
          "Inside (Private) Server Port Number",
          "Protocol (e.g., TCP or UDP)"], "ABCDE",
         "A complete `nat server` definition specifies: Protocol (TCP/UDP), Global (public) IP and port, and Inside (private) IP and port."),
        ("NAT Blackhole Route Characteristics", "Which of the following statements regarding NAT Blackhole Routes on Huawei firewalls are correct?",
         ["A blackhole route points traffic destined for the NAT address pool to a NULL0 virtual interface",
          "It prevents routing loops between the firewall and the upstream router for idle/unassigned pool IPs",
          "It is required when the public address pool is on a different subnet than the firewall's egress interface",
          "It permanently disables all Internet access for internal users"], "ABC",
         "A blackhole route (`ip route-static <pool-ip> 32 NULL0`) drops traffic destined to unused pool IPs, breaking routing loops between the firewall and ISP gateway. It does not disable Internet access."),
        ("Server-Map Entry Characteristics", "Which of the following statements regarding Server-Map entries on Huawei firewalls are true?",
         ["Static Server-Map entries are generated by NAT Server and remain active until deleted",
          "Dynamic Server-Map entries are generated by ASPF or NAT No-PAT and have expiration timers",
          "A Server-Map entry acts as an authorized temporary pinhole for subsequent traffic matching",
          "Server-Map entries replace the firewall's OSPF link-state database"], "ABC",
         "Server-Map entries provide pre-allocated forwarding pinholes. NAT Server generates permanent static entries; ASPF and No-PAT generate temporary dynamic entries with aging timers."),
        ("Easy IP Characteristics", "Which of the following statements accurately describe Easy IP?",
         ["It is a specialized implementation of NAPT",
          "It uses the public IP address of the egress interface directly without creating an address group",
          "It is particularly suited for dynamic WAN links using PPPoE or DHCP",
          "It requires an enterprise to purchase a /24 public IPv4 address block"], "ABC",
         "Easy IP multiplexes traffic over the egress interface's IP address directly, requiring no address pool, making it optimal for dynamic dial-up/DHCP WAN connections."),
        ("Bidirectional NAT Scenarios", "In which of the following scenarios is Bidirectional NAT commonly deployed on enterprise firewalls?",
         ["Intranet users accessing intranet servers using the server's public IP address (NAT Hairpinning)",
          "Preventing asymmetric routing when external users access internal servers through complex multi-homed topologies",
          "Allowing internal servers to communicate with isolated legacy subnets requiring overlapping IP translation",
          "Broadcasting high-definition television signals over Wi-Fi"], "ABC",
         "Bidirectional NAT resolves NAT loopback (hairpinning), prevents asymmetric routing in multi-ISP server hosting, and translates overlapping private subnets."),
        ("NAT Address Group Modes", "When defining an address group (`nat address-group`) in Huawei VRP, which operational modes can be assigned?",
         ["PAT mode (default port address translation enabled)",
          "No-PAT mode (port address translation disabled, 1-to-1 IP translation)",
          "Unencrypted mode (disabling all security features)",
          "Transparent mode (operating as a bridge)"], "AB",
         "Address groups operate either in PAT mode (default, port multiplexing enabled) or No-PAT mode (port multiplexing disabled via the `no-pat` keyword)."),
        ("NAT IPsec Traversal Issues", "Why does standard NAT cause problems for traditional IPsec VPN tunnels without NAT-T?",
         ["AH validates outer IP headers, causing integrity checks to fail when NAT modifies the IP address",
          "ESP packets lack Layer 4 TCP/UDP port headers, preventing standard NAPT devices from multiplexing multiple tunnels over a single public IP",
          "IKE Phase 1 Main Mode identity validation can fail if pre-shared keys are bound to private IP identities",
          "IPsec packets are physically blocked by standard copper Ethernet cables"], "ABC",
         "NAT breaks AH integrity (IP header hash mismatch), prevents NAPT port multiplexing for portless ESP, and complicates IKE aggressive/main mode identity matching behind NAT."),
        ("NAT-T Operational Mechanisms", "How does NAT-T (NAT Traversal) resolve IPsec NAT compatibility issues?",
         ["It encapsulates IPsec ESP packets inside UDP datagrams using port 4500",
          "It automatically detects the presence of NAT devices during IKE Phase 1 negotiation",
          "It allows NAPT devices to translate the outer UDP port 4500 header normally",
          "It disables encryption on the IPsec tunnel to reduce packet size"], "ABC",
         "NAT-T detects NAT during IKE Phase 1 and encapsulates ESP into UDP port 4500, allowing NAPT devices to translate the port header without corrupting the encrypted payload."),
        ("Benefits of Private IP Addressing", "What benefits are achieved by using RFC 1918 private IPv4 addressing combined with NAT?",
         ["Conservation of scarce, expensive public IPv4 addresses",
          "Internal network topology hiding from external reconnaissance",
          "Flexibility to design internal IP addressing schemas without coordinating with ISPs",
          "Guaranteed 100% immunity from all email phishing attacks"], "ABC",
         "Private addressing conserves public IPs, obscures internal network topology from external port scanners, and gives administrators complete addressing freedom. It does not stop phishing."),
        ("Smart NAT Architecture", "Which of the following components comprise the operational architecture of Smart NAT?",
         ["A primary address pool used for 1-to-1 No-PAT translation",
          "A designated reserved public IP address within the pool used for NAPT translation when the primary pool is exhausted",
          "Automatic fallback to NAPT to prevent connection drops for subsequent users",
          "A mandatory requirement to reboot the firewall every hour"], "ABC",
         "Smart NAT uses a dual-tier approach: No-PAT for initial connections, with automatic fallback to NAPT using a reserved pool IP when pool addresses are exhausted."),
        ("NAT Inbound Policy Order", "When an external packet arrives destined to a NAT Server on a Huawei firewall, which sequence of inspection occurs?",
         ["The firewall matches the packet against the Server-Map table to determine the internal private destination IP",
          "The firewall matches the Security Policy using the translated private destination IP",
          "If permitted by Security Policy, a session entry is created and the packet is routed to the server",
          "The firewall converts the packet into an ICMP Echo Request"], "ABC",
         "Inbound NAT Server processing: 1. Server-Map lookup rewrites destination IP/port; 2. Security policy evaluates the translated private IP; 3. If allowed, a session entry is created and the packet is forwarded."),
        ("NAT Session Entry Information", "In `display firewall session table verbose`, which fields indicate that NAT was applied to a connection?",
         ["The original 5-tuple (Source IP, Destination IP, Protocol, Source Port, Destination Port)",
          "The translated 5-tuple indicated by translation arrows (`-->`)",
          "Zone and interface transition records",
          "The serial number of the client computer monitor"], "ABC",
         "The verbose session output details the pre-NAT 5-tuple, the post-NAT 5-tuple (indicated by `-->`), ingress/egress interfaces, zone IDs, and translation flags."),
        ("Reasons to Exclude Traffic from NAT (No-NAT)", "For which of the following traffic types is a 'no-nat' policy rule typically configured?",
         ["Site-to-Site IPsec VPN traffic between branch offices",
          "Internal management traffic between the Trust zone and Local zone",
          "Traffic between internal VLANs routed across the firewall",
          "General web browsing to external public Internet search engines"], "ABC",
         "IPsec VPN traffic, firewall management flows, and inter-VLAN routing require original private IPs to be preserved and are exempted from NAT using 'no-nat' rules. Public Internet traffic requires NAT."),
        ("NAT Multipool Deployment Factors", "Which criteria can be used in Huawei NAT policies to steer traffic to different NAT address groups?",
         ["Source IP Subnet (e.g. Sales subnet vs R&D subnet)",
          "Source Security Zone (e.g. Guest Wi-Fi vs Corporate Trust)",
          "Destination IP Subnet or Service Port",
          "User or User Group identity authenticated via AAA",
          "Physical room temperature in the server room"], "ABCD",
         "Huawei NAT policies steer traffic to distinct address pools based on source/dest zones, IP subnets, services, and authenticated user/group identities."),
        ("NAT Troubleshooting Commands", "Which of the following CLI commands are useful for troubleshooting NAT operations on Huawei USG firewalls?",
         ["`display nat-policy all`",
          "`display nat address-group`",
          "`display firewall server-map`",
          "`display firewall session table verbose`",
          "`reset saved-configuration`"], "ABCD",
         "NAT diagnostics utilize `display nat-policy`, `display nat address-group`, `display firewall server-map`, and `display firewall session table verbose`. `reset saved-configuration` erases system configs."),
        ("NAT ALG FTP Commands Modified", "In FTP active mode, which application-layer commands are inspected and rewritten by an FTP NAT ALG?",
         ["PORT command (specifying client IP and listening data port)",
          "EPRT command (extended port command in IPv6/IPv4)",
          "PASV / EPSV response commands (specifying server data port)",
          "USER and PASS authentication commands"], "ABC",
         "FTP ALG inspects and translates socket parameters in PORT, EPRT, PASV, and EPSV commands/replies. USER and PASS contain login credentials and are not rewritten by ALG."),
        ("Static 1-to-1 NAT Characteristics", "Which of the following are true regarding Static 1-to-1 NAT?",
         ["One private IP address is permanently mapped to one public IP address",
          "Port numbers are not translated",
          "Communication can be initiated bidirectionally (both inbound and outbound)",
          "It multiplexes 10,000 internal hosts onto one public IP"], "ABC",
         "Static 1-to-1 NAT maps a single private IP to a single public IP permanently without port translation, enabling bidirectional session initiation. It does not perform port multiplexing."),
        ("Destination NAT Use Cases", "Which of the following represent common use cases for Destination NAT?",
         ["Publishing internal enterprise web, mail, and DNS servers to the Internet",
          "Server load balancing (distributing external requests across internal server farms)",
          "Port redirection (e.g., exposing an internal server on external port 8080 while internal port is 80)",
          "Translating client source IP addresses when browsing external websites"], "ABC",
         "Destination NAT publishes internal servers, redirects ports, and load-balances incoming traffic across server clusters. Translating client source IPs is the role of Source NAT."),
        ("NAT Hairpinning Required Rules", "To successfully implement NAT Hairpinning for intranet users accessing an intranet server via public IP, which two policies/rules are needed on the firewall?",
         ["A Destination NAT / NAT Server rule mapping the public IP to the server's private IP",
          "A Source NAT rule translating the intranet client's IP to the firewall's interface IP for traffic destined to the server's private IP",
          "A rule that permanently blocks all ICMP echo requests",
          "A rule that converts Ethernet frames into Frame Relay"], "AB",
         "NAT hairpinning requires Destination NAT (translating the public server IP to private server IP) AND Source NAT (translating client private IP to firewall IP) so server replies return through the firewall."),
        ("NAT Table Memory Management", "How does a Huawei firewall prevent NAT table resource exhaustion?",
         ["Enforcing aging timers on session and server-map entries",
          "Setting maximum concurrent connection limits per source IP address",
          "Supporting NAPT port reuse algorithms",
          "Disabling all IP routing protocols during peak hours"], "ABC",
         "Firewalls manage NAT memory through session aging timers, per-IP connection rate/session limits, and efficient port allocation/reuse. Routing protocols are not disabled."),
        ("NAT Server Multi-Port Publishing", "Which configurations allow publishing multiple distinct internal servers using a SINGLE public IPv4 address?",
         ["Mapping public port 80 to Web Server A (192.168.1.10:80)",
          "Mapping public port 443 to Secure Web Server B (192.168.1.20:443)",
          "Mapping public port 25 to Mail Server C (192.168.1.30:25)",
          "Mapping public port 80 to all 50 internal servers simultaneously without port distinction"], "ABC",
         "Using port-based NAT Server (PAT), an administrator maps distinct public port numbers on a single public IP to different internal server private IPs and ports."),
        ("Address Translation Security Side-Effects", "What positive security side-effects are introduced by deploying Source NAT?",
         ["Internal private IP addressing structure is completely obscured from external networks",
          "External Internet hosts cannot directly initiate unsolicited connections to internal client PCs",
          "It helps protect internal hosts against direct IP-based vulnerability scanning",
          "It eliminates the need for host-level antivirus software"], "ABC",
         "Source NAT hides internal IP addressing and prevents direct inbound external connection attempts to client workstations. Endpoint antivirus is still required for defense."),
        ("NAT No-PAT Server-Map Type", "What type of Server-Map entry is generated by NAT No-PAT?",
         ["A dynamic Server-Map entry recording the private-to-public IP binding",
          "It has a configurable aging timer that expires after host sessions end",
          "A permanent static routing table entry in the RIB",
          "A physical hardware interrupt on the motherboard"], "AB",
         "NAT No-PAT generates dynamic Server-Map entries linking private host IPs to allocated public IPs. These entries age out once all sessions associated with that host expire."),
        ("Easy IP vs NAPT Pool Comparison", "What are the primary differences between Easy IP and standard NAPT using an address pool?",
         ["Easy IP uses the egress interface IP directly; standard NAPT uses an address group pool",
          "Easy IP requires no address pool configuration commands",
          "Easy IP adapts automatically if the egress interface IP changes dynamically via DHCP/PPPoE",
          "Easy IP cannot translate TCP connections"], "ABC",
         "Easy IP translates to the egress interface IP automatically without an address group, adapting seamlessly to dynamic IP changes. Both Easy IP and standard NAPT translate TCP and UDP flows."),
        ("NAT Policy Actions Available", "Which of the following actions can be configured within a Huawei firewall NAT Policy rule?",
         ["Source NAT (using an address group or Easy IP)",
          "No-NAT (exempting matching traffic from translation)",
          "Reboot (restarting the firewall upon match)",
          "Format (erasing system storage)"], "AB",
         "The standard actions in a NAT Policy rule are 'Source NAT' (specifying an address group or Easy IP) and 'No-NAT' (exempting traffic from translation)."),
        ("NAT Blackhole Route Creation Command", "Which Huawei VRP command syntax creates a 32-bit blackhole route for a public NAT pool IP?",
         ["`ip route-static 203.0.113.5 255.255.255.255 NULL0`",
          "`ip route-static 203.0.113.5 32 NULL0`",
          "`nat blackhole create 203.0.113.5`",
          "`undo ip route-static 203.0.113.5`"], "AB",
         "In Huawei VRP, a blackhole route is created using standard static routing pointing to the NULL0 interface: `ip route-static <ip> 32 NULL0` or with mask `255.255.255.255 NULL0`."),
        ("NAT Impact on End-to-End Principle", "Why is traditional NAT sometimes criticized in fundamental Internet architecture discussions?",
         ["It violates the original end-to-end connectivity model of the Internet",
          "It complicates peer-to-peer (P2P) communications and VoIP call establishment",
          "It breaks protocols that carry IP addresses inside their application payloads unless ALGs are deployed",
          "It requires all routers on the Internet to be manufactured by the same vendor"], "ABC",
         "NAT breaks the pure end-to-end principle where any two Internet nodes can directly address each other, complicating P2P, VoIP (SIP), and protocols with embedded IP addresses without ALGs."),
        ("Multi-homed Multi-ISP NAT Design", "In an enterprise multi-homed to ISP1 and ISP2, how should NAT policies be structured?",
         ["Configure separate NAT policies translating traffic egressing towards ISP1 to ISP1's public address pool",
          "Configure separate NAT policies translating traffic egressing towards ISP2 to ISP2's public address pool",
          "Translate all traffic to ISP1's public IP even when forwarding out through ISP2's interface",
          "Disable all routing protocols completely"], "AB",
         "In multi-ISP setups, egress traffic must be translated to the public address pool belonging to that specific ISP; otherwise, the ISP's ingress anti-spoofing filters (uRPF) will drop the packets.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 5,
            "chapter_title": "Firewall NAT Technologies",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 5 TRUE/FALSE (30 questions)
    tf_data = [
        ("NAT No-PAT Port Multiplexing", "NAT No-PAT translates transport layer port numbers to allow multiple internal hosts to share a single public IP address.", "B",
         "False. NAT No-PAT does NOT translate port numbers; it performs 1-to-1 IP translation without port multiplexing."),
        ("NAPT Port Multiplexing", "NAPT translates both IP addresses and transport layer port numbers, enabling thousands of hosts to share a single public IP address.", "A",
         "True. NAPT (Network Address Port Translation) multiplexes connections over TCP/UDP ports, maximizing public IP utilization."),
        ("Easy IP Address Pool", "Easy IP requires the administrator to manually configure a dedicated address group containing at least two public IP addresses.", "B",
         "False. Easy IP uses the public IP address configured directly on the firewall's egress interface, requiring no address group pool."),
        ("Smart NAT Fallback", "Smart NAT operates in No-PAT mode initially and automatically falls back to NAPT using a reserved IP when public pool addresses are exhausted.", "A",
         "True. Smart NAT combines No-PAT and NAPT, using a designated reserved IP to perform NAPT for subsequent connections when pool IPs are depleted."),
        ("NAT Server Inbound Publishing", "The NAT Server feature is used to publish internal intranet servers so that external Internet users can access them.", "A",
         "True. NAT Server maps public IP addresses and ports to private server addresses and ports, enabling inbound Internet access to internal services."),
        ("Static Server-Map Generation", "Configuring a `nat server` rule on a Huawei firewall automatically generates a static Server-Map table entry.", "A",
         "True. `nat server` creates a permanent, static Server-Map entry that defines the translation between public and private socket parameters."),
        ("Bidirectional NAT Definition", "Bidirectional NAT translates both the Source IP address and the Destination IP address of the same packet simultaneously.", "A",
         "True. Bidirectional NAT applies Source NAT and Destination NAT concurrently on the same packet flow."),
        ("NAT Hairpinning Issue", "Without Source NAT, intranet clients accessing intranet servers via public IP addresses experience connection failures because server replies bypass the firewall.", "A",
         "True. The server replies directly to the client's private IP across the local switch; the client drops the packet because it expects a reply from the public IP."),
        ("NAT ALG Payload Inspection", "NAT ALG is required for multi-channel protocols like FTP active mode because standard NAT does not inspect or translate IP addresses embedded inside application payloads.", "A",
         "True. Standard NAT rewrites only L3/L4 headers. ALG inspects application payloads (e.g. PORT commands) and rewrites embedded IP/port information."),
        ("NAT Blackhole Route Function", "A NAT blackhole route prevents routing loops between the firewall and upstream routers for unused IP addresses in a NAT address pool.", "A",
         "True. Pointing unused pool IPs to NULL0 terminates unassigned traffic at the firewall, preventing routing loops with the ISP gateway."),
        ("No-NAT Policy Use Case", "A 'no-nat' policy rule is commonly used to exempt site-to-site IPsec VPN traffic from undergoing Internet Source NAT.", "A",
         "True. VPN traffic between branch private subnets must preserve original private IP addresses and must not be translated by Internet Source NAT."),
        ("Inbound Security Policy Matching IP", "When external traffic accesses a server published via NAT Server, the security policy must permit traffic using the server's private IP address.", "A",
         "True. Because destination translation occurs before security policy evaluation, the security policy rule must match the server's translated private IP address."),
        ("Outbound Security Policy Matching IP", "When internal clients access the Internet via Source NAT, the security policy evaluates traffic using the translated public IP address.", "B",
         "False. On outbound traffic, the security policy is evaluated against the original private source IP before Source NAT rewrites the packet header."),
        ("NAT Table Capacity Unlimited", "A firewall's NAPT translation table has unlimited capacity and can support an infinite number of simultaneous connections.", "B",
         "False. NAT table capacity is bounded by firewall memory and available 16-bit transport layer port numbers (~60,000 ports per public IP)."),
        ("AH Incompatibility with NAT", "The IPsec Authentication Header (AH) protocol operates seamlessly across standard NAT devices without any issues.", "B",
         "False. AH integrity checks include the outer IP header. When NAT modifies the IP address, the AH checksum verification fails, causing the packet to be dropped."),
        ("NAT-T UDP Port 4500", "NAT Traversal (NAT-T) encapsulates IPsec ESP packets inside UDP datagrams using port 4500 to traverse NAT devices.", "A",
         "True. NAT-T encapsulates ESP into UDP port 4500, enabling standard NAPT devices to translate the port header without corrupting the IPsec payload."),
        ("Dynamic Server-Map Expiration", "Dynamic Server-Map entries generated by ASPF or NAT No-PAT expire and are deleted automatically when their aging timer elapses.", "A",
         "True. Dynamic Server-Map entries are temporary pinholes with aging timers, unlike static Server-Map entries generated by NAT Server."),
        ("NAT Address Pool Subnet Requirement", "A NAT address group must always reside on the exact same IP subnet as the firewall's egress interface.", "B",
         "False. Address pools can reside on different subnets, provided upstream routers route the pool prefix to the firewall and blackhole routes are configured."),
        ("Display Server-Map Command", "The command `display firewall server-map` displays active static and dynamic Server-Map entries on a Huawei firewall.", "A",
         "True. `display firewall server-map` is the standard VRP command to inspect active Server-Map entries."),
        ("Easy IP for Dynamic PPPoE", "Easy IP is especially suitable for WAN connections where the public IP address is dynamically assigned via PPPoE or DHCP.", "A",
         "True. Easy IP dynamically tracks the IP address of the egress interface, eliminating the need to update address pools when WAN IPs change."),
        ("Multiple Servers on One Public IP", "An enterprise can publish both a Web server (port 80) and a Mail server (port 25) on the same public IP address using port-based NAT Server.", "A",
         "True. By mapping distinct public port numbers on the same public IP, multiple internal servers can be published simultaneously."),
        ("NAT Policy First Match Rule", "Huawei NAT policy rules are evaluated from bottom to top, prioritizing the default rule.", "B",
         "False. NAT policies are evaluated sequentially from top to bottom, stopping at the first matching rule."),
        ("Static 1-to-1 NAT Port Mapping", "Static 1-to-1 NAT allows multiple internal hosts to share one public IP address by translating port numbers.", "B",
         "False. Static 1-to-1 NAT maps one private IP to one public IP without port translation; it does not multiplex multiple hosts."),
        ("NAT No-PAT Host Tracking", "In NAT No-PAT, once a public IP is allocated to an internal host, other hosts cannot use that public IP until all sessions of the first host terminate.", "A",
         "True. No-PAT allocates the entire public IP exclusively to one host at a time because port multiplexing is disabled."),
        ("SIP Protocol and NAT", "SIP VoIP traffic requires NAT ALG on firewalls because SIP embeds private IP addresses and dynamic RTP media ports inside its message payload.", "A",
         "True. SIP SDP payloads carry private IP and port parameters; without SIP ALG, voice/video RTP streams fail to establish across NAT."),
        ("Twice NAT Source and Dest", "Twice NAT is another term for Bidirectional NAT, where both source and destination addresses are translated simultaneously.", "A",
         "True. 'Twice NAT' and 'Bidirectional NAT' are synonymous terms in network security engineering."),
        ("NAT Prevents External Inbound", "By default, Source NAT prevents external Internet hosts from initiating unsolicited connections directly to internal client PCs.", "A",
         "True. External hosts cannot initiate connections to private internal IPs unless explicit inbound port mappings (NAT Server) or pinholes exist."),
        ("Blackhole Route Next-Hop Interface", "A NAT blackhole route uses the NULL0 virtual interface as its next hop to silently discard matching packets.", "A",
         "True. Routes pointing to interface NULL0 discard packets immediately without generating ICMP error replies or forwarding loops."),
        ("NAT Overlapping Address Pools", "Assigning overlapping IP address ranges to two distinct NAT address groups is recommended as best practice.", "B",
         "False. Overlapping pools cause address allocation conflicts, routing ambiguity, and unpredictable translation behavior."),
        ("Verbose Session Table NAT Indicator", "In the output of `display firewall session table verbose`, the symbol `-->` indicates the post-NAT translated socket information.", "A",
         "True. Huawei firewalls use the arrow notation `-->` in verbose session displays to show original vs translated IP addresses and port numbers.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 5,
            "chapter_title": "Firewall NAT Technologies",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch5_questions()
    print(f"Chapter 5 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
