# scripts/generate_ch3.py
"""
Generates Chapter 3 data: 36 Single Choice, 28 Multiple Choice, 26 True/False.
Chapter 3: Common Network Security Threats and Threat Prevention
"""
import json

def get_ch3_questions():
    single = []
    multi = []
    tf = []

    # CHAPTER 3 SINGLE CHOICE (36 questions)
    s_data = [
        ("Malware Classification - Virus", "Which type of malicious software attaches its code to legitimate executable files and requires user interaction (such as launching the infected program) to replicate?",
         ["Worm", "Computer Virus", "Trojan Horse", "Spyware"], "B",
         "A computer virus requires a host program or file and relies on human execution of the infected host to spread to other files or systems."),
        ("Malware Classification - Worm", "Which malware family is characterized as a self-replicating standalone program that autonomously propagates across computer networks by exploiting operating system vulnerabilities without requiring host files?",
         ["Computer Virus", "Computer Worm", "Logic Bomb", "Rootkit"], "B",
         "A worm is an independent standalone program that replicates automatically over network connections by exploiting software flaws, propagating rapidly without human intervention or host files (e.g., Code Red, SQL Slammer)."),
        ("Malware Classification - Trojan Horse", "A program masquerading as a legitimate system optimization utility that secretly opens an unauthorized remote access backdoor for an external attacker is classified as a:",
         ["Trojan Horse", "Worm", "Macro Virus", "Boot Sector Virus"], "A",
         "A Trojan horse disguises itself as useful, legitimate software while concealing malicious functionality, such as opening backdoors or exfiltrating data. Unlike viruses and worms, Trojans do not self-replicate."),
        ("Ransomware Encryption Method", "Modern ransomware families commonly employ which cryptographic approach to lock a victim's files before demanding cryptocurrency?",
         ["Rot13 substitution cipher",
          "Hybrid encryption using strong symmetric ciphers (e.g., AES-256) for file encryption and asymmetric ciphers (e.g., RSA-2048) to protect the key",
          "One-way MD5 hashing of user documents",
          "Cleartext base64 obfuscation without keys"], "B",
         "Ransomware employs hybrid encryption: high-speed symmetric algorithms (AES) encrypt local files, and an asymmetric public key encrypts the AES key, ensuring that only the attacker possessing the private key can decrypt the data."),
        ("Rootkit Capability", "What is the primary distinguishing feature of a Rootkit in malware operations?",
         ["Displaying continuous pop-up advertisements in web browsers",
          "Subverting operating system kernel APIs to hide malicious processes, files, registry keys, and network connections from detection",
          "Overheating the computer power supply unit through electrical resonance",
          "Reformatting hard drives immediately upon insertion of a USB drive"], "B",
         "Rootkits operate at deep operating system layers (kernel/hypervisor), hooking system calls and data structures to conceal their presence, active processes, files, and backdoors from antivirus tools and administrators."),
        ("Botnet Command and Control", "In a botnet architecture, how does the botmaster coordinate and transmit commands to thousands of compromised zombie devices?",
         ["By sending physical letters to each device owner",
          "Via Command and Control (C2) communication channels using protocols such as IRC, HTTP/HTTPS, DNS, or P2P",
          "Through manual console logins at each individual workstation",
          "Using standard broadcast television frequencies"], "B",
         "Botnets rely on centralized or distributed Command and Control (C2) servers communicating over standard protocols (HTTP/HTTPS, IRC, DNS tunneling, P2P) to issue synchronized instructions to zombies for DDoS attacks or spam campaigns."),
        ("Reconnaissance - Ping Sweep", "What is the primary objective of an attacker conducting an ICMP ping sweep across an enterprise IP subnet?",
         ["To crack the administrator's domain password",
          "To identify live, responsive host IP addresses across the target network range",
          "To exhaust the firewall's physical flash storage",
          "To modify the DNS records on the authoritative nameserver"], "B",
         "A ping sweep transmits ICMP Echo Requests across a range of sequential IP addresses to map out which IP addresses correspond to active, online systems based on receiving ICMP Echo Replies."),
        ("Port Scanning - TCP SYN Scan", "Why is a TCP SYN scan (half-open scan) frequently referred to as a 'stealth scan' compared to a full TCP Connect scan?",
         ["It operates entirely without transmitting any IP packets",
          "It terminates the handshake with an RST segment after receiving SYN-ACK, avoiding the creation of an established connection in server application logs",
          "It encrypts the TCP header using quantum cryptography",
          "It forces the destination server to power down before logging occurs"], "B",
         "In a SYN scan, the scanner sends a SYN. If the target responds with SYN-ACK (indicating an open port), the scanner immediately responds with an RST rather than completing the 3-way handshake, avoiding session establishment and logging by legacy application daemons."),
        ("Port Scanning - TCP Connect Scan", "Which of the following describes the operation of a TCP Connect scan on a target port?",
         ["It relies on specialized kernel drivers to send malformed TCP packets",
          "It completes the entire TCP 3-way handshake (SYN, SYN-ACK, ACK) using standard operating system socket system calls",
          "It transmits only ICMP Echo packets to high UDP ports",
          "It leaves target ports permanently frozen in the LISTEN state"], "B",
         "A TCP Connect scan uses standard operating system network APIs (`connect()`) to complete the full 3-way handshake. Because an established connection is formed, it is easily detected and recorded in server application access logs."),
        ("Port Scanning - UDP Scan", "How does an attacker determine that a target UDP port is closed during a UDP port scan?",
         ["The target returns a TCP RST segment",
          "The target replies with an ICMP Port Unreachable message (Type 3, Code 3)",
          "The target sends an ARP Reply frame with an all-zero MAC address",
          "The target transmits a DHCP NAK packet"], "B",
         "According to RFC 792, if a host receives a UDP datagram addressed to a closed port, it responds with an ICMP Type 3, Code 3 (Destination Unreachable: Port Unreachable) error message."),
        ("Sniffing - Promiscuous Mode", "What occurs when a network interface card (NIC) is configured into 'promiscuous mode'?",
         ["The NIC refuses to transmit any outbound packets",
          "The NIC captures and passes all received frames to the OS, regardless of destination MAC address",
          "The NIC automatically encrypts all Ethernet traffic using AES-GCM",
          "The NIC disables its physical transceiver to save power"], "B",
         "Normally, a NIC discards frames whose destination MAC does not match its own MAC, broadcast, or joined multicast groups. In promiscuous mode, the NIC captures and forwards every frame on the physical wire to packet analysis software."),
        ("Sniffing - MAC Flooding Attack", "What is the operational goal of an attacker executing a MAC flooding (CAM table overflow) attack against a Layer 2 switch?",
         ["To crack the switch's console enable password",
          "To exhaust the switch's MAC address table memory, forcing the switch to flood unknown unicast frames out all ports like a hub",
          "To permanently burn the switch's ASIC microchips",
          "To force all connected PCs to reboot into safe mode"], "B",
         "Switches forward frames based on MAC tables. By flooding the switch with thousands of bogus source MACs, the CAM table fills up completely. When the table overflows, the switch defaults to broadcast flooding for all incoming unicast frames, allowing the attacker to sniff traffic from other ports."),
        ("ARP Spoofing Mechanism", "In an ARP spoofing (cache poisoning) attack, what deceptive information does the attacker broadcast or unicast to victim hosts?",
         ["The attacker claims that all DNS queries should be sent over Telnet",
          "The attacker associates its own MAC address with the IP address of the default gateway",
          "The attacker changes the physical serial number of the target router",
          "The attacker advertises an invalid BGP autonomous system number"], "B",
         "In ARP cache poisoning, the attacker transmits gratuitous or forged ARP replies informing victims that the default gateway's IP address maps to the attacker's MAC address, diverting outbound traffic through the attacker's machine for Man-in-the-Middle interception."),
        ("DHCP Starvation Attack", "What is the primary mechanism of a DHCP Starvation attack?",
         ["Flooding the DHCP server with malformed ICMP ping packets",
          "Broadcasting thousands of DHCP requests with spoofed, randomized MAC addresses to exhaust the available IP address pool",
          "Modifying the physical lease file on the DHCP server hard drive",
          "Encrypting the server's network card firmware using ransomware"], "B",
         "A DHCP Starvation attack floods the DHCP server with continuous DHCP Discover/Request messages, each using a distinct randomized MAC address. The server assigns all available pool leases to bogus MACs, denying IP addresses to legitimate incoming clients."),
        ("Rogue DHCP Server Attack", "What threat does an unauthorized 'Rogue DHCP Server' introduce into a corporate LAN segment?",
         ["It causes physical short circuits across Ethernet cables",
          "It assigns malicious default gateway and rogue DNS server IP addresses to unsuspecting clients, facilitating MitM and phishing",
          "It permanently disables all wireless antennas within 500 meters",
          "It deletes all files stored on domain controllers"], "B",
         "A rogue DHCP server responds faster than the legitimate server, configuring clients with the attacker's IP as the default gateway and rogue DNS servers, enabling seamless traffic interception, credential harvesting, and website spoofing."),
        ("DoS - SYN Flood Mechanism", "How does a classic TCP SYN Flood attack cause a Denial of Service on a target web server?",
         ["By overwriting the server's master boot record (MBR)",
          "By sending massive volumes of SYN packets with unreachable/spoofed source IPs, filling the server's half-open connection backlog queue (SYN_RECEIVED)",
          "By executing unauthorized SQL DROP TABLE commands against backend databases",
          "By physically disabling the server's network interface card"], "B",
         "The attacker sends a deluge of TCP SYN segments with spoofed source IPs. The server allocates a Transmission Control Block (TCB) in memory and enters SYN_RECEIVED, awaiting final ACKs that never arrive, quickly exhausting the connection backlog queue."),
        ("SYN Flood Defense - SYN Cookie", "How does the 'SYN Cookie' defense mechanism mitigate TCP SYN flood attacks on servers and firewalls?",
         ["It blocks all incoming TCP traffic permanently",
          "It encodes connection parameters into the Initial Sequence Number (ISN) of the SYN-ACK without allocating server memory until the client returns a valid ACK",
          "It requires every web client to enter a CAPTCHA before sending a SYN",
          "It converts TCP packets into unacknowledged UDP datagrams"], "B",
         "SYN Cookies eliminate memory allocation during the SYN_RECEIVED state. The server encodes socket state and cryptographic hashes into the SYN-ACK sequence number; connection memory is allocated only when the client returns a valid final ACK containing the cookie value."),
        ("DoS - Land Attack", "What is the unique characteristic of a 'Land Attack' packet?",
         ["The packet length exceeds 65535 bytes",
          "The Source IP address and Port are identical to the Destination IP address and Port",
          "The packet contains completely unencrypted credit card numbers",
          "The packet has the URG and FIN flags set simultaneously"], "B",
         "In a Land Attack, the attacker crafts a TCP SYN packet where the Source IP and Port match the victim's own IP address and Port. Vulnerable operating systems attempt to process the connection with themselves, entering infinite loops and crashing."),
        ("DoS - Smurf Attack", "Which protocol and addressing combination is exploited in a classic Smurf DDoS attack?",
         ["TCP SYN packets sent to a unicast web server",
          "ICMP Echo Requests sent to an IP directed broadcast address with the victim's spoofed IP as the source address",
          "DNS queries sent over cleartext Telnet sessions",
          "BGP route advertisements containing private AS numbers"], "B",
         "In a Smurf attack, the attacker broadcasts ICMP Echo Requests to intermediate amplifying networks with the victim's IP spoofed as the source address. Hundreds of responsive hosts reply simultaneously to the victim, saturating its inbound bandwidth."),
        ("DoS - Fraggle Attack", "How does a Fraggle attack differ fundamentally from a Smurf attack?",
         ["Fraggle uses UDP Echo packets (port 7) instead of ICMP Echo packets",
          "Fraggle targets only wireless Bluetooth devices",
          "Fraggle encrypts the packet payload using RSA-4096",
          "Fraggle requires physical access to the victim's motherboard"], "A",
         "Fraggle is the UDP counterpart to the Smurf attack. It sends UDP Echo datagrams (typically to port 7) to broadcast addresses with the victim's spoofed source IP, prompting hosts to send UDP replies that overwhelm the victim."),
        ("DoS - Ping of Death", "What structural anomaly in a network packet constitutes a 'Ping of Death' attack?",
         ["An ICMP packet carrying an audio recording of a siren",
          "An IP packet that, when reassembled from fragments, exceeds the maximum legal IPv4 packet size of 65,535 bytes",
          "A packet transmitted without an Ethernet preamble",
          "A TCP packet where all header fields are filled with zeros"], "B",
         "The maximum size of an IPv4 packet including header is 65,535 bytes. A Ping of Death transmits fragmented ICMP packets whose total reassembled size exceeds 65,535 bytes, causing buffer overflows and crashes in vulnerable network stacks."),
        ("DoS - Teardrop Attack", "What mechanism causes system crashes in a 'Teardrop' fragmentation attack?",
         ["Flooding the router with million-hop TTL packets",
          "Transmitting packet fragments with overlapping, conflicting fragment offsets, corrupting OS kernel memory buffers during reassembly",
          "Overheating server CPUs by requesting complex mathematical square roots",
          "Injecting malicious SQL syntax into Ethernet frame headers"], "B",
         "Teardrop exploits IP fragmentation reassembly flaws. The attacker crafts overlapping, contradictory Fragment Offset and Length fields. When the target operating system attempts to reassemble the malformed fragments into a contiguous buffer, a memory fault or kernel panic occurs."),
        ("Application Layer DoS - CC Attack", "What is a Challenge Collapsar (CC) attack, and at which OSI layer does it primarily operate?",
         ["A physical fiber disconnection attack at Layer 1",
          "An Application Layer (Layer 7) HTTP/HTTPS flood that repeatedly requests computationally expensive web pages or database queries",
          "A Layer 2 MAC address exhaustion attack on core switches",
          "A hardware BIOS flashing attack on border routers"], "B",
         "A CC attack targets Layer 7 (Application Layer). The attacker uses proxy networks or botnets to issue floods of legitimate-looking HTTP GET/POST requests for resource-intensive web pages, exhausting web server CPUs, memory pools, and database connection limits."),
        ("DoS - Slowloris Attack", "How does a Slowloris attack exhaust web server resources without generating massive volumetric bandwidth?",
         ["By sending single 100-gigabyte video files to port 80",
          "By opening multiple HTTP connections and sending incomplete HTTP headers at slow, periodic intervals, holding server threads open until the maximum concurrent pool is exhausted",
          "By flooding the web server with high-frequency ICMP echo requests",
          "By manipulating the server's BGP routing table"], "B",
         "Slowloris is a low-and-slow Layer 7 DoS attack. It opens numerous TCP connections to a web server and transmits partial HTTP headers periodically just before the keep-alive timeout expires, keeping server worker threads indefinitely occupied until no new clients can connect."),
        ("NTP Amplification Attack", "Why are Network Time Protocol (NTP) servers frequently exploited in volumetric amplification DDoS attacks?",
         ["NTP uses 4096-bit asymmetric encryption",
          "Vulnerable NTP servers supporting the legacy 'monlist' command return lists of the last 600 clients, producing amplification factors exceeding 500x",
          "NTP operates exclusively over high-latency satellite links",
          "NTP packets automatically delete victim routing tables"], "B",
         "The NTP 'monlist' command sends a tiny UDP request that triggers a response containing up to 600 recent client IP addresses. By spoofing the victim's IP, the attacker generates an enormous asymmetric amplification flood directing hundreds of times more traffic onto the victim."),
        ("DNS Amplification Factor", "How does an attacker maximize the bandwidth amplification factor in a DNS reflection attack?",
         ["By requesting standard 1-byte ICMP replies",
          "By querying open DNS resolvers for large 'ANY' or 'TXT' resource records with EDNS0 support, spoofing the victim's source IP",
          "By establishing encrypted SSH tunnels to all DNS servers simultaneously",
          "By disabling TCP checksum calculation on client computers"], "B",
         "In a DNS amplification attack, an attacker sends small UDP queries (e.g. requesting the 'ANY' record for a domain signed with DNSSEC) to open recursive resolvers. The resulting responses are tens of times larger than the requests, overwhelming the spoofed victim's link."),
        ("IP Spoofing Purpose", "What is the primary technical objective of an attacker when utilizing IP address spoofing in DDoS attacks?",
         ["To ensure the attacker receives all reply data packets for analysis",
          "To conceal the attacker's true geographical identity and redirect victim response traffic to an innocent third party or unroutable sinkhole",
          "To accelerate Ethernet switching speeds across local subnets",
          "To legally comply with national cybersecurity regulations"], "B",
         "IP spoofing hides the real origin of the attack traffic and causes target systems to send replies to the spoofed victim (in reflection attacks) or drop them into black holes, rendering source-based blocking ineffective without deep packet inspection."),
        ("Defense-in-Depth Tiers", "Which of the following security architectures exemplifies the Defense-in-Depth principle for an enterprise data center?",
         ["Relying exclusively on a single hardware firewall with default permit rules",
          "Deploying border firewalls, perimeter IPS, internal DMZ segmentation, host-level antivirus/EDR, and data-at-rest encryption",
          "Configuring all server IP addresses into the public Untrust security zone",
          "Disabling all user authentication mechanisms to reduce network latency"], "B",
         "Defense-in-Depth creates multiple concentric rings of protection across the perimeter, network segments, host operating systems, applications, and storage, ensuring that if one boundary is breached, subsequent layers continue defense."),
        ("Anti-DDoS Scrubbing Center", "What is the operational function of an Anti-DDoS Traffic Scrubbing Center during a volumetric attack?",
         ["To format all hard drives on the victim server",
          "To divert incoming traffic using BGP routing, clean the traffic by stripping malicious flood packets, and reinject legitimate traffic back to the enterprise",
          "To physically replace all fiber optic cables leading into the data center",
          "To shut down the entire Internet connection to prevent electrical overheating"], "B",
         "When a DDoS attack is detected, traffic destined for the victim is diverted via BGP or DNS to a specialized scrubbing center. High-performance cleaning engines filter out flood packets (SYN, UDP, HTTP floods) and reinject clean legitimate traffic back to the target host."),
        ("Malware - Logic Bomb", "What distinguishes a 'Logic Bomb' from other standard malware varieties?",
         ["It relies exclusively on audio microphones to detect targets",
          "It remains dormant in a system until triggered by a specific predefined event, date, or logical condition, upon which it executes its destructive payload",
          "It spreads autonomously across all reachable subnets within 10 milliseconds",
          "It only infects computers running Unix operating systems"], "B",
         "A logic bomb is malicious code deliberately inserted into a software system that remains dormant until triggered by a specific condition (e.g., a specific date/time, a user being deleted from payroll, or a failed command execution)."),
        ("Social Engineering - Watering Hole", "What is a 'Watering Hole' attack strategy?",
         ["Flooding an enterprise drinking water cooler with electrical interference",
          "Compromising legitimate third-party websites frequently visited by employees of a target organization to deliver drive-by malware downloads",
          "Sending broadcast emails asking employees to drink more water",
          "Sniffing unencrypted VoIP packets across WAN links"], "B",
         "In a Watering Hole attack, adversaries profile target organizations to identify industry websites frequently visited by their employees. The attackers compromise that third-party website, injecting malicious scripts to infect visitors from the target company via drive-by downloads."),
        ("Man-in-the-Middle (MitM) Definition", "In a Man-in-the-Middle (MitM) attack, what position does the attacker establish?",
         ["The attacker sits behind the destination database server without network access",
          "The attacker intercepts, relays, and potentially alters communication between two legitimate parties without either party being aware of the intrusion",
          "The attacker only monitors environmental temperatures inside the server rack",
          "The attacker acts as an accredited Certificate Authority"], "B",
         "An MitM attacker inserts themselves into the active communication path between two endpoints (via ARP poisoning, rogue Wi-Fi, or DNS spoofing), reading, modifying, or injecting data into the conversation transparently."),
        ("Buffer Overflow Vulnerability", "What causes a traditional Buffer Overflow vulnerability in software applications?",
         ["The CPU clock frequency drops below operating specifications",
          "An application writes more data to a memory buffer than the buffer is allocated to hold, overwriting adjacent memory spaces such as the return address pointer",
          "The Ethernet cable length exceeds 100 meters without a repeater",
          "The database table contains more than 10,000 text rows"], "B",
         "A buffer overflow occurs when a program writes input data beyond the boundary of an allocated stack or heap memory buffer without proper bounds checking, corrupting adjacent control data (such as the instruction pointer) to hijack execution flow."),
        ("SQL Injection Threat", "What is the core operational mechanism of a SQL Injection (SQLi) attack on a web application?",
         ["Flooding the database port with malformed UDP datagrams",
          "Injecting malicious SQL commands through user input fields that the backend database executes as genuine database queries",
          "Physically disconnecting the SCSI storage cables from the database server",
          "Rewriting the DNS records for the database server's domain name"], "B",
         "SQL Injection occurs when untrusted user input is concatenated directly into dynamic SQL query strings without sanitization or parameterized queries, allowing attackers to manipulate database commands to bypass authentication or extract entire tables."),
        ("Cross-Site Scripting (XSS)", "What is the fundamental mechanism of a Cross-Site Scripting (XSS) attack?",
         ["Executing unauthorized SQL statements on the backend database engine",
          "Injecting malicious client-side JavaScript into trusted web pages viewed by other users, stealing session cookies or redirecting users",
          "Flooding the border firewall with malformed ICMP echo packets",
          "Modifying the physical firmware of the web server's motherboard"], "B",
         "XSS occurs when a web application includes unsanitized user input in its web output. When other users view the page, their browser executes the injected malicious script in the context of the trusted site, exposing session tokens and cookies."),
        ("Zero-Day Vulnerability Definition", "What defines a 'Zero-Day Vulnerability' in cybersecurity practice?",
         ["A vulnerability that requires exactly zero days of effort to patch completely",
          "A software security flaw that is unknown to the vendor or for which no official patch or fix has been publicly released",
          "A vulnerability that only impacts computers manufactured in the year 2000",
          "A flaw that can only be exploited during nighttime hours"], "B",
         "A Zero-Day vulnerability is an undisclosed software or hardware security flaw unknown to the product vendor (giving them 'zero days' of defense notice) or for which no patch currently exists, making proactive behavioral defense vital.")
    ]

    for item in s_data:
        single.append({
            "chapter_num": 3,
            "chapter_title": "Common Network Security Threats and Threat Prevention",
            "topic": item[0],
            "type": "Single Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 3 MULTIPLE CHOICE (28 questions)
    m_data = [
        ("Malware Broad Categories", "Which of the following are recognized classifications of malicious software (malware)?",
         ["Computer Viruses", "Worms", "Trojan Horses", "Ransomware", "Standard Hypervisors"], "ABCD",
         "Major malware types include viruses, worms, Trojans, ransomware, rootkits, spyware, and botnets. Hypervisors are legitimate virtualization software layers."),
        ("Virus vs Worm Differences", "Which of the following statements correctly distinguish a computer worm from a computer virus?",
         ["A virus requires a host program or file to infect; a worm is an independent standalone program",
          "A virus typically requires human intervention (executing the host) to spread; a worm propagates autonomously over network connections",
          "A worm can exploit network service vulnerabilities directly to infect adjacent systems",
          "A virus never causes any damage to user files"], "ABC",
         "Viruses require host files and user execution to spread; worms are autonomous standalone programs that exploit network vulnerabilities directly to self-propagate across systems. Both can cause severe file and system damage."),
        ("Port Scanning Techniques", "Which of the following are common TCP/IP port scanning techniques utilized by penetration testers and threat actors?",
         ["TCP Connect Scan (Full 3-way handshake)",
          "TCP SYN Scan (Half-open stealth scan)",
          "TCP FIN / NULL / XMAS Scan (Inverse RFC scanning)",
          "UDP Port Scan",
          "Optical Fiber Polarization Scan"], "ABCD",
         "Standard scanning methods include TCP Connect, TCP SYN, TCP FIN/NULL/XMAS, and UDP scanning. Optical polarization is a physical transmission property, not a port scanning method."),
        ("Layer 2 Sniffing Attacks", "Which of the following techniques can an attacker use on a switched Ethernet LAN to intercept and sniff traffic destined for other hosts?",
         ["ARP Cache Poisoning (ARP Spoofing)",
          "MAC Address Table Flooding (CAM table overflow)",
          "DHCP Server Rogue Spoofing",
          "BGP Route Leaking on Core ISP Routers"], "ABC",
         "On local switched LANs, attackers bypass unicast switching isolation using ARP spoofing, MAC table flooding (forcing hub failover), and rogue DHCP servers. BGP route leaking occurs at wide-area inter-domain routing tiers."),
        ("Network Layer Spoofing Types", "Which of the following represent spoofing attack vectors commonly executed across network communications?",
         ["IP Address Spoofing",
          "MAC Address Spoofing",
          "DNS Cache Poisoning / Domain Spoofing",
          "DHCP Server Spoofing",
          "Processor Serial Number Overclocking"], "ABCD",
         "Network spoofing involves falsifying identity headers across layers: MAC spoofing (Layer 2), IP spoofing (Layer 3), DHCP spoofing (Layer 7), and DNS poisoning (Layer 7). Overclocking is a physical hardware tuning process."),
        ("Volumetric DDoS Attack Methods", "Which of the following attack types are categorized as volumetric DoS/DDoS flooding attacks?",
         ["UDP Flood", "ICMP Echo Flood (Ping Flood)", "TCP SYN Flood", "DNS Amplification Flood", "SQL Injection"], "ABCD",
         "Volumetric floods aim to saturate network link bandwidth or state tables using huge traffic volumes: UDP floods, ICMP floods, SYN floods, and DNS amplification. SQL injection is an application logic exploit."),
        ("Malformed Packet DoS Attacks", "Which of the following attacks rely on sending malformed, oversized, or contradictory packet headers rather than high traffic volume?",
         ["Ping of Death (oversized IP packets)",
          "Teardrop Attack (overlapping fragment offsets)",
          "Land Attack (identical source/destination IP and port)",
          "Smurf Amplification Attack"], "ABC",
         "Ping of Death, Teardrop, and Land attacks are vulnerability-based malformed packet attacks that crash host networking stacks with minimal traffic volume. Smurf is a volumetric amplification flood."),
        ("Application Layer (L7) Attacks", "Which of the following attacks operate primarily at Layer 7 (Application Layer) of the OSI model?",
         ["Challenge Collapsar (CC) HTTP GET Flood",
          "Slowloris HTTP Connection Exhaustion",
          "SQL Injection (SQLi)",
          "Cross-Site Scripting (XSS)",
          "Ethernet Preamble Corrupting Attack"], "ABCD",
         "CC attacks, Slowloris, SQL Injection, and XSS target application logic and protocols (HTTP, SQL) at Layer 7. The Ethernet preamble operates at Layer 1/2."),
        ("Amplification DDoS Mechanisms", "Which protocols are frequently exploited to launch distributed reflection and amplification DoS attacks?",
         ["NTP (Network Time Protocol using 'monlist')",
          "DNS (Domain Name System querying 'ANY' records)",
          "SNMP (Simple Network Management Protocol queries)",
          "SSDP (Simple Service Discovery Protocol)",
          "SSH (Secure Shell Protocol)"], "ABCD",
         "Connectionless UDP services with large response-to-request ratios (NTP, DNS, SNMP, SSDP) are prime vectors for reflection amplification attacks. SSH runs over TCP, preventing spoofed reflection."),
        ("ARP Poisoning Mitigation", "Which security mechanisms implemented on enterprise switches protect against ARP spoofing / poisoning attacks?",
         ["Dynamic ARP Inspection (DAI)",
          "DHCP Snooping binding table integration",
          "Configuring static ARP entries on critical endpoints and gateways",
          "Disabling Ethernet CRC verification"], "ABC",
         "DAI validates ARP packets against the DHCP Snooping database or static bindings, discarding unauthorized ARP responses. Static ARP mappings also prevent cache poisoning. Disabling CRC ruins data integrity."),
        ("SYN Flood Countermeasures", "Which defensive techniques are effective in mitigating TCP SYN flood attacks on firewalls and enterprise servers?",
         ["SYN Cookie technology",
          "TCP SYN Proxy / Embryonic connection inspection",
          "Rate limiting incoming SYN requests per second from external zones",
          "Disabling TCP keepalive timers entirely"], "ABC",
         "SYN floods are mitigated by SYN Cookies (stateless verification), TCP SYN Proxy (firewall completes 3-way handshake before connecting to server), and SYN rate limiting. Disabling keepalives degrades session management."),
        ("Anti-DDoS System Phases", "What are the core operational phases of an enterprise Anti-DDoS defense architecture?",
         ["Traffic Detection (identifying anomaly spikes and flood patterns)",
          "Traffic Diversion (redirecting victim traffic to scrubbing centers)",
          "Traffic Scrubbing (filtering attack packets while retaining legitimate requests)",
          "Traffic Reinjection (forwarding cleaned traffic to original server)",
          "Traffic Deletion (deleting all enterprise databases)"], "ABCD",
         "Anti-DDoS scrubbing follows four distinct stages: 1. Detection (monitoring telemetry); 2. Diversion (rerouting via BGP/DNS); 3. Scrubbing (deep packet filtering); and 4. Reinjection (clean traffic delivery)."),
        ("Defense-in-Depth Components", "Which defensive layers should be incorporated into a comprehensive enterprise Defense-in-Depth strategy?",
         ["Physical Security (access control, biometric badges, CCTV)",
          "Perimeter Security (Next-Generation Firewalls, Anti-DDoS, IPS)",
          "Network Security (VLAN segmentation, 802.1X NAC, encrypted tunnels)",
          "Endpoint Security (EDR, host firewalls, patch management)",
          "Data Security (encryption at rest/in transit, DLP, backup)"], "ABCDE",
         "Defense-in-Depth mandates overlapping controls across Physical, Perimeter, Network, Endpoint, Application, and Data dimensions to ensure multi-layered resilience."),
        ("Social Engineering Varieties", "Which of the following attack methods rely predominantly on social manipulation rather than software exploits?",
         ["Phishing (fraudulent emails soliciting credentials)",
          "Vishing (voice telephone pretexting by fake technicians)",
          "Smishing (SMS text phishing)",
          "Watering Hole attack",
          "SYN Flood attack"], "ABCD",
         "Phishing, vishing, smishing, and watering hole attacks manipulate human psychology, trust, and habit to deliver malicious payloads. SYN flood is a network protocol resource exhaustion attack."),
        ("Botnet Utilization Scenarios", "For which malicious activities are botnets commonly deployed by threat actors?",
         ["Launching massive distributed denial-of-service (DDoS) attacks",
          "Sending billions of unsolicited spam and phishing emails",
          "Conducting large-scale cryptocurrency mining across zombie devices",
          "Coordinated credential stuffing and password brute-forcing",
          "Providing free high-speed bandwidth to non-profit organizations"], "ABCD",
         "Botnets provide distributed compute and bandwidth for DDoS floods, spam dissemination, illicit crypto mining, proxy anonymity networks, and automated brute-force attacks."),
        ("Vulnerability Assessment Tools", "Which of the following tools and capabilities are standard components of vulnerability assessment and penetration testing?",
         ["Network port scanners (e.g., Nmap)",
          "Automated vulnerability scanners (e.g., Nessus, OpenVAS)",
          "Web application vulnerability scanners (e.g., OWASP ZAP)",
          "Exploit frameworks (e.g., Metasploit)",
          "Physical soldering irons for switch chassis assembly"], "ABCD",
         "Vulnerability assessments leverage port discovery (Nmap), vulnerability scanners (Nessus/OpenVAS), web application scanners (ZAP), and exploit validation tools (Metasploit)."),
        ("Ransomware Infection Vectors", "Through which common entry vectors does ransomware initially compromise enterprise networks?",
         ["Phishing emails carrying weaponized macro documents or malicious links",
          "Exposed Remote Desktop Protocol (RDP) ports with weak or compromised passwords",
          "Exploitation of unpatched software vulnerabilities (e.g., SMB flaws like EternalBlue)",
          "Drive-by downloads from compromised websites",
          "Standard certified fiber optic patch cables"], "ABCD",
         "Ransomware commonly infiltrates via email phishing, exposed remote desktop services, unpatched perimeter vulnerabilities, and malicious web drive-bys."),
        ("Web Application Threats (OWASP Top 10)", "Which of the following security threats are included in the OWASP Top 10 vulnerabilities for web applications?",
         ["Injection flaws (such as SQL Injection and Command Injection)",
          "Broken Authentication and Session Management",
          "Cross-Site Scripting (XSS)",
          "Security Misconfigurations and Outdated Components",
          "Optical Cable Attenuation"], "ABCD",
         "The OWASP Top 10 highlights critical application risks including Injection, Broken Authentication, XSS, Security Misconfigurations, and Insecure Design."),
        ("Teardrop and Fragmentation Risks", "Why are fragmented IP packets historically utilized by attackers to bypass network defenses?",
         ["Initial fragments may lack Layer 4 port headers, complicating stateful policy inspection",
          "Overlapping fragment offsets can exploit reassembly buffer bugs in target kernels",
          "Some primitive packet filters inspect only the first fragment and blindly permit subsequent fragments",
          "Fragmented packets automatically travel twice as fast across fiber links"], "ABC",
         "Fragmented packets can split TCP/UDP headers across packets, evade legacy packet filters that inspect only Fragment 0, and trigger reassembly crashes via overlapping offsets (Teardrop)."),
        ("IP Address Spoofing Defenses", "Which network security techniques are utilized by internet service providers and routers to block spoofed IP traffic?",
         ["Unicast Reverse Path Forwarding (uRPF)",
          "Ingress and egress access control list (ACL) packet filtering (BCP 38)",
          "IP Source Guard (IPSG) on access switches",
          "Disabling all IP routing protocols across the Internet"], "ABC",
         "Spoofed source IPs are filtered using uRPF (checking if source IP is reachable via incoming interface), BCP 38 ingress filtering, and IP Source Guard on local switch ports."),
        ("Zero-Day Mitigation Strategies", "Because signature-based antivirus cannot detect unknown zero-day attacks, which modern defenses are recommended?",
         ["Heuristic and behavioral anomaly detection",
          "Sandboxing and dynamic malware analysis",
          "Endpoint Detection and Response (EDR) behavioral monitoring",
          "Strict network micro-segmentation and Zero Trust access policies",
          "Relying solely on paper log books"], "ABCD",
         "Zero-day threats lack known signatures. Defense requires behavioral heuristics, sandboxing execution environments, EDR anomaly telemetry, and Zero Trust micro-segmentation."),
        ("Smurf Attack Amplifiers", "In a Smurf attack, what elements are required to successfully launch and amplify the flood?",
         ["An attacker capable of crafting spoofed ICMP Echo Request packets",
          "An amplifying intermediary network that forwards directed broadcast packets to its local broadcast domain",
          "Multiple responsive hosts on the intermediary network that reply to the victim's spoofed IP",
          "A victim host whose network link becomes saturated by the replies",
          "Direct administrative access to the victim's BIOS"], "ABCD",
         "Smurf attacks require an attacker sending spoofed packets, an intermediary broadcast-forwarding network (amplifier), responsive hosts on that segment, and an overwhelmed victim."),
        ("DNS Spoofing Impacts", "What adverse consequences occur when an attacker successfully executes DNS cache poisoning against a local resolver?",
         ["Users requesting legitimate websites (e.g. online banking) are redirected to attacker-controlled phishing servers",
          "Corporate emails can be intercepted by pointing MX records to rogue mail servers",
          "Software update domains can be hijacked to distribute malware updates",
          "The client's physical RAM modules are instantly formatted"], "ABC",
         "DNS poisoning corrupts IP resolution mappings, diverting web traffic to phishing clones, rerouting emails via rogue MX hosts, and facilitating drive-by malware delivery."),
        ("MAC Address Flooding Effects", "What happens to a network switch when its CAM (Content Addressable Memory) table is exhausted during a MAC flood attack?",
         ["The switch can no longer learn new legitimate MAC-to-port mappings",
          "The switch begins flooding incoming unicast frames out of all ports within the VLAN (acting like a hub)",
          "Network performance degrades drastically due to excessive broadcast traffic",
          "The switch turns off its power supply permanently"], "ABC",
         "CAM exhaustion forces the switch into fail-open mode, broadcasting unicast frames across all ports, degrading bandwidth and exposing traffic to sniffing on any switch port."),
        ("CC Attack Defense Techniques", "Which countermeasures are effective against Layer 7 Challenge Collapsar (CC) HTTP GET floods?",
         ["Web Application Firewall (WAF) rate limiting and IP reputation filtering",
          "JavaScript challenge validation (verifying client is a genuine browser, not a script)",
          "CAPTCHA verification for suspicious high-frequency request patterns",
          "Disabling power to all external DNS root servers"], "ABC",
         "CC attacks are mitigated by WAF rate limits, JavaScript computational challenges, CAPTCHA verification, and behavior-based bot management."),
        ("Drive-By Download Mechanism", "Which conditions facilitate a successful 'Drive-By Download' infection?",
         ["A victim visits a compromised or malicious website",
          "The malicious site hosts an exploit kit probing browser or plugin vulnerabilities",
          "The vulnerability is silently exploited without explicit user download consent",
          "The user must physically disassemble the computer monitor"], "ABC",
         "Drive-by downloads silently exploit browser, PDF, or plugin flaws when a user merely visits a compromised website, installing malware without requiring user clicks or downloads."),
        ("Slowloris Attack Characteristics", "Which operational features distinguish a Slowloris attack from traditional volumetric HTTP floods?",
         ["It consumes very minimal upstream bandwidth from the attacker",
          "It holds server connections open by sending partial, incomplete HTTP request headers at regular intervals",
          "It targets thread-based web servers (such as Apache 1.x/2.x) with fixed worker limits",
          "It uses 100-gigabit UDP packet floods"], "ABC",
         "Slowloris is a low-bandwidth, asymmetric Layer 7 attack. It slowly sends partial headers to exhaust server thread/connection pools, selectively devastating thread-based web servers like Apache."),
        ("Defense Against Rogue DHCP", "Which feature on Huawei enterprise switches effectively eliminates rogue DHCP server attacks?",
         ["DHCP Snooping with trusted and untrusted port designation",
          "Configuring the switch to drop DHCP Offer/ACK packets received on untrusted access ports",
          "Enabling 802.1Q trunking on all access ports",
          "Disabling all IP routing across the campus network"], "AB",
         "DHCP Snooping designates switch ports as 'trusted' (connected to legitimate DHCP servers) or 'untrusted' (connected to users). Any DHCP Offer/ACK received on an untrusted port is immediately dropped.")
    ]

    for item in m_data:
        multi.append({
            "chapter_num": 3,
            "chapter_title": "Common Network Security Threats and Threat Prevention",
            "topic": item[0],
            "type": "Multiple Choice",
            "stem": item[1],
            "options": item[2],
            "answer": item[3],
            "explanation": item[4]
        })

    # CHAPTER 3 TRUE/FALSE (26 questions)
    tf_data = [
        ("Virus vs Worm Replication", "Unlike a computer virus, a computer worm does not require a host file and can replicate autonomously across network connections.", "A",
         "True. Worms are standalone malicious programs that replicate across networks independently by exploiting vulnerabilities, whereas viruses attach to host files and require human execution."),
        ("Trojan Self-Replication", "A Trojan horse is designed to replicate itself aggressively across all computers on a local area network like a worm.", "B",
         "False. Trojans do not self-replicate. They rely on social engineering, deception, or bundling with legitimate utilities to trick users into installing them."),
        ("Ransomware Key Recovery", "If ransomware uses strong AES-256 and RSA-2048 encryption, victims can easily decrypt their files in seconds using simple mathematical tools without the private key.", "B",
         "False. Modern asymmetric and symmetric cryptography is computationally infeasible to break via brute-force; without the private key held by the attacker or an implementation flaw, decryption is impossible."),
        ("Rootkit Detection Ease", "Because rootkits modify kernel-level data structures to hide their presence, standard Task Manager and basic antivirus tools can always detect them immediately.", "B",
         "False. Rootkits hook system APIs and kernel structures precisely to hide their processes, drivers, and open ports, making them invisible to standard operating system utilities and basic scanners."),
        ("Port Scanning Legality", "Port scanning sends packets to target ports and is used both by network administrators for security audits and by attackers for vulnerability reconnaissance.", "A",
         "True. Port scanning is a dual-use technique. Administrators use tools like Nmap to audit open services and firewall rules, while adversaries use them to discover exploitable services."),
        ("TCP SYN Scan Completion", "In a TCP SYN port scan, the scanning host completes the full 3-way handshake by sending a final ACK segment before logging out.", "B",
         "False. A TCP SYN scan is a half-open scan. If a SYN-ACK is received, the scanner sends an RST segment to tear down the connection immediately, intentionally avoiding full handshake completion."),
        ("UDP Port Scan Response", "When a UDP port scan probes an open UDP port, the target host is required by RFC standards to return an ICMP Echo Reply.", "B",
         "False. ICMP Echo Replies are responses to ICMP Echo Requests. For an open UDP port, the target application either responds with an application-specific UDP response or produces no response (open|filtered)."),
        ("Switch Hub Failover in MAC Flooding", "When an attacker exhausts a switch's CAM table via MAC flooding, many switches default to broadcasting incoming unicast frames out all ports, allowing the attacker to sniff traffic.", "A",
         "True. When the MAC table memory is full, the switch cannot learn new addresses. Incoming frames with unknown destination MACs are flooded out all ports in the VLAN (fail-open mode), enabling sniffing."),
        ("ARP Protocol Authentication", "The standard Address Resolution Protocol (ARP) includes built-in cryptographic authentication to ensure ARP replies come from legitimate devices.", "B",
         "False. ARP (RFC 826) was developed without security authentication. Hosts accept and update their cache with unsolicited ARP replies, leaving the protocol vulnerable to ARP spoofing and poisoning."),
        ("Gratuitous ARP Poisoning", "Attackers can exploit Gratuitous ARP to silently poison the ARP caches of all hosts across a subnet simultaneously.", "A",
         "True. By broadcasting a Gratuitous ARP packet claiming ownership of an IP address (such as the default gateway), an attacker overwrites the ARP tables of all listening hosts in the broadcast domain."),
        ("DHCP Snooping Role", "DHCP Snooping prevents rogue DHCP servers by allowing DHCP reply messages (Offer/ACK) to enter the switch only through designated 'trusted' ports.", "A",
         "True. DHCP Snooping classifies switch ports into trusted and untrusted. Only trusted ports can send DHCP server messages (Offer, ACK); untrusted ports are blocked from sending them, neutralizing rogue DHCP servers."),
        ("SYN Flood Memory Exhaustion", "A TCP SYN flood attacks a server's bandwidth rather than its memory connection tables.", "B",
         "False. While high-volume SYN floods consume bandwidth, their primary kill mechanism is exhausting the server's half-open connection backlog queue (memory allocated for TCP control blocks)."),
        ("SYN Cookie Memory Allocation", "When SYN Cookie defense is active, a server allocates full connection memory buffers immediately upon receiving the initial SYN packet.", "B",
         "False. SYN Cookies prevent memory allocation during the SYN_RECEIVED state. State is encoded into the SYN-ACK sequence number, and memory is allocated only after the client returns a valid ACK."),
        ("Land Attack IP Match", "In a Land attack, the source IP address and source port are forged to match the destination IP address and destination port of the victim.", "A",
         "True. The defining feature of a Land attack is setting Source IP = Destination IP and Source Port = Destination Port, tricking the target into opening a connection with itself and freezing."),
        ("Smurf Attack UDP Protocol", "A Smurf attack uses UDP port 7 packets to flood an amplifying network.", "B",
         "False. A Smurf attack uses ICMP Echo Requests. The Fraggle attack is the counterpart that uses UDP datagrams (typically port 7)."),
        ("Ping of Death Legality", "The Ping of Death attack exploits the fact that the IPv4 specification permits packets to exceed 1 megabyte in size.", "B",
         "False. The maximum legal size of an IPv4 datagram is 65,535 bytes. A Ping of Death creates fragmented packets whose total reassembled size illegally exceeds 65,535 bytes, crashing unpatched systems."),
        ("Teardrop Offset Overlap", "The Teardrop attack crashes vulnerable systems by crafting packet fragments with overlapping and contradictory fragment offset values.", "A",
         "True. Teardrop manipulates the Fragment Offset and Length fields so that fragments overlap during reassembly, triggering buffer overflows or system crashes in unpatched kernels."),
        ("CC Attack Target Layer", "A Challenge Collapsar (CC) attack targets Layer 2 MAC address tables on core enterprise switches.", "B",
         "False. A CC attack is a Layer 7 (Application Layer) HTTP/HTTPS flood designed to overwhelm web server CPUs and database backends by repeatedly requesting complex web pages."),
        ("Slowloris Bandwidth Need", "Slowloris requires massive gigabit-level bandwidth to crash enterprise web servers.", "B",
         "False. Slowloris is a low-bandwidth attack that sends incomplete HTTP headers very slowly, occupying server threads until the maximum connection limit is reached, requiring minimal attacker bandwidth."),
        ("NTP Monlist Amplification", "NTP amplification attacks exploit the 'monlist' command to generate responses that are hundreds of times larger than the original request.", "A",
         "True. The NTP 'monlist' command returns the addresses of the last 600 systems that communicated with the server, providing massive bandwidth amplification (over 500x) against a spoofed victim IP."),
        ("IP Spoofing for TCP Downloads", "An attacker can successfully use a spoofed source IP address to download confidential files from a remote FTP server without any other access.", "B",
         "False. TCP requires a bidirectional 3-way handshake. If the attacker spoofs the source IP, the server sends SYN-ACK to the spoofed IP, not the attacker. The attacker cannot complete the handshake or receive downloaded data."),
        ("Anti-DDoS Traffic Diversion", "During a DDoS attack, traffic diversion redirects incoming traffic destined for the victim to a scrubbing center using mechanisms like BGP routing updates.", "A",
         "True. Anti-DDoS diversion announces more specific BGP routes or adjusts DNS to route traffic to specialized scrubbing centers for filtering before legitimate traffic is reinjected."),
        ("Logic Bomb Triggering", "A logic bomb executes its payload immediately upon entering a computer system, regardless of dates or events.", "B",
         "False. A logic bomb remains dormant until a specific trigger condition is met (such as a calendar date, account deletion, or specific event)."),
        ("SQL Injection Impact", "SQL injection attacks occur because web applications improperly concatenate untrusted user input directly into executable SQL statements.", "A",
         "True. SQL injection is caused by lack of input validation and failure to use parameterized queries (prepared statements), allowing user inputs to alter SQL query logic."),
        ("XSS Execution Context", "Cross-Site Scripting (XSS) attacks execute malicious code within the victim user's web browser rather than directly on the web server's operating system.", "A",
         "True. In an XSS attack, the injected script executes inside the client's browser, enabling the attacker to steal cookies, hijack user sessions, or manipulate the webpage appearance."),
        ("Zero-Day Signature Protection", "Traditional signature-based antivirus software provides immediate 100% protection against previously unknown zero-day exploits.", "B",
         "False. Signature-based antivirus relies on known hashes and patterns. Because zero-day exploits are previously unknown, signatures do not exist, making behavioral analysis and sandboxing necessary.")
    ]

    for item in tf_data:
        tf.append({
            "chapter_num": 3,
            "chapter_title": "Common Network Security Threats and Threat Prevention",
            "topic": item[0],
            "type": "True/False",
            "stem": item[1],
            "options": ["True", "False"],
            "answer": item[2],
            "explanation": item[3]
        })

    return single, multi, tf

if __name__ == "__main__":
    s, m, t = get_ch3_questions()
    print(f"Chapter 3 generated: {len(s)} Single, {len(m)} Multi, {len(t)} TF.")
